export const BZM22_PARAMETER_ROLES = {
  contract: "評価契約",
  state: "状態入力",
  control: "行動・制約",
  transition: "状態遷移",
  cashflow: "価値台帳",
  intervention: "介入差分",
  output: "派生出力",
} as const;

export type Bzm22ParameterRole = keyof typeof BZM22_PARAMETER_ROLES;

export const BZM22_PARAMETER_RELATION_LABELS = {
  direct: "式へ直接",
  indirect: "遷移経由",
  guard: "計算境界",
  output: "計算出力",
  unused: "現試算未接続",
  alias: "同値参照",
} as const;

export type Bzm22ParameterRelation = keyof typeof BZM22_PARAMETER_RELATION_LABELS;

export const BZM22_FORMULA_CATALOG = {
  "—": { title: "管理・再現性", tex: String.raw`\text{計算式へ数値接続なし}`, description: "識別・証拠・再現性を守る項目、または現pilotでは未接続の項目。" },
  F0: { title: "評価契約", tex: String.raw`\mathcal C_{\mathrm{eval}}=(v,\tau,H_v,H_{\mathrm{econ}},M_r,\mathcal R)`, description: "版、時点、地平、評価規則を固定する。" },
  F1: { title: "意思決定状態", tex: String.raw`\mathbf s_t=(\mathbf x_t,\mathbf n_t,\boldsymbol\ell_t,\mathbf e_t,\mathbf k_t,\widehat{\mathbf c}_t,\mathbf r_t,\mathbf b_t)`, description: "判断時点で利用できる型付き状態。" },
  F2: { title: "登録行動束", tex: String.raw`\mathbf z_t=(a_t,\mathbf i_t)`, description: "実行する行動と投入資源を一つの制御として扱う。" },
  F3: { title: "実行可能集合", tex: String.raw`\Gamma_{\mathrm{exec}}^{\mathrm{reg}}(\mathbf s_t)=\{\mathbf z:g_j(\mathbf s_t,\mathbf z)\leq0\}`, description: "資金、権限、契約、期限を満たす登録行動だけを残す。" },
  F4: { title: "ゲート別状態遷移", tex: String.raw`(p_i(a),\mathbf s_{t+1},\Delta t_i)`, description: "現pilotのゲート別確率、次状態、所要時間。完全な遷移核ではない。" },
  F5: { title: "月次CF現在価値", tex: String.raw`PV_{CF}(a)=\sum_t d_t s_t(a)CF_t(a)`, description: "月次CFを生存重みと割引で現在価値化する。" },
  F6: { title: "終端・残存価値", tex: String.raw`TV(a),\ RV_i(a),\ L_{\mathrm{fail},i}(a)`, description: "成功終端と途中停止・失敗の価値脚を分ける。" },
  F7: { title: "基準到達指数", tex: String.raw`Q(a)=\prod_{i\in G}p_i(a)`, description: "登録条件を通常想定で通り切る強さ。" },
  F8: { title: "逆風耐久指数", tex: String.raw`S(a)=\min_{\delta\in\Delta_{\mathrm{reg}}}\prod_{i\in G}p_i(a)m_{i\delta}(a)`, description: "登録済み逆風条件でも通り切れる強さ。戦略余力全体ではない。" },
  F9: { title: "全条件通過時価値", tex: String.raw`P(a)=\operatorname E[V_{\mathrm{net}}\mid G,a]`, description: "全条件を通過した経路に限る現在価値。" },
  F10: { title: "全分岐期待価値", tex: String.raw`J(a)=PV_{CF}(a)+d_HQ(a)TV(a)+\sum_i w_i(a)RV_i(a)`, description: "途中CF、成功、停止・失敗を全分岐で加重する。" },
  F11: { title: "必要資金ギャップ", tex: String.raw`F_{\mathrm{gap},t}(a)=\max\{0,F_{\mathrm{req},t}(a)-F_{\mathrm{commit},t}-C_t\}`, description: "現金と確約資金で埋まらない必要資金。" },
  F12: { title: "生存加重追加資金", tex: String.raw`\operatorname E[F_{\mathrm{topup}}(a)]=\sum_t s_t(a)F_{\mathrm{gap},t}(a)`, description: "経路が続く確率を掛けた追加資金総額。" },
  F13: { title: "戦略余力診断", tex: String.raw`Y_t=(\Gamma_{\mathrm{exec}}^{\mathrm{reg}},\mathcal K,T_Y^{2.2,a})`, description: "行動集合、頑健捕捉領域、喪失時点を分けて診断する。Sとは別。" },
  F14: { title: "介入差分", tex: String.raw`\Delta V_{r\mid d}=J_r(a;d)-J_r(a;0)`, description: "同じ登録方針で介入あり・なしの価値差を測る。" },
  J: { title: "J出力", tex: String.raw`J=J(a)`, description: "F10の派生出力。" },
  P: { title: "P出力", tex: String.raw`P=P(a)`, description: "F9の派生出力。" },
  Q: { title: "Q出力", tex: String.raw`Q=Q(a)`, description: "F7の派生出力。" },
  S: { title: "S出力", tex: String.raw`S=S(a)`, description: "F8の派生出力。" },
} as const;

export type Bzm22FormulaRef = keyof typeof BZM22_FORMULA_CATALOG;

interface Bzm22ParameterPresentationEntry {
  japaneseName: string;
  formulaConnection: string;
  role: Bzm22ParameterRole;
  roleLabel: (typeof BZM22_PARAMETER_ROLES)[Bzm22ParameterRole];
}

export interface Bzm22ParameterCatalogEntry extends Bzm22ParameterPresentationEntry {
  dataNameTex: string;
  symbolTex: string;
  formulaRefs: readonly Bzm22FormulaRef[];
  relation: Bzm22ParameterRelation;
  relationLabel: (typeof BZM22_PARAMETER_RELATION_LABELS)[Bzm22ParameterRelation];
}

function entry(
  role: Bzm22ParameterRole,
  japaneseName: string,
  _symbolCandidate: string,
  formulaConnection: string,
): Bzm22ParameterPresentationEntry {
  return {
    japaneseName,
    formulaConnection,
    role,
    roleLabel: BZM22_PARAMETER_ROLES[role],
  };
}

const contract = (name: string, symbol: string, connection: string) => entry("contract", name, symbol, connection);
const state = (name: string, symbol: string, connection: string) => entry("state", name, symbol, connection);
const control = (name: string, symbol: string, connection: string) => entry("control", name, symbol, connection);
const transition = (name: string, symbol: string, connection: string) => entry("transition", name, symbol, connection);
const cashflow = (name: string, symbol: string, connection: string) => entry("cashflow", name, symbol, connection);
const intervention = (name: string, symbol: string, connection: string) => entry("intervention", name, symbol, connection);
const output = (name: string, symbol: string, connection: string) => entry("output", name, symbol, connection);

/**
 * BZM 2.2 provisional-pilot-v0.1 の103スロットを、人が式から逆引きするための表示正本。
 * 内部IDとの1対1対応は check_bzm_2_2_pilot_ui_contract.mts で固定する。
 */
const BZM22_PARAMETER_PRESENTATION = {
  "version_horizon_rules.model_id": contract("モデル識別子", String.raw`\mathcal M`, "どの評価モデルで計算したかを固定し、別モデルの値との混同を防ぐ。"),
  "version_horizon_rules.model_version": contract("モデル版", String.raw`v_{\mathcal M}`, "状態・遷移・計算規則の版を固定し、同じ時系列に異なる仕様を混ぜない。"),
  "version_horizon_rules.valuation_date": contract("価値基準日", String.raw`\tau_v`, "全キャッシュフローを現在価値へ割り引く基準日を定める。"),
  "version_horizon_rules.information_cutoff": contract("情報締切", String.raw`\tau`, "この時点までに得た情報集合だけを状態・確率・価値へ使う。"),
  "version_horizon_rules.currency": contract("評価通貨", String.raw`\chi`, "金額脚を共通通貨へ揃え、J(a)とP(a)を同一尺度で計算する。"),
  "version_horizon_rules.forward_validation_count": contract("前向き検証件数", String.raw`N_{\mathrm{FV}}`, "予測時点を凍結した後に結果を照合できた件数。校正状態の判定に使う。"),
  "version_horizon_rules.initial_state_id": contract("初期状態ID", String.raw`\mathrm{id}(\mathbf s_0)`, "固定方針aを開始する評価時点の状態を一意に指す。"),
  "version_horizon_rules.H_v": contract("計画評価地平", String.raw`H_v`, "固定計画\pi_0の到達指標を観測する期限を定める。"),
  "version_horizon_rules.H_econ": contract("経済評価地平", String.raw`H_{\mathrm{econ}}`, "J(a)・P(a)でCFと終端価値を追う最終期限を定める。"),
  "version_horizon_rules.valuation_rule": contract("価値評価規則", String.raw`M_r`, "視点rごとの割引・価格づけ・残存価値の扱いを固定する。"),
  "version_horizon_rules.decision_criterion": contract("意思決定基準", String.raw`\mathcal D_d`, "controller dが登録済み行動を比較するときの目的と制約を定める。"),
  "version_horizon_rules.near_tie_tolerance": contract("近接値許容幅", String.raw`\varepsilon_{\mathrm{tie}}`, "行動価値差が実質同値とみなされる金額幅を定める。"),
  "version_horizon_rules.tie_break_rule": contract("同値時の優先規則", String.raw`\mathcal R_{\mathrm{tie}}`, "価値差が許容幅内の行動を、事前登録した規則で順序づける。"),
  "version_horizon_rules.public_value_rule": contract("公共価値集約規則", String.raw`M_{\mathrm{public}}`, "財政脚と社会便益を会社価値へ混ぜず、公共視点だけで換算・集約する。"),

  "decision_state.state_id": state("意思決定状態ID", String.raw`\mathrm{id}(\mathbf s_t)`, "評価時点tの型付き状態\mathbf s_tを一意に指す。"),
  "decision_state.decision_order": state("意思決定順序", String.raw`k(\mathbf s_t)`, "DAG上の判断順序を定め、未来情報の先取りと循環を防ぐ。"),
  "decision_state.elapsed_months": state("評価開始後の経過月", String.raw`t(\mathbf s_t)`, "CF・期限・遷移時間を初期状態からの共通時計へ置く。"),
  "decision_state.technical_state": state("技術進捗・証拠状態", String.raw`\mathbf x_t^{\mathrm{tech}}`, "技術の検証済み進捗を遷移確率、残課題、終端条件へ接続する。"),
  "decision_state.manufacturing_state": state("製造・再現性状態", String.raw`\mathbf x_t^{\mathrm{mfg}}`, "量産再現性・品質証拠を遷移確率、残費用、所要時間へ接続する。"),
  "decision_state.market_state": state("市場・相手方状態", String.raw`(\mathbf n_t,\boldsymbol\ell_t,\mathbf e_t)_{\mathrm{market}}`, "顧客確約、受容、競争・期限を市場経路の制約と遷移へ接続する。"),
  "decision_state.rights_state": state("権利・契約・統治状態", String.raw`\mathbf k_t`, "許認可、契約、決裁権限を行動の実行可能集合へ接続する。"),
  "decision_state.organization_state": state("組織実行能力の推定状態", String.raw`\widehat{\mathbf c}_t`, "反復記録から得た能力posteriorを次状態と所要時間の予測へ使う。"),
  "decision_state.cash_state": state("使途別現金状態", String.raw`\mathbf r_t^{\mathrm{cash}}`, "行動の資金制約と無資金経路の最初のcash cliffを判定する。"),
  "decision_state.slack_state": state("戦略余力の型付き診断", String.raw`(\Gamma,\mathcal K,T_Y)_t`, "実行可能行動、頑健捕捉領域、経路喪失時点を分けて保持する。"),
  "decision_state.belief_state": state("未確定事象の信念状態", String.raw`\mathbf b_t=\Pr(\theta\mid\mathcal I_t)`, "技術・採用・調達などの信念をgateと物理遷移へ接続する。"),
  "decision_state.decision_controller": state("意思決定主体", String.raw`d`, "どの主体が方針を選び、その目的を最大化するかを固定する。"),
  "decision_state.controller_objective": state("意思決定主体の目的", String.raw`u_d`, "行動価値J_{u_d}(\mathbf s,\mathbf z)を比較する評価視点を定める。"),
  "decision_state.sunk_cost": state("既発生費用", String.raw`C_{\mathrm{sunk}}`, "開示には残すが、将来行動の比較目的からは除外する。"),
  "decision_state.remaining_cost": state("目標までの残費用", String.raw`C_{\mathrm{rem}}(\mathbf s_t)`, "必要資金、遷移CF、投入増分の効果を見積もる基礎状態になる。"),
  "decision_state.remaining_time": state("目標までの残時間", String.raw`T_{\mathrm{rem}}(\mathbf s_t)`, "経済地平、期限、遷移所要時間との競争を判定する。"),
  "decision_state.available_information": state("利用可能情報集合", String.raw`\mathcal I_t`, "状態推定と信念更新に使った証拠範囲を固定し、後知恵を防ぐ。"),

  "action_bundle.action_id_bundle_id": control("行動・投入束ID", String.raw`\mathbf z_t=(a_t,\mathbf i_t)`, "実行する行動と投入資源を一つの制御として遷移・価値計算へ渡す。"),
  "action_bundle.component_kinds": control("標準行動構成", String.raw`\kappa(\mathbf z_t)`, "実験、採用、設備、営業など行動束を構成する標準要素を列挙する。"),
  "action_bundle.custom_components": control("固有行動構成", String.raw`\kappa_{\mathrm{custom}}(\mathbf z_t)`, "標準分類にないPJ固有の実行要素を欠落させず保持する。"),
  "action_bundle.sequence": control("行動実行順序", String.raw`\operatorname{seq}(\mathbf z_t)`, "順序依存の権限、期限、CF、状態遷移を時系列へ接続する。"),
  "action_bundle.shared_resources": control("共有資源使用量", String.raw`\mathbf r^{\mathrm{shared}}(\mathbf z_t)`, "CEO注意、研究者、設備、資金の同時使用をポートフォリオ制約へ渡す。"),
  "action_bundle.availability": control("行動の登録・利用状態", String.raw`\operatorname{avail}(\mathbf z_t)`, "登録済み、確認待ち、対象外を分け、未登録行動を実行可能と扱わない。"),
  "action_bundle.feasibility": control("行動実行可能性", String.raw`\{g_j,\sigma_j\}_{j\in\mathcal J(\mathbf z)}`, "数量・時間・権限・契約制約から\Gamma_{\mathrm{exec}}^{\mathrm{reg}}を作る。"),
  "action_bundle.authority": control("実行権限", String.raw`\operatorname{auth}(\mathbf z_t)`, "取締役会、株主、大学などの承認を実行可能性へ反映する。"),
  "action_bundle.consents": control("必要同意", String.raw`\mathcal A_{\mathrm{consent}}(\mathbf z_t)`, "相手方同意の充足・違反・不明を行動制約へ反映する。"),
  "action_bundle.financing_status": control("資金調達段階", String.raw`\phi_{\mathrm{fund}}(\mathbf z_t)`, "関心、term sheet、契約、着金を分けて資金実行可能性へ接続する。"),
  "action_bundle.committed_funding": control("拘束力ある確約資金", String.raw`F_{\mathrm{commit}}(\mathbf z_t)`, "期限まで利用可能な確約資金だけをcash cliffのcapacityへ入れる。"),
  "action_bundle.duration": control("行動所要時間", String.raw`\Delta t(\mathbf z_t)`, "次の判断時点、期限超過、割引期間を決める。"),
  "action_bundle.C_now": control("現在支出", String.raw`C_r^{\mathrm{now}}(\mathbf s,\mathbf z)`, "将来の正式計算契約用。現pilotでは月次CFへ既に含まれるため、J(a)から別途控除しない。"),
  "action_bundle.benefit_now": control("現在便益", String.raw`B_r^{\mathrm{now}}(\mathbf s,\mathbf z)`, "将来の正式計算契約用。現pilotでは別加算せず、状態遷移との二重計上を防ぐ。"),
  "action_bundle.required_funding": control("行動に必要な資金", String.raw`F_{\mathrm{req}}(\mathbf z_t)`, "無資金経路のminimum-cash補填額を行動の資金制約へ渡す。"),
  "action_bundle.information_gain": control("期待情報獲得", String.raw`\Delta\mathcal I(\mathbf z_t)`, "探索行動が不明制約や信念状態をどの結果集合へ更新するかを示す。"),

  "transition.transition_id": transition("状態遷移ID", String.raw`\mathrm{id}(\kappa_t)`, "状態・制御・次状態・所要時間の一組を一意に追跡する。"),
  "transition.p_phys": transition("ゲート別遷移確率", String.raw`p_i(a)`, "現pilotでは固定方針aのゲート別確率p_i(a)をJ(a)へ渡す。完全な物理遷移核P⁰ではない。"),
  "transition.next_state_id": transition("次状態ID", String.raw`\mathrm{id}(\mathbf s')`, "行動後に到達する状態を継続価値と次の実行可能集合へ接続する。"),
  "transition.terminal_outcome": transition("終端結果", String.raw`\zeta\in\mathcal T\cup\mathcal F`, "目標到達、hard failure、closureを排他的な終端分岐として固定する。"),
  "transition.T_C": transition("目標到達時間", String.raw`T_C(a)`, "固定方針aで目標集合へ初めて到達する経過時間を示す。"),
  "transition.T_Y": transition("戦略余力喪失時間", String.raw`T_Y^{2.2,a}`, "固定方針aが頑健捕捉領域から初めて外れる判断時点を示す。"),
  "transition.terminal_value": transition("目標到達後の終端価値", String.raw`TV_r(\zeta)`, "全条件通過分岐の将来価値をP(a)とJ(a)の成功脚へ渡す。"),
  "transition.failure_loss": transition("失敗損失の監査集計", "", "現pilotのJへ直接入る値ではない。Jは条件ごとの符号付き停止時価値を使い、この項目は監査用の集計としてだけ残す。"),
  "transition.transition_cf": transition("遷移区間CFの同値参照", String.raw`CF_r^{\mathrm{PV}}[j]\equiv A_j^{\mathrm{JPY}}`, "cashflow_ledger.model_amount_million_jpyと同じ月次CF列を遷移側から参照する互換slot。二度加算しない。"),

  "cashflow_ledger.cashflow_event_id": cashflow("キャッシュフロー事象ID", String.raw`e_j`, "一つの経済事象を一意にし、同じ金額の重複計上を防ぐ。"),
  "cashflow_ledger.economic_event_group_key": cashflow("経済事象グループ", String.raw`g(e_j)`, "複数脚が同じ経済事象に由来することを示し、nettingと重複検査に使う。"),
  "cashflow_ledger.perspective_leg": cashflow("評価視点別の脚", String.raw`\ell_{jr}`, "会社、BZSF、公共など視点rごとの負担・便益脚を分離する。"),
  "cashflow_ledger.owner": cashflow("価値・費用の帰属主体", String.raw`o(e_j)`, "そのCFを誰の価値台帳へ帰属させるかを決める。"),
  "cashflow_ledger.counterparty": cashflow("相手方", String.raw`c(e_j)`, "支払・受取の相手を示し、内部振替と外部価値を区別する。"),
  "cashflow_ledger.scope": cashflow("CFの対象範囲", String.raw`\operatorname{scope}(e_j)`, "PJ、会社、基金、公共など計算へ含める範囲を固定する。"),
  "cashflow_ledger.amount_currency": cashflow("原通貨", String.raw`\chi_j`, "原金額の通貨を保持し、換算前後の監査を可能にする。"),
  "cashflow_ledger.model_amount_million_jpy": cashflow("モデル用円換算額", String.raw`A_j^{\mathrm{JPY}}`, "換算後の金額を月次CF、P(a)、J(a)へ渡す。"),
  "cashflow_ledger.conversion_rate_to_jpy": cashflow("対円換算レート", String.raw`FX_j`, "原通貨額をA_j^{\mathrm{JPY}}へ変換する。"),
  "cashflow_ledger.conversion_rate_date": cashflow("換算レート基準日", String.raw`t_j^{FX}`, "どの時点の為替を使ったかを固定する。"),
  "cashflow_ledger.conversion_rate_source_ref": cashflow("換算レート根拠", String.raw`\operatorname{src}_j^{FX}`, "使用した為替レートの一次根拠を追跡する。"),
  "cashflow_ledger.conversion_rule_ref": cashflow("通貨換算規則", String.raw`\mathcal R_j^{FX}`, "期中平均、取引日、固定レートなど換算方法を固定する。"),
  "cashflow_ledger.timing": cashflow("CF発生時点", String.raw`t_j`, "各CFへ対応する割引d_{t_j}と経路生存重みs_{t_j}(a)を決める。"),
  "cashflow_ledger.nominal_or_real": cashflow("名目・実質区分", String.raw`\nu_j`, "物価基準と割引率の整合を保つ。"),
  "cashflow_ledger.price_base_date": cashflow("価格基準日", String.raw`t_j^{\mathrm{price}}`, "実質額をどの物価時点へ揃えたかを固定する。"),
  "cashflow_ledger.tax_treatment": cashflow("税務上の扱い", String.raw`\tau_j^{\mathrm{tax}}`, "税込・税抜、課税・非課税などを視点別CFへ反映する。"),
  "cashflow_ledger.tax_subject_ref": cashflow("税務扱いの根拠", String.raw`\operatorname{src}_j^{\mathrm{tax}}`, "税区分を決めた契約・制度・証拠を追跡する。"),
  "cashflow_ledger.source_ref": cashflow("CF根拠", String.raw`\operatorname{src}(e_j)`, "金額、時点、帰属を裏づける一次根拠へ接続する。"),
  "cashflow_ledger.information_cutoff": cashflow("CF情報締切", String.raw`\tau(e_j)`, "評価締切後に判明したCFを当時の計算へ混ぜない。"),
  "cashflow_ledger.included_in": cashflow("計算への包含先", String.raw`\mathcal V(e_j)`, "同じCFをtransition CF、P(a)、J(a)のどこで一度だけ数えるかを示す。"),
  "cashflow_ledger.perspective_attribution": cashflow("評価視点への帰属", String.raw`r(e_j)`, "同じ経済事象を会社・BZSF・公共の各視点へ正しく写像する。"),
  "cashflow_ledger.public_fiscal_amount": cashflow("公共財政額", String.raw`F_j^{\mathrm{public}}`, "補助、税収、行政支出など財政脚を公共視点へ渡す。"),
  "cashflow_ledger.public_social_benefit_vector": cashflow("社会便益ベクトル", String.raw`\mathbf B_j^{\mathrm{social}}`, "異なる単位の社会便益を換算前のベクトルとして保持する。"),
  "cashflow_ledger.public_social_converted_amount": cashflow("社会便益換算額", String.raw`B_j^{\mathrm{social},\yen}`, "事前登録した公共価値規則で換算した社会便益額を示す。"),
  "cashflow_ledger.public_aggregated_amount": cashflow("公共価値集約額", String.raw`A_j^{\mathrm{public}}`, "財政額と換算済み社会便益を公共視点の規則で集約する。"),
  "cashflow_ledger.public_aggregation_input_hash": cashflow("公共集約入力ハッシュ", String.raw`h_j^{\mathrm{public}}`, "集約に使った財政脚、便益ベクトル、換算規則の同一性を検査する。"),

  "intervention.intervention_id": intervention("介入ID", String.raw`d`, "比較する支援・介入を一意にし、無介入との差分を追跡する。"),
  "intervention.enabled": intervention("介入適用フラグ", String.raw`\mathbf 1\{d\ \mathrm{on}\}`, "scenarioで介入効果を有効化するかを明示する。"),
  "intervention.cost_effect": intervention("介入の費用効果", String.raw`\Delta C(d)`, "介入が現在支出・残費用をどう変えるかを行動価値へ渡す。"),
  "intervention.funding_effect": intervention("介入の資金効果", String.raw`\Delta F(d)`, "確約資金、必要資金、cash cliff capacityへの変化を渡す。"),
  "intervention.action_set_effect": intervention("介入の行動集合効果", String.raw`\Delta\Gamma(d)`, "介入で新たに開く、閉じる、確認済みになる行動を実行可能集合へ渡す。"),
  "intervention.transition_effect": intervention("介入の遷移効果", String.raw`\Delta\mathbb P^0_d`, "次状態と所要時間の物理分布が介入でどう変わるかを渡す。"),
  "intervention.terminal_effect": intervention("介入の終端価値効果", String.raw`\Delta TV_r(d)`, "介入が目標到達後または失敗時の残存価値をどう変えるかを渡す。"),
  "intervention.information_effect": intervention("介入の情報効果", String.raw`\Delta\mathcal I(d)`, "介入で得る証拠が信念と不明制約をどう更新するかを渡す。"),

  "derived_outputs.J_r": output("全分岐込み期待現在価値", String.raw`J_r(a)`, "固定方針aの途中CF、成功、失敗、残存価値を全分岐で加重した現在価値。"),
  "derived_outputs.E_V_net_given_G_a": output("全条件通過時の現在価値", String.raw`\operatorname E[V_{\mathrm{net}}\mid G,a]`, "固定方針aで登録条件Gをすべて通過した経路だけの現在価値。"),
  "derived_outputs.q_plan_pi0_Hv": output("既存固定計画の到達指標", String.raw`q_{\mathrm{plan}}^{\pi_0}(H_v)`, "測定済みの既存固定計画\pi_0が地平H_vまでに到達する指標。未測定なら対象外。"),
  "derived_outputs.V_r_pi0": output("既存固定計画の価値", String.raw`V_r^{\pi_0}`, "既存固定計画\pi_0を視点rから評価した価値。未登録なら別方針で補わない。"),
  "derived_outputs.pi_d_star": output("登録済み固定方針", String.raw`\pi_{\mathrm{reg}}=a`, "このpilotで評価する登録済み固定方針a。最適方針でも実行推奨でもない。"),
  "derived_outputs.q_G_pi_d_star": output("基準到達指数", String.raw`Q(a)=\prod_{i\in G}p_i(a)`, "登録済み固定方針aが登録条件Gを順に通るgate積proxy。校正済み確率ではない。"),
  "derived_outputs.V_r_pi_d_star": output("全分岐込み期待現在価値の同値参照", String.raw`V_r^{\pi_{\mathrm{reg}}}=J_r(a)`, "J_r(a)と同じ値を旧契約名で保持する互換slot。別の計算出力ではない。"),
  "derived_outputs.E_V_net_pi_given_G": output("全条件通過時価値の同値参照", String.raw`\operatorname E[V_{\mathrm{net}}^{\pi_{\mathrm{reg}}}\mid G]`, "E[V_{net}\mid G,a]と同じ値を旧契約名で保持する互換slot。"),
  "derived_outputs.Omega_d": output("介入の総価値", String.raw`\Omega_d`, "介入dによる費用、資金、行動集合、遷移、終端価値の総差分をまとめる。"),
  "derived_outputs.Delta_V_r_given_d": output("介入時の価値差", String.raw`\Delta V_{r\mid d}`, "同じcontroller・視点・評価規則の下で介入ありとなしの価値差を示す。"),
  "derived_outputs.expected_cumulative_funding": output("生存重み付き最小資金補填必要額", String.raw`\operatorname E[F_{\mathrm{topup}}(a)]`, "固定方針aの無資金残高経路で必要な最小補填額を生存重みで集約する互換出力。"),
  "derived_outputs.expected_failure_loss": output("期待失敗損失", String.raw`\operatorname E[L_{\mathrm{fail}}(a)]`, "固定方針aの各失敗分岐損失をその経路重みで集約する。"),
  "derived_outputs.expected_exit_value": output("期待失敗残存価値の符号付き参照", String.raw`\operatorname E[V_{\mathrm{fail}}(a)]=-\operatorname E[L_{\mathrm{fail}}(a)]`, "期待失敗損失と同じ失敗脚を価値符号で保持する互換slot。別の出口予測ではない。"),
} as const satisfies Record<string, Bzm22ParameterPresentationEntry>;

export type Bzm22ParameterId = keyof typeof BZM22_PARAMETER_PRESENTATION;

export const BZM22_PARAMETER_RELATIONS = {
  "version_horizon_rules.model_id": "guard",
  "version_horizon_rules.model_version": "guard",
  "version_horizon_rules.valuation_date": "direct",
  "version_horizon_rules.information_cutoff": "guard",
  "version_horizon_rules.currency": "guard",
  "version_horizon_rules.forward_validation_count": "guard",
  "version_horizon_rules.initial_state_id": "guard",
  "version_horizon_rules.H_v": "unused",
  "version_horizon_rules.H_econ": "direct",
  "version_horizon_rules.valuation_rule": "direct",
  "version_horizon_rules.decision_criterion": "unused",
  "version_horizon_rules.near_tie_tolerance": "unused",
  "version_horizon_rules.tie_break_rule": "unused",
  "version_horizon_rules.public_value_rule": "unused",

  "decision_state.state_id": "guard",
  "decision_state.decision_order": "guard",
  "decision_state.elapsed_months": "direct",
  "decision_state.technical_state": "indirect",
  "decision_state.manufacturing_state": "indirect",
  "decision_state.market_state": "indirect",
  "decision_state.rights_state": "indirect",
  "decision_state.organization_state": "indirect",
  "decision_state.cash_state": "direct",
  "decision_state.slack_state": "indirect",
  "decision_state.belief_state": "direct",
  "decision_state.decision_controller": "guard",
  "decision_state.controller_objective": "guard",
  "decision_state.sunk_cost": "unused",
  "decision_state.remaining_cost": "direct",
  "decision_state.remaining_time": "direct",
  "decision_state.available_information": "guard",

  "action_bundle.action_id_bundle_id": "guard",
  "action_bundle.component_kinds": "indirect",
  "action_bundle.custom_components": "indirect",
  "action_bundle.sequence": "indirect",
  "action_bundle.shared_resources": "unused",
  "action_bundle.availability": "guard",
  "action_bundle.feasibility": "guard",
  "action_bundle.authority": "guard",
  "action_bundle.consents": "guard",
  "action_bundle.financing_status": "guard",
  "action_bundle.committed_funding": "direct",
  "action_bundle.duration": "direct",
  "action_bundle.C_now": "unused",
  "action_bundle.benefit_now": "unused",
  "action_bundle.required_funding": "direct",
  "action_bundle.information_gain": "indirect",

  "transition.transition_id": "guard",
  "transition.p_phys": "direct",
  "transition.next_state_id": "indirect",
  "transition.terminal_outcome": "direct",
  "transition.T_C": "output",
  "transition.T_Y": "output",
  "transition.terminal_value": "direct",
  "transition.failure_loss": "unused",
  "transition.transition_cf": "alias",

  "cashflow_ledger.cashflow_event_id": "guard",
  "cashflow_ledger.economic_event_group_key": "guard",
  "cashflow_ledger.perspective_leg": "guard",
  "cashflow_ledger.owner": "guard",
  "cashflow_ledger.counterparty": "guard",
  "cashflow_ledger.scope": "guard",
  "cashflow_ledger.amount_currency": "guard",
  "cashflow_ledger.model_amount_million_jpy": "direct",
  "cashflow_ledger.conversion_rate_to_jpy": "indirect",
  "cashflow_ledger.conversion_rate_date": "guard",
  "cashflow_ledger.conversion_rate_source_ref": "guard",
  "cashflow_ledger.conversion_rule_ref": "guard",
  "cashflow_ledger.timing": "direct",
  "cashflow_ledger.nominal_or_real": "guard",
  "cashflow_ledger.price_base_date": "guard",
  "cashflow_ledger.tax_treatment": "indirect",
  "cashflow_ledger.tax_subject_ref": "guard",
  "cashflow_ledger.source_ref": "guard",
  "cashflow_ledger.information_cutoff": "guard",
  "cashflow_ledger.included_in": "guard",
  "cashflow_ledger.perspective_attribution": "guard",
  "cashflow_ledger.public_fiscal_amount": "unused",
  "cashflow_ledger.public_social_benefit_vector": "unused",
  "cashflow_ledger.public_social_converted_amount": "unused",
  "cashflow_ledger.public_aggregated_amount": "unused",
  "cashflow_ledger.public_aggregation_input_hash": "unused",

  "intervention.intervention_id": "guard",
  "intervention.enabled": "guard",
  "intervention.cost_effect": "unused",
  "intervention.funding_effect": "unused",
  "intervention.action_set_effect": "unused",
  "intervention.transition_effect": "unused",
  "intervention.terminal_effect": "unused",
  "intervention.information_effect": "unused",

  "derived_outputs.J_r": "output",
  "derived_outputs.E_V_net_given_G_a": "output",
  "derived_outputs.q_plan_pi0_Hv": "unused",
  "derived_outputs.V_r_pi0": "unused",
  "derived_outputs.pi_d_star": "output",
  "derived_outputs.q_G_pi_d_star": "output",
  "derived_outputs.V_r_pi_d_star": "alias",
  "derived_outputs.E_V_net_pi_given_G": "alias",
  "derived_outputs.Omega_d": "unused",
  "derived_outputs.Delta_V_r_given_d": "unused",
  "derived_outputs.expected_cumulative_funding": "output",
  "derived_outputs.expected_failure_loss": "output",
  "derived_outputs.expected_exit_value": "alias",
} as const satisfies Record<Bzm22ParameterId, Bzm22ParameterRelation>;

/** 理論本文に対応がある場合だけ置く。管理・根拠・識別用の項目は空文字のままにする。 */
export const BZM22_PARAMETER_THEORY_SYMBOLS = {
  "version_horizon_rules.model_id": "",
  "version_horizon_rules.model_version": "",
  "version_horizon_rules.valuation_date": "",
  "version_horizon_rules.information_cutoff": "",
  "version_horizon_rules.currency": "",
  "version_horizon_rules.forward_validation_count": "",
  "version_horizon_rules.initial_state_id": "",
  "version_horizon_rules.H_v": String.raw`H_v`,
  "version_horizon_rules.H_econ": String.raw`H_{\mathrm{econ}}`,
  "version_horizon_rules.valuation_rule": String.raw`M_r`,
  "version_horizon_rules.decision_criterion": "",
  "version_horizon_rules.near_tie_tolerance": "",
  "version_horizon_rules.tie_break_rule": "",
  "version_horizon_rules.public_value_rule": "",

  "decision_state.state_id": "",
  "decision_state.decision_order": "",
  "decision_state.elapsed_months": String.raw`t`,
  "decision_state.technical_state": String.raw`\mathbf x_t`,
  "decision_state.manufacturing_state": String.raw`\mathbf x_t`,
  "decision_state.market_state": String.raw`(\mathbf n_t,\boldsymbol\ell_t,\mathbf e_t)`,
  "decision_state.rights_state": String.raw`\mathbf k_t`,
  "decision_state.organization_state": String.raw`\widehat{\mathbf c}_t`,
  "decision_state.cash_state": String.raw`\mathbf r_t`,
  "decision_state.slack_state": "",
  "decision_state.belief_state": String.raw`\mathbf b_t`,
  "decision_state.decision_controller": String.raw`d`,
  "decision_state.controller_objective": String.raw`u_d`,
  "decision_state.sunk_cost": "",
  "decision_state.remaining_cost": "",
  "decision_state.remaining_time": "",
  "decision_state.available_information": String.raw`\mathcal I_t`,

  "action_bundle.action_id_bundle_id": "",
  "action_bundle.component_kinds": "",
  "action_bundle.custom_components": "",
  "action_bundle.sequence": "",
  "action_bundle.shared_resources": String.raw`\mathbf r_t^{\mathrm{shared}}`,
  "action_bundle.availability": "",
  "action_bundle.feasibility": String.raw`\{g_j,\sigma_j\}_{j\in\mathcal J(\mathbf z)}`,
  "action_bundle.authority": "",
  "action_bundle.consents": "",
  "action_bundle.financing_status": "",
  "action_bundle.committed_funding": "",
  "action_bundle.duration": String.raw`\Delta t`,
  "action_bundle.C_now": "",
  "action_bundle.benefit_now": "",
  "action_bundle.required_funding": String.raw`F_{\mathrm{req}}(a)`,
  "action_bundle.information_gain": String.raw`\Delta\mathcal I(a)`,

  "transition.transition_id": "",
  "transition.p_phys": String.raw`p_i(a)`,
  "transition.next_state_id": "",
  "transition.terminal_outcome": String.raw`\zeta\in\mathcal T\cup\mathcal F`,
  "transition.T_C": String.raw`T_C(a)`,
  "transition.T_Y": String.raw`T_Y^{2.2,a}`,
  "transition.terminal_value": String.raw`TV(a)`,
  "transition.failure_loss": "",
  "transition.transition_cf": String.raw`CF_t(a)`,

  "cashflow_ledger.cashflow_event_id": "",
  "cashflow_ledger.economic_event_group_key": "",
  "cashflow_ledger.perspective_leg": "",
  "cashflow_ledger.owner": "",
  "cashflow_ledger.counterparty": "",
  "cashflow_ledger.scope": "",
  "cashflow_ledger.amount_currency": "",
  "cashflow_ledger.model_amount_million_jpy": String.raw`CF_t(a)`,
  "cashflow_ledger.conversion_rate_to_jpy": "",
  "cashflow_ledger.conversion_rate_date": "",
  "cashflow_ledger.conversion_rate_source_ref": "",
  "cashflow_ledger.conversion_rule_ref": "",
  "cashflow_ledger.timing": String.raw`t`,
  "cashflow_ledger.nominal_or_real": "",
  "cashflow_ledger.price_base_date": "",
  "cashflow_ledger.tax_treatment": "",
  "cashflow_ledger.tax_subject_ref": "",
  "cashflow_ledger.source_ref": "",
  "cashflow_ledger.information_cutoff": "",
  "cashflow_ledger.included_in": "",
  "cashflow_ledger.perspective_attribution": "",
  "cashflow_ledger.public_fiscal_amount": "",
  "cashflow_ledger.public_social_benefit_vector": "",
  "cashflow_ledger.public_social_converted_amount": "",
  "cashflow_ledger.public_aggregated_amount": "",
  "cashflow_ledger.public_aggregation_input_hash": "",

  "intervention.intervention_id": "",
  "intervention.enabled": "",
  "intervention.cost_effect": "",
  "intervention.funding_effect": "",
  "intervention.action_set_effect": "",
  "intervention.transition_effect": "",
  "intervention.terminal_effect": "",
  "intervention.information_effect": "",

  "derived_outputs.J_r": String.raw`J_r(a)`,
  "derived_outputs.E_V_net_given_G_a": String.raw`P(a)=\operatorname E[V_{\mathrm{net}}\mid G,a]`,
  "derived_outputs.q_plan_pi0_Hv": String.raw`q_{\mathrm{plan}}^{\pi_0}(H_v)`,
  "derived_outputs.V_r_pi0": String.raw`V_r^{\pi_0}`,
  "derived_outputs.pi_d_star": String.raw`\pi_{\mathrm{reg}}=a`,
  "derived_outputs.q_G_pi_d_star": String.raw`Q(a)=\prod_{i\in G}p_i(a)`,
  "derived_outputs.V_r_pi_d_star": String.raw`V_r^{\pi_{\mathrm{reg}}}=J_r(a)`,
  "derived_outputs.E_V_net_pi_given_G": String.raw`\operatorname E[V_{\mathrm{net}}^{\pi_{\mathrm{reg}}}\mid G]=P(a)`,
  "derived_outputs.Omega_d": String.raw`\Omega_d`,
  "derived_outputs.Delta_V_r_given_d": String.raw`\Delta V_{r\mid d}`,
  "derived_outputs.expected_cumulative_funding": String.raw`\operatorname E[F_{\mathrm{topup}}(a)]`,
  "derived_outputs.expected_failure_loss": String.raw`\operatorname E[L_{\mathrm{fail}}(a)]`,
  "derived_outputs.expected_exit_value": String.raw`-\operatorname E[L_{\mathrm{fail}}(a)]`,
} as const satisfies Record<Bzm22ParameterId, string>;

export const BZM22_PARAMETER_FORMULA_REFS = {
  "version_horizon_rules.model_id": ["F0"],
  "version_horizon_rules.model_version": ["F0"],
  "version_horizon_rules.valuation_date": ["F0"],
  "version_horizon_rules.information_cutoff": ["F0"],
  "version_horizon_rules.currency": ["F0"],
  "version_horizon_rules.forward_validation_count": ["F0"],
  "version_horizon_rules.initial_state_id": ["F0", "F1"],
  "version_horizon_rules.H_v": ["F0", "F7", "F8"],
  "version_horizon_rules.H_econ": ["F0", "F9", "F10"],
  "version_horizon_rules.valuation_rule": ["F0", "F5", "F9", "F10"],
  "version_horizon_rules.decision_criterion": ["F0"],
  "version_horizon_rules.near_tie_tolerance": ["F0"],
  "version_horizon_rules.tie_break_rule": ["F0"],
  "version_horizon_rules.public_value_rule": ["F0", "F5"],

  "decision_state.state_id": ["F1"],
  "decision_state.decision_order": ["F1"],
  "decision_state.elapsed_months": ["F1", "F5"],
  "decision_state.technical_state": ["F1", "F4"],
  "decision_state.manufacturing_state": ["F1", "F4"],
  "decision_state.market_state": ["F1", "F4"],
  "decision_state.rights_state": ["F1", "F3"],
  "decision_state.organization_state": ["F1", "F4"],
  "decision_state.cash_state": ["F1", "F3", "F11"],
  "decision_state.slack_state": ["F13"],
  "decision_state.belief_state": ["F1", "F4", "F7"],
  "decision_state.decision_controller": ["F0", "F1"],
  "decision_state.controller_objective": ["F0", "F10"],
  "decision_state.sunk_cost": ["—"],
  "decision_state.remaining_cost": ["F1", "F11"],
  "decision_state.remaining_time": ["F1", "F4"],
  "decision_state.available_information": ["F0", "F1"],

  "action_bundle.action_id_bundle_id": ["F2"],
  "action_bundle.component_kinds": ["F2"],
  "action_bundle.custom_components": ["F2"],
  "action_bundle.sequence": ["F2", "F4"],
  "action_bundle.shared_resources": ["F2", "F3"],
  "action_bundle.availability": ["F2", "F3"],
  "action_bundle.feasibility": ["F3"],
  "action_bundle.authority": ["F3"],
  "action_bundle.consents": ["F3"],
  "action_bundle.financing_status": ["F3", "F11"],
  "action_bundle.committed_funding": ["F11"],
  "action_bundle.duration": ["F2", "F4", "F5"],
  "action_bundle.C_now": ["—"],
  "action_bundle.benefit_now": ["—"],
  "action_bundle.required_funding": ["F11"],
  "action_bundle.information_gain": ["F2", "F4"],

  "transition.transition_id": ["F4"],
  "transition.p_phys": ["F4", "F7", "F8", "F10"],
  "transition.next_state_id": ["F4"],
  "transition.terminal_outcome": ["F4", "F6"],
  "transition.T_C": ["F4", "F7"],
  "transition.T_Y": ["F13"],
  "transition.terminal_value": ["F6", "F9", "F10"],
  "transition.failure_loss": ["F6", "F10"],
  "transition.transition_cf": ["F5", "F10"],

  "cashflow_ledger.cashflow_event_id": ["F0", "F5"],
  "cashflow_ledger.economic_event_group_key": ["F0", "F5"],
  "cashflow_ledger.perspective_leg": ["F5"],
  "cashflow_ledger.owner": ["F0", "F5"],
  "cashflow_ledger.counterparty": ["F0"],
  "cashflow_ledger.scope": ["F0", "F5"],
  "cashflow_ledger.amount_currency": ["F0", "F5"],
  "cashflow_ledger.model_amount_million_jpy": ["F5", "F9", "F10"],
  "cashflow_ledger.conversion_rate_to_jpy": ["F5"],
  "cashflow_ledger.conversion_rate_date": ["F0", "F5"],
  "cashflow_ledger.conversion_rate_source_ref": ["F0"],
  "cashflow_ledger.conversion_rule_ref": ["F0", "F5"],
  "cashflow_ledger.timing": ["F5", "F9", "F10"],
  "cashflow_ledger.nominal_or_real": ["F0", "F5"],
  "cashflow_ledger.price_base_date": ["F0", "F5"],
  "cashflow_ledger.tax_treatment": ["F0", "F5"],
  "cashflow_ledger.tax_subject_ref": ["F0"],
  "cashflow_ledger.source_ref": ["F0"],
  "cashflow_ledger.information_cutoff": ["F0"],
  "cashflow_ledger.included_in": ["F0", "F5"],
  "cashflow_ledger.perspective_attribution": ["F0", "F5"],
  "cashflow_ledger.public_fiscal_amount": ["F5"],
  "cashflow_ledger.public_social_benefit_vector": ["F5"],
  "cashflow_ledger.public_social_converted_amount": ["F5"],
  "cashflow_ledger.public_aggregated_amount": ["F5"],
  "cashflow_ledger.public_aggregation_input_hash": ["F0"],

  "intervention.intervention_id": ["F0", "F14"],
  "intervention.enabled": ["F0", "F14"],
  "intervention.cost_effect": ["F14"],
  "intervention.funding_effect": ["F14"],
  "intervention.action_set_effect": ["F14"],
  "intervention.transition_effect": ["F14"],
  "intervention.terminal_effect": ["F14"],
  "intervention.information_effect": ["F14"],

  "derived_outputs.J_r": ["F10", "J"],
  "derived_outputs.E_V_net_given_G_a": ["F9", "P"],
  "derived_outputs.q_plan_pi0_Hv": ["—"],
  "derived_outputs.V_r_pi0": ["—"],
  "derived_outputs.pi_d_star": ["F0", "F2"],
  "derived_outputs.q_G_pi_d_star": ["F7", "Q"],
  "derived_outputs.V_r_pi_d_star": ["F10", "J"],
  "derived_outputs.E_V_net_pi_given_G": ["F9", "P"],
  "derived_outputs.Omega_d": ["—"],
  "derived_outputs.Delta_V_r_given_d": ["F14"],
  "derived_outputs.expected_cumulative_funding": ["F12"],
  "derived_outputs.expected_failure_loss": ["F10"],
  "derived_outputs.expected_exit_value": ["F10"],
} as const satisfies Record<Bzm22ParameterId, readonly Bzm22FormulaRef[]>;

function dataNameTex(id: Bzm22ParameterId) {
  return String.raw`\mathtt{${id.replaceAll("_", String.raw`\_`)}}`;
}

export const BZM22_PARAMETER_CATALOG = Object.fromEntries(
  (Object.keys(BZM22_PARAMETER_PRESENTATION) as Bzm22ParameterId[]).map((id) => {
    const presentation = BZM22_PARAMETER_PRESENTATION[id];
    const relation = BZM22_PARAMETER_RELATIONS[id];
    return [id, {
      ...presentation,
      dataNameTex: dataNameTex(id),
      symbolTex: BZM22_PARAMETER_THEORY_SYMBOLS[id],
      formulaRefs: BZM22_PARAMETER_FORMULA_REFS[id],
      relation,
      relationLabel: BZM22_PARAMETER_RELATION_LABELS[relation],
    }];
  }),
) as unknown as { readonly [K in Bzm22ParameterId]: Bzm22ParameterCatalogEntry };

export function getBzm22ParameterCatalogEntry(id: string): Bzm22ParameterCatalogEntry {
  const catalog = BZM22_PARAMETER_CATALOG as Record<string, Bzm22ParameterCatalogEntry>;
  const found = catalog[id];
  if (!found) throw new Error(`BZM 2.2 parameter catalog missing: ${id}`);
  return found;
}
