import type { CockpitData } from "@/lib/supabase-data";
import type { VentureRow } from "@/lib/venture-map-data";

export const AAA_PROJECT_ID = "p99";

export const aaaVenture: VentureRow = {
  project_id: AAA_PROJECT_ID,
  project_name: "AAA",
  short_label: "AAA",
  lane: "gx_energy",
  lanes: [
    { domain: "energy_environment", weight: 0.38 },
    { domain: "advanced_materials_manufacturing", weight: 0.24 },
    { domain: "ai_technologies", weight: 0.2 },
    { domain: "defence_space_robotics_transport", weight: 0.18 },
  ],
  founded_at: "2025-07-01",
  status: "active",
  outcome_pattern: "rocket",
  origin_org: "Tokyo Frontier Lab",
  origin_pi: "Dr. Arai",
  amd_role: "venture architect / founding sales / governance design",
  short_description:
    "Autonomous Adaptive Assembly。老朽インフラと分散型エネルギー設備を対象に、現場ロボット、異常検知AI、遠隔オペレーションを束ねる次世代フィールドOS。",
  is_public: true,
  amd_support_started_at: "2024-06-01",
  amd_support_ended_at: null,
};

export const aaaCockpitData: CockpitData = {
  project: {
    projectId: AAA_PROJECT_ID,
    projectName: "AAA",
    clientName: "Autonomous Adaptive Assembly",
    status: "active",
    projectType: "startup_studio",
  },
  currentYm: "202605",
  billingCycles: ["202605", "202604", "202603", "202602", "202601", "202512"].map((ym, index) => ({
    projectId: AAA_PROJECT_ID,
    ym,
    status: "active",
    budgetYen: 1_800_000,
    budgetReportedAmount: 1_800_000,
    meetingStartAt: index === 0 ? null : `${ym.slice(0, 4)}-${ym.slice(4)}-24T10:00:00+09:00`,
    meetingEventId: index === 0 ? null : `aaa-mtg-${ym}`,
    reportFixedAt: index === 0 ? null : `${ym.slice(0, 4)}-${ym.slice(4)}-27T18:00:00+09:00`,
    budgetConfirmedAt: `${ym.slice(0, 4)}-${ym.slice(4)}-03T09:00:00+09:00`,
    invoiceIssuedAt: index === 0 ? null : `${ym.slice(0, 4)}-${ym.slice(4)}-28T12:00:00+09:00`,
    invoiceSentAt: index === 0 ? null : `${ym.slice(0, 4)}-${ym.slice(4)}-28T13:00:00+09:00`,
    payoutNoticeUploadedAt: index === 0 ? null : `${ym.slice(0, 4)}-${ym.slice(4)}-29T11:00:00+09:00`,
    paymentConfirmedAt: index < 2 ? null : `${ym.slice(0, 4)}-${ym.slice(4)}-30T15:00:00+09:00`,
    reimburseConfirmDone: index !== 0,
    rewardPaidAt: index < 2 ? null : `${ym.slice(0, 4)}-${ym.slice(4)}-30T16:00:00+09:00`,
    invoiceYm: ym,
    invoiceBaseLinesJson: null,
    invoiceSubject: "AAA venture architecture retainer",
    msProgressSummaryJson: null,
    rewardSummaryJson: null,
  })),
  planCycle: {
    planCycleId: "PC-p99-202504",
    projectId: AAA_PROJECT_ID,
    status: "active",
    budgetYen: 21_600_000,
    totalPoints: 180,
    periodStartYm: "202504",
    periodEndYm: "202606",
  },
  milestones: [
    {
      milestoneId: "aaa-ms1",
      planCycleId: "PC-p99-202504",
      title: "Flagship PoC to paid deployment",
      points: 62,
      tag: "SALES",
      goalLevel: "L1",
      isActive: true,
      successCriteria: "3社PoCのうち2社を年額契約へ移行し、現場運用KPIを月次で回せる状態にする。",
      sortOrder: 1,
    },
    {
      milestoneId: "aaa-ms2",
      planCycleId: "PC-p99-202504",
      title: "Autonomous inspection productization",
      points: 68,
      tag: "PRODUCT",
      goalLevel: "L1",
      isActive: true,
      successCriteria: "異常検知、遠隔介入、作業ログ監査を1つのoperator cockpitへ統合する。",
      sortOrder: 2,
    },
    {
      milestoneId: "aaa-ms3",
      planCycleId: "PC-p99-202504",
      title: "Governance and founder operating rhythm",
      points: 50,
      tag: "ORG",
      goalLevel: "L1",
      isActive: true,
      successCriteria: "安全責任分界、月次board pack、採用scorecardを固定し、CEO候補へ運用移譲する。",
      sortOrder: 3,
    },
  ],
  progress: [
    { milestoneKey: "aaa-ms1", ym: "202605", progressPct: 86, consumedPt: 53, source: "demo", note: "2社で有償トライアル契約済み。残り1社は6月稟議。", confirmedAt: null },
    { milestoneKey: "aaa-ms2", ym: "202605", progressPct: 78, consumedPt: 53, source: "demo", note: "夜間巡回と異音検知は安定。遠隔介入UIを磨き込み中。", confirmedAt: null },
    { milestoneKey: "aaa-ms3", ym: "202605", progressPct: 72, consumedPt: 36, source: "demo", note: "CEO候補と週次operating rhythmを開始。", confirmedAt: null },
  ],
  reports: [
    {
      reportId: "aaa-report-202605",
      projectId: AAA_PROJECT_ID,
      ym: "202605",
      status: "draft",
      draftExcerpt: "AAAはPoCから有償導入へ移行する局面。M/X/Fともに上昇し、特にBRL/HRLの改善がスコアを押し上げた。",
      finalExcerpt: "",
      hasDraft: true,
      hasFinal: false,
      generatedAt: "2026-05-16T10:00:00+09:00",
      fixedAt: null,
    },
  ],
  members: ["masa", "eimi", "riri"],
  nudges: [
    { message: "p99: 6月board packに、初回有償契約のARR感度表を追加", status: "open", level: "high", postedAt: null },
    { message: "p99: CEO候補面談メモをFRL根拠へ反映", status: "open", level: "medium", postedAt: null },
  ],
  tasks: [
    { taskId: "aaa-task-1", title: "Paid pilot LOI final check", status: "doing", assignee: "masa", priority: "high", milestoneId: "aaa-ms1" },
    { taskId: "aaa-task-2", title: "Operator cockpit demo script", status: "todo", assignee: "eimi", priority: "high", milestoneId: "aaa-ms2" },
    { taskId: "aaa-task-3", title: "CEO candidate weekly rhythm design", status: "review", assignee: "riri", priority: "medium", milestoneId: "aaa-ms3" },
  ],
  subItems: [
    { subItemId: "aaa-sub-1", milestoneId: "aaa-ms1", title: "ARR model and renewal trigger", weight: 0.34, status: "doing", assignee: "masa" },
    { subItemId: "aaa-sub-2", milestoneId: "aaa-ms2", title: "Remote intervention UX", weight: 0.42, status: "doing", assignee: "eimi" },
    { subItemId: "aaa-sub-3", milestoneId: "aaa-ms3", title: "Founder scorecard", weight: 0.24, status: "review", assignee: "riri" },
  ],
  responsibilities: [
    { milestoneId: "aaa-ms1", memberId: "masa", share: 0.5, role: "統括" },
    { milestoneId: "aaa-ms2", memberId: "eimi", share: 0.35, role: "担当" },
    { milestoneId: "aaa-ms3", memberId: "riri", share: 0.15, role: "レビュー" },
  ],
  memberMap: { masa: "まさ", eimi: "えいみ", riri: "りり" },
  pastPlanCycles: [],
  msActivities: [
    { memberId: "masa", milestoneId: "aaa-ms1", ym: "202605", narrative: "有償化の意思決定者を現場部長から経営企画へ引き上げた。", generatedAt: "2026-05-16T10:00:00+09:00" },
    { memberId: "eimi", milestoneId: "aaa-ms2", ym: "202605", narrative: "demo cockpitの見せ方を、異常検知より運用意思決定に寄せた。", generatedAt: "2026-05-16T10:00:00+09:00" },
  ],
  memberActivities: [
    {
      id: "aaa-act-1",
      memberId: "masa",
      projectId: AAA_PROJECT_ID,
      ym: "202605",
      source: "meeting",
      sourceItemId: "aaa-mtg-202605",
      milestoneId: "aaa-ms1",
      title: "Paid deployment negotiation",
      contentPreview: "現場KPI、保険料低減、作業停止時間の削減を束ねたROI説明で先方役員の合意を獲得。",
      itemDate: "2026-05-14",
      extractedAt: "2026-05-16T10:00:00+09:00",
    },
  ],
  seasonFinance: null,
  msChangeHistory: [],
  strategySignals: [
    {
      signalId: "aaa-signal-1",
      projectId: AAA_PROJECT_ID,
      ym: "202605",
      signalDate: "2026-05-14",
      signalType: "commercial_progress",
      title: "有償導入の意思決定者を経営企画へ引き上げ",
      summary: "現場PoCから、保険料低減と作業停止時間削減を含むROI説明へ切り替え、初回有償導入の稟議ルートを経営企画へ移した。",
      impactLevel: "high",
      decisionState: "executing",
      status: "confirmed",
      sourceRefs: [{ source: "demo", date: "2026-05-14", snippet: "Paid deployment negotiation" }],
      sourceHash: "demo-aaa-signal-1",
      originKind: "internal",
      researchCategory: null,
      confidence: 0.86,
      createdAt: "2026-05-16T10:00:00+09:00",
      confirmedAt: "2026-05-16T10:00:00+09:00",
    },
    {
      signalId: "aaa-research-1",
      projectId: AAA_PROJECT_ID,
      ym: "202608",
      signalDate: "2026-08-10",
      signalType: "funding",
      title: "現場導入型ロボットの実証支援公募が開始",
      summary: "実証費と現場連携費が対象。次の導入先候補と組んだ申請可否を、締切前に判断できる材料として採用した。",
      impactLevel: "medium",
      decisionState: "observed",
      status: "confirmed",
      sourceRefs: [{ source: "公募主体", date: "2026-08-10", snippet: "実証支援の公募概要" }],
      sourceHash: "demo-aaa-research-1",
      originKind: "external_research",
      researchCategory: "grant",
      confidence: 0.9,
      createdAt: "2026-08-10T09:00:00+09:00",
      confirmedAt: "2026-08-10T09:10:00+09:00",
    },
  ],
};
