export type RawDataSource = {
  id: string;
  label: string;
  owner: string;
  refresh: string;
  landsIn: string[];
  notes: string;
};

export type L2Dataset = {
  id: string;
  label: string;
  table: string;
  source: string;
  cadence: string;
  purpose: string;
};

export type CronOperation = {
  id: string;
  label: string;
  layer: "GAS" | "PWA" | "Codex" | "Claude";
  cadence: string;
  trigger: string;
  defaultParams: string;
  input: string;
  output: string;
  run:
    | { type: "gas"; functionName: string; defaultArgs: unknown[] }
    | { type: "pwa"; path: string; defaultQuery?: Record<string, string | number | boolean> }
    | { type: "manual"; reason: string };
};

const CLAUDE_ROUTINE_MANUAL_REASON =
  "Claude routine (= ~/.claude/scheduled-tasks/) は scheduled-tasks MCP で登録された local cron。PWA からは直接叩けない (= まさ手元 mac の Claude Code セッション内でのみ自動発火)。手動キックは scheduled-tasks MCP 経由か Claude Code セッションで SKILL.md を直接実行";

export const rawDataSources: RawDataSource[] = [
  {
    id: "calendar",
    label: "Google Calendar",
    owner: "GAS",
    refresh: "毎時0分",
    landsIn: ["project_meeting_summaries", "meeting_notifications", "project_strategy_signals"],
    notes: "会議eventを主軸に、終了60-180分後のPJ関連MTGを拾う。",
  },
  {
    id: "notion-minutes",
    label: "Notion AI 議事録",
    owner: "GAS",
    refresh: "Calendar polling時 / 03:00 fallback",
    landsIn: ["project_meeting_summaries", "project_strategy_signals"],
    notes: "eventId / 日付 / PJ relation が空でも、title+date fallbackで拾ってself-healする。",
  },
  {
    id: "gmail",
    label: "Gmail / CircleBack / Meet",
    owner: "GAS + PWA",
    refresh: "MTG抽出時 / source collect時",
    landsIn: ["project_meeting_summaries", "source_cache", "member_activities", "project_strategy_signals"],
    notes: "reportEmails と会議日付周辺で議事録メール・録画通知・関係先往復を拾う。",
  },
  {
    id: "slack",
    label: "Slack",
    owner: "GAS/PWA connectors",
    refresh: "backfill / L2 source collect",
    landsIn: ["project_meeting_summaries", "member_activities", "source_cache", "project_strategy_signals"],
    notes: "PJ channel / thread から進捗・論点・メンバー活動を抽出する。",
  },
  {
    id: "drive",
    label: "Google Drive",
    owner: "GAS/PWA",
    refresh: "monthly / backfill / source collect",
    landsIn: ["project_meeting_summaries", "monthly_reports", "source_cache", "project_strategy_signals"],
    notes: "議事録doc、月次資料、PJ関連ファイルを情報源にする。",
  },
  {
    id: "web-external",
    label: "Web / 外部シグナル",
    owner: "PWA + Codex automation",
    refresh: "daily / weekly / monthly",
    landsIn: ["atlas_stories", "atlas_signals", "macro_index_log", "vc_news"],
    notes: "Atlas、政策、VC、Macrotrend系の外部観測。L2⑪⑫⑮のexternal provenance。",
  },
];

export const l2Datasets: L2Dataset[] = [
  {
    id: "monthly_reports",
    label: "① monthly report",
    table: "monthly_reports",
    source: "Month-end Codex / subscription automation AMD OS L2① 月次報告抽出 / amd-os-ms outbox.monthlyReports (R313 triggerなし確認: 2026-05-29)",
    cadence: "month-end only",
    purpose: "PJ月次レポート本文。後続L2の二次集約ソース。L2⑧ XRL checklist audit の直前入力。",
  },
  {
    id: "protocols",
    label: "② AMDプロトコル",
    table: "protocols / protocol_examples",
    source: "Codex automation / legacy GAS 155",
    cadence: "停止中",
    purpose: "経営判断を、分岐点・判断材料・アクション・結果学習に構造化する。",
  },
  {
    id: "ms_progress",
    label: "③ MS進捗",
    table: "milestone_monthly_progress",
    source: "MMO/Codex automation amd-os-l3-ms-progress-extract / Codex automation review",
    cadence: "毎時 polling (subscription automation)",
    purpose: "月次報告書・MTGサマリ・MS設計から月次進捗%を推定し、Codex automationで修正候補レビューを回す。",
  },
  {
    id: "project_knowledge",
    label: "④ PJナレッジ",
    table: "project_knowledge",
    source: "Codex automation / legacy GAS 155",
    cadence: "停止中",
    purpose: "PJの人物・組織・事実・進行中事項を更新する。",
  },
  {
    id: "member_knowledge",
    label: "⑤ メンバーナレッジ",
    table: "member_knowledge",
    source: "Codex automation / legacy GAS 155",
    cadence: "停止中",
    purpose: "メンバーごとの強み・スキル・関心・最近の活動を抽出する。",
  },
  {
    id: "meeting_summaries",
    label: "⑥ MTGサマリ",
    table: "project_meeting_summaries",
    source: "Codex automation / legacy GAS 153 + 074",
    cadence: "停止中",
    purpose: "calendar event単位で決定・進捗・next action・riskを残す。",
  },
  {
    id: "registry_diffs",
    label: "⑦ OS台帳差分",
    table: "project_registry_diffs",
    source: "Codex automation / future cron",
    cadence: "review batch",
    purpose: "5生データとOS台帳を突合し、反映候補を通知で採否する。",
  },
  {
    id: "xrl_evidence",
    label: "⑧ XRL checklist audit",
    table: "amd_score_inputs.xrl_checklist / xrl_notes / project_founding_members / project_xrl_evidence",
    source: "Month-end audit after L2① monthly_reports",
    cadence: "month-end after L2①",
    purpose: "月次報告書とSupabase内L2断面をXRLチェック項目へ照合し、AMD ScoreのXRLチェックリスト更新候補を作る。",
  },
  {
    id: "project_strategy_signals",
    label: "⑨ 経営ハイライト",
    table: "project_strategy_signals",
    source: "Codex automation amd-os",
    cadence: "daily review",
    purpose: "経営上の重要方針、事業進捗、戦略転換、提携、リスク、次の一手をPJ cockpitへ表示する。",
  },
  {
    id: "textbook_insight_candidates",
    label: "⑩ Textbook Insights",
    table: "textbook_insight_candidates",
    source: "Codex automation/local worker amd-os-l10-textbook-insight-extract / approved後local BZM applier",
    cadence: "TBD / manual start",
    purpose: "Before Zero / 教科書へ追記すべき実務知見候補。通知承認後に pwa/bzm へ追記する。",
  },
  {
    id: "atlas_signals",
    label: "⑪ Atlas Signals",
    table: "atlas_signals / atlas_stories / atlas_reports",
    source: "daily consolidated evidence amd-os-l2-consolidated-evidence / Atlas signal collection automation",
    cadence: "daily evidence review",
    purpose: "外部ニュース・政策・市場・技術シグナルを、戦略判断とAtlas派生レポートの根拠として保持する。",
  },
  {
    id: "macrotrend_evidence",
    label: "⑫ Macrotrend Evidence / Index",
    table: "observation_log / macro_index_log / macro_lane_weights / triple_helix_state_log",
    source: "daily consolidated evidence + PWA non-LLM cron macro-aggregate-indicators",
    cadence: "monthly deterministic aggregate + daily evidence review",
    purpose: "研究費・公募・VC投資・政策言及・Atlas signal countをlane/monthで集計し、AMD ScoreやVenture Mapのmacro根拠にする。",
  },
  {
    id: "member_weekly_activities",
    label: "⑬ Member Weekly Activities",
    table: "member_activities(source='member_weekly')",
    source: "separate weekly subscription automation candidate; PWA Anthropic route remains guarded/manual",
    cadence: "weekly candidate",
    purpose: "メンバー週次活動をmypage、reward、L2⑤、MS contribution reviewへ接続する。",
  },
  {
    id: "finance_ops_evidence",
    label: "⑭ Finance Ops Evidence",
    table: "company_finance_recurring_items / company_finance_receipt_events",
    source: "PWA non-LLM finance cron + admin review + optional Codex automation",
    cadence: "daily / monthly finance ops",
    purpose: "サブスク・継続費・自動振替・領収書イベントをManagement Score finance軸と月次PLへ接続する。",
  },
  {
    id: "vc_news_funding_signals",
    label: "⑮ VC News / Funding Signals",
    table: "vc_news / vcs / vc_funds / vc_investments / project_vc_relations",
    source: "Codex automation amd-os-l2-vc-news-funding-signals; PWA vc-discover stays guarded/manual",
    cadence: "weekly Sat 09:00 JST",
    purpose: "VCニュース・ファンド組成・投資活動・fundraising signalをVC inboxで確認し、VC/Fund/PJ関係へ接続する。",
  },
  {
    id: "management_monthly_signal_evaluations",
    label: "⑯ Management Monthly Signal Evaluation",
    table: "company_management_signal_reviews",
    source: "Month-end 17:00 JST Codex / subscription automation candidate; revised management-score UI is canonical UX direction",
    cadence: "monthly last day 17:00 JST",
    purpose: "Management Scoreと予実表を、数字再掲ではなく状態ラベル/アイコン・自然文評価・判断コメント・次に見るべきことへ変換する。",
  },
  {
    id: "amd_score_inputs",
    label: "Score Inputs",
    table: "amd_score_inputs",
    source: "manual evidence / Codex automation",
    cadence: "停止中",
    purpose: "PJごとのM/X/F入力値と根拠。HUD/PJ signal boardのスコア正本。",
  },
];

const DISABLED_REASON = "停止中。Codex automation / 明示的な手動review batchへ移管済み。Run Nowで直接起動しない。";

function disabledCron({
  id,
  label,
  layer,
  cadence,
  trigger,
  input,
  output,
}: {
  id: string;
  label: string;
  layer: CronOperation["layer"];
  cadence: string;
  trigger: string;
  input: string;
  output: string;
}): CronOperation {
  return {
    id,
    label,
    layer,
    cadence: `停止中 / 旧頻度: ${cadence}`,
    trigger: `disabled: ${trigger}`,
    defaultParams: "{\"disabled\":true}",
    input,
    output,
    run: { type: "manual", reason: DISABLED_REASON },
  };
}

export const cronOperations: CronOperation[] = [
  disabledCron({
    id: "gas-meeting-hourly",
    label: "MTGサマリ hourly polling",
    layer: "GAS",
    cadence: "毎時0分",
    trigger: "nav_meeting_pollRecentlyEndedEvents",
    input: "Google Calendar + Notion AI議事録 + Gmail",
    output: "project_meeting_summaries / meeting_notifications",
  }),
  disabledCron({
    id: "gas-monthly-fallback",
    label: "MTGサマリ daily fallback",
    layer: "GAS",
    cadence: "03:00 daily",
    trigger: "nav_cronMonthlyExtractAt3",
    input: "当月Notion/Gmail月次抽出",
    output: "project_meeting_summaries",
  }),
  disabledCron({
    id: "gas-reward-v2-estimate",
    label: "Reward V2 progress estimate",
    layer: "GAS",
    cadence: "03:30 daily",
    trigger: "cron_progressEstimateDaily_",
    input: "DB_MonthlyReports + DB_ProgressEvents + 差分データ",
    output: "DB_MilestoneProgressPending / DB_MilestoneMonthlyProgress",
  }),
  disabledCron({
    id: "gas-reward-scoring-events",
    label: "進捗イベント差分抽出",
    layer: "GAS",
    cadence: "04:00 daily",
    trigger: "reward_trigger_dailyExtract",
    input: "過去24hで更新された月次報告書",
    output: "progress events / responsibilities draft",
  }),
  disabledCron({
    id: "gas-l2-member-knowledge",
    label: "メンバーナレッジ抽出",
    layer: "GAS",
    cadence: "毎時",
    trigger: "nav_member_knowledge_pollAll",
    input: "member_activities + project_meeting_summaries",
    output: "member_knowledge / l2_notifications",
  }),
  disabledCron({
    id: "gas-l2-project-knowledge",
    label: "PJナレッジ抽出",
    layer: "GAS",
    cadence: "毎時",
    trigger: "nav_project_knowledge_pollAll",
    input: "monthly_reports + project_meeting_summaries",
    output: "project_knowledge / l2_notifications",
  }),
  disabledCron({
    id: "gas-l2-protocols",
    label: "AMDプロトコル抽出",
    layer: "GAS",
    cadence: "毎時",
    trigger: "nav_protocol_pollAll",
    input: "project_meeting_summaries.decided / risks / next_actions",
    output: "protocols / protocol_examples / l2_notifications",
  }),
  disabledCron({
    id: "pwa-hourly-estimate",
    label: "MS進捗 hourly estimate (旧PWA)",
    layer: "PWA",
    cadence: "毎時0分 JST (旧GAS 154から)",
    trigger: "/api/cron/hourly-estimate",
    input: "monthly_reports + meeting_summaries + MS設計",
    output: "milestone_monthly_progress / progress_estimate_state / reward_summary_json",
  }),
  disabledCron({
    id: "pwa-lane-suggest",
    label: "ASPI lane suggest",
    layer: "PWA",
    cadence: "週次 (GAS 154から)",
    trigger: "/api/cron/lane-suggest",
    input: "ASPI domains + source hints",
    output: "lane_suggestions",
  }),
  disabledCron({
    id: "pwa-kaken-ingest",
    label: "KAKEN ingest",
    layer: "PWA",
    cadence: "週次 (GAS 154から)",
    trigger: "/api/cron/kaken-ingest",
    input: "KAKEN OpenSearch + fallback LLM",
    output: "observation_log key=I_R",
  }),
  disabledCron({
    id: "pwa-grant-ingest",
    label: "Grant ingest",
    layer: "PWA",
    cadence: "週次 (GAS 154から)",
    trigger: "/api/cron/grant-ingest",
    input: "公募/助成金ソース + LLM抽出",
    output: "observation_log key=B",
  }),
  disabledCron({
    id: "pwa-vc-investment-ingest",
    label: "VC investment ingest",
    layer: "PWA",
    cadence: "週次 (GAS 154から)",
    trigger: "/api/cron/vc-investment-ingest",
    input: "VC投資ニュース + LLM抽出",
    output: "observation_log key=V",
  }),
  disabledCron({
    id: "pwa-atlas-daily",
    label: "Atlas daily report",
    layer: "PWA",
    cadence: "日次 21:00",
    trigger: "/api/cron/atlas-daily",
    input: "atlas_signals / atlas_stories",
    output: "atlas_reports daily",
  }),
  disabledCron({
    id: "pwa-atlas-weekly",
    label: "Atlas weekly report",
    layer: "PWA",
    cadence: "週次 金08:00",
    trigger: "/api/cron/atlas-weekly",
    input: "atlas_signals / atlas_stories",
    output: "atlas_reports weekly",
  }),
  disabledCron({
    id: "pwa-atlas-monthly",
    label: "Atlas monthly report",
    layer: "PWA",
    cadence: "月次 1日22:00",
    trigger: "/api/cron/atlas-monthly",
    input: "atlas_signals / atlas_stories",
    output: "atlas_reports monthly",
  }),
  disabledCron({
    id: "pwa-atlas-collect",
    label: "Atlas collect",
    layer: "PWA",
    cadence: "route only / 旧scheduled",
    trigger: "/api/cron/atlas-collect",
    input: "Anthropic web_search + auto tag",
    output: "atlas_signals / atlas_stories",
  }),
  disabledCron({
    id: "pwa-atlas-collect-policy",
    label: "Atlas policy collect",
    layer: "PWA",
    cadence: "日次 22:00",
    trigger: "/api/cron/atlas-collect-policy",
    input: "政策ソース大量fetch + LLM抽出",
    output: "atlas_signals / atlas_stories",
  }),
  disabledCron({
    id: "pwa-atlas-divergence",
    label: "Atlas divergence",
    layer: "PWA",
    cadence: "週次 日21:00",
    trigger: "/api/cron/atlas-divergence",
    input: "world/Japan atlas signals",
    output: "atlas_divergences",
  }),
  disabledCron({
    id: "pwa-member-activities",
    label: "PJメンバー活動抽出",
    layer: "PWA",
    cadence: "日次 19:00",
    trigger: "/api/cron/member-activities",
    input: "monthly_reports + meeting_summaries + source_cache",
    output: "member_activities",
  }),
  {
    id: "manual-monthly-reports-backfill",
    label: "Monthly reports backfill",
    layer: "PWA",
    cadence: "on-demand",
    trigger: "/api/cron/monthly-reports-backfill",
    defaultParams: "{\"query\":{\"limit\":6,\"concurrency\":5}}",
    input: "billing_cycles - monthly_reports missing rows + source_cache + milestones",
    output: "monthly_reports",
    run: { type: "manual", reason: "Sonnetで月次報告書を生成する重いbackfill。対象月・件数を確認してcurl/Codex側で実行する" },
  },
  disabledCron({
    id: "pwa-member-weekly-activities",
    label: "メンバー週次活動抽出",
    layer: "PWA",
    cadence: "日次 18:00 JST",
    trigger: "/api/cron/member-weekly-activities",
    input: "Gmail + shared member calendars + source_cache",
    output: "member_activities(source=member_weekly)",
  }),
  disabledCron({
    id: "pwa-venture-narrative-refresh",
    label: "Venture narrative refresh",
    layer: "PWA",
    cadence: "日次 18:45",
    trigger: "/api/cron/venture-narrative-refresh",
    input: "project_ventures + feedbacks + project facts",
    output: "project_ventures narrative fields / learnings",
  }),
  disabledCron({
    id: "pwa-venture-xrl-refresh",
    label: "Venture XRL refresh",
    layer: "PWA",
    cadence: "日次 18:15",
    trigger: "/api/cron/venture-xrl-refresh",
    input: "project_events + venture_members + project_ventures",
    output: "project_xrl_log source=llm_proposal",
  }),
  disabledCron({
    id: "pwa-relearn-lane-weights",
    label: "ASPI lane weights relearn",
    layer: "PWA",
    cadence: "日次 18:30",
    trigger: "/api/cron/relearn-lane-weights",
    input: "macro outcomes + lane evidence",
    output: "macro_lane_weights",
  }),
  disabledCron({
    id: "pwa-founding-members-extract",
    label: "関連メンバー抽出",
    layer: "PWA",
    cadence: "週次 月18:30",
    trigger: "/api/cron/founding-members-extract",
    input: "project_ventures.master_md_text + AMD member aliases",
    output: "project_founding_members / l2_notifications",
  }),
  {
    id: "codex-project-strategy-signals",
    label: "経営ハイライト L2レビュー",
    layer: "Codex",
    cadence: "日次 03:20 JST",
    trigger: "Codex automation amd-os",
    defaultParams: "{\"outbox\":\"/Users/masa/.codex/automations/amd-os/strategy-signals-outbox\"}",
    input: "Gmail + Drive + Calendar + Slack + Notion + OS snapshot",
    output: "project_strategy_signals / l2_notifications(l2_kind=project_strategy_signal)",
    run: { type: "manual", reason: "Codex automationがoutboxを作り、LaunchAgentの非LLM applierが反映する" },
  },
  disabledCron({
    id: "pwa-seeds-ingest",
    label: "Seeds ingest",
    layer: "PWA",
    cadence: "週次 月00:00",
    trigger: "/api/cron/seeds-ingest",
    input: "研究シーズ/大学ソース + LLM抽出",
    output: "seeds / seed_news",
  }),
  {
    id: "codex-vc-news-funding-signals",
    label: "VC News / Funding Signals L2⑮",
    layer: "Codex",
    cadence: "週次 土09:00 JST",
    trigger: "Codex automation amd-os-l2-vc-news-funding-signals",
    defaultParams: "{\"outbox\":\"/Users/masa/.codex/automations/amd-os-l2-vc-news-funding-signals/outbox\"}",
    input: "国内deeptech VCニュース + fund / investment public signals + existing VC DB",
    output: "vcs / vc_funds / vc_news",
    run: { type: "manual", reason: "PWA /api/cron/vc-discover はLLM/web_search経路のためactive Vercel cronに戻さず、subscription/Codex automationをprimaryにする" },
  },
  {
    id: "pwa-papers-quarterly-ingest",
    label: "Papers quarterly ingest",
    layer: "PWA",
    cadence: "週次 火03:20 JST",
    trigger: "/api/cron/papers-quarterly-ingest",
    defaultParams: "{}",
    input: "研究論文ソース",
    output: "papers_log / seeds",
    run: { type: "pwa", path: "/api/cron/papers-quarterly-ingest" },
  },
  {
    id: "pwa-sync-pj-facts",
    label: "PJ facts sync",
    layer: "PWA",
    cadence: "日次 04:00 JST",
    trigger: "/api/cron/sync-pj-facts",
    defaultParams: "{}",
    input: "project registry / project_ventures",
    output: "project facts tables",
    run: { type: "pwa", path: "/api/cron/sync-pj-facts" },
  },
  {
    id: "pwa-macro-aggregate-indicators",
    label: "Macro aggregate indicators",
    layer: "PWA",
    cadence: "月次 2日04:00 JST",
    trigger: "/api/cron/macro-aggregate-indicators",
    defaultParams: "{\"query\":{\"since\":\"YYYY-MM\"}}",
    input: "observation_log + atlas_signals",
    output: "macro_index_log aggregates",
    run: { type: "pwa", path: "/api/cron/macro-aggregate-indicators" },
  },
  disabledCron({
    id: "pwa-macro-backfill-historical",
    label: "Macro historical backfill",
    layer: "PWA",
    cadence: "週次 日03:00",
    trigger: "/api/cron/macro-backfill-historical",
    input: "historical policy/investment milestones + LLM",
    output: "macro_index_log",
  }),
  {
    id: "manual-triple-helix-recompute",
    label: "Triple Helix recompute",
    layer: "PWA",
    cadence: "on-demand / weekly candidate",
    trigger: "/api/cron/triple-helix-recompute",
    defaultParams: "{}",
    input: "papers_log + atlas_signals + observation_log + project_ventures.lanes",
    output: "triple_helix_state_log",
    run: { type: "manual", reason: "ASPI 8 domain × 16 quarter のBVAR/Kalman再計算。実行範囲と時間を見て手動で起動する" },
  },
  disabledCron({
    id: "pwa-frl-grit-resilience",
    label: "FRL grit/resilience",
    layer: "PWA",
    cadence: "月次 1日18:00",
    trigger: "/api/cron/frl-grit-resilience-extract",
    input: "直近3ヶ月 monthly_reports + meeting_summaries",
    output: "amd_score_inputs.frl_grit / frl_resilience",
  }),
  {
    id: "manual-freeze-period-backfill",
    label: "Freeze period backfill",
    layer: "PWA",
    cadence: "on-demand / daily candidate",
    trigger: "/api/cron/freeze-period-backfill",
    defaultParams: "{}",
    input: "休止PJの monthly_reports + project_meeting_summaries",
    output: "freeze_period_backfills",
    run: { type: "manual", reason: "Sonnetで休止期間サマリを生成する。対象PJと再開月の確認後に手動で起動する" },
  },
  disabledCron({
    id: "pwa-amd-score-l2",
    label: "AMD Score L2 refresh",
    layer: "PWA",
    cadence: "週次 日18:00",
    trigger: "/api/cron/amd-score-l2-refresh",
    input: "L2 evidence + project facts",
    output: "amd_score_inputs",
  }),
  {
    id: "pwa-freee-payment-sync",
    label: "freee入金同期",
    layer: "PWA",
    cadence: "日次 09:10 JST",
    trigger: "/api/cron/freee-payment-sync",
    defaultParams: "{\"query\":{\"ym\":\"YYYYMM\",\"dryRun\":0}}",
    input: "freee会計 income deals + projects.freee_partner_id + billing_cycles",
    output: "billing_cycles.payment_confirmed_at / billing_log",
    run: { type: "pwa", path: "/api/cron/freee-payment-sync", defaultQuery: { dryRun: 0 } },
  },
  {
    id: "pwa-payment-confirm-nudges",
    label: "入金確認nudge",
    layer: "PWA",
    cadence: "日次 09:30 JST",
    trigger: "/api/cron/payment-confirm-nudges",
    defaultParams: "{\"query\":{\"ym\":\"YYYYMM\",\"dryRun\":0}}",
    input: "billing_cycles + projects.payment_due_rule + members.is_admin",
    output: "Slack DM / billing_cycles.payment_confirmed_at",
    run: { type: "pwa", path: "/api/cron/payment-confirm-nudges", defaultQuery: { dryRun: 0 } },
  },
  {
    id: "pwa-payout-reward-cache-refresh",
    label: "報酬キャッシュ再計算",
    layer: "PWA",
    cadence: "日次 03:05 JST",
    trigger: "/api/cron/payout-reward-cache-refresh",
    defaultParams: "{\"query\":{\"ym\":\"YYYYMM\"}}",
    input: "billing_cycles + value_milestones + milestone_monthly_progress + milestone_responsibility",
    output: "billing_cycles.reward_summary_json / budget_yen fallback",
    run: { type: "pwa", path: "/api/cron/payout-reward-cache-refresh", defaultQuery: {} },
  },
  {
    id: "manual-management-score-raw",
    label: "Management Score raw data",
    layer: "PWA",
    cadence: "manual",
    trigger: "/api/cron/management-score-raw-data",
    defaultParams: "{\"query\":{\"includeFreee\":0}}",
    input: "member_activities + billing + PJ継続 + pipeline + freee(optional)",
    output: "amd_management_score_raw_signals / company_actual_monthly",
    run: { type: "manual", reason: "手動実行はCodex automation側で対象月を明示して行う" },
  },
  {
    id: "manual-management-score-calc",
    label: "Management Score calculate",
    layer: "PWA",
    cadence: "manual / after raw",
    trigger: "/api/cron/management-score-calculate",
    defaultParams: "{\"query\":{}}",
    input: "amd_management_score_raw_signals",
    output: "amd_management_score_snapshots / evidence",
    run: { type: "manual", reason: "手動実行はCodex automation側でraw収集後に行う" },
  },
  // === Subscription / Codex automation (= L2 ①〜⑩。L2①/⑦/⑨/⑩はoutbox、L2⑧は月末audit、L2②〜⑥はMMO automation) ===
  // PWA からは直接叩けない。古いClaude routine名は現行復旧先として使わない。
  {
    id: "codex-l1-monthly-report-extract",
    label: "L2 ① 月次報告抽出 (Codex automation)",
    layer: "Codex",
    cadence: "month-end only",
    trigger: "AMD OS L2① 月次報告抽出",
    defaultParams: "(SKILL.md に従う)",
    input: "Supabase internal OS/L2 snapshot / active・sales PJ 対象月。5生データは明示fallback",
    output: "monthly_reports via amd-os-ms/outbox.monthlyReports",
    run: { type: "manual", reason: "Codex automationがoutboxを作り、LaunchAgentの非LLM applierが反映する" },
  },
  {
    id: "codex-l2-protocol-extract",
    label: "L2 ② AMDプロトコル抽出 (daily consolidated evidence)",
    layer: "Codex",
    cadence: "daily 08:00 JST",
    trigger: "amd-os-l2-consolidated-evidence",
    defaultParams: "(SKILL.md に従う)",
    input: "project_meeting_summaries (decided) + monthly_reports / l2_feedbacks",
    output: "protocols (candidate) / l2_notifications",
    run: { type: "manual", reason: "Daily consolidated L2 evidence routine の一部。旧個別Claude routine扱いではない" },
  },
  {
    id: "mmo-l3-ms-progress-extract",
    label: "L2 ③ MS進捗推定 (MMO Codex Desktop automation)",
    layer: "Codex",
    cadence: "毎時0分 JST",
    trigger: "amd-os-l3-ms-progress-extract (scheduled-task)",
    defaultParams: "(SKILL.md に従う。PWA/GAS hourly は停止済み)",
    input: "monthly_reports + project_meeting_summaries / value_milestones / progress_estimate_state",
    output: "milestone_monthly_progress / project_monthly_notes / progress_estimate_state",
    run: { type: "manual", reason: "MMOマシン Codex Desktop automation の現行writer。PWA/GAS background LLM cronは復活させない" },
  },
  {
    id: "codex-l4-project-knowledge-extract",
    label: "L2 ④ PJナレッジ抽出 (daily consolidated evidence)",
    layer: "Codex",
    cadence: "daily 08:00 JST",
    trigger: "amd-os-l2-consolidated-evidence",
    defaultParams: "(SKILL.md に従う、汚染防御 v4_meta_strict 継承)",
    input: "monthly_reports (status≠invalid) + project_meeting_summaries / l2_feedbacks",
    output: "project_knowledge (candidate, 9 category) / l2_notifications",
    run: { type: "manual", reason: "Daily consolidated L2 evidence routine の一部。旧個別Claude routine扱いではない" },
  },
  {
    id: "codex-l5-member-knowledge-extract",
    label: "L2 ⑤ メンバーナレッジ抽出 (daily consolidated evidence)",
    layer: "Codex",
    cadence: "daily 08:00 JST",
    trigger: "amd-os-l2-consolidated-evidence",
    defaultParams: "(SKILL.md に従う、3 セクション C/A/B = milestone_responsibility/member_activities/meeting_summaries)",
    input: "milestone_responsibility + member_activities (90日) + project_meeting_summaries (60日) / l2_feedbacks",
    output: "member_knowledge (candidate, 7 category) / l2_notifications",
    run: { type: "manual", reason: "Daily consolidated L2 evidence routine の一部。旧個別Claude routine扱いではない" },
  },
  {
    id: "mmo-l6-meeting-flow",
    label: "L2 ⑥ MTGサマリ + MTGフロー (MMO Codex Desktop automation)",
    layer: "Codex",
    cadence: "09:00-21:00 hourly JST",
    trigger: "amd-os-l6-meeting-flow",
    defaultParams: "(SKILL.md に従う、5 ソース全部見る = Calendar + Notion + Gmail + Drive + Slack)",
    input: "Calendar events + Notion 議事録 (Stage 1-3 fallback + AI transcription) + Gmail thread + Drive Doc + Slack thread / l2_feedbacks",
    output: "project_meeting_summaries / meeting_notifications",
    run: { type: "manual", reason: "MMOマシン Codex Desktop automation の現行writer。event-window based なのでdaily consolidated routineには入れない" },
  },
  {
    id: "codex-l7-registry-diff-extract",
    label: "L2 ⑦ OS台帳差分抽出 (daily consolidated evidence)",
    layer: "Codex",
    cadence: "daily 08:00 JST",
    trigger: "amd-os-l2-consolidated-evidence",
    defaultParams: "(SKILL.md に従う、既存 Codex amd-os-ms と並行稼働中)",
    input: "5 生データ (Gmail/Notion/Calendar/Slack/Drive) vs OS 台帳 (project_members/projects.report_emails/project_partners)",
    output: "project_registry_diffs (pending) / l2_notifications",
    run: { type: "manual", reason: "Daily consolidated L2 evidence routine の一部。outbox/applier contract は維持" },
  },
  {
    id: "subscription-l8-xrl-checklist-audit",
    label: "L2 ⑧ XRL checklist audit (month-end)",
    layer: "Codex",
    cadence: "month-end after L2①",
    trigger: "L2① monthly_reports completion / month-end audit",
    defaultParams: "xrl-level-definitions.ts に従う、ecosystem PJ は対象外",
    input: "L2① monthly_reports + Supabase internal L2 snapshot + project_founding_members + confirmed project_xrl_evidence",
    output: "review proposal for amd_score_inputs.xrl_checklist / xrl_notes",
    run: { type: "manual", reason: "XRLはdailyではなく月末成熟度監査。project_xrl_evidence daily collectorは通常復活させない" },
  },
  {
    id: "codex-l9-strategy-signal-extract",
    label: "L2 ⑨ 経営ハイライト抽出 (daily consolidated evidence)",
    layer: "Codex",
    cadence: "daily 08:00 JST",
    trigger: "amd-os-l2-consolidated-evidence",
    defaultParams: "(SKILL.md に従う、done のみ / polarity 必須 / 修正依頼は対話型 UI 経由)",
    input: "5 生データ + OS snapshot (monthly_reports / project_meeting_summaries / project_xrl_log / amd_score_inputs)",
    output: "project_strategy_signals (candidate, 10 signal_type) / l2_notifications",
    run: { type: "manual", reason: "Daily consolidated L2 evidence routine の一部。outbox/applier contract は維持" },
  },
  {
    id: "codex-l10-textbook-insight-extract",
    label: "L2 ⑩ Textbook Insights 抽出 (daily consolidated evidence)",
    layer: "Codex",
    cadence: "daily 08:00 JST / candidate generation",
    trigger: "amd-os-l2-consolidated-evidence",
    defaultParams: "(SKILL.md に従う、承認前に pwa/bzm へ追記しない)",
    input: "Supabase 内の既存 L2 / OS データ (monthly_reports / meeting_summaries / strategy_signals / protocols / XRL evidence ほか)",
    output: "textbook_insight_candidates (candidate) / l2_notifications。approved後は local BZM applier",
    run: { type: "manual", reason: "Daily consolidated L2 evidence routine の候補生成対象。approved後のBZM追記はlocal applierのみ" },
  },
];

export function findCronOperation(id: string) {
  return cronOperations.find((op) => op.id === id) ?? null;
}
