export type RawDataSource = {
  id: string;
  label: string;
  owner: string;
  refresh: string;
  landsIn: string[];
  notes: string;
};

export type L2Dataset = {
  id: string;
  label: string;
  // 層 (tier): データの吟味度。cadence(D/M/W/H)とは直交する軸。
  // L1 = 生データを吟味せず吸い出し/同期しただけ (LLMなし)。
  // L2 = LLM が吟味して「欲しい情報の形」に抽出した中核データ。
  // L3 = L2 群のカバレッジ自体を見張るメタレイヤー (不在検知)。
  // 正本: pwa/spec/3-0-l2-data-list-current-spec.md の「層 (tier) 軸」。
  tier: "L1" | "L2" | "L3";
  table: string;
  source: string;
  cadence: string;
  purpose: string;
};

export type CronOperation = {
  id: string;
  label: string;
  layer: "GAS" | "PWA" | "Codex" | "Claude";
  cadence: string;
  trigger: string;
  defaultParams: string;
  input: string;
  output: string;
  run:
    | { type: "gas"; functionName: string; defaultArgs: unknown[] }
    | { type: "pwa"; path: string; defaultQuery?: Record<string, string | number | boolean> }
    | { type: "manual"; reason: string };
};

const CODEX_WRITER_MANUAL_REASON =
  "PWA から直接叩かず、Codex automation / MMO側 launcher / local worker を起点に実行する。current truth は 3-0 と 5-8 を参照";

const PLANNED_WRITER_MANUAL_REASON =
  "まだ recurring writer 未実装。current truth は 5-8 の second wave / third wave を参照";

export const rawDataSources: RawDataSource[] = [
  {
    id: "calendar",
    label: "Google Calendar",
    owner: "GAS",
    refresh: "毎時0分",
    landsIn: ["project_meeting_summaries", "meeting_notifications", "project_strategy_signals", "contract_signals"],
    notes: "会議eventを主軸に、終了60-180分後のPJ関連MTGを拾う。",
  },
  {
    id: "notion-minutes",
    label: "Notion AI 議事録",
    owner: "GAS",
    refresh: "Calendar polling時 / 03:00 fallback",
    landsIn: ["project_meeting_summaries", "project_strategy_signals", "contract_signals"],
    notes: "eventId / 日付 / PJ relation が空でも、title+date fallbackで拾ってself-healする。",
  },
  {
    id: "gmail",
    label: "Gmail / CircleBack / Meet",
    owner: "GAS + PWA",
    refresh: "MTG抽出時 / source collect時",
    landsIn: ["project_meeting_summaries", "source_cache", "member_activities", "project_strategy_signals", "contract_signals"],
    notes: "reportEmails と会議日付周辺で議事録メール・録画通知・関係先往復を拾う。",
  },
  {
    id: "slack",
    label: "Slack",
    owner: "GAS/PWA connectors",
    refresh: "backfill / L2 source collect",
    landsIn: ["project_meeting_summaries", "member_activities", "source_cache", "project_strategy_signals", "contract_signals"],
    notes: "PJ channel / thread から進捗・論点・メンバー活動を抽出する。",
  },
  {
    id: "drive",
    label: "Google Drive",
    owner: "GAS/PWA",
    refresh: "monthly / backfill / source collect",
    landsIn: ["project_meeting_summaries", "monthly_reports", "source_cache", "project_strategy_signals", "contract_signals", "contract_documents"],
    notes: "議事録doc、月次資料、PJ関連ファイルを情報源にする。",
  },
  {
    id: "web-external",
    label: "Web / 外部シグナル",
    owner: "PWA + Codex automation",
    refresh: "daily / weekly / monthly",
    landsIn: ["atlas_stories", "atlas_signals", "macro_index_log", "vc_news"],
    notes: "Atlas、政策、VC、Macrotrend系の外部観測。L2とは別系統。",
  },
];

export const l2Datasets: L2Dataset[] = [
  {
    id: "monthly_reports",
    label: "M-1 月次報告書",
    tier: "L2",
    table: "monthly_reports",
    source: "Codex automation `AMD OS M-1 月次報告抽出` (`amd-os-l2`) / `amd-os-ms` outbox.monthlyReports",
    cadence: "daily 05:30 JST / ACTIVE",
    purpose: "PJごとの月次報告書。まずこれがないと後続L2が痩せる。",
  },
  {
    id: "protocols",
    label: "D-1 AMDプロトコル",
    tier: "L2",
    table: "protocols / protocol_examples",
    source: "MMO側 Codex Desktop automation `amd-os-l2-protocol-extract`",
    cadence: "daily 08:00 JST 相当",
    purpose: "経営判断を、分岐点・判断材料・アクション・結果学習に構造化する。",
  },
  {
    id: "ms_progress",
    label: "D-2 MS進捗",
    tier: "L2",
    table: "milestone_monthly_progress",
    source: "MMO側 Codex Desktop automation `amd-os-l3-ms-progress-extract` + non-LLM `ms-schedule-progress`",
    cadence: "毎時0分相当 / default按分はnon-LLM",
    purpose: "月次進捗%を推定。ただしデフォルト按分(ms-schedule-progress)は非LLM派生で、LLMは乖離revision提案のみ(=L2部分)。",
  },
  {
    id: "project_knowledge",
    label: "D-3 PJナレッジ",
    tier: "L2",
    table: "project_knowledge",
    source: "MMO側 Codex Desktop automation `amd-os-l4-project-knowledge-extract`",
    cadence: "daily 08:15 JST 相当",
    purpose: "PJの人物・組織・事実・進行中事項を更新する。",
  },
  {
    id: "member_knowledge",
    label: "D-4 メンバーナレッジ",
    tier: "L2",
    table: "member_knowledge",
    source: "MMO側 Codex Desktop automation `amd-os-l5-member-knowledge-extract`",
    cadence: "daily 08:30 JST 相当",
    purpose: "メンバーごとの強み・スキル・関心・最近の活動を抽出する。",
  },
  {
    id: "meeting_summaries",
    label: "H-1 MTGフロー",
    tier: "L2",
    table: "project_meeting_summaries",
    source: "Codex automation `AMD OS H-1 MTGフロー` (`amd-os-l6-meeting-flow`) / MMO launcher",
    cadence: "毎時 09:00-21:00 JST / ACTIVE",
    purpose: "会議サマリ、予定MTGカード、次アクションまでまとめて回す。",
  },
  {
    id: "registry_diffs",
    label: "D-5 OS台帳差分",
    tier: "L2",
    table: "project_registry_diffs",
    source: "`amd-os-ms` 系へ束ねる予定。専用writerは未再始動",
    cadence: "review batch / 実質保留中",
    purpose: "5生データとOS台帳を突合し、反映候補を通知で採否する。",
  },
  {
    id: "xrl_evidence",
    label: "M-2 XRL根拠",
    tier: "L2",
    table: "project_xrl_evidence / project_xrl_log",
    source: "`amd-os-ms` 系へ束ねる予定。専用writerは未再始動",
    cadence: "month-end / 実質保留中",
    purpose: "AMD ScoreのXRL/FRL/Triple Helix根拠を構造化する。",
  },
  {
    id: "project_strategy_signals",
    label: "D-6 経営ハイライト",
    tier: "L2",
    table: "project_strategy_signals",
    source: "Codex automation `AMD OS D-6 経営ハイライト抽出` (`amd-os`)",
    cadence: "daily 03:20 JST / ACTIVE",
    purpose: "経営上の重要方針、事業進捗、戦略転換、提携、リスク、次の一手をPJ cockpitへ表示する。",
  },
  {
    id: "textbook_insight_candidates",
    label: "D-7 Textbook Insights",
    tier: "L2",
    table: "textbook_insight_candidates",
    source: "Codex automation/local worker amd-os-l10-textbook-insight-extract / approved後local BZM applier",
    cadence: "TBD / manual start",
    purpose: "Before Zero / 教科書へ追記すべき実務知見候補。通知承認後に pwa/bzm へ追記する。",
  },
  {
    id: "atlas_signals",
    label: "D-8 Atlas外部シグナル",
    tier: "L2",
    table: "atlas_signals",
    source: "Codex automation `AMD OS D-8 Atlas外部シグナル抽出` (`amd-atlas-2`)",
    cadence: "daily 08:10 JST / ACTIVE",
    purpose: "外部ニュース・政策・市場・技術シグナルを AMD 向けに絞って残す。",
  },
  {
    id: "macrotrend_index",
    label: "D-9 Macrotrend",
    tier: "L2",
    table: "observation_log / macro_index_log",
    source: "observation writer は再整理中 / index は PWA non-LLM cron `macro-aggregate-indicators`",
    cadence: "観測は未整理 / index は月初04:00 JST",
    purpose: "外部観測とその集計 index。index 側は non-LLM。",
  },
  {
    id: "member_activities",
    label: "D-10 メンバー活動根拠",
    tier: "L2",
    table: "member_activities",
    source: "Codex automation `AMD OS D-10 メンバー活動根拠抽出 (Mac)` (`amd-os-l2-2`)。PWA route は evidence 収集と POST 保存",
    cadence: "daily 18:30 JST / synthesis_method=codex",
    purpose: "メンバーごとの活動根拠。reward、mypage、D-4 の入力になる。",
  },
  {
    id: "media_mentions",
    label: "D-11 メディア掲載根拠",
    tier: "L2",
    table: "project_media_mentions",
    source: "Codex automation `AMD OS D-11 メディア掲載候補抽出` (`amd-os-d-11`) → `POST /api/media-mentions/extract`",
    cadence: "daily 08:25 JST / candidate-first",
    purpose: "公開URLを根拠にメディア掲載や外部露出を候補化。通知で承認された行だけを表示する。",
  },
  {
    id: "contract_signals",
    label: "D-13 契約予兆",
    tier: "L2",
    table: "contract_signals / contracts / contract_documents",
    source: "Codex automation `AMD OS D-13 契約シグナル抽出` (`amd-os-d-13`) → `POST /api/contracts/extract-l2`",
    cadence: "daily 03:35 JST / review-first",
    purpose: "5生データから契約締結予兆を検知し、候補signalと高確度の契約予定枠を契約管理へ入れる。",
  },
  {
    id: "action_items",
    label: "D-14 要対応",
    tier: "L2",
    table: "action_items",
    source: "既存PWA route `POST /api/action-items/extract` はある。前段の Codex collector は未実装",
    cadence: "daily target / 現在は自動化runnerなし",
    purpose: "期日つき inbound 義務 (株主総会招集/議決権/事前承諾/契約更新/振込 等) を期日管理する。終了PJ・個人 scope も対象。",
  },
  {
    id: "finance_freee_actuals",
    label: "D-12 Finance / freee実績",
    tier: "L1",
    table: "company_actual_monthly / company_finance_recurring_items / company_finance_receipt_events",
    source: "PWA non-LLM cron (management-score-raw-data / freee-payment-sync) + admin review",
    cadence: "daily (non-LLM sync)",
    purpose: "freee取引履歴・継続費を吟味せずそのまま月次試算表の実績へ同期するL1相当。LLMは通らない。",
  },
  {
    id: "coverage_gaps",
    label: "L3-1 Coverage Scanner (不在検知)",
    tier: "L3",
    table: "l2_coverage_gaps",
    source: "既存PWA route `POST /api/coverage-gaps/extract` はある。前段の Codex collector は未実装",
    cadence: "daily target / 現在は自動化runnerなし",
    purpose: "来た生データ × 既存L2カバレッジ の差分(不在検知)。OS化されてない重要情報を候補提示する上位安全網。設計 design/coverage_gap_scanner.md。",
  },
  {
    id: "vc_news_funding",
    label: "W-1 VCニュース・資金調達",
    tier: "L2",
    table: "vc_news / vcs / vc_funds / vc_investments / project_vc_relations",
    source: "Codex automation `AMD OS W-1 VCニュース・資金調達シグナル抽出` (`amd-os-l2-vc-news-funding-signals`)",
    cadence: "土曜 09:00 JST / ACTIVE",
    purpose: "VCニュース、ファンド組成、投資活動、資金調達シグナル。",
  },
  {
    id: "management_monthly_signal",
    label: "M-3 月末の会社評価文",
    tier: "L2",
    table: "company_management_signal_reviews",
    source: "まだ専用writerなし。旧 target は month-end routine",
    cadence: "未実装",
    purpose: "月末時点の会社状態を、自然文の評価として残す。",
  },
  {
    id: "amd_score_inputs",
    label: "Score Inputs",
    tier: "L2",
    table: "amd_score_inputs",
    source: "manual evidence / Codex automation",
    cadence: "停止中",
    purpose: "PJごとのM/X/F入力値と根拠。HUD/PJ signal boardのスコア正本。",
  },
];

const DISABLED_REASON = "停止中。Codex automation / 明示的な手動review batchへ移管済み。Run Nowで直接起動しない。";

function disabledCron({
  id,
  label,
  layer,
  cadence,
  trigger,
  input,
  output,
}: {
  id: string;
  label: string;
  layer: CronOperation["layer"];
  cadence: string;
  trigger: string;
  input: string;
  output: string;
}): CronOperation {
  return {
    id,
    label,
    layer,
    cadence: `停止中 / 旧頻度: ${cadence}`,
    trigger: `disabled: ${trigger}`,
    defaultParams: "{\"disabled\":true}",
    input,
    output,
    run: { type: "manual", reason: DISABLED_REASON },
  };
}

export const cronOperations: CronOperation[] = [
  disabledCron({
    id: "gas-meeting-hourly",
    label: "MTGサマリ hourly polling",
    layer: "GAS",
    cadence: "毎時0分",
    trigger: "nav_meeting_pollRecentlyEndedEvents",
    input: "Google Calendar + Notion AI議事録 + Gmail",
    output: "project_meeting_summaries / meeting_notifications",
  }),
  disabledCron({
    id: "gas-monthly-fallback",
    label: "MTGサマリ daily fallback",
    layer: "GAS",
    cadence: "03:00 daily",
    trigger: "nav_cronMonthlyExtractAt3",
    input: "当月Notion/Gmail月次抽出",
    output: "project_meeting_summaries",
  }),
  disabledCron({
    id: "gas-reward-v2-estimate",
    label: "Reward V2 progress estimate",
    layer: "GAS",
    cadence: "03:30 daily",
    trigger: "cron_progressEstimateDaily_",
    input: "DB_MonthlyReports + DB_ProgressEvents + 差分データ",
    output: "DB_MilestoneProgressPending / DB_MilestoneMonthlyProgress",
  }),
  disabledCron({
    id: "gas-reward-scoring-events",
    label: "進捗イベント差分抽出",
    layer: "GAS",
    cadence: "04:00 daily",
    trigger: "reward_trigger_dailyExtract",
    input: "過去24hで更新された月次報告書",
    output: "progress events / responsibilities draft",
  }),
  disabledCron({
    id: "gas-l2-member-knowledge",
    label: "メンバーナレッジ抽出",
    layer: "GAS",
    cadence: "毎時",
    trigger: "nav_member_knowledge_pollAll",
    input: "member_activities + project_meeting_summaries",
    output: "member_knowledge / l2_notifications",
  }),
  disabledCron({
    id: "gas-l2-project-knowledge",
    label: "PJナレッジ抽出",
    layer: "GAS",
    cadence: "毎時",
    trigger: "nav_project_knowledge_pollAll",
    input: "monthly_reports + project_meeting_summaries",
    output: "project_knowledge / l2_notifications",
  }),
  disabledCron({
    id: "gas-l2-protocols",
    label: "AMDプロトコル抽出",
    layer: "GAS",
    cadence: "毎時",
    trigger: "nav_protocol_pollAll",
    input: "project_meeting_summaries.decided / risks / next_actions",
    output: "protocols / protocol_examples / l2_notifications",
  }),
  disabledCron({
    id: "pwa-hourly-estimate",
    label: "MS進捗 hourly estimate (旧PWA)",
    layer: "PWA",
    cadence: "毎時0分 JST (旧GAS 154から)",
    trigger: "/api/cron/hourly-estimate",
    input: "monthly_reports + meeting_summaries + MS設計",
    output: "milestone_monthly_progress / progress_estimate_state / reward_summary_json",
  }),
  disabledCron({
    id: "pwa-lane-suggest",
    label: "ASPI lane suggest",
    layer: "PWA",
    cadence: "週次 (GAS 154から)",
    trigger: "/api/cron/lane-suggest",
    input: "ASPI domains + source hints",
    output: "lane_suggestions",
  }),
  disabledCron({
    id: "pwa-kaken-ingest",
    label: "KAKEN ingest",
    layer: "PWA",
    cadence: "週次 (GAS 154から)",
    trigger: "/api/cron/kaken-ingest",
    input: "KAKEN OpenSearch + fallback LLM",
    output: "observation_log key=I_R",
  }),
  disabledCron({
    id: "pwa-grant-ingest",
    label: "Grant ingest",
    layer: "PWA",
    cadence: "週次 (GAS 154から)",
    trigger: "/api/cron/grant-ingest",
    input: "公募/助成金ソース + LLM抽出",
    output: "observation_log key=B",
  }),
  disabledCron({
    id: "pwa-vc-investment-ingest",
    label: "VC investment ingest",
    layer: "PWA",
    cadence: "週次 (GAS 154から)",
    trigger: "/api/cron/vc-investment-ingest",
    input: "VC投資ニュース + LLM抽出",
    output: "observation_log key=V",
  }),
  disabledCron({
    id: "pwa-atlas-daily",
    label: "Atlas daily report",
    layer: "PWA",
    cadence: "日次 21:00",
    trigger: "/api/cron/atlas-daily",
    input: "atlas_signals / atlas_stories",
    output: "atlas_reports daily",
  }),
  disabledCron({
    id: "pwa-atlas-weekly",
    label: "Atlas weekly report",
    layer: "PWA",
    cadence: "週次 金08:00",
    trigger: "/api/cron/atlas-weekly",
    input: "atlas_signals / atlas_stories",
    output: "atlas_reports weekly",
  }),
  disabledCron({
    id: "pwa-atlas-monthly",
    label: "Atlas monthly report",
    layer: "PWA",
    cadence: "月次 1日22:00",
    trigger: "/api/cron/atlas-monthly",
    input: "atlas_signals / atlas_stories",
    output: "atlas_reports monthly",
  }),
  disabledCron({
    id: "pwa-atlas-collect",
    label: "Atlas collect",
    layer: "PWA",
    cadence: "route only / 旧scheduled",
    trigger: "/api/cron/atlas-collect",
    input: "Anthropic web_search + auto tag",
    output: "atlas_signals / atlas_stories",
  }),
  disabledCron({
    id: "pwa-atlas-collect-policy",
    label: "Atlas policy collect",
    layer: "PWA",
    cadence: "日次 22:00",
    trigger: "/api/cron/atlas-collect-policy",
    input: "政策ソース大量fetch + LLM抽出",
    output: "atlas_signals / atlas_stories",
  }),
  disabledCron({
    id: "pwa-atlas-divergence",
    label: "Atlas divergence",
    layer: "PWA",
    cadence: "週次 日21:00",
    trigger: "/api/cron/atlas-divergence",
    input: "world/Japan atlas signals",
    output: "atlas_divergences",
  }),
  disabledCron({
    id: "pwa-member-activities",
    label: "PJメンバー活動抽出",
    layer: "PWA",
    cadence: "日次 19:00",
    trigger: "/api/cron/member-activities",
    input: "monthly_reports + meeting_summaries + source_cache",
    output: "member_activities",
  }),
  {
    id: "manual-monthly-reports-backfill",
    label: "Monthly reports backfill",
    layer: "PWA",
    cadence: "on-demand",
    trigger: "/api/cron/monthly-reports-backfill",
    defaultParams: "{\"query\":{\"limit\":6,\"concurrency\":5}}",
    input: "billing_cycles - monthly_reports missing rows + source_cache + milestones",
    output: "monthly_reports",
    run: { type: "manual", reason: "Sonnetで月次報告書を生成する重いbackfill。対象月・件数を確認してcurl/Codex側で実行する" },
  },
  disabledCron({
    id: "pwa-member-weekly-activities",
    label: "メンバー週次活動抽出",
    layer: "PWA",
    cadence: "日次 18:00 JST",
    trigger: "/api/cron/member-weekly-activities",
    input: "legacy GET synthesis は停止。定期D-10は mode=evidence -> Codex synthesis -> POST save",
    output: "member_activities(source=member_weekly)",
  }),
  disabledCron({
    id: "pwa-venture-narrative-refresh",
    label: "Venture narrative refresh",
    layer: "PWA",
    cadence: "日次 18:45",
    trigger: "/api/cron/venture-narrative-refresh",
    input: "project_ventures + feedbacks + project facts",
    output: "project_ventures narrative fields / learnings",
  }),
  disabledCron({
    id: "pwa-venture-xrl-refresh",
    label: "Venture XRL refresh",
    layer: "PWA",
    cadence: "日次 18:15",
    trigger: "/api/cron/venture-xrl-refresh",
    input: "project_events + venture_members + project_ventures",
    output: "project_xrl_log source=llm_proposal",
  }),
  disabledCron({
    id: "pwa-relearn-lane-weights",
    label: "ASPI lane weights relearn",
    layer: "PWA",
    cadence: "日次 18:30",
    trigger: "/api/cron/relearn-lane-weights",
    input: "macro outcomes + lane evidence",
    output: "macro_lane_weights",
  }),
  disabledCron({
    id: "pwa-founding-members-extract",
    label: "関連メンバー抽出",
    layer: "PWA",
    cadence: "週次 月18:30",
    trigger: "/api/cron/founding-members-extract",
    input: "project_ventures.master_md_text + AMD member aliases",
    output: "project_founding_members / l2_notifications",
  }),
  {
    id: "codex-project-strategy-signals",
    label: "経営ハイライト L2レビュー",
    layer: "Codex",
    cadence: "日次 03:20 JST",
    trigger: "Codex automation amd-os",
    defaultParams: "{\"outbox\":\"/Users/masa/.codex/automations/amd-os/strategy-signals-outbox\"}",
    input: "Gmail + Drive + Calendar + Slack + Notion + OS snapshot",
    output: "project_strategy_signals / l2_notifications(l2_kind=project_strategy_signal)",
    run: { type: "manual", reason: "Codex automationがoutboxを作り、LaunchAgentの非LLM applierが反映する" },
  },
  disabledCron({
    id: "pwa-seeds-ingest",
    label: "Seeds ingest",
    layer: "PWA",
    cadence: "週次 月00:00",
    trigger: "/api/cron/seeds-ingest",
    input: "研究シーズ/大学ソース + LLM抽出",
    output: "seeds / seed_news",
  }),
  disabledCron({
    id: "pwa-vc-discover",
    label: "VC discover",
    layer: "PWA",
    cadence: "週次 土00:00",
    trigger: "/api/cron/vc-discover",
    input: "国内deeptech VC探索 + web_search",
    output: "vcs / vc_funds / vc_news",
  }),
  {
    id: "pwa-papers-quarterly-ingest",
    label: "Papers quarterly ingest",
    layer: "PWA",
    cadence: "週次 火03:20 JST",
    trigger: "/api/cron/papers-quarterly-ingest",
    defaultParams: "{}",
    input: "研究論文ソース",
    output: "papers_log / seeds",
    run: { type: "pwa", path: "/api/cron/papers-quarterly-ingest" },
  },
  {
    id: "pwa-sync-pj-facts",
    label: "PJ facts sync",
    layer: "PWA",
    cadence: "日次 04:00 JST",
    trigger: "/api/cron/sync-pj-facts",
    defaultParams: "{}",
    input: "project registry / project_ventures",
    output: "project facts tables",
    run: { type: "pwa", path: "/api/cron/sync-pj-facts" },
  },
  {
    id: "pwa-macro-aggregate-indicators",
    label: "Macro aggregate indicators",
    layer: "PWA",
    cadence: "月次 2日04:00 JST",
    trigger: "/api/cron/macro-aggregate-indicators",
    defaultParams: "{\"query\":{\"since\":\"YYYY-MM\"}}",
    input: "observation_log + atlas_signals",
    output: "macro_index_log aggregates",
    run: { type: "pwa", path: "/api/cron/macro-aggregate-indicators" },
  },
  disabledCron({
    id: "pwa-macro-backfill-historical",
    label: "Macro historical backfill",
    layer: "PWA",
    cadence: "週次 日03:00",
    trigger: "/api/cron/macro-backfill-historical",
    input: "historical policy/investment milestones + LLM",
    output: "macro_index_log",
  }),
  {
    id: "manual-triple-helix-recompute",
    label: "Triple Helix recompute",
    layer: "PWA",
    cadence: "on-demand / weekly candidate",
    trigger: "/api/cron/triple-helix-recompute",
    defaultParams: "{}",
    input: "papers_log + atlas_signals + observation_log + project_ventures.lanes",
    output: "triple_helix_state_log",
    run: { type: "manual", reason: "ASPI 8 domain × 16 quarter のBVAR/Kalman再計算。実行範囲と時間を見て手動で起動する" },
  },
  disabledCron({
    id: "pwa-frl-grit-resilience",
    label: "FRL grit/resilience",
    layer: "PWA",
    cadence: "月次 1日18:00",
    trigger: "/api/cron/frl-grit-resilience-extract",
    input: "直近3ヶ月 monthly_reports + meeting_summaries",
    output: "amd_score_inputs.frl_grit / frl_resilience",
  }),
  {
    id: "manual-freeze-period-backfill",
    label: "Freeze period backfill",
    layer: "PWA",
    cadence: "on-demand / daily candidate",
    trigger: "/api/cron/freeze-period-backfill",
    defaultParams: "{}",
    input: "休止PJの monthly_reports + project_meeting_summaries",
    output: "freeze_period_backfills",
    run: { type: "manual", reason: "Sonnetで休止期間サマリを生成する。対象PJと再開月の確認後に手動で起動する" },
  },
  disabledCron({
    id: "pwa-amd-score-l2",
    label: "AMD Score L2 refresh",
    layer: "PWA",
    cadence: "週次 日18:00",
    trigger: "/api/cron/amd-score-l2-refresh",
    input: "L2 evidence + project facts",
    output: "amd_score_inputs",
  }),
  {
    id: "pwa-freee-payment-sync",
    label: "freee入金同期",
    layer: "PWA",
    cadence: "日次 09:10 JST",
    trigger: "/api/cron/freee-payment-sync",
    defaultParams: "{\"query\":{\"ym\":\"YYYYMM\",\"dryRun\":0}}",
    input: "freee会計 income deals + projects.freee_partner_id + billing_cycles",
    output: "billing_cycles.payment_confirmed_at / billing_log",
    run: { type: "pwa", path: "/api/cron/freee-payment-sync", defaultQuery: { dryRun: 0 } },
  },
  {
    id: "pwa-payment-confirm-nudges",
    label: "入金確認nudge",
    layer: "PWA",
    cadence: "日次 09:30 JST",
    trigger: "/api/cron/payment-confirm-nudges",
    defaultParams: "{\"query\":{\"ym\":\"YYYYMM\",\"dryRun\":0}}",
    input: "billing_cycles + projects.payment_due_rule + members.is_admin",
    output: "Slack DM / billing_cycles.payment_confirmed_at",
    run: { type: "pwa", path: "/api/cron/payment-confirm-nudges", defaultQuery: { dryRun: 0 } },
  },
  {
    id: "pwa-payout-reward-cache-refresh",
    label: "報酬キャッシュ再計算",
    layer: "PWA",
    cadence: "日次 03:05 JST",
    trigger: "/api/cron/payout-reward-cache-refresh",
    defaultParams: "{\"query\":{\"ym\":\"YYYYMM\"}}",
    input: "billing_cycles + value_milestones + milestone_monthly_progress + milestone_responsibility",
    output: "billing_cycles.reward_summary_json / budget_yen fallback",
    run: { type: "pwa", path: "/api/cron/payout-reward-cache-refresh", defaultQuery: {} },
  },
  {
    id: "pwa-management-score-refresh",
    label: "Management Score / 月次試算表更新",
    layer: "PWA",
    cadence: "日次 06:00 JST",
    trigger: "/api/cron/management-score-refresh",
    defaultParams: "{\"query\":{\"ym\":\"YYYYMM\"}}",
    input: "freee PL + freee wallet_txns + member_activities + billing + PJ継続 + pipeline",
    output: "company_actual_monthly / amd_management_score_raw_signals / amd_management_score_snapshots",
    run: { type: "pwa", path: "/api/cron/management-score-refresh", defaultQuery: {} },
  },
  {
    id: "manual-management-score-raw",
    label: "Management Score raw data",
    layer: "PWA",
    cadence: "manual",
    trigger: "/api/cron/management-score-raw-data",
    defaultParams: "{\"query\":{\"includeFreee\":0}}",
    input: "member_activities + billing + PJ継続 + pipeline + freee(optional)",
    output: "amd_management_score_raw_signals / company_actual_monthly",
    run: { type: "manual", reason: "手動実行はCodex automation側で対象月を明示して行う" },
  },
  {
    id: "manual-management-score-calc",
    label: "Management Score calculate",
    layer: "PWA",
    cadence: "manual / after raw",
    trigger: "/api/cron/management-score-calculate",
    defaultParams: "{\"query\":{}}",
    input: "amd_management_score_raw_signals",
    output: "amd_management_score_snapshots / evidence",
    run: { type: "manual", reason: "手動実行はCodex automation側でraw収集後に行う" },
  },
  // === Current L1-L3 writers (2026-06-16 current truth) ===
  {
    id: "codex-l1-monthly-report-extract",
    label: "M-1 月次報告抽出 (Codex automation)",
    layer: "Codex",
    cadence: "daily 05:30 JST",
    trigger: "AMD OS M-1 月次報告抽出",
    defaultParams: "(SKILL.md に従う)",
    input: "5 生データ + OS snapshot / active・sales PJ 当月・前月",
    output: "monthly_reports via amd-os-ms/outbox.monthlyReports",
    run: { type: "manual", reason: "Codex automationがoutboxを作り、LaunchAgentの非LLM applierが反映する" },
  },
  {
    id: "claude-l2-protocol-extract",
    label: "D-1 AMDプロトコル抽出 (MMO Codex)",
    layer: "Codex",
    cadence: "daily 08:00 JST",
    trigger: "amd-os-l2-protocol-extract (MMO Codex Desktop)",
    defaultParams: "(SKILL.md に従う)",
    input: "project_meeting_summaries (decided) + monthly_reports / l2_feedbacks",
    output: "protocols (candidate) / l2_notifications",
    run: { type: "manual", reason: CODEX_WRITER_MANUAL_REASON },
  },
  {
    id: "claude-l3-ms-progress-extract",
    label: "D-2 MS進捗推定 (MMO Codex + non-LLM)",
    layer: "Codex",
    cadence: "毎時0分 JST",
    trigger: "amd-os-l3-ms-progress-extract (MMO Codex Desktop) / ms-schedule-progress",
    defaultParams: "(SKILL.md に従う。PWA/GAS hourly は停止済み)",
    input: "monthly_reports + project_meeting_summaries / value_milestones / progress_estimate_state",
    output: "milestone_monthly_progress / project_monthly_notes / progress_estimate_state",
    run: { type: "manual", reason: CODEX_WRITER_MANUAL_REASON },
  },
  {
    id: "claude-l4-project-knowledge-extract",
    label: "D-3 PJナレッジ抽出 (MMO Codex)",
    layer: "Codex",
    cadence: "daily 08:15 JST",
    trigger: "amd-os-l4-project-knowledge-extract (MMO Codex Desktop)",
    defaultParams: "(SKILL.md に従う、汚染防御 v4_meta_strict 継承)",
    input: "monthly_reports (status≠invalid) + project_meeting_summaries / l2_feedbacks",
    output: "project_knowledge (candidate, 9 category) / l2_notifications",
    run: { type: "manual", reason: CODEX_WRITER_MANUAL_REASON },
  },
  {
    id: "claude-l5-member-knowledge-extract",
    label: "D-4 メンバーナレッジ抽出 (MMO Codex)",
    layer: "Codex",
    cadence: "daily 08:30 JST",
    trigger: "amd-os-l5-member-knowledge-extract (MMO Codex Desktop)",
    defaultParams: "(SKILL.md に従う、3 セクション C/A/B = milestone_responsibility/member_activities/meeting_summaries)",
    input: "milestone_responsibility + member_activities (90日) + project_meeting_summaries (60日) / l2_feedbacks",
    output: "member_knowledge (candidate, 7 category) / l2_notifications",
    run: { type: "manual", reason: CODEX_WRITER_MANUAL_REASON },
  },
  {
    id: "claude-l6-meeting-extract",
    label: "H-1 MTGフロー (MMO / Mac Codex)",
    layer: "Codex",
    cadence: "毎時 09:00-21:00 JST",
    trigger: "AMD OS H-1 MTGフロー / amd-os-l6-meeting-flow-launcher",
    defaultParams: "(SKILL.md に従う、5 ソース全部見る = Calendar + Notion + Gmail + Drive + Slack)",
    input: "Calendar events + Notion 議事録 (Stage 1-3 fallback + AI transcription) + Gmail thread + Drive Doc + Slack thread / l2_feedbacks",
    output: "project_meeting_summaries / meeting_notifications",
    run: { type: "manual", reason: CODEX_WRITER_MANUAL_REASON },
  },
  {
    id: "claude-l7-registry-diff-extract",
    label: "D-5 OS台帳差分抽出 (Codex second wave)",
    layer: "Codex",
    cadence: "daily target / second wave",
    trigger: "amd-os-ms / amd-os-l7-registry-diff-extract",
    defaultParams: "(second wave 実装時に SKILL.md へ従う)",
    input: "5 生データ (Gmail/Notion/Calendar/Slack/Drive) vs OS 台帳 (project_members/projects.report_emails/project_partners)",
    output: "project_registry_diffs (pending) / l2_notifications",
    run: { type: "manual", reason: PLANNED_WRITER_MANUAL_REASON },
  },
  {
    id: "claude-l8-xrl-evidence-extract",
    label: "M-2 XRL根拠抽出 (Codex second wave)",
    layer: "Codex",
    cadence: "month-end / second wave",
    trigger: "amd-os-ms / amd-os-l8-xrl-evidence-extract",
    defaultParams: "(second wave 実装時に SKILL.md へ従う、ecosystem PJ は対象外)",
    input: "5 生データ + monthly_reports + project_meeting_summaries + project_knowledge + project_founding_members",
    output: "project_xrl_evidence (candidate, axis: trl/brl/grl/srl/hrl) / l2_notifications",
    run: { type: "manual", reason: PLANNED_WRITER_MANUAL_REASON },
  },
  {
    id: "claude-l9-strategy-signal-extract",
    label: "D-6 経営ハイライト抽出 (Codex automation)",
    layer: "Codex",
    cadence: "daily 03:20 JST",
    trigger: "AMD OS D-6 経営ハイライト抽出 / amd-os",
    defaultParams: "(SKILL.md に従う、done のみ / polarity 必須 / 修正依頼は対話型 UI 経由)",
    input: "5 生データ + OS snapshot (monthly_reports / project_meeting_summaries / project_xrl_log / amd_score_inputs)",
    output: "project_strategy_signals (candidate, 10 signal_type) / l2_notifications",
    run: { type: "manual", reason: CODEX_WRITER_MANUAL_REASON },
  },
  {
    id: "claude-l10-textbook-insight-extract",
    label: "D-7 Textbook Insights 抽出 (local worker)",
    layer: "Codex",
    cadence: "TBD / manual start",
    trigger: "amd-os-l10-textbook-insight-extract (local worker)",
    defaultParams: "(SKILL.md に従う、承認前に pwa/bzm へ追記しない)",
    input: "Supabase 内の既存 L2 / OS データ (monthly_reports / meeting_summaries / strategy_signals / protocols / XRL evidence ほか)",
    output: "textbook_insight_candidates (candidate) / l2_notifications。approved後は local BZM applier",
    run: { type: "manual", reason: CODEX_WRITER_MANUAL_REASON },
  },
];

export function findCronOperation(id: string) {
  return cronOperations.find((op) => op.id === id) ?? null;
}
