import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const __dirname = dirname(fileURLToPath(import.meta.url));

const LOGO_SYMBOL_ASSET_PATH = join(__dirname, "content", "assets", "logo-symbol.png");
const LOGO_TYPE_ASSET_PATH = join(__dirname, "content", "assets", "logo-type.png");

function toDataUrl(path) {
  const buf = readFileSync(path);
  return `data:image/png;base64,${buf.toString("base64")}`;
}

const symbolDataUrl = toDataUrl(LOGO_SYMBOL_ASSET_PATH);
const typeDataUrl = toDataUrl(LOGO_TYPE_ASSET_PATH);

const outDir = join(__dirname, "server");
mkdirSync(outDir, { recursive: true });

const outPath = join(outDir, "brand-data.mjs");
const banner = "// Generated by build.mjs — do not edit by hand. Run `npm run build` to regenerate.\n";
const body = `${banner}export const LOGO_SYMBOL_DATA_URL = ${JSON.stringify(symbolDataUrl)};
export const LOGO_TYPE_DATA_URL = ${JSON.stringify(typeDataUrl)};
`;
writeFileSync(outPath, body, "utf8");

console.log(`build.mjs: wrote server/brand-data.mjs (${(body.length / 1024).toFixed(1)} KB)`);

const vendorDir = join(__dirname, "public", "vendor");
mkdirSync(vendorDir, { recursive: true });
await esbuild.build({
  entryPoints: [join(__dirname, "node_modules", "@vercel", "blob", "dist", "client.js")],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2020",
  outfile: join(vendorDir, "blob-client.mjs"),
  logLevel: "silent",
});
console.log("build.mjs: wrote public/vendor/blob-client.mjs (browser bundle of @vercel/blob/client)");
