import Foundation

enum AMDOSParityCatalog {
    static func userTitle(for id: AMDOSScreenID) -> String {
        switch id {
        case .today: return "ダッシュボード"
        case .mypage: return "マイページ"
        case .projects: return "プロジェクト"
        case .myProjects: return "参加PJ"
        case .projectWorkspace: return "PJ ダッシュボード"
        case .projectCockpit: return "コックピット"
        case .projectConfig: return "プロジェクト設定"
        case .projectReportPrint: return "月次報告書"
        case .notifications: return "通知"
        case .reimbursements: return "立替"
        case .businessCards: return "名刺"
        case .nativeBusinessCards: return "名刺"
        case .company: return "会社"
        case .contracts: return "契約"
        case .japaneseCultureMap: return "日本文化マップ"
        case .knowledgeMap: return "材料知識地図"
        case .monthlyAgreement: return "月初合意"
        case .atlasHome: return "Atlas"
        case .atlasThemes: return "Atlasテーマ"
        case .atlasDecisions: return "Atlas判断"
        case .atlasDivergence: return "Atlas乖離"
        case .atlasInbox: return "Atlas受信箱"
        case .atlasInboxSubmit: return "Atlasシグナル送信"
        case .atlasMacrotrends: return "Atlasマクロ"
        case .atlasMap: return "Atlasマップ"
        case .materials: return "材料知識地図"
        case .seeds: return "研究シーズ"
        case .seedDetail: return "シーズ詳細"
        case .seedInbox: return "シーズ受信箱"
        case .poc: return "PoC候補"
        case .vcs: return "VC一覧"
        case .vcDetail: return "VC詳細"
        case .vcEdit: return "VC編集"
        case .vcInbox: return "VC受信箱"
        case .scholar: return "Scholar"
        case .institutions: return "研究機関"
        case .institutionDetail: return "研究機関詳細"
        case .institutionCockpit: return "研究機関コックピット"
        case .institutionAssess: return "研究機関評価"
        case .ventureMap: return "Venture Map"
        case .amdScore: return "現行SPS"
        case .amdScoreDetail: return "現行SPS詳細"
        case .amdScoreRetrofit: return "退役済みスコア導線"
        case .ventureCyberspace: return "現行SPS"
        case .ventureOscillator: return "Oscillator"
        case .ventureStateSpace: return "State Space"
        case .ventureSuDetail: return "SU詳細"
        case .ventureTimeline3D: return "Timeline 3D"
        case .managementScore: return "Management Score"
        case .proactive: return "Proactive"
        case .adminHome: return "管理ホーム"
        case .adminCompany: return "会社情報"
        case .adminContexts: return "コンテキスト"
        case .adminInvoices: return "請求"
        case .adminBilling: return "請求"
        case .adminFinance: return "財務"
        case .adminPayouts: return "支払"
        case .adminContracts: return "契約"
        case .adminMembers: return "メンバー"
        case .adminGovernance: return "ガバナンス"
        case .adminCoverageGaps: return "Coverage Gaps"
        case .adminIP: return "知財"
        case .adminCultureMap: return "日本文化マップ"
        case .adminMonthlyAgreements: return "月初合意管理"
        case .adminPrivateWiki: return "人物メモ"
        case .adminManagementKnowledge: return "経営ナレッジ"
        case .adminProjects: return "プロジェクト管理"
        case .adminPrompts: return "プロンプト"
        case .adminProtocols: return "プロトコル"
        case .adminSchedule: return "運営カレンダー"
        case .adminMsOverview: return "MS概要"
        case .adminSeasonPL: return "シーズン予実"
        case .adminSettings: return "設定"
        case .adminTsukuyomi: return "つくよみ"
        case .adminWeekly: return "週次活動"
        case .hudDashboard: return "HUDダッシュボード"
        case .hudEmbedDashboard: return "HUD公開表示"
        case .hudNotifications: return "HUD通知"
        case .hudProjectCockpit: return "HUDコックピット"
        case .hudAtlas: return "HUD Atlas"
        case .hudSeeds: return "HUDシーズ"
        case .hudVcs: return "HUD VC"
        case .hudAmdScoreRetrofit: return "HUD Score再計算"
        case .cyber3DLab: return "3D Lab"
        case .cyberGlassCube: return "Glass Cube"
        case .cyberHudWall: return "HUD Wall"
        case .manual: return "マニュアル"
        case .manualDetail: return "マニュアル本文"
        case .spec: return "仕様書"
        case .specDetail: return "仕様書本文"
        case .bzm: return "BZM"
        case .bzmDetail: return "BZM本文"
        case .bzmPublic: return "BZM公開版"
        case .bzmPublicDetail: return "BZM公開本文"
        case .account: return "アカウント"
        case .paymentConfirm: return "入金確認"
        }
    }

    static func icon(for id: AMDOSScreenID) -> String {
        switch id {
        case .today: return "rectangle.grid.2x2.fill"
        case .mypage: return "person.fill"
        case .projects, .myProjects, .projectWorkspace, .projectCockpit, .projectConfig, .projectReportPrint: return "rectangle.3.group.fill"
        case .notifications, .hudNotifications: return "bell.fill"
        case .reimbursements: return "receipt"
        case .businessCards, .nativeBusinessCards: return "person.text.rectangle"
        case .company: return "building.2.fill"
        case .contracts: return "signature"
        case .japaneseCultureMap: return "map.fill"
        case .knowledgeMap: return "circle.hexagongrid.fill"
        case .monthlyAgreement, .adminMonthlyAgreements: return "checkmark.seal.fill"
        case .atlasHome, .atlasThemes, .atlasDecisions, .atlasDivergence, .atlasInbox, .atlasInboxSubmit, .atlasMacrotrends, .atlasMap, .hudAtlas: return "globe.americas.fill"
        case .materials: return "circle.hexagongrid.fill"
        case .seeds, .seedDetail, .seedInbox, .hudSeeds: return "leaf.fill"
        case .poc: return "arrow.triangle.2.circlepath"
        case .vcs, .vcDetail, .vcEdit, .vcInbox, .hudVcs: return "chart.line.uptrend.xyaxis"
        case .scholar: return "graduationcap.fill"
        case .institutions, .institutionDetail, .institutionCockpit, .institutionAssess: return "building.columns.fill"
        case .ventureMap, .amdScore, .amdScoreDetail, .amdScoreRetrofit, .ventureCyberspace, .ventureOscillator, .ventureStateSpace, .ventureSuDetail, .ventureTimeline3D, .hudAmdScoreRetrofit: return "scope"
        case .managementScore: return "gauge.with.dots.needle.67percent"
        case .proactive: return "sparkles"
        case .adminHome: return "house.fill"
        case .adminCompany: return "building.2.fill"
        case .adminContexts, .adminPrivateWiki: return "lock.document"
        case .adminInvoices, .adminBilling: return "doc.text.fill"
        case .adminFinance: return "yensign.circle.fill"
        case .adminPayouts: return "banknote.fill"
        case .adminContracts: return "signature"
        case .adminMembers: return "person.2.fill"
        case .adminGovernance: return "building.columns"
        case .adminCoverageGaps: return "exclamationmark.triangle.fill"
        case .adminIP: return "lightbulb.max.fill"
        case .adminCultureMap: return "map.fill"
        case .adminManagementKnowledge: return "books.vertical.fill"
        case .adminProjects: return "folder.fill"
        case .adminPrompts: return "text.bubble.fill"
        case .adminProtocols: return "list.number"
        case .adminSchedule: return "calendar"
        case .adminMsOverview, .adminSeasonPL: return "chart.bar.fill"
        case .adminSettings: return "gearshape.fill"
        case .adminTsukuyomi: return "moon.stars.fill"
        case .adminWeekly: return "calendar.badge.clock"
        case .hudDashboard, .hudEmbedDashboard: return "display"
        case .hudProjectCockpit: return "rectangle.split.3x1.fill"
        case .cyber3DLab, .cyberGlassCube, .cyberHudWall: return "cube.transparent.fill"
        case .manual, .manualDetail: return "book.closed.fill"
        case .spec, .specDetail: return "doc.badge.gearshape"
        case .bzm, .bzmDetail, .bzmPublic, .bzmPublicDetail: return "text.book.closed.fill"
        case .account: return "person.crop.circle"
        case .paymentConfirm: return "yensign.circle.fill"
        }
    }

    static func areaLabel(_ area: AMDOSArea) -> String {
        switch area {
        case .work: return "仕事"
        case .explore: return "探索"
        case .admin: return "管理"
        case .settings: return "設定"
        }
    }

    static func navigation(for area: AMDOSArea, isAdmin: Bool) -> [AMDOSScreenID] {
        switch area {
        case .work:
            return [.today, .mypage, .projects, .myProjects, .projectCockpit, .projectConfig, .projectReportPrint, .notifications, .reimbursements, .businessCards, .nativeBusinessCards, .monthlyAgreement]
        case .explore:
            return [.company, .contracts, .knowledgeMap, .atlasHome, .atlasThemes, .atlasDecisions, .atlasDivergence, .atlasInbox, .atlasInboxSubmit, .atlasMacrotrends, .atlasMap, .materials, .seeds, .seedInbox, .poc, .vcs, .vcInbox, .scholar, .institutions, .institutionAssess, .ventureMap, .amdScore, .amdScoreRetrofit, .ventureCyberspace, .ventureOscillator, .ventureStateSpace, .ventureTimeline3D, .managementScore, .proactive]
        case .admin:
            return isAdmin ? [.adminHome, .adminCompany, .adminContexts, .adminInvoices, .adminFinance, .adminPayouts, .adminContracts, .adminMembers, .adminGovernance, .adminCoverageGaps, .adminIP, .adminCultureMap, .adminMonthlyAgreements, .adminPrivateWiki, .adminManagementKnowledge, .adminProjects, .adminPrompts, .adminProtocols, .adminSchedule, .adminMsOverview, .adminSeasonPL, .adminSettings, .adminTsukuyomi, .adminWeekly] : []
        case .settings:
            return [.hudDashboard, .hudNotifications, .hudProjectCockpit, .hudAtlas, .hudSeeds, .hudVcs, .hudAmdScoreRetrofit, .cyber3DLab, .cyberGlassCube, .cyberHudWall, .manual, .spec, .bzm, .bzmPublic, .account]
        }
    }
}
