import fs from 'node:fs';
import assert from 'node:assert/strict';
import { computeCostModel, effectiveUnitPrice, deriveCostBasis, rolesInEffect, type CostModelBundle } from '../src/lib/project-cost-model.ts';
import { computeProcessSummary } from '../src/lib/cost-process-summary.ts';
const ui=fs.readFileSync(new URL('../src/components/cockpit/CostEconomicsSummary.tsx',import.meta.url),'utf8');
for(const text of ['cost-economics-summary','cost-all-in','cost-budget-headroom','顧客1工場の排水処理量','供給に必要な菌体製造量','初期投資と回収期間を比較','確定利益ではない']) assert(ui.includes(text),text);
const bundle:CostModelBundle=JSON.parse(fs.readFileSync(new URL('./__fixtures__/sol_cost_optimistic_261008.json',import.meta.url),'utf8'));
const sel={strain:'wild' as const,application:'dye' as const,location:'onsite' as const,method:'投入' as const,tankMode:'既設' as const};
const calc=(b:CostModelBundle)=>{const c=computeCostModel(b,{strain:sel.strain});return {s:c.scenarios.find(x=>x.key==='dye:投入-既設')!,l:computeProcessSummary(b,c,sel)!};};
const close=(a:number,b:number)=>assert(Math.abs(a-b)<1e-6,`${a} != ${b}`);
const modify=(role:string,value:number|string)=>{const b=structuredClone(bundle);b.assumptions=b.assumptions.map(a=>a.roleKey===role?{...a,...(typeof value==='string'?{valueText:value}:{value})}:a);return b;};
const {s,l}=calc(bundle);
close(l.total,427.8649159390744);close(l.opex,254.38809819880066);close(l.capex,173.47681774027376);
close(l.sx,s.totalPerUnit);close(l.customer,s.customerCostPerUnit);close(l.total,s.allInCostPerUnit);
close(s.feeCeilingPerUnit!,282.93558980632133);close(s.customerOutlayPerUnit,500);close(s.gapToAllowedPerUnit,72.1350840609256);
assert.equal(s.customerResidualPerUnit,null);assert.equal(s.unpricedExtraPerUnit,null);
assert.equal(deriveCostBasis(bundle.assumptions,sel).annualVolume,30000);
assert.equal(s.reactorCustomerCapexTotal,25650000);
assert(rolesInEffect(bundle,sel).has('customer_total_budget'));
assert(!rolesInEffect(bundle,sel).has('sale_price'),'総額枠があると旧SOL単独価格を使わない');
assert(!rolesInEffect(bundle,{...sel,location:'offsite',tankMode:'新設'}).has('customer_total_budget'));
assert(!rolesInEffect(bundle,{...sel,application:'metal'}).has('customer_total_budget'),'色素分解の上限を金属へ流用しない');
const borne=calc(modify('reactor_customer_borne','off'));
close(borne.l.total,l.total);close(borne.s.totalPerUnit+borne.s.customerCostPerUnit,l.total);
close(borne.s.gapToAllowedPerUnit,s.gapToAllowedPerUnit);
const residual=calc(modify('customer_residual_cost',100));close(residual.s.feeCeilingPerUnit!,s.feeCeilingPerUnit!-100);close(residual.s.gapToAllowedPerUnit,s.gapToAllowedPerUnit-100);
const extra=calc(modify('unpriced_extra_cost',50));close(extra.s.gapToAllowedPerUnit,s.gapToAllowedPerUnit-50);
const cooler=calc(modify('culture_cooling_cop',10));close(l.total-cooler.l.total,18.09258324413423/2);
const overhead=calc(modify('business_overhead_annual',300000000));close(overhead.l.total-l.total,7.5);
const gasOff=modify('co2_flue_gas','off');const gas=gasOff.items.find(i=>i.priceRule==='flue_gas_transport')!;close(effectiveUnitPrice(gas,gasOff.assumptions,deriveCostBasis(gasOff.assumptions,sel),sel,gasOff.items),0);
assert(!rolesInEffect(gasOff,sel).has('flue_gas_pressure_pa'),'排ガスOFFでは搬送差圧を使わない');
const light=structuredClone(bundle);light.items=light.items.map(i=>i.costItemId==='ci2_c_led_power'?{...i,unitPrice:0}:i);
assert(calc(light).l.total<l.total-100,'照明単価は照明・冷却・排ガス搬送へ連動する');
const c=computeCostModel(bundle,{strain:'wild'});
for(const row of c.scenarios){const z=computeProcessSummary(bundle,c,{...sel,application:row.application,location:row.location,method:row.method,tankMode:row.tankMode})!;close(z.total,row.allInCostPerUnit);}
console.log('OK: 総額上限・顧客全登録費・負担切替・未確認/入力済み費・冷却/排ガス/管理連動・処理量の契約');
