import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { parseProjectOrganizationChart } from "../src/lib/project-organization-chart.ts";
const fixture = JSON.parse(readFileSync(new URL("./__fixtures__/project_organization_chart.json", import.meta.url), "utf8"));
const chart = parseProjectOrganizationChart(JSON.stringify(fixture))!;
assert.equal(chart.status, "proposed");
assert.equal(chart.departments.length, 2);
assert.equal(chart.collaborations.length, 3);
assert.ok(chart.collaborations.every((c) => c.departmentId === "technology"));
assert.deepEqual(chart.governingBodies.map((g) => g.label), ["株主総会", "経営会議", "代表取締役／CEO"]);
assert.equal(parseProjectOrganizationChart(null), null);
assert.equal(parseProjectOrganizationChart(""), null);
assert.throws(() => parseProjectOrganizationChart("{broken"));
assert.throws(() => parseProjectOrganizationChart({ ...fixture, version: 2 }));
assert.throws(() => parseProjectOrganizationChart({ ...fixture, status: "assumed" }));
assert.throws(() => parseProjectOrganizationChart({ ...fixture, departments: [] }));
assert.throws(() => parseProjectOrganizationChart({ ...fixture, departments: [fixture.departments[0], fixture.departments[0]] }));
assert.throws(() => parseProjectOrganizationChart({ ...fixture, collaborations: [{ ...fixture.collaborations[0], departmentId: "missing" }] }));
assert.throws(() => parseProjectOrganizationChart({ ...fixture, departments: [{ ...fixture.departments[0], roles: "<script>" }] }));
const registered = parseProjectOrganizationChart({ ...fixture, status: "confirmed", collaborations: [] })!;
assert.equal(registered.status, "confirmed");
assert.equal(registered.collaborations.length, 0);
console.log("Organization chart validation: proposed/confirmed, empty, malformed and invalid edges passed");
