import assert from 'node:assert/strict';
import {zipSync,strToU8} from 'fflate';
import {validateWorkflowBytes} from '@/lib/workflow-file-validation';
import {workflowFileError,WORD_DOCX,WORD_DOC} from '@/lib/workflow-files';
const docx=Buffer.from(zipSync({'[Content_Types].xml':strToU8('<Types/>'),'word/document.xml':strToU8('<document/>')}));
assert.equal(workflowFileError('契約の下書き.docx',docx.length,'draft'),'');
assert.notEqual(workflowFileError('draft.docx',docx.length,'revision'),'');
assert.notEqual(workflowFileError('file.exe',100,'draft'),'');
assert.notEqual(workflowFileError('empty.pdf',0,'revision'),'');
assert.notEqual(workflowFileError('large.pdf',25_000_001,'revision'),'');
validateWorkflowBytes(docx,WORD_DOCX);
validateWorkflowBytes(Buffer.from('d0cf11e0a1b11ae100','hex'),WORD_DOC);
validateWorkflowBytes(Buffer.from('%PDF-1.7\n%%EOF'),'application/pdf');
assert.throws(()=>validateWorkflowBytes(Buffer.from('not a pdf'),'application/pdf'));
assert.throws(()=>validateWorkflowBytes(Buffer.from('not a word'),WORD_DOC));
assert.throws(()=>validateWorkflowBytes(Buffer.from(zipSync({'not-word.txt':strToU8('x')})),WORD_DOCX));
assert.throws(()=>validateWorkflowBytes(Buffer.from(zipSync({'[Content_Types].xml':strToU8('<Types/>'),'word/document.xml':strToU8('<document/>'),'word/vbaProject.bin':strToU8('macro')})),WORD_DOCX));
assert.throws(()=>validateWorkflowBytes(Buffer.from('broken zip'),WORD_DOCX));
console.log('Word/PDF形式・サイズ・偽装・マクロ・承認用PDFの境界: PASS');
