import assert from 'node:assert/strict';
import fs from 'node:fs';
import {resolveFundingPlan} from '../src/lib/project-funding-plan.ts';
import {deriveCapitalPlan,validateCapitalPlan} from '../src/lib/capital-plan.ts';
const sql=fs.readFileSync('scripts/migrations/410_sol_current_funding_plan_20260930.sql','utf8');
const blocks=[...sql.matchAll(/\$sol_finance\$([\s\S]*?)\$sol_finance\$::jsonb/g)].map(m=>JSON.parse(m[1]));
assert.equal(blocks.length,4);
const plan=resolveFundingPlan(blocks[3])!;
assert.equal(plan.months.length,15);
assert.equal(plan.summary.nextRoundYm,'2028-07');
assert.equal(plan.summary.nextRoundAmountYen,null);
const scenario=(key:string)=>plan.months.map(m=>m.planning_details_json.scenarios.find(s=>s.key===key)!);
const base=scenario('adopted');
assert.equal(base.at(-1)!.closingYen,3_589_253);
assert.equal(base.reduce((a,r)=>a+r.seedInflowYen,0),100_000_000);
assert.equal(base.reduce((a,r)=>a+r.bridgeInflowYen,0),0);
assert.equal(base.reduce((a,r)=>a+r.ordinarySpendYen+r.equipmentSpendYen+r.interestYen,0),126_088_080);
assert.ok(Math.abs(base.reduce((a,r)=>a+r.loanDrawdownYen,0)-29_677_333)<10);
for(const r of base) assert.equal(r.grantReceiptYen,r.loanRepaymentYen);
for(const r of scenario('rejected')) for(const k of ['loanDrawdownYen','grantReceiptYen','loanRepaymentYen','loanBalanceYen','interestYen'] as const) assert.equal(r[k],0);
assert.equal(scenario('rejected')[9].bridgeInflowYen,40_000_000);
assert.equal(scenario('approval_delay')[9].bridgeInflowYen,35_000_000);
assert.equal(scenario('rejected').at(-1)!.closingYen,14_137_600);
assert.ok(scenario('approval_delay').at(-1)!.closingYen>plan.summary.reserveYen);
const missing=structuredClone(blocks[3]); missing.splice(4,1);
assert.throws(()=>resolveFundingPlan(missing),/月数/);
const corrupted=structuredClone(blocks[3]);corrupted[7].planning_details_json.scenarios[0].closingYen+=100;
assert.throws(()=>resolveFundingPlan(corrupted),/残高/);
const duplicated=structuredClone(blocks[3]);duplicated[4].planning_details_json.scenarios.push(duplicated[4].planning_details_json.scenarios[0]);
assert.throws(()=>resolveFundingPlan(duplicated),/ケース数/);
const cap=deriveCapitalPlan({id:'sol',name:'SOL',...blocks[2]});
const seed=cap.events.find((e:any)=>e.id==='sx-seed')!;
assert.equal(seed.type,'convertible_issue');assert.equal(seed.conversionCap?.value,500_000_000);assert.equal(seed.conversionDiscount?.value,.2);
assert.equal(seed.allocations.reduce((a:any,r:any)=>a+r.amount.value,0),100_000_000);
assert.equal(seed.allocations.reduce((a:any,r:any)=>a+r.shares.value,0)/(120_000+30_000),.2);
assert.deepEqual(cap.holders.slice(0,-1),blocks[0].holders,'Existing holder names must survive');
assert.equal(cap.events.find((e:any)=>e.id==='sx-series-a-event')!.date,'2028-07-01');
assert.deepEqual(validateCapitalPlan(cap).filter(e=>e.severity==='error').map(e=>e.code),['empty_equity_issue'],'Unknown Series A terms must prevent submitted/frozen use');
assert.match(sql,/Capital plan changed since review/);
assert.doesNotMatch(sql,/SET\s+opening_cash_yen|SET\s+closing_cash_yen|UPDATE public\.project_pl_monthly/i,'Keep complete old accounting forecast as reference');
console.log('SOL funding plan: 15 months, 4 cases, loans/repayment, capital terms, concurrency guards: PASS');
