import assert from 'node:assert/strict';
import {classifyContractMail,currentMailText,workflowActions} from '../src/lib/workflows.ts';
const input={subject:'',body:'',filenames:[],labels:['INBOX'],from:'partner@example.com',bulk:false,knownThread:false};
for(const labels of [['SENT'],['INBOX'],[]])assert.equal(classifyContractMail({...input,labels,subject:'秘密保持契約書の修正案'}),'exchange');
assert.equal(classifyContractMail({...input,subject:'電子契約の署名依頼'}),'signature_request');
assert.equal(classifyContractMail({...input,subject:'合意締結が完了しました'}),'completion');
assert.equal(classifyContractMail({...input,subject:'NDAひな形',labels:['DRAFT']}),null);
assert.equal(classifyContractMail({...input,subject:'NDA',labels:['SPAM']}),null);
assert.equal(classifyContractMail({...input,subject:'パスワードのお知らせ NDA'}),null);
assert.equal(classifyContractMail({...input,subject:'契約社員の求人情報'}),null);
assert.equal(classifyContractMail({...input,subject:'NDA講座',bulk:true}),null);
assert.equal(classifyContractMail({...input,subject:'Re: ご連絡',body:'承知しました。',knownThread:true}),'exchange');
assert.equal(classifyContractMail({...input,subject:'Re: 日程',body:'来週でお願いします。\nOn Thursday, someone wrote:\n署名依頼 NDA'}),null);
assert.equal(classifyContractMail({...input,subject:'日程',body:'来週\n> 秘密保持契約書'}),null);
assert.equal(currentMailText('確認したよ\n-- \n契約を支える会社'), '確認したよ');
assert.equal(workflowActions('submitted','ID001','ID001','ID002').approve,false);
assert.equal(workflowActions('submitted','ID002','ID001','ID002').approve,true);
assert.equal(workflowActions('approved','ID001','ID001','ID002').release,true);
assert.equal(workflowActions('superseded','ID001','ID001','ID002').release,false);
assert.equal(workflowActions('released','ID002','ID001','ID002').complete,true);
console.log('契約メール分類・引用除外・本人承認・再申請の検証: PASS');
