#!/usr/bin/env node
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { CONTRACT, CURRENT_SPS_TUPLE, Q_FACTORS, expectedSps, stableHash, validateInitialPayload } from "./sps_initial_assessment_tool.mjs";
const here = path.dirname(fileURLToPath(import.meta.url));
const migration = fs.readFileSync(path.join(here, "migrations/301_sps_initial_assessment_review_flow.sql"), "utf8");
const seed = "33333333-3333-4333-8333-333333333333";
const sourceFacts = { seed: { title: "試験技術", summary: "公開要約" }, funding: [{ program: "JST", fiscal_year: 2026 }], news: [{ title: "採択", body_summary: "短い要約" }], contacts: [{ contacted_on: "2026-08-01", method: "meeting" }], projects: [] };
const input = { seed_id: seed, source_fingerprint: "c".repeat(64), source_facts: sourceFacts };
const preparedPromptBody = "\n正本prompt本文\n";
const prepared = { version: 1, contract: CONTRACT, generated_at: "2026-08-20T00:00:00.000Z", prompt: { body: preparedPromptBody, hash: stableHash(preparedPromptBody) }, model: { ...CURRENT_SPS_TUPLE, hash: stableHash(CURRENT_SPS_TUPLE) }, q_factor_ids: Q_FACTORS, inputs: [input] }; prepared.prepared_hash = stableHash(prepared);
const evidence = Q_FACTORS.map((id) => ({ id, name: id, direction: "neutral", evidence: "公開要約に直接の裏付けはなく、初回帯を広く置く", assessment: "不確実" }));
const proposal = { seed_id: seed, ...CURRENT_SPS_TUPLE, stage_lower: "S1", stage_upper: "S2", stage_tag: "stage_inferred", q_lower_pct: 5, q_upper_pct: 20, q_main_factor: "unit_economics", q_evidence: evidence, p_class: "initial-industrial-value", p_lower_yen: 1000000, p_upper_yen: 10000000, sps_lower_yen: 50000, sps_upper_yen: 2000000, notes: "根拠不足を帯幅へ反映した初回候補", semantic_key: "試験技術 初回評価", proposal_summary: "初回SPS評価候補" };
const payload = { version: 1, contract: CONTRACT, prompt_hash: prepared.prompt.hash, prepared_hash: prepared.prepared_hash, proposals: [proposal] };
assert.deepEqual(validateInitialPayload(payload, prepared), []);
assert.equal(expectedSps(10000000, 20), 2000000);
const missing = structuredClone(payload); missing.proposals[0].q_evidence.pop();
assert(validateInitialPayload(missing, prepared).some((x) => x.includes("11 factors")));
const privateText = structuredClone(payload); privateText.proposals[0].notes = "https://example.com";
assert(validateInitialPayload(privateText, prepared).some((x) => x.includes("private text")));
const tamperedPrepared = structuredClone(prepared); tamperedPrepared.prompt.body = "改竄";
assert(validateInitialPayload(payload, tamperedPrepared).some((x) => x.includes("prepared_hash")));
const latePrepared = structuredClone(prepared); latePrepared.inputs[0].source_facts.contacts.push({ contacted_on: "2026-08-21", method: "meeting" }); latePrepared.prepared_hash = stableHash(Object.fromEntries(Object.entries(latePrepared).filter(([key]) => key !== "prepared_hash")));
assert(validateInitialPayload({ ...payload, prepared_hash: latePrepared.prepared_hash }, latePrepared).some((x) => x.includes("information_cutoff")));
const reversedStage = structuredClone(payload); reversedStage.proposals[0].stage_lower = "S4"; reversedStage.proposals[0].stage_upper = "S2";
assert(validateInitialPayload(reversedStage, prepared).some((x) => x.includes("stage range")));
const badDirection = structuredClone(payload); badDirection.proposals[0].q_evidence[0].direction = "positive";
assert(validateInitialPayload(badDirection, prepared).some((x) => x.includes("q_evidence[0]")));
const bareUrl = structuredClone(payload); bareUrl.proposals[0].notes = "example.jp を参照";
assert(validateInitialPayload(bareUrl, prepared).some((x) => x.includes("private text")));
const secret = structuredClone(payload); secret.proposals[0].notes = "API key abc";
assert(validateInitialPayload(secret, prepared).some((x) => x.includes("private text")));
const eduUrl = structuredClone(payload); eduUrl.proposals[0].notes = "example.edu を参照";
assert(validateInitialPayload(eduUrl, prepared).some((x) => x.includes("private text")));
assert.match(migration, /sps_initial_candidate_00_seed_lock[\s\S]*BEFORE INSERT/);
assert.match(migration, /seed already has a complete current SPS tuple/);
assert.match(migration, /sps_initial_assessment_source_snapshot/);
assert.match(migration, /candidate source fingerprint is stale; prepare a new initial assessment/);
assert.match(migration, /submit_sps_initial_assessment_candidates/);
assert.match(migration, /EXCEPTION WHEN unique_violation/);
assert.match(migration, /ORDER BY value->>'seed_id'/);
assert.match(migration, /source_facts=item->'source_facts'/);
assert.match(migration, /sps_initial_candidate_immutable/);
assert.match(migration, /completed initial SPS candidate history is immutable/);
assert.match(migration, /source_initial_candidate_id/);
assert.match(migration, /WITH ORDINALITY/);
assert.match(migration, /ORDER BY f\.id/);
assert.match(migration, /ORDER BY n\.id/);
assert.match(migration, /ORDER BY c\.id/);
assert.match(migration, /ORDER BY sp\.project_id/);
assert.match(migration, /to_jsonb\(NEW\.prompt_body\)::text/);
assert.match(migration, /source state changed after information cutoff/);
assert.match(migration, /extensions\.digest/);
assert.match(migration, /f\.status IN \('awarded','ongoing','completed'\)/);
assert.match(migration, /\[認証情報省略\]/);
const tool = fs.readFileSync(path.join(here, "sps_initial_assessment_tool.mjs"), "utf8");
assert.match(tool, /\.limit\(1000\)/);
assert.match(tool, /source_fingerprint: input\.source_fingerprint/);
assert.doesNotMatch(tool, /source_fingerprint: p\.source_fingerprint/);
assert.match(tool, /prompt or model changed after prepare/);
assert.match(tool, /const body = String\(data\?\.body \?\? ""\); if \(error \|\| !body\.trim\(\)\)/);
assert.match(migration, /stage_lower must not exceed stage_upper/);
assert.match(migration, /q_evidence must contain exactly 11 factors/);
assert.match(migration, /apply_sps_initial_assessment_candidate[\s\S]*pg_advisory_xact_lock/);
assert.match(migration, /INSERT INTO public\.seed_screening_bands[\s\S]*true/);
assert.doesNotMatch(migration, /UPDATE public\.seed_screening_bands/);
assert.match(migration, /REVOKE ALL ON FUNCTION public\.apply_sps_initial_assessment_candidate/);
console.log("SPS initial assessment flow tests passed");
