import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

// Generic detector for a leaked absolute home-directory path (any OS user),
// not a hardcoded username: matches /Users/<name>/... or /home/<name>/...
const ABSOLUTE_HOME_PATH_PATTERN = /\/(?:Users|home)\/[^\/\s"']+\//;

const __dirname = dirname(fileURLToPath(import.meta.url));

const SOURCE_HTML_PATH = join(__dirname, "content", "index.html");
const LOGO_SYMBOL_ASSET_PATH = join(__dirname, "content", "assets", "logo-symbol.png");
const LOGO_TYPE_ASSET_PATH = join(__dirname, "content", "assets", "logo-type.png");
const COVER_ILLUSTRATION_ASSET_PATH = join(__dirname, "content", "assets", "cover-illustration.png");
const TECH_PHOTO_ASSET_PATH = join(__dirname, "content", "assets", "tech-photo.png");

// content/index.html is a snapshot whose <img src> literals point at the
// local content/assets copies via relative paths. We search-and-replace
// those exact strings with data URLs built from the same files, so this
// package has no dependency on any path outside this directory.
const LOGO_SYMBOL_SOURCE_REF = "./assets/logo-symbol.png";
const LOGO_TYPE_SOURCE_REF = "./assets/logo-type.png";
const COVER_ILLUSTRATION_SOURCE_REF = "./assets/cover-illustration.png";
const TECH_PHOTO_SOURCE_REF = "./assets/tech-photo.png";

function toDataUrl(path) {
  const buf = readFileSync(path);
  return `data:image/png;base64,${buf.toString("base64")}`;
}

const html = readFileSync(SOURCE_HTML_PATH, "utf8");
const symbolDataUrl = toDataUrl(LOGO_SYMBOL_ASSET_PATH);
const typeDataUrl = toDataUrl(LOGO_TYPE_ASSET_PATH);
const coverIllustrationDataUrl = toDataUrl(COVER_ILLUSTRATION_ASSET_PATH);
const techPhotoDataUrl = toDataUrl(TECH_PHOTO_ASSET_PATH);

const inlined = html
  .split(LOGO_SYMBOL_SOURCE_REF).join(symbolDataUrl)
  .split(LOGO_TYPE_SOURCE_REF).join(typeDataUrl)
  .split(COVER_ILLUSTRATION_SOURCE_REF).join(coverIllustrationDataUrl)
  .split(TECH_PHOTO_SOURCE_REF).join(techPhotoDataUrl);

if (ABSOLUTE_HOME_PATH_PATTERN.test(inlined)) {
  throw new Error("build.mjs: unresolved absolute home-directory path remains in output HTML");
}

const outDir = join(__dirname, "server");
mkdirSync(outDir, { recursive: true });

const outPath = join(outDir, "deck-data.mjs");
const banner = "// Generated by build.mjs — do not edit by hand. Run `npm run build` to regenerate.\n";
const body = `${banner}export const DECK_HTML = ${JSON.stringify(inlined)};
export const LOGO_SYMBOL_DATA_URL = ${JSON.stringify(symbolDataUrl)};
export const LOGO_TYPE_DATA_URL = ${JSON.stringify(typeDataUrl)};
`;
writeFileSync(outPath, body, "utf8");

console.log(`build.mjs: wrote server/deck-data.mjs (${(body.length / 1024).toFixed(1)} KB)`);

const vendorDir = join(__dirname, "public", "vendor");
mkdirSync(vendorDir, { recursive: true });
await esbuild.build({
  entryPoints: [join(__dirname, "node_modules", "@vercel", "blob", "dist", "client.js")],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2020",
  outfile: join(vendorDir, "blob-client.mjs"),
  logLevel: "silent",
});
console.log("build.mjs: wrote public/vendor/blob-client.mjs (browser bundle of @vercel/blob/client)");
