/**
 * Audited method-level auth ownership, not user identity. Empty entries retain
 * middleware getUser and disambiguate static routes from dynamic siblings.
 * Regenerate only after reviewing scripts/api_auth_route_inventory.mjs and run
 * npm run test:api-auth. Unmatched paths/methods retain full validation.
 * A new static route may match an existing dynamic template; the full-source
 * inventory check must pass before shipping so that route gets its own entry.
 */
export const API_ROUTE_AUTH_METHODS: Readonly<Record<string, readonly string[]>> = {
  "/api/action-items/extract": [],
  "/api/action-items": ["GET","HEAD","PATCH","POST"],
  "/api/activities/infer": ["POST"],
  "/api/admin/budget-approval": ["POST"],
  "/api/admin/cash-entries": ["DELETE","POST"],
  "/api/admin/cash-import-sheet": [],
  "/api/admin/cash-loan-events": ["DELETE","POST"],
  "/api/admin/cash": ["GET","HEAD"],
  "/api/admin/change-history": ["GET","HEAD","POST"],
  "/api/admin/collect-vc-investment-history": [],
  "/api/admin/company-media/asset-crop": ["PATCH"],
  "/api/admin/company-media/group-cover": ["PATCH"],
  "/api/admin/company-members/photo": ["POST"],
  "/api/admin/dd": [],
  "/api/admin/enrich-vcs": [],
  "/api/admin/extract-amd-pj-investments": [],
  "/api/admin/finance/obligations": [],
  "/api/admin/finance/receipts": ["POST"],
  "/api/admin/finance/reconciliation": ["GET","HEAD","POST"],
  "/api/admin/finance/recurring": ["PATCH","POST"],
  "/api/admin/freee-partners": ["GET","HEAD"],
  "/api/admin/inspect-sheet": [],
  "/api/admin/invoices/draft": ["POST"],
  "/api/admin/invoices/freee-partner": ["PATCH"],
  "/api/admin/invoices/invoice-ym": ["PATCH"],
  "/api/admin/kiyo/money-flow": ["GET","HEAD"],
  "/api/admin/lane-suggestions/[id]": ["PATCH"],
  "/api/admin/management-knowledge": ["GET","HEAD","PATCH","POST"],
  "/api/admin/members": ["PATCH","POST"],
  "/api/admin/monthly-work-agreements/amount-change-reasons": ["GET","HEAD","POST"],
  "/api/admin/monthly-work-agreements/revision-requests": ["GET","HEAD","PATCH"],
  "/api/admin/monthly-work-agreements": ["GET","HEAD"],
  "/api/admin/ms-overview/[planCycleId]": ["POST","PUT"],
  "/api/admin/ms-overview": ["GET","HEAD"],
  "/api/admin/payment-confirm": [],
  "/api/admin/payouts/member-breakdown": ["GET","HEAD"],
  "/api/admin/payouts": ["GET","HEAD","PATCH","POST"],
  "/api/admin/pj-introduction-html": ["POST"],
  "/api/admin/private-wiki": ["GET","HEAD","PATCH","POST"],
  "/api/admin/project-members/[id]": ["DELETE"],
  "/api/admin/project-members/bulk": ["POST"],
  "/api/admin/project-profitability": ["GET","HEAD"],
  "/api/admin/projects/[id]": ["PATCH"],
  "/api/admin/projects/[id]/weekly-slack-report": ["PATCH"],
  "/api/admin/prompts/[id]": ["PATCH"],
  "/api/admin/restore-from-sheet": [],
  "/api/admin/schedule/actions": ["POST"],
  "/api/admin/schedule/rebuild": ["POST"],
  "/api/admin/schedule": ["GET","HEAD"],
  "/api/admin/season-pl": ["GET","HEAD"],
  "/api/admin/seed-vcs": [],
  "/api/admin/settings": ["DELETE","GET","HEAD","PATCH","POST"],
  "/api/admin/space-permissions": ["GET","HEAD","POST"],
  "/api/admin/sx-partner-sheet-export": [],
  "/api/admin/tsukuyomi/context": ["GET","HEAD","PATCH","POST"],
  "/api/admin/weekly": ["GET","HEAD"],
  "/api/admin/workspace-access": ["GET","HEAD","PATCH","POST"],
  "/api/atlas/auto-tag": [],
  "/api/atlas/backfill": [],
  "/api/atlas/decisions": ["PATCH","POST"],
  "/api/atlas/match-stories": [],
  "/api/atlas/merge-stories": ["POST"],
  "/api/atlas/move-signal": ["POST"],
  "/api/atlas/recent-titles": [],
  "/api/atlas/seed": [],
  "/api/atlas/signals-ingest": [],
  "/api/atlas/signals/review": ["POST"],
  "/api/atlas/signals/submit": ["POST"],
  "/api/atlas/themes/apply": ["POST"],
  "/api/atlas/themes/cluster": ["POST"],
  "/api/atlas/themes/list": ["GET","HEAD"],
  "/api/auth/email-start": [],
  "/api/automation/weekly-slack-report": [],
  "/api/build-info": [],
  "/api/business-cards/[cardId]/image": ["GET","HEAD"],
  "/api/business-cards/[cardId]": [],
  "/api/business-cards": [],
  "/api/bzm-reader/asset/[...path]": ["GET","HEAD"],
  "/api/bzm/theory-map": ["DELETE","GET","HEAD","PATCH","POST"],
  "/api/calendar-feeds": [],
  "/api/company-media/file/[assetId]": ["GET","HEAD"],
  "/api/contracts/[contractId]": ["PATCH"],
  "/api/contracts/apply": ["GET","HEAD","POST"],
  "/api/contracts/documents": ["POST"],
  "/api/contracts/extract-l2": [],
  "/api/contracts/nudges/dry-run": ["GET","HEAD"],
  "/api/contracts": ["GET","HEAD","PATCH","POST"],
  "/api/contracts/signal-dry-run": ["GET","HEAD"],
  "/api/contracts/terms": ["PATCH","POST"],
  "/api/coverage-gaps/extract": [],
  "/api/cron/amd-score-l2-refresh": [],
  "/api/cron/atlas-collect-policy": [],
  "/api/cron/atlas-collect": [],
  "/api/cron/atlas-daily": [],
  "/api/cron/atlas-divergence": [],
  "/api/cron/atlas-monthly": [],
  "/api/cron/atlas-weekly": [],
  "/api/cron/company-operating-facts": [],
  "/api/cron/company-schedule": [],
  "/api/cron/contract-billing-auto-confirm": ["POST"],
  "/api/cron/founding-members-extract": [],
  "/api/cron/freee-accounting-weekly": [],
  "/api/cron/freee-cash-balance-sync": [],
  "/api/cron/freee-cash-ledger-sync": [],
  "/api/cron/freee-member-payout-sync": [],
  "/api/cron/freee-payment-sync": [],
  "/api/cron/freee-revenue-by-partner": [],
  "/api/cron/freeze-period-backfill": [],
  "/api/cron/frl-grit-resilience-extract": [],
  "/api/cron/governance-email-sweep": [],
  "/api/cron/graduation-detection": [],
  "/api/cron/grant-ingest": [],
  "/api/cron/hourly-estimate": [],
  "/api/cron/kaken-ingest": [],
  "/api/cron/lane-suggest": [],
  "/api/cron/macro-aggregate-indicators": [],
  "/api/cron/macro-backfill-historical": [],
  "/api/cron/management-score-calculate": [],
  "/api/cron/management-score-raw-data": [],
  "/api/cron/management-score-refresh": [],
  "/api/cron/member-activities": [],
  "/api/cron/member-weekly-activities": [],
  "/api/cron/monthly-reports-backfill": [],
  "/api/cron/ms-schedule-progress": [],
  "/api/cron/papers-quarterly-ingest": [],
  "/api/cron/payment-confirm-nudges": ["POST"],
  "/api/cron/payment-obligations": ["POST"],
  "/api/cron/payout-notice-prebuild": [],
  "/api/cron/payout-reward-cache-refresh": ["POST"],
  "/api/cron/proactive-todo-extract": [],
  "/api/cron/reimbursement-reminders": [],
  "/api/cron/relearn-lane-weights": [],
  "/api/cron/seeds-ingest": [],
  "/api/cron/slack-source-sync": [],
  "/api/cron/sync-pj-facts": [],
  "/api/cron/triple-helix-recompute": [],
  "/api/cron/vc-discover": [],
  "/api/cron/vc-investment-ingest": [],
  "/api/cron/venture-narrative-refresh": [],
  "/api/cron/venture-xrl-refresh": [],
  "/api/dashboard/company-content": ["GET","HEAD"],
  "/api/dashboard/extraction-status": ["GET","HEAD"],
  "/api/dashboard/freee-connection-status": ["GET","HEAD"],
  "/api/dashboard/portfolio-pulse": ["GET","HEAD"],
  "/api/dd/[slug]/edit": [],
  "/api/dd/summary": ["GET","HEAD"],
  "/api/dialogue-meeting/narrate": [],
  "/api/dialogue-meeting": [],
  "/api/finance/live-cash-balances": [],
  "/api/founding-members/revise": ["POST"],
  "/api/funding-stats": ["GET","HEAD"],
  "/api/governance/capital-plans/export": [],
  "/api/governance/capital-plans": ["PATCH","POST"],
  "/api/governance/company-overview-export": [],
  "/api/governance/extract": [],
  "/api/governance/killer-factors": ["GET","HEAD","POST"],
  "/api/governance": ["DELETE","PATCH","POST"],
  "/api/grants": ["DELETE","GET","HEAD","PATCH","POST"],
  "/api/guardrails/evaluate": [],
  "/api/hud/dashboard": [],
  "/api/institution-regulations": ["GET","HEAD","POST"],
  "/api/institutions/assess": [],
  "/api/institutions/policies": [],
  "/api/institutions/support-program-recommendations": ["POST"],
  "/api/institutions/support-programs": ["GET","HEAD"],
  "/api/internal/notion-context": [],
  "/api/invoice/create": ["POST"],
  "/api/invoice/preview": ["GET","HEAD"],
  "/api/macos/auth/google-complete": ["POST"],
  "/api/macos/document": [],
  "/api/macos/ip": ["GET","HEAD"],
  "/api/macos/management-score/inputs": ["GET","HEAD"],
  "/api/macos/materials": ["GET","HEAD"],
  "/api/management-score/finance/simulate": ["POST"],
  "/api/manual/tsukuyomi/ask": ["POST"],
  "/api/media-mentions/extract": [],
  "/api/meeting-assets/adopt-drive-folder": [],
  "/api/meeting-assets/file/[assetId]": ["GET","HEAD"],
  "/api/meeting-assets/insert-markdown": ["POST"],
  "/api/meeting-assets": ["DELETE","GET","HEAD","PATCH","POST"],
  "/api/meeting-calendar/upsert-plan": [],
  "/api/meeting-prep/calendar-sync": [],
  "/api/meeting-prep": [],
  "/api/meeting-summary/backfill": [],
  "/api/meeting-summary/manual-update": ["POST"],
  "/api/meeting-summary/narrate": [],
  "/api/meeting-workflow/actions/[actionId]/complete": [],
  "/api/meeting-workflow/finalize": [],
  "/api/model/bzm30": ["GET","HEAD"],
  "/api/model/sections": ["GET","HEAD"],
  "/api/monthly-report/edit-by-tsukuyomi": ["POST"],
  "/api/monthly-report/external-manual-update": ["GET","HEAD","POST"],
  "/api/monthly-report/history": ["GET","HEAD"],
  "/api/monthly-report/manual-update": ["POST"],
  "/api/monthly-report/pdf": ["POST"],
  "/api/monthly-work-agreement/agree": ["POST"],
  "/api/monthly-work-agreement/request-revision": ["POST"],
  "/api/monthly-work-agreement": ["GET","HEAD"],
  "/api/ms/auth/callback": [],
  "/api/ms/auth/start": [],
  "/api/ms/calendar": [],
  "/api/mypage/weekly-activities/refresh": ["POST"],
  "/api/mypage/weekly-tasks": ["GET","HEAD","POST"],
  "/api/notifications/feedback/dialog/confirm": [],
  "/api/notifications/feedback/dialog/refine": [],
  "/api/notifications/feedback/dialog/start": [],
  "/api/notifications/feedback": [],
  "/api/page-viewing": [],
  "/api/proactive-todos/[id]/resolve": [],
  "/api/progress/batch-save": ["POST"],
  "/api/progress/confirm": ["POST"],
  "/api/progress/estimate": ["POST"],
  "/api/progress/events": ["GET","HEAD","PATCH"],
  "/api/progress/ms-schedule": [],
  "/api/progress/reimbursement": ["GET","HEAD"],
  "/api/progress/revisions": ["GET","HEAD","PATCH","POST"],
  "/api/progress/unconfirmed": ["GET","HEAD"],
  "/api/project-business-plan": [],
  "/api/project-cost-model": [],
  "/api/project-development-issues": [],
  "/api/project-events/parse": ["POST"],
  "/api/project-ip": [],
  "/api/project-organization-chart": [],
  "/api/project-surface/cockpit/[projectId]": [],
  "/api/project-surface/navigation/[projectId]": [],
  "/api/project-tech": [],
  "/api/project-ventures/[projectId]/narrative-regen": ["POST"],
  "/api/project-ventures/[projectId]/pl-hearing/turn": ["POST"],
  "/api/project-ventures/[projectId]/xrl-revise": ["POST"],
  "/api/project-workspace/[projectId]/automation-context": [],
  "/api/project-workspace/[projectId]/effort": [],
  "/api/project-workspace/[projectId]/management": [],
  "/api/project-workspace/[projectId]": [],
  "/api/project-workspace/[projectId]/theme/[trackKey]": [],
  "/api/project-workspace/access": [],
  "/api/project/[projectId]/amd-contributions": [],
  "/api/project/[projectId]/amd-score-detail": [],
  "/api/project/[projectId]/business-summary": [],
  "/api/project/[projectId]/bzm-2-2-acquisitions": [],
  "/api/project/[projectId]/bzm-2-2-pilot": [],
  "/api/project/[projectId]/contract-list": [],
  "/api/project/[projectId]/org": ["GET","HEAD"],
  "/api/project/[projectId]/overview": [],
  "/api/project/[projectId]/proper-nouns": [],
  "/api/project/[projectId]/question-tree": [],
  "/api/project/[projectId]/season-budget": [],
  "/api/project/[projectId]/shared-publication": [],
  "/api/project/[projectId]/sps-current": [],
  "/api/project/[projectId]/workspace-bundle": [],
  "/api/project/[projectId]/workspace-meetings": [],
  "/api/project/monthly-note": ["GET","HEAD","POST"],
  "/api/project/monthly-report-print": ["GET","HEAD"],
  "/api/project/monthly-reports": [],
  "/api/reimbursements/decision": ["POST"],
  "/api/reimbursements": [],
  "/api/report/fix": ["POST"],
  "/api/report/generate": ["POST"],
  "/api/rewards/sync": ["POST"],
  "/api/seeds/[seedId]/commercialization": ["POST"],
  "/api/seeds/[seedId]/deep-dive": ["GET","HEAD"],
  "/api/seeds/bzm30-sensitivity": ["GET","HEAD"],
  "/api/seeds/bzm30": ["GET","HEAD"],
  "/api/seeds/screening-bands": ["GET","HEAD"],
  "/api/settings/cron-run": [],
  "/api/slack/interactive": [],
  "/api/slack/messages": [],
  "/api/slack/reimbursement-decision": [],
  "/api/sources/gmail/collect": [],
  "/api/sources/slack/collect": [],
  "/api/sps/current": ["GET","HEAD"],
  "/api/strategy-signals": [],
  "/api/task-calendar/register-tasks": [],
  "/api/task-calendar/schedule-plan": [],
  "/api/tasks": [],
  "/api/tsukuyomi/chat": ["POST"],
  "/api/tsukuyomi/post": ["POST"],
  "/api/workspace-documents/[documentId]/assets": [],
  "/api/workspace-documents/[documentId]/deck/publish": [],
  "/api/workspace-documents/[documentId]/deck": [],
  "/api/workspace-documents/[documentId]/edit-frame": [],
  "/api/workspace-documents/[documentId]/open": [],
  "/api/workspace-documents/[documentId]/pdf": [],
  "/api/workspace-documents/[documentId]/render": [],
  "/api/workspace-documents/[documentId]/revisions/[revisionNo]": [],
  "/api/workspace-documents/[documentId]/revisions": [],
  "/api/workspace-documents/[documentId]": [],
  "/api/workspace-documents/[documentId]/source": [],
  "/api/workspace-documents": [],
};

const routes = Object.entries(API_ROUTE_AUTH_METHODS).map(([template, methods]) => {
  const segments = template.split('/').filter(Boolean);
  const rank = segments.map(segment => segment.startsWith('[[...') ? 0 : segment.startsWith('[...') ? 1 : segment.startsWith('[') ? 2 : 3);
  const pattern = segments.map(segment => {
    if (segment.startsWith('[[...')) return '(?:/.*)?';
    if (segment.startsWith('[...')) return '/.+';
    if (segment.startsWith('[')) return '/[^/]+';
    return '/' + segment.replace(/[^a-zA-Z0-9_-]/g, character => "\\" + character);
  }).join('');
  return { methods, rank, pattern: new RegExp('^' + pattern + '/?$') };
}).sort((a, b) => {
  for (let i = 0; i < Math.max(a.rank.length, b.rank.length); i++) {
    const difference = (b.rank[i] ?? -1) - (a.rank[i] ?? -1);
    if (difference) return difference;
  }
  return 0;
});

export function apiRouteOwnsAuthentication(pathname: string, method: string): boolean {
  const route = routes.find(candidate => candidate.pattern.test(pathname));
  if (!route) return false;
  return route.methods.includes(method);
}
