/**
 * POST /api/invoice/create
 * freee APIで請求書を作成し、Supabaseに記録する。
 * body: { projectId, ym, issueDate, dueDate, subject, lines, remark }
 *
 * legacy route。現行正本は /admin/invoices + Edge Function issue-invoice。
 * 残す間も「発行」と「送付」を混ぜず、billing_cycles.invoice_issued_* 側だけ更新する。
 */

import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { freeeApi } from "@/lib/freee-client";
import { requireAdmin } from "@/lib/supabase/api-auth";

interface InvoiceLine {
  description: string;
  quantity: number;
  unitPrice: number;
}

function toInvoiceBaseLinesJson(lines: InvoiceLine[]) {
  return JSON.stringify(lines.map((line) => ({
    type: "item",
    description: line.description,
    quantity: String(line.quantity || 1),
    unit_price: String(line.unitPrice || 0),
  })));
}

export async function POST(req: Request) {
  const auth = await requireAdmin();
  if (!auth.ok) return auth.errorResponse;

  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL || "https://placeholder.supabase.co",
    process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "placeholder"
  );

  try {
    const { projectId, ym, issueDate, dueDate, subject, lines, remark } = await req.json();

    if (!projectId || !ym || !issueDate || !dueDate) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }
    if (!Array.isArray(lines) || lines.length === 0) {
      return NextResponse.json({ error: "lines required" }, { status: 400 });
    }

    // プロジェクト情報
    const { data: project } = await supabase
      .from("projects")
      .select("project_id, project_name, client_name, freee_partner_id")
      .eq("project_id", projectId)
      .single();

    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    if (!project.freee_partner_id) {
      return NextResponse.json({ error: "freee取引先IDが未設定です" }, { status: 400 });
    }

    const companyId = parseInt(process.env.FREEE_COMPANY_ID || "0");

    // freee請求書作成リクエスト
    const inputLines = lines as InvoiceLine[];
    const invoiceLines = inputLines.map((line, i) => ({
      type: "normal",
      description: line.description,
      quantity: line.quantity,
      unit_price: line.unitPrice,
      tax_code: 21, // 10% tax
      order: i,
    }));

    const invoiceBody = {
      company_id: companyId,
      partner_id: parseInt(project.freee_partner_id),
      invoice_number: "", // auto-generated by freee
      title: subject || `${project.project_name} 請求書`,
      issue_date: issueDate,
      due_date: dueDate,
      invoice_layout: "default_classic",
      tax_entry_method: "exclusive",
      invoice_contents: invoiceLines,
      message: remark || "",
    };

    // freee API: 請求書作成
    const createRes = await freeeApi("POST", "/api/1/invoices", invoiceBody) as {
      invoice: { id: number; invoice_number: string; total_amount: number };
    };

    const freeeInvoiceId = createRes.invoice.id;
    const freeeInvoiceNumber = createRes.invoice.invoice_number;
    const totalAmount = createRes.invoice.total_amount;

    // Supabase billing_cycles 更新。発行と送付は別 step なので invoice_sent_at は触らない。
    const now = new Date().toISOString();
    const { data: updatedRows, error: updateError } = await supabase
      .from("billing_cycles")
      .update({
        invoice_issued_at: now,
        invoice_issued_by: auth.user.email,
        freee_invoice_number: freeeInvoiceNumber,
        invoice_subject: subject || `${project.project_name} 請求書`,
        invoice_base_lines_json: toInvoiceBaseLinesJson(inputLines),
      })
      .eq("project_id", projectId)
      .eq("ym", ym)
      .select("id");
    if (updateError) throw updateError;
    if (!updatedRows || updatedRows.length === 0) {
      return NextResponse.json({ error: "billing_cycle not found" }, { status: 404 });
    }

    return NextResponse.json({
      ok: true,
      freeeInvoiceId,
      freeeInvoiceNumber,
      totalAmount,
      issuedAt: now,
    });
  } catch (err) {
    console.error("Invoice creation error:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Unknown error" },
      { status: 500 }
    );
  }
}
