-- l2m team ledger: initial Lind 3 roster from the existing iPhone BossCatalog.
-- Existing local kill records stay on the device. No schedule or member is seeded.
-- Unverified cycles remain marked as such and can be corrected separately.
insert into public.game_servers (slug, display_name) values ('lind-3', 'リンド3') on conflict (slug) do nothing;

insert into public.boss_catalog (id, display_name, short_name, default_respawn_seconds, default_cycle_verified) values
  ('felis', 'フェリス', 'フェリ', 7200, true),
  ('basila', 'バシラ', 'バシ', 9000, true),
  ('chertuba', 'チェルトゥバ', 'チェル', 10800, true),
  ('pan_narod', 'パン ナロード', 'パンナ', 10800, true),
  ('enkura', 'エンクラ', 'エン', 12600, true),
  ('tempest', 'テンペスト', 'テンペ', 12600, true),
  ('stan', 'スタン', 'スタン', 14400, true),
  ('matura', 'マトゥラ', 'マト', 14400, true),
  ('timitris', 'ティミトリス', 'トリス', 18000, true),
  ('talkin', 'タルキン', 'タル', 18000, true),
  ('kelsus', 'ケルソス', 'ケル', 21600, true),
  ('behemoth', 'ベヒモス', 'ベヒ', 21600, true),
  ('saruka', 'サルカ', 'サルカ', 25200, true),
  ('tarakin', 'タラキン', 'タラ', 25200, true),
  ('medusa', 'メデューサ', 'メデュ', 25200, true),
  ('randall', 'ランドール', 'ランド', 28800, true),
  ('pandride', 'パン ドライド', 'パンド', 28800, true),
  ('mutant_kruma', 'ミュータント クルマ', 'MC', 28800, true),
  ('timiniel', 'ティミニエル', 'ニエル', 28800, true),
  ('glaki', 'グラーキ', 'グラ', 28800, true),
  ('katan', 'カタン', 'カタン', 28800, true),
  ('contaminated_kruma', '汚染したクルマ', '汚染', 28800, true),
  ('coroon', 'コルーン', 'コル', 36000, true),
  ('savan', 'サヴァン', 'サバ', 43200, true),
  ('dragon_beast', 'ドラゴン ビースト', 'ドラビ', 43200, true),
  ('andras', 'アンドラス', 'アンド', 43200, true),
  ('black_lily', 'ブラック リリー', 'リリー', 43200, true),
  ('cabrio', 'カブリオ', 'カブ', 43200, true),
  ('samuel', 'サミュエル', 'サミュ', 43200, true),
  ('mirror_of_oblivion', '忘却の鏡', '鏡', 43200, true),
  ('core_susceptor', 'コア サセプタ', 'コア', 43200, true),
  ('cyrax', 'サイラックス', 'サイラ', 86400, true),
  ('modeus', 'モデウス', 'モデ', 86400, true),
  ('barak', 'バラック', 'バラ', 86400, true),
  ('baron', 'バロン', 'バロ', 86400, true),
  ('queen_ant', 'クイーン アント', 'QA', 21600, false),
  ('breka', 'ブレカ', 'ブレカ', 21600, false),
  ('cell', 'セル', 'セル', 43200, false),
  ('repiro', 'レピロ', 'レピロ', 25200, false),
  ('tromba', 'トロンバ', 'トロ', 25200, false),
  ('gareth', 'ガレス', 'ガレス', 32400, false),
  ('hisilrome', 'ヒシルローメ', 'ヒシル', 21600, false),
  ('balbo', 'バルボ', 'バルボ', 43200, false),
  ('raha', 'ラーハ', 'ラーハ', 118800, false),
  ('furi', 'フリント', 'フリ', 18000, false),
  ('half', 'ハーフ', 'ハーフ', 72000, false),
  ('naiad', 'ナイアス', 'ナイアス', 54000, false),
  ('shade', 'シャディス', 'シャデ', 43200, false),
  ('kusu', 'オルクス', 'クス', 86400, false),
  ('spirit_wind', 'シーラー', '風', 43200, false),
  ('spirit_dark', 'ムーフ', '闇', 43200, false),
  ('spirit_earth', 'ノルムス', '地', 64800, false),
  ('spirit_water', 'ウカンバ', '水', 64800, false),
  ('tana', 'タナトス', 'タナ', 90000, false),
  ('fen', 'オルフェン', 'フェン', 86400, false),
  ('feni', 'フェニックス', 'フェニ', 86400, false),
  ('heka', 'ヘカトン', 'ヘカ', 43200, false)
on conflict (id) do nothing;

insert into public.server_bosses (game_server_id, boss_id, respawn_seconds, cycle_verified, initial_spawn_delay_hours)
select gs.id, bc.id, bc.default_respawn_seconds, bc.default_cycle_verified, seed.initial_spawn_delay_hours
from public.game_servers gs
cross join (values
  ('felis', 0),
  ('basila', 0),
  ('chertuba', 0),
  ('pan_narod', 0),
  ('enkura', 0),
  ('tempest', 0),
  ('stan', 0),
  ('matura', 0),
  ('timitris', 0),
  ('talkin', 0),
  ('kelsus', 6),
  ('behemoth', 6),
  ('saruka', 0),
  ('tarakin', 0),
  ('medusa', 0),
  ('randall', 10),
  ('pandride', 0),
  ('mutant_kruma', 6),
  ('timiniel', 6),
  ('glaki', 6),
  ('katan', 6),
  ('contaminated_kruma', 6),
  ('coroon', 6),
  ('savan', 6),
  ('dragon_beast', 14),
  ('andras', 10),
  ('black_lily', 10),
  ('cabrio', 10),
  ('samuel', 10),
  ('mirror_of_oblivion', 10),
  ('core_susceptor', 14),
  ('cyrax', 6),
  ('modeus', 14),
  ('barak', 6),
  ('baron', 14),
  ('queen_ant', 14),
  ('breka', 0),
  ('cell', 0),
  ('repiro', 0),
  ('tromba', 0),
  ('gareth', 6),
  ('hisilrome', 6),
  ('balbo', 6),
  ('raha', 14),
  ('furi', 10),
  ('half', 10),
  ('naiad', 10),
  ('shade', 10),
  ('kusu', 14),
  ('spirit_wind', 14),
  ('spirit_dark', 14),
  ('spirit_earth', 14),
  ('spirit_water', 14),
  ('tana', 14),
  ('fen', 14),
  ('feni', 14),
  ('heka', 6)
) as seed(boss_id, initial_spawn_delay_hours)
join public.boss_catalog bc on bc.id = seed.boss_id
where gs.slug = 'lind-3'
on conflict (game_server_id, boss_id) do nothing;
