-- 024_vc_unmatched_stubs.sql
--
-- import-contacts-from-sheet 1 回目で 69 件 unmatched_vcs (alias 不明) として
-- skip された VC のうち、AMD 案件で頻出する主要ものを stub で追加。
-- 次の import 実行で relation が拾えるように、alias map と一致する name で投入。
-- thesis 等は cron / 手入力 / enrich-vcs で後から埋める前提。

INSERT INTO vcs (name, name_en, slug, type, amd_rating, amd_rating_note, amd_rating_updated_at, notes)
VALUES
  ('Reazon HD', 'Reazon Holdings', 'reazon-hd', 'corporate', 2, '事業会社系。KT で MTG 履歴。', NOW(), NULL),
  ('農林中金キャピタル', 'Norinchukin Capital', 'norinchukin-capital', 'cvc', 2, '農林中金 CVC。KT で 2 号ファンドで検討中。', NOW(), NULL),
  ('武蔵工業CVC', 'Musashi Seimitsu Industry CVC', 'musashi-cvc', 'cvc', 2, '武蔵精密工業系。KT で site visit + DD 開始済 (2023 時点)。', NOW(), NULL),
  ('三井住友信託銀行', 'Sumitomo Mitsui Trust Bank (SMTB)', 'smtb', 'corporate', 2, '信託銀行系。KT で NDA ひな形受領。', NOW(), NULL),
  ('JMTC', 'Japan Materials Technology Capital (JMTC)', 'jmtc', 'cvc', 3, '日本曹達系。KT / CTB / LST / MC で接点あり、リード対応の場面も。', NOW(), NULL),
  ('Colopl Next', 'Colopl Next', 'colopl-next', 'cvc', 1, 'コロプラ CVC。KT で 9/4 mtg。', NOW(), NULL),
  ('Incubate Capital Japan', 'Incubate Capital Japan (ICJ)', 'incubate-capital-japan', 'independent', 2, 'シード VC。KT / SE / r3kt / JC で接点。', NOW(), NULL),
  ('Will VC', 'Will VC (WV)', 'will-vc', 'independent', 2, 'KT で lead capable + 検討継続 (★2)。', NOW(), NULL),
  ('Pacific Capital', 'Pacific Capital (PacCap)', 'pacific-capital', 'independent', 2, 'KT で接点 ★3。', NOW(), NULL),
  ('Prime Partners', 'Prime Partners', 'prime-partners', 'independent', 2, 'KT で 8/8 mtg、50-500M ticket。', NOW(), NULL),
  ('UNITED', 'UNITED', 'united', 'cvc', 2, 'KT で前回お断り→再アプローチ→8/30 mtg。', NOW(), NULL),
  ('日本生命', 'Nippon Life Insurance', 'nippon-life', 'corporate', 1, 'KT で再アプローチ中。', NOW(), NULL),
  ('Z Venture Capital', 'Z Venture Capital (ZVC)', 'z-venture-capital', 'cvc', 1, 'Z Holdings (Yahoo / LINE) 系 CVC。KT / r3kt で接点。', NOW(), NULL),
  ('Globis Capital Partners Japan', 'Globis Capital Partners Japan (GCPJ)', 'gcpj-extra', 'independent', 1, 'KT で再アプローチ中。', NOW(), NULL),
  ('Innovation Engine', 'Innovation Engine', 'innovation-engine', 'independent', 2, 'KT で 8/9 社長プレゼン予定。', NOW(), NULL),
  ('伊予銀ベンチャー (ITV)', 'Iyo Bank Venture (ITV)', 'itv', 'cvc', 1, 'KT で打診中、コンフリクト確認中。', NOW(), NULL),
  ('Samsung Next', 'Samsung Next', 'samsung-next', 'cvc', 1, 'Samsung 系 CVC、海外。KT で接点 (Dave Lin 経由)。', NOW(), NULL),
  ('Bricks Fund Tokyo', 'Bricks Fund Tokyo', 'bricks-fund-tokyo', 'independent', 2, 'KT で接点。', NOW(), NULL),
  ('Eneos Innovation Investment (EEI)', 'Eneos Innovation Investment (EEI)', 'eei', 'cvc', 2, 'ENEOS 系 CVC。KT / MC で接点 ★3。', NOW(), NULL),
  ('Toyota Boshoku', 'Toyota Boshoku Corporation', 'toyota-boshoku', 'corporate', 1, '事業会社 (KT 関連)。', NOW(), NULL),
  ('epiST', 'epiST', 'epist', 'independent', 2, 'KT で follow 検討継続。', NOW(), NULL),
  ('Oval', 'Oval', 'oval', 'independent', 2, 'KT で follow リード待ち。', NOW(), NULL),
  ('Emellience Partners', 'Emellience Partners', 'emellience', 'independent', 2, 'KT で lead capable。', NOW(), NULL),
  ('AMANO', 'AMANO Corporation', 'amano', 'corporate', 1, 'KT で下里さん経由、レス遅い。', NOW(), NULL),
  ('寺田倉庫', 'Terrada Warehouse', 'terada-warehouse', 'corporate', 1, '事業会社。KT で接点。', NOW(), NULL),
  ('筑波SBI', 'Tsukuba SBI', 'tsukuba-sbi', 'cvc', 2, 'SBI 系の地域ファンド。KT / CTB で接点。', NOW(), NULL),
  ('PBC', 'PBC', 'pbc', 'independent', 1, 'KT で接点。詳細不明 stub。', NOW(), NULL),
  ('三菱UFJ信託銀行', 'Mitsubishi UFJ Trust Bank (MUTB)', 'mutb', 'corporate', 2, '信託銀行。UntroD と提携 Real Tech Debt Fund 運営。KT で接点。', NOW(), NULL),
  ('GHO Ventures', 'GHO Ventures (GHOV)', 'ghov', 'independent', 1, 'KT で接点 stub。', NOW(), NULL),
  ('Hataraku Capital', 'Hataraku Capital', 'hataraku-capital', 'independent', 1, 'KT で接点 stub。', NOW(), NULL),
  ('ENEOS', 'ENEOS Holdings', 'eneos', 'corporate', 1, '事業会社 (CVC は別エントリ EEI)。', NOW(), NULL),
  ('Bandai Namco 021 Fund (021)', 'Bandai Namco Entertainment 021 Fund', 'bn-021-fund', 'cvc', 1, 'r3kt で info 接点。', NOW(), NULL),
  ('くふうカンパニー', 'Kufu Company', 'kufu-company', 'corporate', 1, 'r3kt で info 接点。', NOW(), NULL),
  ('ベクトルグループ', 'Vector Group', 'vector-group', 'corporate', 1, 'r3kt で info 接点。', NOW(), NULL),
  ('山口キャピタル', 'Yamaguchi Capital', 'yamaguchi-capital', 'cvc', 1, 'r3kt で接点。', NOW(), NULL),
  ('DIMENSION', 'DIMENSION', 'dimension', 'independent', 2, 'r3kt / MC で接点。', NOW(), NULL),
  ('JST SUCCESS', 'JST SUCCESS', 'jst-success', 'government', 3, 'CTB で NDA 押印郵送済 (★4 follow)。', NOW(), NULL),
  ('Catalys Pacific', 'Catalys Pacific', 'catalys-pacific', 'overseas', 3, 'CTB で武田さん経由、英語資料送付済 (★3)。', NOW(), NULL),
  ('CEJ', 'CEJ', 'cej', 'independent', 3, 'CTB で lead capable (★3)。詳細不明 stub。', NOW(), NULL),
  ('FTI', 'FTI', 'fti', 'independent', 3, 'CTB で再面談予定 (★3)。', NOW(), NULL),
  ('NTAVP', 'NTA Venture Partners (NTAVP)', 'ntavp', 'independent', 1, 'CTB / LST 接点。', NOW(), NULL),
  ('IF (Investment Fund)', 'IF Investment Fund', 'if-investment', 'independent', 1, 'OPT / CTB / LST で接点 stub。', NOW(), NULL),
  ('ATAC', 'ATAC', 'atac', 'independent', 1, 'CTB / LST / r3kt で接点 lead capable。', NOW(), NULL),
  ('みずほキャピタル', 'Mizuho Capital', 'mizuho-capital', 'cvc', 1, 'CTB / MC / r3kt で接点。', NOW(), NULL),
  ('みやこキャピタル', 'Miyako Capital', 'miyako-capital', 'cvc', 1, 'CTB で接点。', NOW(), NULL),
  ('りそなキャピタル', 'Resona Capital', 'resona-capital', 'cvc', 1, 'CTB で follow A以降。', NOW(), NULL),
  ('南都キャピタル', 'Nanto Capital Partners', 'nanto-capital', 'cvc', 1, 'CTB で follow A以降。', NOW(), NULL),
  ('大鵬薬品', 'Taiho Pharmaceutical', 'taiho-pharmaceutical', 'corporate', 1, '事業会社。CTB で接点。', NOW(), NULL),
  ('常陽キャピタル', 'Joyo Capital Partners', 'joyo-capital', 'cvc', 1, 'CTB で follow A以降。', NOW(), NULL),
  ('肥銀キャピタル', 'Hi-Gin Capital', 'higin-capital', 'cvc', 1, 'CTB で follow A以降。', NOW(), NULL),
  ('ゼロイチキャピタル', '01Booster Capital', '01-capital', 'independent', 1, 'CTB で接点。', NOW(), NULL),
  ('QBパートナーズ', 'QB Partners', 'qb-partners', 'independent', 1, 'CTB で接点。', NOW(), NULL),
  ('TNP', 'Tohoku Innovation Capital (TNP)', 'tnp', 'university_affiliated', 2, 'CTB で接点 (東北 / 北日本系 stub)。', NOW(), NULL),
  ('WIZP', 'WIZ Partners', 'wizp', 'independent', 1, 'CTB で MTG 実施、出資は次回以降。', NOW(), NULL),
  ('新生キャピタルパートナーズ', 'Shinsei Capital Partners', 'shinsei-capital', 'cvc', 1, 'CTB で 2025 シリーズ A 検討候補。', NOW(), NULL),
  ('IP Bridge VP (IPVP)', 'IP Bridge Venture Partners', 'ipvp', 'independent', 1, 'CTB で将来出資希望、ヘルスケア。', NOW(), NULL),
  ('エムスリー', 'M3 Inc.', 'm3', 'corporate', 1, 'CTB で接点したが市場規模 / アーリー過ぎで無理判定。', NOW(), NULL),
  ('Daiichi Capital Investment Partners (DCIP)', 'DCIP', 'dcip', 'cvc', 1, 'CTB で lead capable (★)。', NOW(), NULL),
  ('DMC', 'DMC', 'dmc', 'independent', 1, 'CTB で 7/28 mtg 検討開始。', NOW(), NULL),
  ('Remeges Ventures', 'Remeges Ventures', 'remeges-ventures', 'overseas', 2, 'CTB で接点。海外。', NOW(), NULL),
  ('東京センチュリー', 'Tokyo Century Corp', 'tokyo-century', 'corporate', 1, 'リース系事業会社。LST で接点。', NOW(), NULL),
  ('ビジネスエージェント', 'Business Agent', 'business-agent', 'independent', 1, 'LST で接点 stub。', NOW(), NULL),
  ('MZ Web3 Fund (MZF)', 'MZ Web3 Fund', 'mzf', 'independent', 1, 'JC で接点。', NOW(), NULL),
  ('Future Innovation Capital (FIC)', 'Future Innovation Capital (FIC)', 'fic', 'independent', 1, 'JC / CTB で接点。', NOW(), NULL),
  ('Station Ai', 'Station Ai', 'station-ai', 'independent', 1, 'JC で接点。', NOW(), NULL),
  ('X-tech Ventures', 'X-tech Ventures', 'x-tech-ventures', 'independent', 1, 'JC で接点。', NOW(), NULL),
  ('アニマルスピリッツ', 'Animal Spirits', 'animal-spirits', 'independent', 1, 'JC で接点。', NOW(), NULL),
  ('GGG', 'Gen Z Group (GGG)', 'ggg', 'independent', 1, 'JC で接点 stub。', NOW(), NULL),
  ('ナショナルサーチファンド', 'National Search Fund', 'national-search-fund', 'independent', 1, 'JC で接点。', NOW(), NULL),
  ('愛知キャピタル', 'Aichi Capital', 'aichi-capital', 'cvc', 1, 'JC で接点。', NOW(), NULL),
  ('積水化学', 'Sekisui Chemical', 'sekisui-chemical', 'corporate', 1, '事業会社。JC で接点。', NOW(), NULL),
  ('セントラルシードファンド', 'Central Seed Fund', 'central-seed-fund', 'independent', 1, 'JC で接点。', NOW(), NULL),
  ('デライトベンチャーズ', 'Delight Ventures', 'delight-ventures', 'independent', 1, 'DeNA 系。JC で接点。', NOW(), NULL),
  ('JST 融資', 'JST Loan Program', 'jst-loan', 'government', 2, 'JST 融資制度。MC で接点。', NOW(), NULL),
  ('JX金属', 'JX Metals', 'jx-metals', 'corporate', 1, '事業会社。MC で接点 (元株主、JX に EXIT 済)。', NOW(), NULL),
  ('Henkel', 'Henkel Tech Ventures', 'henkel', 'corporate', 1, 'ドイツ系事業会社。MC で接点。', NOW(), NULL),
  ('JAIC', 'Japan Asia Investment Co. (JAIC)', 'jaic', 'independent', 1, 'MC で接点。アジア系。', NOW(), NULL),
  ('ROHM', 'ROHM Co. Ltd.', 'rohm', 'corporate', 1, '事業会社 (半導体)。MC で接点。', NOW(), NULL),
  ('signifiant', 'Signifiant', 'signifiant', 'overseas', 1, '海外 VC。MC で接点。', NOW(), NULL),
  ('endeavourU', 'endeavourU', 'endeavour-u', 'independent', 1, 'MC で接点 stub。', NOW(), NULL),
  ('Cool Japan Fund', 'Cool Japan Fund', 'cool-japan', 'government', 1, '官民ファンド (海外展開支援)。MC で接点。', NOW(), NULL),
  ('FUND BOARD', 'Fund Board', 'fund-board', 'independent', 1, 'MC で接点 stub。', NOW(), NULL),
  ('七十七キャピタル (77BC)', '77 Bank Capital (77BC)', '77bc', 'cvc', 1, '七十七銀行系。MC / KT で対象外扱い。', NOW(), NULL),
  ('伊藤忠VT', 'Itochu Technology Ventures', 'itochu-tv', 'cvc', 1, '伊藤忠系。MC で接点。', NOW(), NULL),
  ('フィデル・パートナーズ', 'Fidel Partners', 'fidel-partners', 'independent', 1, 'MC で接点 stub。', NOW(), NULL),
  ('Fast Track Initiative (FTI)', 'Fast Track Initiative', 'fast-track-initiative', 'independent', 1, '吉川さん (元 BNV) / 二見さん。CTB で接点。', NOW(), NULL),
  ('Medical Incubator Japan (MIJ)', 'Medical Incubator Japan (MIJ)', 'mij', 'independent', 3, '医療機器系。CTB で武田さん経由 (★3)。', NOW(), NULL),
  ('AN Venture Partners (ANVP)', 'AN Venture Partners', 'anvp', 'independent', 3, '千代田化工系で接点。CTB ヘルスケア。', NOW(), NULL),
  ('STA1', 'A-START', 'a-start-extra', 'independent', 1, 'A-START / r3kt で接点。', NOW(), NULL),
  ('Hakobune', 'Hakobune', 'hakobune-extra', 'independent', 2, 'r3kt 接点。', NOW(), NULL)
ON CONFLICT (name) DO NOTHING;
