-- 393: SX コスト試算を 260913 二段階版へ組み替える（2026-09-13 まさ確定）
--
-- 先に 392 を適用すること。260820版（ちこ作成）の明細を土台に、次を行う。
--   - 中央培養の明細を 円/m³ → 円/kg-DCW・年額固定へ換算し、年間生産能力の前提を足す
--   - 色素分解と金属回収で前提・明細を分ける。金属の取り込み効率を株ごとに置き直す
--   - 人件費を総コストへ入れる。巡回サービス・閉鎖系の追加費用（強化株のみ）・色素用の後処理・色素の濃さを足す
-- 生成: えいみ 2026-09-13（SXセッション）。DB から取り出した現行データを変換して書き出した。
begin;
update project_cost_models set case_kind = 'multi', case_label = '色素分解・金属回収', version_label = '260913 二段階版', summary_md = 'SXの排液処理を、**菌体の製造原価**と**用途別の処理原価**の二段階で試算する。

**第1段 菌体の製造原価** — 株（強化株／自然株）ごとに、中央培養拠点で乾燥菌体1kgをつくる原価を出す。同じ株なら用途では変わらない。強化株は閉鎖系の追加費用が乗る。

**第2段 用途別の処理原価** — 第1段の原価を一定として、色素分解と金属回収のそれぞれで排水1m³あたりの総コストを出す。用途で変わるのは、必要な菌体の量（対象物質の濃度 ÷ 取り込み効率 ÷ 菌体使用回数）と、使用済み菌体の後処理。

画面上部のスイッチで株を切り替える。切り替えは保存しない（見るだけ）。

ちこ作成の260820版の明細を土台に、2026-09-13に二段階へ組み替えた。人件費・巡回サービス・閉鎖系の追加費用・色素用の後処理・色素の濃さを追加し、いずれも確度つきで置いている。', system_scope_md = '**対象** — 工場排液を、生きたシアノバクテリア（藍藻）で処理する。用途は色素分解と金属回収の2つを並べる。

**規模** — 顧客工場1拠点あたり 100 m³/日 × 300 日/年 ＝ 30,000 m³/年。1バッチ100 m³、反応時間（HRT）4時間のバッチ運転。

**第1段：菌体は中央培養拠点で作る** — 各現場では培養しない。乾燥菌体1kgあたりの原価は、「(培養設備の償却年額 ＋ 年ごとの固定費) ÷ 年間生産能力 ＋ 菌体量に比例する費用」で出す。年間生産能力いっぱいで割るので、稼働が低いと実際の1kgあたり原価は上がる。

**第2段：方式は2つを並べて比較する**
- **A：循環カートリッジ方式** — 菌体をカートリッジ内の保持モジュールに留め、排液を循環させて接触させる。モジュールは耐用バッチ数ごとに交換する。
- **B：直接投入方式** — 菌体を槽へ直接投入して撹拌し、反応後に UF/MF 膜で菌体を分離回収する。膜は約3年で交換する。

**槽は既設／新設の2通り** — 顧客の既存調整タンクを流用できれば0円。新設ならコンクリート地下タンク100 m³で1,800万円（10年償却）。方式×槽で、用途ごとに4シナリオになる。

**設備は独立プラント新設ではなく増分アドオン** — 顧客の既存調整タンク・排水ライン・ユーティリティ・主処理設備を使い、密閉接触・循環、菌体捕捉、回収サービスを足す（2026-07-23 確定）。

**収益モデル** — 処理費のみ。売価500円/m³。回収物（金属など）の売却収入はまだモデルに入れていない。

**人件費と巡回サービス** — 総コストに入れる（2026-09-13 まさ指示）。人件費は中島先生の試算にある手動運用の作業時間で置き、人件費を除いた値も併記する。菌体の搬入・搬出と、モジュール・膜の交換作業は巡回サービスとして別に積む。', source_note = '原典: Google Sheets SX_コスト試算_260820 (ちこ)。中島先生の設備・運用想定を反映した版。 2026-09-13 に二段階版へ組み替え（migration 393）。', updated_at = now() where cost_model_id = 'cm_p21_260820';
update project_cost_assumptions set code = null, group_label = '人件費', label = '1バッチあたり作業時間（A:循環）', value = 5.75, value_text = null, unit = 'h', confidence = 'A', source_kind = '先生回答', owner = '中島先生', is_key = true, role_key = 'batch_hours_circulation', note = '出所：中島試算シート100m³ケース①循環。手動運用のときの時間。二段階版ではこの時間で人件費を総コストへ入れる。無人運転で何時間まで減るかは未確認（ダイキアクシスへ確認中）。', visibility = 'amd_internal', sort_order = 160, strain = null, application = null, updated_at = now() where cost_assumption_id = 'ca_batch_hours_circulation';
update project_cost_assumptions set code = null, group_label = '人件費', label = '1バッチあたり作業時間（B:投入）', value = 7.5, value_text = null, unit = 'h', confidence = 'A', source_kind = '先生回答', owner = '中島先生', is_key = true, role_key = 'batch_hours_injection', note = '出所：中島試算シート100m³ケース②投入。手動運用のときの時間。二段階版ではこの時間で人件費を総コストへ入れる。無人運転で何時間まで減るかは未確認（ダイキアクシスへ確認中）。', visibility = 'amd_internal', sort_order = 200, strain = null, application = null, updated_at = now() where cost_assumption_id = 'ca_batch_hours_injection';
update project_cost_assumptions set code = null, group_label = '共通前提', label = '人件費単価', value = 4000, value_text = null, unit = '円/h', confidence = 'B', source_kind = '仮置き', owner = 'AMD', is_key = false, role_key = 'labor_rate', note = '現場の運転人件費と、巡回サービス（搬入・搬出・交換作業）の両方に使う。', visibility = 'amd_internal', sort_order = 50, strain = null, application = null, updated_at = now() where cost_assumption_id = 'ca_labor_rate';
update project_cost_assumptions set code = null, group_label = '対象物質', label = '菌体使用回数（色素分解）', value = 1, value_text = null, unit = '回', confidence = 'H', source_kind = '要検証', owner = '杉浦先生', is_key = true, role_key = 'reuse_count', note = '★最大の感度。1＝再利用せず毎回新品。技術的事実ではない保守的仮定。まさの記憶では色素分解なら数十回使い回せる可能性があるが未確認（2026-08-23時点でうろ覚えと明言）。二段階版では菌体原価を1kgあたりで持つので、使用回数を上げると菌体費がそのまま回数分下がる。杉浦先生へ確認中。', visibility = 'amd_internal', sort_order = 130, strain = null, application = 'dye', updated_at = now() where cost_assumption_id = 'ca_reuse_count';
update project_cost_assumptions set code = null, group_label = '中央培養', label = '（旧版）供給先数（中央培養の按分先）', value = 1, value_text = null, unit = '拠点', confidence = 'C', source_kind = '仮置き', owner = 'AMD', is_key = false, role_key = null, note = '二段階版では使わない。菌体の製造原価を「年間生産能力」で割って1kgあたりにしたため、供給先数で割る必要がなくなった。旧版との対応のために残している。', visibility = 'amd_internal', sort_order = 140, strain = null, application = null, updated_at = now() where cost_assumption_id = 'ca_supply_sites';
update project_cost_assumptions set code = null, group_label = '対象物質', label = '対象物質の濃度（金属）', value = 50, value_text = null, unit = 'ppm', confidence = 'A', source_kind = '仮置き', owner = '杉浦先生', is_key = true, role_key = 'target_concentration', note = '★V-401。金属回収ケースの対象金属濃度。260820版から据え置き。色素分解ケースは別行で持つ。', visibility = 'amd_internal', sort_order = 80, strain = null, application = 'metal', updated_at = now() where cost_assumption_id = 'ca_target_concentration';
update project_cost_assumptions set code = null, group_label = '対象物質', label = '取り込み効率α（金属・自然株）', value = 0.042, value_text = null, unit = 'g/g菌体', confidence = 'H', source_kind = '推定', owner = '杉浦先生', is_key = true, role_key = 'uptake_alpha', note = '★V-402。9/2定例の単回試験で、同じ菌体濃度（OD5）の野生型は50ppm中40ppmを取り込み、強化株1は50ppmを全量取り込んで鉄量が乾燥菌体重量比5.3%だった。菌体量が同じと仮定し 5.3% × 40/50 ≒ 4.2% と置いた。260820版の0.05は出所が確認できないため置き換えた。', visibility = 'amd_internal', sort_order = 90, strain = 'wild', application = 'metal', updated_at = now() where cost_assumption_id = 'ca_uptake_alpha';
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('ca2_culture_capacity', 'cm_p21_260820', null, '第1段 菌体の製造原価', '中央培養拠点の年間生産能力', 33333, null, 'kg-DCW/年', 'H', '推定', '杉浦先生', true, 'culture_capacity_kg_year', '旧版は「必要な菌体量＝生産量」と暗黙に置いていた（1拠点・使い捨て・50ppm・α0.05で33,333kg/年）。その値を引き継いだ仮置き。培養液1Lあたりの1日の増殖量と培養容積の実測が入るまで確定しない。生産能力いっぱいで割るので、実際の稼働が低いと1kgあたり原価は上がる。', 'amd_internal', 300, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('ca2_biomass_override', 'cm_p21_260820', null, '第1段 菌体の製造原価', '菌体の製造原価（上書き）', null, null, '円/kg-DCW', 'H', '仮置き', null, true, 'biomass_cost_per_kg_override', '空欄なら第1段の明細から計算する。値を入れるとその原価で第2段を計算する。閉鎖型の商用相場（約390〜770円/kg）を入れると、菌体原価が相場並みのときの成否が見られる。', 'amd_internal', 310, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('ca2_target_concentration_dye', 'cm_p21_260820', null, '対象物質', '対象物質の濃度（色素）', 50, null, 'mg/L', 'H', '仮置き', 'AMD（内部）', true, 'target_concentration', '染色排水の色素濃度は文献上 10〜250 mg/L（多くは10〜50）。その中央の50で置いた。SXが実際に狙う排液の色の濃さは未測定。食品系排液の色は単一の色素濃度ではなく色度で測るため、そのまま当てはめられない。', 'amd_internal', 85, null, 'dye');
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('ca2_uptake_alpha_dye', 'cm_p21_260820', null, '対象物質', '取り込み効率α（色素）', 0.05, null, 'g/g菌体', 'H', '仮置き', '杉浦先生', true, 'uptake_alpha', '色素1gを処理するのに菌体が何g要るかの逆数。SXでは未測定。金属と同じ0.05で仮置きした。シアノ系菌体の色素吸着量は、理想条件での上限で約0.28 g/gという報告がある。分解で消える場合は「菌体1gが寿命までに処理できる量」として読む。菌体使用回数と掛け合わせて効く。', 'amd_internal', 95, null, 'dye');
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('ca2_uptake_alpha_metal_enhanced', 'cm_p21_260820', null, '対象物質', '取り込み効率α（金属・強化株）', 0.053, null, 'g/g菌体', 'H', '実測', '杉浦先生', true, 'uptake_alpha', '9/2定例の単回試験で、強化株1（OD5）が鉄模擬排液50ppmを24時間で全量取り込み、鉄量が乾燥菌体重量比5.3%。上限に届いていないので、実際の取り込み効率はこれ以上。反復試験と上限探索が技術検証に登録済み。', 'amd_internal', 92, 'enhanced', 'metal');
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('ca2_reuse_count_metal', 'cm_p21_260820', null, '対象物質', '菌体使用回数（金属回収）', 1, null, '回', 'A', '推定', null, false, 'reuse_count', '現行の工程は酸で菌体ごと溶かして金属を回収するため1回で使い切る。酸で金属だけを外して菌体を再利用できることが実証されたら変える。', 'amd_internal', 135, null, 'metal');
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('ca2_patrol_travel_hours', 'cm_p21_260820', null, '巡回サービス', '1回あたりの移動時間（往復）', 2.0, null, 'h', 'H', '仮置き', 'ダイキアクシス', false, 'patrol_travel_hours', '中央培養拠点から顧客工場までの往復。拠点の立地が決まるまで仮置き。', 'amd_internal', 400, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('ca2_patrol_work_hours', 'cm_p21_260820', null, '巡回サービス', '1回あたりの搬入・搬出作業', 1.0, null, 'h', 'H', '仮置き', 'ダイキアクシス', false, 'patrol_work_hours', '菌体の搬入と使用済み菌体の搬出を同じ訪問でまとめる前提。', 'amd_internal', 410, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('ca2_patrol_vehicle_cost', 'cm_p21_260820', null, '巡回サービス', '1回あたりの車両費', 5000, null, '円/回', 'H', '仮置き', 'ダイキアクシス', false, 'patrol_vehicle_cost', '燃料・車両償却・高速代の目安。', 'amd_internal', 420, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('ca2_patrol_batches_per_delivery', 'cm_p21_260820', null, '巡回サービス', '1回の搬入でまかなうバッチ数', 5, null, '回', 'H', '仮置き', 'ダイキアクシス', false, 'patrol_batches_per_delivery', '菌体を現場で何日保管できるかが分かるまで、週1回（5バッチ分）で置く。菌体使用回数がこれより多いときは、使用回数ごとに1回訪問する。', 'amd_internal', 430, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('ca2_patrol_module_work_hours', 'cm_p21_260820', null, '巡回サービス', 'モジュール交換1回の作業時間（A:循環）', 4.0, null, 'h', 'H', '仮置き', 'ダイキアクシス', false, 'patrol_module_work_hours', '移動は搬入の訪問に合わせる前提で、作業時間だけを積む。', 'amd_internal', 440, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('ca2_patrol_membrane_work_hours', 'cm_p21_260820', null, '巡回サービス', '膜交換1回の作業時間（B:投入）', 8.0, null, 'h', 'H', '仮置き', 'ダイキアクシス', false, 'patrol_membrane_work_hours', '移動は搬入の訪問に合わせる前提で、作業時間だけを積む。', 'amd_internal', 450, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('ca2_spent_wet_factor', 'cm_p21_260820', null, '使用済み菌体の処分', '脱水後の湿重量倍率', 5.0, null, 'kg湿/kg-DCW', 'H', '推定', 'ダイキアクシス', false, 'spent_wet_factor', '含水率80%の脱水汚泥として出す想定（乾燥菌体1kg → 湿重量5kg）。脱水の程度で大きく変わる。', 'amd_internal', 500, null, 'dye');
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('ca2_sludge_disposal_price', 'cm_p21_260820', null, '使用済み菌体の処分', '汚泥の処分単価（収集運搬込み）', 35, null, '円/kg湿', 'B', '資料記載', 'ダイキアクシス', false, 'sludge_disposal_price', '産業廃棄物（汚泥）の処理料金相場 25〜50円/kg の中央。色素を含む菌体の廃棄物区分は未確認。', 'amd_internal', 510, null, 'dye');
update project_cost_items set scenario = '循環', cost_type = 'CAPEX', group_label = '反応・回収設備', mid_label = '分析装置（ポータブル吸光光度計等。金属・色の両方で使う）', leaf_label = '計装', basis = '初期投資配賦', quantity = 1, quantity_unit = '式', unit_price = 1400000, unit_price_unit = '円/式', price_rule = null, annual_factor = 1, useful_life_years = 10, is_breakdown = false, confidence = 'C', source_kind = '先生回答', owner = '中島先生', note = null, visibility = 'amd_internal', sort_order = 350, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_077';
update project_cost_items set scenario = '投入', cost_type = 'CAPEX', group_label = '反応・分離設備', mid_label = '分析装置（吸光光度計等。金属・色の両方で使う）', leaf_label = '計装', basis = '初期投資配賦', quantity = 1, quantity_unit = '式', unit_price = 1400000, unit_price_unit = '円/式', price_rule = null, annual_factor = 1, useful_life_years = 10, is_breakdown = false, confidence = 'C', source_kind = '先生回答', owner = '中島先生', note = '◎', visibility = 'amd_internal', sort_order = 650, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_107';
update project_cost_items set scenario = '中央培養', cost_type = 'OPEX', group_label = '培養', mid_label = '原料', leaf_label = '培地主原料', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 9.0, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '中央培養拠点で発生する菌体製造費。現場設備OPEXとは分離し「中央培養」タグへ。菌体製造原価として事業全体で別途配賦する。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 780, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_120';
update project_cost_items set scenario = '中央培養', cost_type = 'OPEX', group_label = '培養', mid_label = '原料', leaf_label = '栄養塩', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 10.8, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 790, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_121';
update project_cost_items set scenario = '中央培養', cost_type = 'OPEX', group_label = '培養', mid_label = '原料', leaf_label = '微量元素・添加剤', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 7.2, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 800, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_122';
update project_cost_items set scenario = '中央培養', cost_type = 'OPEX', group_label = '培養', mid_label = 'ユーティリティ', leaf_label = 'CO2', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 4.5, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 810, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_123';
update project_cost_items set scenario = '中央培養', cost_type = 'OPEX', group_label = '培養', mid_label = 'ユーティリティ', leaf_label = '補給水', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 1.8, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 820, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_124';
update project_cost_items set scenario = '中央培養', cost_type = 'OPEX', group_label = '培養', mid_label = '洗浄', leaf_label = '洗浄水', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 2.7, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 830, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_125';
update project_cost_items set scenario = '中央培養', cost_type = 'OPEX', group_label = '培養', mid_label = '洗浄', leaf_label = '洗浄薬剤', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 4.5, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 840, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_126';
update project_cost_items set scenario = '中央培養', cost_type = 'OPEX', group_label = '培養', mid_label = '濃縮・回収', leaf_label = '濃縮用フィルタ', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 9.0, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'B', source_kind = '仮置き', owner = 'AMD', note = '二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 850, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_127';
update project_cost_items set scenario = '中央培養', cost_type = 'OPEX', group_label = '培養', mid_label = '濃縮・回収', leaf_label = '濃縮補助材', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 5.4, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 860, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_128';
update project_cost_items set scenario = '中央培養', cost_type = 'OPEX', group_label = '培養', mid_label = '品質確認', leaf_label = 'サンプリング分析', basis = '年額固定', quantity = 1, quantity_unit = '年', unit_price = 120000.0, unit_price_unit = '円/年', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '二段階版で年額固定に換算した（旧版の4円/m³ × 30,000m³）。検査の回数は菌体量ではなくバッチに付くため。', visibility = 'amd_internal', sort_order = 870, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_129';
update project_cost_items set scenario = '中央培養', cost_type = 'OPEX', group_label = '培養', mid_label = '品質確認', leaf_label = '品質確認試験', basis = '年額固定', quantity = 1, quantity_unit = '年', unit_price = 120000.0, unit_price_unit = '円/年', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '二段階版で年額固定に換算した（旧版の4円/m³ × 30,000m³）。検査の回数は菌体量ではなくバッチに付くため。', visibility = 'amd_internal', sort_order = 880, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_130';
update project_cost_items set scenario = '共通', cost_type = 'OPEX', group_label = '培養', mid_label = '保管・物流', leaf_label = '保管容器', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 2.7, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '中央培養拠点から現場への菌体輸送・保管にかかる費用のため、現場側コストとして残す（培養そのものの費用ではなく、拠点ごとに発生する物流費）。金額は仮置きで、中央拠点⇔現場の距離・頻度が決まり次第見直す。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 890, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_131';
update project_cost_items set scenario = '共通', cost_type = 'OPEX', group_label = '培養', mid_label = '保管・物流', leaf_label = '搬送容器・梱包', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 2.7, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 900, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_132';
update project_cost_items set scenario = '共通', cost_type = 'OPEX', group_label = '培養', mid_label = '保管・物流', leaf_label = '搬送費', basis = '毎m³比例', quantity = 1, quantity_unit = 'm³', unit_price = 0, unit_price_unit = '円/m³', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '巡回サービス（菌体の搬入・搬出）へ統合した。二重計上を避けるため0円。', visibility = 'amd_internal', sort_order = 910, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_133';
update project_cost_items set scenario = '中央培養', cost_type = 'OPEX', group_label = '培養', mid_label = 'ロス補充', leaf_label = '培養ロス補充', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 5.4, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 920, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_134';
update project_cost_items set scenario = '共通', cost_type = 'OPEX', group_label = 'シアノ回収後処理', mid_label = '酸処理', leaf_label = '酸', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 18.0, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'B', source_kind = '仮置き', owner = 'AMD', note = '金属回収のみ（酸で菌体ごと溶かして金属を回収する工程）。二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 930, strain = null, application = 'metal', updated_at = now() where cost_item_id = 'ci_260820_135';
update project_cost_items set scenario = '共通', cost_type = 'OPEX', group_label = 'シアノ回収後処理', mid_label = '酸処理', leaf_label = '洗浄水', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 2.7, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '金属回収のみ（酸で菌体ごと溶かして金属を回収する工程）。二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 940, strain = null, application = 'metal', updated_at = now() where cost_item_id = 'ci_260820_136';
update project_cost_items set scenario = '共通', cost_type = 'OPEX', group_label = 'シアノ回収後処理', mid_label = '中和', leaf_label = '中和剤', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 9.0, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '金属回収のみ（酸で菌体ごと溶かして金属を回収する工程）。二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 950, strain = null, application = 'metal', updated_at = now() where cost_item_id = 'ci_260820_137';
update project_cost_items set scenario = '共通', cost_type = 'OPEX', group_label = 'シアノ回収後処理', mid_label = '残渣処理', leaf_label = '残渣処分', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 5.4, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '金属回収のみ（酸で菌体ごと溶かして金属を回収する工程）。二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 960, strain = null, application = 'metal', updated_at = now() where cost_item_id = 'ci_260820_138';
update project_cost_items set scenario = '共通', cost_type = 'OPEX', group_label = 'シアノ回収後処理', mid_label = '残渣処理', leaf_label = '廃液処理', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 3.6, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '金属回収のみ（酸で菌体ごと溶かして金属を回収する工程）。二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 970, strain = null, application = 'metal', updated_at = now() where cost_item_id = 'ci_260820_139';
update project_cost_items set scenario = '共通', cost_type = 'OPEX', group_label = 'シアノ回収後処理', mid_label = '品質確認', leaf_label = '回収物分析', basis = '毎m³比例', quantity = 1, quantity_unit = 'm³', unit_price = 4, unit_price_unit = '円/m³', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '金属回収のみ。', visibility = 'amd_internal', sort_order = 980, strain = null, application = 'metal', updated_at = now() where cost_item_id = 'ci_260820_140';
update project_cost_items set scenario = '共通', cost_type = 'OPEX', group_label = 'シアノ回収後処理', mid_label = '物流', leaf_label = '搬送費', basis = '毎m³比例', quantity = 1, quantity_unit = 'm³', unit_price = 0, unit_price_unit = '円/m³', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '金属回収のみ。巡回サービスへ統合した。二重計上を避けるため0円。', visibility = 'amd_internal', sort_order = 990, strain = null, application = 'metal', updated_at = now() where cost_item_id = 'ci_260820_141';
update project_cost_items set scenario = '循環', cost_type = 'OPEX', group_label = '反応・カートリッジ/全体共通', mid_label = '反応', leaf_label = '菌体ロス補充分', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 9.0, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'B', source_kind = '仮置き', owner = 'AMD', note = '物理的なロス分の補充。名称を「補充菌体」から明確化。現行は毎m³一定額の暫定計算で、菌体寿命の概念を持たない。菌体再利用可能バッチ数（上部注記参照）が確定したら式を組み直す。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 1000, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_142';
update project_cost_items set scenario = '循環', cost_type = 'OPEX', group_label = '反応・カートリッジ/全体共通', mid_label = '反応', leaf_label = '菌体性能低下による交換・再生分', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 4.5, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '菌体の金属吸収能力が落ちた分の交換・再生費用。名称を「性能低下見合い追加投入」から明確化。現行式は性能低下率を単純に追加投入する暫定計算。菌体の再生可否・再利用回数・再生コストが未確定のため、この式は暫定扱い。確定後に組み直す。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 1010, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_143';
update project_cost_items set scenario = '循環', cost_type = 'OPEX', group_label = '人件費', mid_label = '現場の運転', leaf_label = '1バッチあたり作業時間 × 人件費単価 × 年間バッチ数', basis = 'バッチ連動', quantity = 1, quantity_unit = 'h/バッチ', unit_price = 0, unit_price_unit = '円/年', price_rule = 'labor_batch', annual_factor = 300, useful_life_years = null, is_breakdown = false, confidence = 'A', source_kind = '先生回答', owner = 'ダイキアクシス', note = '二段階版で総コストへ入れた（2026-09-13 まさ指示）。作業時間は前提「1バッチあたり作業時間（A:循環）」を読む。中島試算の手動運用値で、無人運転で何時間まで減るかは未確認。画面では人件費を除いた値も併記する。', visibility = 'amd_internal', sort_order = 1170, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_159';
update project_cost_items set scenario = '投入', cost_type = 'OPEX', group_label = 'リアクター/分離回収/全体共通', mid_label = '反応', leaf_label = '菌体ロス補充分', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 9.0, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'B', source_kind = '仮置き', owner = 'AMD', note = '物理的なロス分の補充。名称を「補充菌体」から明確化。現行は毎m³一定額の暫定計算で、菌体寿命の概念を持たない。菌体再利用可能バッチ数（上部注記参照）が確定したら式を組み直す。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 1180, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_160';
update project_cost_items set scenario = '投入', cost_type = 'OPEX', group_label = 'リアクター/分離回収/全体共通', mid_label = '反応', leaf_label = '菌体性能低下による交換・再生分', basis = '毎kg菌体比例', quantity = 1, quantity_unit = 'kg-DCW', unit_price = 4.5, unit_price_unit = '円/kg-DCW', price_rule = null, annual_factor = 1, useful_life_years = null, is_breakdown = false, confidence = 'C', source_kind = '仮置き', owner = 'AMD', note = '菌体の金属吸収能力が落ちた分の交換・再生費用。名称を「性能低下見合い追加投入」から明確化。現行式は性能低下率を単純に追加投入する暫定計算。菌体の再生可否・再利用回数・再生コストが未確定のため、この式は暫定扱い。確定後に組み直す。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', visibility = 'amd_internal', sort_order = 1190, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_161';
update project_cost_items set scenario = '投入', cost_type = 'OPEX', group_label = '人件費', mid_label = '現場の運転', leaf_label = '1バッチあたり作業時間 × 人件費単価 × 年間バッチ数', basis = 'バッチ連動', quantity = 1, quantity_unit = 'h/バッチ', unit_price = 0, unit_price_unit = '円/年', price_rule = 'labor_batch', annual_factor = 300, useful_life_years = null, is_breakdown = false, confidence = 'A', source_kind = '先生回答', owner = 'ダイキアクシス', note = '二段階版で総コストへ入れた（2026-09-13 まさ指示）。作業時間は前提「1バッチあたり作業時間（B:投入）」を読む。中島試算の手動運用値で、無人運転で何時間まで減るかは未確認。画面では人件費を除いた値も併記する。', visibility = 'amd_internal', sort_order = 1370, strain = null, application = null, updated_at = now() where cost_item_id = 'ci_260820_179';
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_c_exhaust_filter', 'cm_p21_260820', '中央培養', 'CAPEX', '閉鎖系の追加（強化株のみ）', '排気の除菌フィルター設備', '培養槽の排気口', '初期投資配賦', 1, null, 500000, '円/式', null, 1, 7, false, 'H', '仮置き', '中島先生', '培養設備からの排気を、菌を捕まえられるフィルターを通して出す。カテゴリー1相当で積んだ。GILSPと判定されれば不要になる可能性がある。', 'amd_internal', 1000, 'enhanced', null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_c_waste_inactivation', 'cm_p21_260820', '中央培養', 'CAPEX', '閉鎖系の追加（強化株のみ）', '培養廃液の不活化設備', 'オートクレーブまたは薬剤不活化槽', '初期投資配賦', 1, null, 1500000, '円/式', null, 1, 7, false, 'H', '仮置き', '中島先生', '廃液・廃棄物を不活化する設備。', 'amd_internal', 1010, 'enhanced', null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_c_work_area', 'cm_p21_260820', '中央培養', 'CAPEX', '閉鎖系の追加（強化株のみ）', '作業区域の区画・表示・区別保管', '区画・掲示・専用保管庫', '初期投資配賦', 1, null, 300000, '円/式', null, 1, 7, false, 'H', '仮置き', '中島先生', '他の区域と明確に区別できる作業区域、表示、組換え微生物を区別して保管する設備。', 'amd_internal', 1020, 'enhanced', null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_c_filter_replace', 'cm_p21_260820', '中央培養', 'OPEX', '閉鎖系の追加（強化株のみ）', '除菌フィルターの交換', '年4回程度', '年額固定', 1, null, 120000, '円/年', null, 1, null, false, 'H', '仮置き', '中島先生', '交換時に付着した菌を不活化する作業を含む。カテゴリー1相当で積んだ。GILSPと判定されれば不要になる可能性がある。', 'amd_internal', 1030, 'enhanced', null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_c_integrity_test', 'cm_p21_260820', '中央培養', 'OPEX', '閉鎖系の追加（強化株のみ）', '培養設備の密閉性能検査', '設置時・定期・漏れ止め部品の交換時', '年額固定', 1, null, 200000, '円/年', null, 1, null, false, 'H', '仮置き', '中島先生', '設置時と定期に、漏出防止に関わる部品を交換したときはその都度検査する。カテゴリー1相当で積んだ。GILSPと判定されれば不要になる可能性がある。', 'amd_internal', 1040, 'enhanced', null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_c_safety_committee', 'cm_p21_260820', '中央培養', 'OPEX', '閉鎖系の追加（強化株のみ）', '安全委員会の運営・教育訓練・記録保存', '年60時間 × 4,000円', '年額固定', 1, null, 240000, '円/年', null, 1, null, false, 'H', '仮置き', '中島先生', '使用区分の判断の審議記録は、使用終了後20年保存する。', 'amd_internal', 1050, 'enhanced', null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_c_waste_chem', 'cm_p21_260820', '中央培養', 'OPEX', '閉鎖系の追加（強化株のみ）', '培養廃液の不活化（薬剤）', '菌体1kgあたりの培養液 約200L分', '毎kg菌体比例', 1, null, 2.0, '円/kg-DCW', null, 1, null, false, 'H', '仮置き', '中島先生', '運転時菌体濃度5g/Lで菌体1kg＝培養液200L。有効塩素30mg/L相当の薬剤で置いた。', 'amd_internal', 1060, 'enhanced', null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_s_treated_water', 'cm_p21_260820', '共通', 'OPEX', '閉鎖系の追加（強化株のみ）', '処理水の不活化（薬剤）', '次亜塩素酸・有効塩素30mg/L相当', '毎m³比例', 1, null, 10, '円/m³', null, 1, null, false, 'H', '仮置き', 'ダイキアクシス', '放流前に処理水を不活化する。GILSPなら「含まれる菌の数を最小限にとどめる措置」で足りる可能性がある。色素排水は色が光を吸うため紫外線が使えない。実排水は有機物で塩素の必要量が数倍になる。', 'amd_internal', 1100, 'enhanced', null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_s_exhaust_filter', 'cm_p21_260820', '共通', 'CAPEX', '閉鎖系の追加（強化株のみ）', '排気の除菌フィルター（現場の密閉槽）', '密閉接触槽の排気口', '初期投資配賦', 1, null, 300000, '円/式', null, 1, 10, false, 'H', '仮置き', 'ダイキアクシス', 'カテゴリー1相当で積んだ。GILSPと判定されれば不要になる可能性がある。', 'amd_internal', 1110, 'enhanced', null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_s_work_area', 'cm_p21_260820', '共通', 'CAPEX', '閉鎖系の追加（強化株のみ）', '作業区域の区画・表示', '顧客工場内の区画と掲示', '初期投資配賦', 1, null, 100000, '円/式', null, 1, 10, false, 'H', '仮置き', 'ダイキアクシス', '顧客工場の一角を作業区域として区別し、表示する。', 'amd_internal', 1120, 'enhanced', null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_s_integrity_test', 'cm_p21_260820', '共通', 'OPEX', '閉鎖系の追加（強化株のみ）', '現場設備の密閉性能検査', '設置時・定期・漏れ止め部品の交換時', '年額固定', 1, null, 150000, '円/年', null, 1, null, false, 'H', '仮置き', 'ダイキアクシス', 'カテゴリー1相当で積んだ。GILSPと判定されれば不要になる可能性がある。', 'amd_internal', 1130, 'enhanced', null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_s_filter_replace', 'cm_p21_260820', '共通', 'OPEX', '閉鎖系の追加（強化株のみ）', '除菌フィルターの交換（現場）', '年2回程度', '年額固定', 1, null, 60000, '円/年', null, 1, null, false, 'H', '仮置き', 'ダイキアクシス', 'カテゴリー1相当で積んだ。GILSPと判定されれば不要になる可能性がある。', 'amd_internal', 1140, 'enhanced', null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_s_training', 'cm_p21_260820', '共通', 'OPEX', '閉鎖系の追加（強化株のみ）', '立入制限・教育訓練', '年10時間 × 4,000円', '年額固定', 1, null, 40000, '円/年', null, 1, null, false, 'H', '仮置き', 'ダイキアクシス', '教育訓練を受けた人以外の立入りを制限する。', 'amd_internal', 1150, 'enhanced', null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_patrol_delivery', 'cm_p21_260820', '共通', 'OPEX', '巡回サービス', '菌体の搬入・使用済み菌体の搬出', '訪問回数 ×（移動と作業の時間 × 人件費単価 ＋ 車両費）', 'バッチ連動', 1, null, 0, '円/年', 'patrol', 1, null, false, 'H', '仮置き', 'ダイキアクシス', '訪問回数 = 年間バッチ数 ÷ 大きい方（菌体使用回数, 1回の搬入でまかなうバッチ数）。無人運転でも菌体の搬入・搬出は誰かがやるため、SX側の巡回サービス原価として積む。', 'amd_internal', 1200, null, null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_patrol_module', 'cm_p21_260820', '循環', 'OPEX', '巡回サービス', '菌体保持モジュールの交換作業', '交換回数 × 作業時間 × 人件費単価', 'バッチ連動', 1, null, 0, '円/年', 'patrol_module', 1, null, false, 'H', '仮置き', 'ダイキアクシス', '交換回数 = 年間バッチ数 ÷ モジュール耐用バッチ数。部品代は「菌体保持モジュール交換費」に別計上。', 'amd_internal', 1210, null, null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_patrol_membrane', 'cm_p21_260820', '投入', 'OPEX', '巡回サービス', '膜モジュールの交換作業', '交換回数 × 作業時間 × 人件費単価', 'バッチ連動', 1, null, 0, '円/年', 'patrol_membrane', 1, null, false, 'H', '仮置き', 'ダイキアクシス', '交換回数 = 1 ÷ 膜交換年数。膜の部品代は「UF/MF膜モジュール（交換品）」に別計上。', 'amd_internal', 1220, null, null);
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_dye_disposal', 'cm_p21_260820', '共通', 'OPEX', '使用済み菌体の処分', '使用済み菌体の処分', '脱水汚泥として産業廃棄物処分', '毎kg菌体比例', 1, null, 0, '円/kg-DCW', 'spent_disposal', 1, null, false, 'H', '推定', 'ダイキアクシス', '色素分解では酸で溶かさないため、菌体をそのまま汚泥として処分する想定。単価 = 脱水後の湿重量倍率 × 汚泥の処分単価。菌体使用回数が増えるほど処分量は減る。', 'amd_internal', 1300, null, 'dye');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_dye_analysis', 'cm_p21_260820', '共通', 'OPEX', '処理水の分析', '処理水の色・COD分析', '色度・吸光度・COD', '毎m³比例', 1, null, 4, '円/m³', null, 1, null, false, 'H', '仮置き', 'AMD（内部）', '金属回収の「回収物分析」と同水準で仮置き。', 'amd_internal', 1310, null, 'dye');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application) values ('ci2_dye_wash', 'cm_p21_260820', '共通', 'OPEX', '使用済み菌体の処分', '再利用前の洗浄（色素を外す工程）', '工程未確定', '毎m³比例', 1, null, 0, '円/m³', null, 1, null, false, 'H', '要検証', '中島先生', '菌体を繰り返し使うなら、色素を外す／洗い戻す工程が要る可能性がある。工程が決まっていないため0円で置き、中島先生へ確認中（酸処理が要るかの確認事項と同じ）。', 'amd_internal', 1320, null, 'dye');
update project_cost_questions set addressee = 'ダイキアクシス', question = '自動制御で無人運転する前提に置いていますが、実務上どこに人が必要になりますか。菌体の搬入、使用済み菌体の搬出、モジュール／膜の交換は、年何回・誰が・何時間で回る想定になりますか。', why_it_matters = '現行モデルは人件費を総コストへ算入していない（参考値でA:230円/m³、B:300円/m³）。B:投入／既設は総コスト349.7円/m³で+30%だが、人件費を戻すと-150円/m³で赤字に反転する。顧客側が0人になるならその作業はSXの巡回サービス原価へ移るはずで、現行モデルには1円も入っていない。 二段階版では人件費を手動運用の作業時間で総コストへ入れている（人件費を除いた値も併記）。無人運転の作業時間が分かれば置き換える。', impact_low = 0, impact_high = 300, status = 'open', answer = null, answered_on = null, linked_assumption_id = null, visibility = 'amd_internal', sort_order = 60, updated_at = now() where cost_question_id = 'cq_260820_06';
update project_cost_questions set addressee = 'AMD（内部）', question = '対象物質の濃度と取り込み効率を、色素の単位へ差し替える。現在は金属濃度50ppm ÷ 取り込み効率α 0.05 g金属/g菌体 で必要菌体量が回っている。', why_it_matters = '260820スプレッドシートには「色素」「脱色」「染料」の語が1つも無く、必要菌体量が金属の式のまま。設備構成は両ケース共通なので明細は使えるが、菌体量の駆動部だけが金属のまま残っている。ケースを取り違えたまま議論すると全部の数字の信頼が落ちる。', impact_low = null, impact_high = null, status = 'answered', answer = '二段階版で、対象物質の濃度・取り込み効率・菌体使用回数を色素分解と金属回収の別行に分けた。色素の値は文献相場による仮置きで、実測待ち。', answered_on = '2026-09-13', linked_assumption_id = 'ca_uptake_alpha', visibility = 'amd_internal', sort_order = 90, updated_at = now() where cost_question_id = 'cq_260820_09';
update project_cost_questions set addressee = 'AMD（内部）', question = '菌体使用回数を上げたときに、中央培養CAPEX（34.4円/m³）と現場側物流（11円/m³）が固定のままでよいか整理する。', why_it_matters = '菌体量が1/30になれば培養設備は小さくてよく、運ぶ回数も減るはずだが、現行モデルでは両方とも菌体使用回数に連動していない。使用回数を上げた瞬間、この2つが中央培養コストのほぼ全部になる。', impact_low = 0, impact_high = 45, status = 'answered', answer = '二段階版で菌体の原価を1kgあたりに換算したので、菌体使用回数を上げると培養設備の償却分も含めて回数分下がるようになった。代わりに「中央培養拠点の年間生産能力」を仮置きしており、実測待ち。現場側物流の搬送費は巡回サービスへ統合した。', answered_on = '2026-09-13', linked_assumption_id = null, visibility = 'amd_internal', sort_order = 110, updated_at = now() where cost_question_id = 'cq_260820_11';
insert into project_cost_questions (cost_question_id, cost_model_id, addressee, question, why_it_matters, impact_low, impact_high, status, answer, answered_on, linked_assumption_id, visibility, sort_order) values ('cq2_01', 'cm_p21_260820', '中島先生', '強化株を使う場合の閉鎖系の追加設備はいくらくらいになりそうですか。①培養槽と現場槽の排気の除菌フィルター ②培養廃液の不活化設備（オートクレーブか薬剤槽か） ③密閉性能検査を業者に頼む費用と頻度 ④作業区域の区画と保管設備。', '強化株の閉鎖系費用は全て仮置き（カテゴリー1相当）。第1段の菌体原価と、現場の総コストの両方に乗る。GILSPと判定されれば一部が不要になる。', 0, 52, 'open', null, null, null, 'amd_internal', 170);
insert into project_cost_questions (cost_question_id, cost_model_id, addressee, question, why_it_matters, impact_low, impact_high, status, answer, answered_on, linked_assumption_id, visibility, sort_order) values ('cq2_02', 'cm_p21_260820', 'ダイキアクシス', '色素を処理した後の使用済み菌体は、脱水するとどれくらいの含水率になりますか。産業廃棄物（汚泥）として処分する場合の単価と、色素を含む菌体の廃棄物区分を教えてください。', '色素分解の後処理は「脱水後の湿重量 × 処分単価」で積んでいる。菌体を使い捨てにすると処分量が多く、総コストへの影響が大きい。', 0, 194, 'open', null, null, null, 'amd_internal', 180);
insert into project_cost_questions (cost_question_id, cost_model_id, addressee, question, why_it_matters, impact_low, impact_high, status, answer, answered_on, linked_assumption_id, visibility, sort_order) values ('cq2_03', 'cm_p21_260820', 'AMD（内部）', 'SXが狙う色素系排液（染色・食品）の色の濃さを実測する。染色排水なら色素濃度（mg/L）、食品系なら色度とCODで取る。', '色素分解の必要菌体量は対象物質の濃度に比例する。いまは染色排水の文献相場（10〜250mg/L）の中央50mg/Lで仮置きしている。', null, null, 'open', null, null, null, 'amd_internal', 190);
insert into project_cost_questions (cost_question_id, cost_model_id, addressee, question, why_it_matters, impact_low, impact_high, status, answer, answered_on, linked_assumption_id, visibility, sort_order) values ('cq2_04', 'cm_p21_260820', '杉浦先生', '自然株と強化株で、同じ菌体量・同じ条件のときの金属取り込み量を比べたデータはありますか。9/2の試験で、野生型が40ppmを取り込んだときの乾燥菌体量はいくらでしたか。', '金属回収の取り込み効率は、自然株を「強化株の5.3% × 40/50」と推定で置いている。株の切り替えで金属回収の総コストがどれだけ動くかは、この数字で決まる。', null, null, 'open', null, null, null, 'amd_internal', 200);
insert into project_cost_questions (cost_question_id, cost_model_id, addressee, question, why_it_matters, impact_low, impact_high, status, answer, answered_on, linked_assumption_id, visibility, sort_order) values ('cq2_05', 'cm_p21_260820', '中島先生', '金属回収で使用済み菌体を酸で溶かす工程について教えてください。①乾燥菌体1kgを溶かすのに酸は何kg要りますか ②中和剤は何kg要りますか ③溶かした後の廃液は何L出ますか ④残渣は何kg残りますか。', '金属回収の後処理は260820版の値を換算したもので、酸・中和剤・廃液の量の根拠がない。色素側の処分費と同じ精度で比べるために、量だけをもらってAMD側で円へ変換する。', null, null, 'open', null, null, null, 'amd_internal', 210);
update project_cost_notes set section = 'benchmark', title = '人件費を総コストから外した判断の裏付け', body_md = '中島先生の当初設計は人員が張り付く前提だった。それではコスト的に成立せず、そもそも静脈側（排水処理）に人を張り付ける装置は売れないという判断で、ほぼ人件費のかからない想定へ切り替えた（まさ判断）。

同じツムラヒアリングに、この判断を支える一次情報がある。

- 排水処理・ユーティリティ管理は**有資格者が必要**で、50〜60代のベテランが数年以内に退職する懸念
- 担当者が2名で空き人材がいない場合、**1名の退職だけで工場運転不能になるリスク**
- 育成・採用が追いつかず、**運転管理のアウトソース化を含む対策を模索中**。外部委託サービスへの問い合わせが増加

つまり「人を減らせる」はこの市場ではむしろ売り文句になる。ただし**顧客側の人が0人になるなら、菌体の搬入・使用済み菌体の搬出・モジュール／膜の交換は誰かがやることになり、SX側の巡回サービス原価として立て直す必要がある（現行モデルには未計上）**。

**2026-09-13 追記**: 二段階版では人件費を総コストへ入れ、人件費を除いた値を併記する形に変えた（まさ指示）。無人運転を狙う判断は変えていないが、作業時間が確認できるまでは手動運用の値で積む。', source_url = null, source_label = '2026-07 ツムラ ヒアリングメモ / 2026-08-23 まさ判断', visibility = 'amd_internal', sort_order = 30, updated_at = now() where cost_note_id = 'cn_260820_b3';
update project_cost_notes set section = 'caveat', title = '菌体の製造原価は、生産能力いっぱいで割っている', body_md = '二段階版では、乾燥菌体1kgの原価を「(培養設備の償却年額 ＋ 年ごとの固定費) ÷ 年間生産能力 ＋ 菌体量に比例する費用」で出す。

**年間生産能力いっぱいに稼働している前提**なので、実際の供給量が能力を下回ると、1kgあたりの原価は上がる。旧版の「供給先数で割る」はこの考え方に置き換えたため使っていない。

年間生産能力（33,333kg/年）は、旧版が暗黙に置いていた「必要な菌体量＝生産量」を引き継いだ仮置き。培養液1Lあたりの1日の増殖量と培養容積が分かるまで確定しない。', source_url = null, source_label = '原典③シート I35', visibility = 'amd_internal', sort_order = 40, updated_at = now() where cost_note_id = 'cn_260820_c4';
update project_cost_notes set section = 'history', title = 'この試算が答えていないこと', body_md = '- **回収物の売却収入がモデルに1円も入っていない。** 収入は処理費500円/m³のみ。レアアース回収などのアップサイドが数字として表現できていない
- **事業規模との接続がない。** 1拠点あたり年商1,500万円（30,000m³ × 500円）。FY35 売上200億円という目標に対して、何拠点必要かが出ていない
- **酸処理（菌体再生）の設備が未計上。** 金属回収で菌体を再生して使う経路を採るなら設備が要るが、金額が入っていない
- **閉鎖系の追加費用と巡回サービスは仮置き。** 金額の根拠となる見積がまだない（二段階版で追加）
- **色素側の数字は実測がない。** 色素の濃さ・取り込み効率・菌体使用回数・使用済み菌体の含水率は文献相場か仮置き', source_url = null, source_label = '2026-08-23 レビュー', visibility = 'amd_internal', sort_order = 20, updated_at = now() where cost_note_id = 'cn_260820_h2';
update project_cost_notes set section = 'reading_guide', title = '各行が何を見るためのものか', body_md = '- **第1段 菌体の製造原価** — 株ごとに、乾燥菌体1kgをつくる原価。培養設備の償却・年ごとの固定費・菌体量に比例する費用に分けて見る
- **第2段 菌体費** — 第1段の原価 × 排水1m³あたりに使い切る菌体量
- **現場設備 OPEX／CAPEX** — 方式ごとのコア工程（循環＝カートリッジ、投入＝UF/MF）と、槽
- **人件費** — 現場の運転。総コストに含み、除いた値も併記する
- **巡回サービス** — 菌体の搬入・搬出、モジュールと膜の交換作業
- **閉鎖系の追加** — 強化株のときだけ乗る費用。第1段の分と現場の分の合計
- **後処理** — 使用済み菌体の後始末。金属回収は酸処理、色素分解は汚泥としての処分
- **事業全体 総コスト** — 売価500円/m³に対して成立するか', source_url = null, source_label = '原典②シート「見る意味」列', visibility = 'amd_internal', sort_order = 10, updated_at = now() where cost_note_id = 'cn_260820_r1';
update project_cost_notes set section = 'reading_guide', title = '色素分解は、菌体使用回数で総コストが大きく動く', body_md = '色素分解の菌体使用回数だけを動かしたときの総コスト（円/m³）。他の前提は据え置き。

| 株 | 菌体使用回数 | 色素分解 B:投入／既設 | 人件費を除くと |
|---|---|---|---|
| 強化株 | 1回 | 878.0 | 578.0 |
| 強化株 | 10回 | 540.0 | 240.0 |
| 強化株 | 30回 | 504.9 | 204.9 |
| 自然株 | 1回 | 826.5 | 526.5 |
| 自然株 | 10回 | 517.2 | 217.2 |
| 自然株 | 30回 | 484.2 | 184.2 |

旧版では中央培養の設備償却が使用回数に連動しない固定額だったため、10回を超えると頭打ちになっていた。二段階版では菌体原価を1kgあたりで持つので、**菌体費と使用済み菌体の処分費がどちらも使用回数に反比例する**。

杉浦先生へは引き続き「10回を超えるか」を確認する。', source_url = null, source_label = '2026-09-13 感度分析（二段階版の計算エンジンで実測）', visibility = 'amd_internal', sort_order = 30, updated_at = now() where cost_note_id = 'cn_260820_r3';
insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cn2_c7', 'cm_p21_260820', 'caveat', '強化株の閉鎖系費用は、カテゴリー1相当で積んでいる', '強化株の閉鎖系費用は、判定が確定していないため**カテゴリー1相当**で積んでいる。

**GILSP**と判定されれば、排気の除菌フィルター（設備と交換）、培養設備と現場設備の密閉性能検査、処理水の不活化は、法令上は求められない可能性がある。作業区域の区画・表示、区別保管、廃液の扱い、教育訓練は、GILSPでも必要。

この切り分けで外れる可能性がある額は、B:投入／既設で色素分解 約31.0円/m³、金属回収 約30.3円/m³。', null, '産業利用二種省令 別表・経済産業省／NITE「第二種使用等の手引き」第5.1版（令和8年9月）', 'amd_internal', 70);
insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cn2_c8', 'cm_p21_260820', 'caveat', '人件費は手動運用の作業時間で入れている', '中島先生の試算にある1バッチあたり作業時間（A:循環5.75時間、B:投入7.5時間）で、人件費を総コストへ入れている。

自動制御で無人運転する設計方針は変えていない。無人運転で何時間まで減るかが分かっていないため、いまは根拠のある手動運用の値を使い、**人件費を除いた値も併記**している。実態はこの2つの間にある。', null, null, 'amd_internal', 80);
insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cn2_c9', 'cm_p21_260820', 'caveat', '色素分解の数字は、文献相場と仮置きで組んでいる', '色素分解ケースの対象物質の濃度（50mg/L）、取り込み効率（0.05g/g）、菌体使用回数（1回）、脱水後の湿重量倍率（5倍）は、いずれも実測ではない。

特に**菌体使用回数**は総コストへの効き方が大きい。二段階版では菌体費と処分費がどちらも使用回数に反比例するため、1回と10回で総コストが大きく変わる。', null, null, 'amd_internal', 90);
insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cn2_c10', 'cm_p21_260820', 'caveat', '後処理の数字は、金属と色素で根拠の置き方が違う', '金属回収の後処理（酸・洗浄水・中和剤・残渣処分・廃液処理で乾燥菌体1kgあたり約39円）は、260820版の値を換算したもので、酸や廃液の量の根拠は確認できていない。

色素分解の後処理（使用済み菌体を汚泥として処分。乾燥菌体1kgあたり約175円）は、脱水後の湿重量と汚泥の処分相場から積んだ。

**同じ精度で比べられていない。** 菌体を使い捨てにしたとき色素分解が金属回収より高く見えるのは、この差による部分がある。金属側は酸で菌体を溶かした後の廃液量によっては上がる可能性が高い。', null, null, 'amd_internal', 100);
insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cn2_h3', 'cm_p21_260820', 'history', '260913 二段階版への組み替え', '2026-09-13、まさの指摘で計算の組み方を二段階に変えた。

**なぜ変えたか**: 旧版は中央培養の費用を「排水1m³あたり」で持ち、設備償却を必要菌体量に連動しない固定額で置いていた。そのため菌体使用回数を変えると、菌体1kgあたりの原価が見かけ上 98円 → 約440円 → 約1,200円と動いてしまい、「製造原価は株で決まり、用途では変わらない」という事実と合っていなかった。

**何を変えたか**
- 中央培養の明細を 円/m³ から 円/kg-DCW と年額固定費へ換算し、年間生産能力で割って菌体1kgの原価を出す形にした
- 前提と明細に「どの株・どの用途に効くか」を持たせ、画面で強化株／自然株を切り替えられるようにした
- 色素分解と金属回収を別行に分け、横に並べて比較できるようにした
- 人件費を総コストへ入れた（除いた値も併記）
- 巡回サービス、閉鎖系の追加費用（強化株のみ）、色素用の後処理、色素の濃さを追加した
- 金属の取り込み効率を、9/2定例の試験結果から株ごとに置き直した（自然株 約4.2%、強化株 5.3%以上）

**旧版との対応**（自然株・金属回収・B:投入／既設）: 旧版 349.7円/m³ から、搬送費を巡回サービスへ統合 -9.0、金属の取り込み効率を0.05→0.042へ置き直し +33.0、巡回サービスを追加 +34.4、人件費を算入 +300.0 で、708.1円/m³。旧版と同じ条件に戻すと4シナリオとも旧版の数字に一致することを、計算エンジンの点検で確認している。

**二段階版の B:投入／既設**: 強化株で色素分解 878.0円/m³、金属回収 715.0円/m³。自然株で色素分解 826.5円/m³、金属回収 708.1円/m³。いずれも人件費を手動運用の時間で含む。', null, null, 'amd_internal', 30);
insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cn2_r5', 'cm_p21_260820', 'reading_guide', '二段階の読み方', '1. **株を選ぶ** — 画面上部のスイッチで強化株か自然株を選ぶ。保存はされない
2. **第1段で菌体1kgの原価を見る** — 同じ株なら、色素分解でも金属回収でも同じ原価を使う
3. **第2段で用途を並べて見る** — 色素分解と金属回収で違うのは、排水1m³に使い切る菌体の量と、後処理だけ
4. **下の詳細は用途のタブで切り替える** — 成立ライン・内訳・確からしさは、選んだ用途の4シナリオで出す', null, null, 'amd_internal', 5);
commit;
