-- 401: SX 技術タブに閉鎖系（強化株）の論点を入れる（2026-09-14 まさ依頼「閉鎖系のレポートを技術タブに入れておいて」）
-- 出典は Drive p21_sx/260911_閉鎖系要件と論点整理 のレポート（公開URL https://sx-heisakei-ronten.vercel.app ）。
-- 区分「閉鎖系（強化株）」を sort_order 22〜28 で置き、培養（10）と排水処理（30）の間に並べる。
-- 金額はコスト試算タブが正本なので、ここには入れない（spec 3-20 §3.5）。
begin;
insert into project_tech_topics (tech_topic_id, project_id, block_kind, title, summary, body_md, tech_domain, sort_order, status, confidentiality, source_kind, source_ref, source_url, needs_check, check_reason, created_by, updated_by) values ($t$ptt_sx_closed_overview$t$, $t$p21$t$, $t$article$t$, $t$強化株を閉鎖系で使うための論点 — 全体像$t$, $t$強化株（遺伝子組換え）は法令上、閉鎖系でしか使えない。何が求められ、どこで事業の形が分かれるかを、問いの分岐順に整理した。全文は出典のレポート。$t$, $body$**結論** — 閉鎖系の要件は省令に箇条書きで定められており、装置と運用に落とせる。事業を左右するのは要件の重さではなく、次の2点。

1. **強化株がGILSPと判定されるか。** 判定で、大臣確認の要否、処理水の扱い、審査期間が変わる。株が好熱性（45〜70℃）であることは、GILSPの「増殖が制限される」要件の根拠になりうる（下限温度のデータが要る）。
2. **現場の処理槽で細胞を増やすか。** 増やせば必要な菌体量を下げられるが、顧客工場が規制施設になる。規制と原価の要求が正面から逆を向く。

**問いの系譜**

```mermaid
flowchart LR
  S["強化株は閉鎖系でしか使えない"] --> Q1["問1 閉鎖系の要件"]
  S --> Q2["問2 リアクター設計"]
  S --> Q4["問4 世界の先行事例"]
  Q2 --> Q3["問3 金属を取る仕組み"]
  Q1 --> A11["区分は3段階"]
  A11 --> A111["強化株はどの区分か（未確認）"]
  Q2 --> A23["顧客工場は規制施設になるか（未確認）"]
  Q3 --> A31["吸着か取込みか（未確認）"]
  Q3 --> A33["必要な菌体量の壁"]
  A23 --> M["合流点：処理槽で細胞を増やすか"]
  A33 --> M
```

**合流点 — 処理槽で細胞を増やすか**

| | 増やす | 増やさない |
|---|---|---|
| 原価 | 菌体が現地で増え、必要量の開きを下げられる | 細胞は消耗品のまま |
| 規制 | 培養設備に当たり、顧客工場が規制施設になる | 培養設備と解されない余地が残る |

衝突を避けうる道は、SX拠点で増やしながら処理するオフサイト形態。代わりに運搬費が乗り、運搬も法令上の「使用等」になる。

**このタブの中での置き場所**

- 法令の要件 → 「閉鎖系とは何か」「株の区分ごとの手続きと求められる措置」
- 強化株の判定材料 → 「GILSPの判定条件と、SXの強化株で分かっていること」
- 装置と運用 → 「閉鎖系リアクターに求められる設備と運用」
- 仕組み → 「金属を取る仕組みと光」／前例 → 「世界の先行事例」
- 誰に何を確かめるかと進み具合は、ゴールツリー「強化株を閉鎖系で使えるか」が正本。費用はコスト試算タブが正本。$body$, $t$閉鎖系（強化株）$t$, 22, $t$active$t$, $t$confidential$t$, $t$manual$t$, $t$SolvioraX 閉鎖系の要件と論点整理（2026-09-11、Drive p21_sx/260911_閉鎖系要件と論点整理）$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_topics (tech_topic_id, project_id, block_kind, title, summary, body_md, tech_domain, sort_order, status, confidentiality, source_kind, source_ref, source_url, needs_check, check_reason, created_by, updated_by) values ($t$ptt_sx_closed_law$t$, $t$p21$t$, $t$article$t$, $t$閉鎖系とは何か — カルタヘナ法の第二種使用等$t$, $t$「閉鎖系」は法令用語。使用等には保管・運搬・廃棄も入る。審査期間、所管、大学側の20Lの壁もここにまとめた。$t$, $body$**定義** — 施設外の大気・水・土壌への拡散を防止する意図をもって、所定の措置を執って行う使用等を「第二種使用等」という。これがいわゆる閉鎖系。環境放出を前提とする第一種使用等は大臣の承認と生物多様性影響評価が要り、排水処理で取得するのは現実的でない。強化株を使う限り、必ず第二種使用等になる。

**使用等に入るもの** — 培養だけでなく、保管・運搬・廃棄も入る。大学からSX拠点、SX拠点から顧客現場への輸送も、使用済み菌体の処分も対象。保管は漏出しない容器に入れて表示し、運搬は漏出しない容器に入れて「取扱いに注意を要する」旨を表示する。

**審査にかかる期間** — カテゴリー1以上は審議会の日程調整があるため、**標準処理期間が設けられていない**。過去に確認を受けたものと供与核酸だけが違う場合などに限り、おおむね3週間の目安がある。シアノバクテリアを宿主とする申請は前例が乏しいと見込まれ、設立予定に対して期間が読めない。

**所管省庁（未確認）** — 経済産業省が所管するのは、工業用酵素・触媒・研究用試薬・工業用原料の生産と、事業としての試験・検査（閉鎖系）。排水処理サービスはどちらにも直接は当てはまらない。金属回収を工業用原料の生産と読む余地はあるが推定にとどまる。NITEの事前相談（無料、会社設立前でも可）で確定させる。

**大学側の20L** — 研究開発段階では、培養設備の総容量が20Lを超えると「大量培養実験」になり、措置の区分が変わる。現行の7Lチューブは対象外、設計中の30〜100Lの反応槽は超える。超えると、外部へ流出しない構造、排気を除菌用フィルター等を通して出す設備、植菌・採取・移し替えで漏出しない容器や配管、付着したときの直ちの不活化、区域と保管設備への表示が求められる。$body$, $t$閉鎖系（強化株）$t$, 23, $t$active$t$, $t$internal$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_topics (tech_topic_id, project_id, block_kind, title, summary, body_md, tech_domain, sort_order, status, confidentiality, source_kind, source_ref, source_url, needs_check, check_reason, created_by, updated_by) values ($t$ptt_sx_closed_categories$t$, $t$p21$t$, $t$matrix$t$, $t$株の区分ごとの手続きと求められる措置$t$, $t$GILSP・カテゴリー1・その他で、大臣確認、審査期間、処理水の扱い、設備と運用がどう変わるか。条文の要件を書いており、優劣の記号は付けていない。$t$, null, $t$閉鎖系（強化株）$t$, 24, $t$active$t$, $t$internal$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_topics (tech_topic_id, project_id, block_kind, title, summary, body_md, tech_domain, sort_order, status, confidentiality, source_kind, source_ref, source_url, needs_check, check_reason, created_by, updated_by) values ($t$ptt_sx_closed_gilsp$t$, $t$p21$t$, $t$condition$t$, $t$GILSPの判定条件と、SXの強化株で分かっていること$t$, $t$経済産業省のGILSP基準を1行ずつ置き、SXの強化株で分かっていることと確かめ先を書く。判定が変わると、手続き・処理水・審査期間がまとめて変わる。$t$, $body$強化株2はおよそ100mLの培養段階で、性能試験の前にある。耐性マーカーと増殖速度は株の作り方に依存するので、性能評価の前に確かめれば作り直しを避けられる。増殖の制限は宿主の性質で決まり、好熱性がその根拠になりうる。$body$, $t$閉鎖系（強化株）$t$, 25, $t$active$t$, $t$confidential$t$, $t$literature$t$, $t$GILSP告示（経済産業省）／SXの状況は閉鎖系レポート 1-1-1$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_topics (tech_topic_id, project_id, block_kind, title, summary, body_md, tech_domain, sort_order, status, confidentiality, source_kind, source_ref, source_url, needs_check, check_reason, created_by, updated_by) values ($t$ptt_sx_closed_reactor$t$, $t$p21$t$, $t$condition$t$, $t$閉鎖系リアクターに求められる設備と運用 — 今の設計で足りているか$t$, $t$カテゴリー1相当の要件を装置と運用に落とし、7/10の封じ込め設計で足りているものと足りないものに分けた。$t$, null, $t$閉鎖系（強化株）$t$, 26, $t$active$t$, $t$internal$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）／SX リアクター構造・封じ込め・交換運用設計 v0.1（2026-07-10）$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_topics (tech_topic_id, project_id, block_kind, title, summary, body_md, tech_domain, sort_order, status, confidentiality, source_kind, source_ref, source_url, needs_check, check_reason, created_by, updated_by) values ($t$ptt_sx_closed_mechanism$t$, $t$p21$t$, $t$article$t$, $t$金属を取る仕組みと光 — 吸着と取込み、生きている・取り込む・増える$t$, $t$強化株の価値が乗るのは細胞内への取込み側。処理槽に光が要るか、細胞が消耗品になるかがここで決まる。$t$, $body$**吸着と取込みは性質が正反対**

| | 吸着（細胞の表面に結合） | 取込み（細胞の内部へ運ぶ） |
|---|---|---|
| エネルギー | 不要 | 必要 |
| 生きている必要 | なし（死菌でも進む） | あり |
| 速さ | 速い（分〜時間で頭打ち） | 遅い（時間〜日） |
| 光・二酸化炭素 | 不要 | 要る |

TmtAはメタロチオネイン、つまり細胞の中で金属を掴むタンパク質で、強化株の効果は理屈の上では取込み側に出る。9/2に報告された「強化株1が24時間で50ppmを全量取り込み、乾燥菌体重量比5.3%」は、吸着と取込みが分けて測られていない（技術検証「TmtAと鉄の結合を直接測定する」）。

**光の要否は3段階に分かれる**

| 状態 | 光は要るか | 仕組み |
|---|---|---|
| 生きている | 不要 | 光合成中に蓄えたグリコーゲンを、暗所で呼吸して使う |
| 取り込む | その場では不要。事前の蓄えが要る | 蓄えから作ったATPで輸送体を動かす。蓄えが尽きるまで続く |
| 増える | 要る | 光合成で二酸化炭素を固定する。Synechocystisはグルコースがあっても完全な暗黒では増えず、1日数分の青色光が合図として要る |

「処理槽に光は要らない」という説明は、細胞を別の工程で育てて蓄えさせてから入れる前提なら整合する。有機物を含む排液では、外から炭素とエネルギーを得られる可能性がある（未確認）。

**必要な菌体量**

必要な菌体量 ＝ 対象物質の濃度 ÷ 取り込み効率 ÷ 使い回せる回数。50ppm・強化株の5.3%・使い捨てでは、排水1m³あたり約0.94kg（乾燥重量）。共通の目安「排水1m³あたり培養液10L」（約10g）の約94倍。金額と用途別の原価はコスト試算タブが正本。

**検討して外した案** — 死菌にしてカセットにする案は採らない。TmtAは細胞内のタンパク質で、殺すと流出し、残るのは細胞壁による吸着だけになるため。$body$, $t$閉鎖系（強化株）$t$, 27, $t$active$t$, $t$confidential$t$, $t$manual$t$, $t$閉鎖系レポート 問3（吸着と取込みの文献、シアノバクテリアの暗所代謝の文献、9/2定例の試験値）$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_topics (tech_topic_id, project_id, block_kind, title, summary, body_md, tech_domain, sort_order, status, confidentiality, source_kind, source_ref, source_url, needs_check, check_reason, created_by, updated_by) values ($t$ptt_sx_closed_precedent$t$, $t$p21$t$, $t$article$t$, $t$世界の先行事例 — 生きた組換え体の排水処理は前例がほぼない$t$, $t$実用化されているのは自然由来の微生物か死菌バイオマス。参入障壁が規制側にあることの意味。$t$, $body$| 方式 | 使われている菌 | 実態 |
|---|---|---|
| 活性汚泥法（排水処理の主流） | その場にいる雑多な微生物の集団 | 特定の株を使わない |
| 菌の添加（バイオオーグメンテーション） | 自然界から分離した菌の混合 | 大手水処理事業者も製品化。遺伝子改変をしていない旨を明記している |
| 金属吸着材 | 死菌バイオマス | 1990年代に商品化。AlgaSORB（クロレラ）、BIO-FIX（スピルリナなどを多孔質ビーズに固定）、AMT-BIOCLAIM（バチルス） |

**実用化されていない理由** — 環境放出の承認が各国とも重い。逃げたあとの生存や、他の微生物への遺伝子の移りを予測できない。排水は組成が変わり続けるので、狙った性能を保てない。

**SXにとっての意味** — 競合がいないので、規制を突破できれば持続的な優位になる。一方で、誰も突破していないことには理由があり、規制の重さは技術の改良では下げられない。株の設計と事業の形で対応するほかない。$body$, $t$閉鎖系（強化株）$t$, 28, $t$active$t$, $t$internal$t$, $t$literature$t$, $t$Veolia BioPlus 製品説明／IntechOpen "Application of Biosorption for Removal of Heavy Metals from Wastewater"／閉鎖系レポート 問4$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_c11$t$, $t$ptt_sx_closed_categories$t$, $t$p21$t$, $t$大臣確認$t$, $t$GILSP$t$, $t$不要。自社の安全委員会の判断で開始できる$t$, null, $t$high$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, null, 11, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_c12$t$, $t$ptt_sx_closed_categories$t$, $t$p21$t$, $t$大臣確認$t$, $t$カテゴリー1$t$, $t$必要。区分が合っているかを審議会で確認する$t$, null, $t$high$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, null, 12, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_c13$t$, $t$ptt_sx_closed_categories$t$, $t$p21$t$, $t$大臣確認$t$, $t$その他$t$, $t$必要。拡散防止措置そのものを審議会で確認する$t$, null, $t$high$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, null, 13, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_c21$t$, $t$ptt_sx_closed_categories$t$, $t$p21$t$, $t$審査にかかる期間$t$, $t$GILSP$t$, $t$審査なし$t$, null, $t$high$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, null, 21, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_c22$t$, $t$ptt_sx_closed_categories$t$, $t$p21$t$, $t$審査にかかる期間$t$, $t$カテゴリー1$t$, $t$標準処理期間の定めなし（審議会の日程次第）$t$, null, $t$high$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, null, 22, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_c23$t$, $t$ptt_sx_closed_categories$t$, $t$p21$t$, $t$審査にかかる期間$t$, $t$その他$t$, $t$標準処理期間の定めなし（審議会の日程次第）$t$, null, $t$high$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, null, 23, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_c31$t$, $t$ptt_sx_closed_categories$t$, $t$p21$t$, $t$処理水・廃液の扱い$t$, $t$GILSP$t$, $t$含まれる組換え微生物の数を最小限にとどめる措置をとってから廃棄する（数値基準なし）$t$, null, $t$high$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, null, 31, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_c32$t$, $t$ptt_sx_closed_categories$t$, $t$p21$t$, $t$処理水・廃液の扱い$t$, $t$カテゴリー1$t$, $t$廃液と廃棄物を不活化する$t$, null, $t$high$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, null, 32, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_c33$t$, $t$ptt_sx_closed_categories$t$, $t$p21$t$, $t$処理水・廃液の扱い$t$, $t$その他$t$, $t$大臣確認を受けた措置による$t$, null, $t$high$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, null, 33, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_c41$t$, $t$ptt_sx_closed_categories$t$, $t$p21$t$, $t$設備と運用$t$, $t$GILSP$t$, $t$作業区域、培養設備、器具の洗浄・不活化設備、性状の試験検査設備、区別保管設備、持ち出し時の漏出しない容器$t$, null, $t$high$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, null, 41, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_c42$t$, $t$ptt_sx_closed_categories$t$, $t$p21$t$, $t$設備と運用$t$, $t$カテゴリー1$t$, $t$GILSPの要件に加え、外部との物理的な分離、培養設備の密閉性能の検査（設置時・定期・漏れ止め部品の交換時）、必要に応じて菌を捕まえる換気、廃液の不活化、立入制限、「カテゴリー1 取扱い中」の表示$t$, null, $t$high$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, null, 42, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_c43$t$, $t$ptt_sx_closed_categories$t$, $t$p21$t$, $t$設備と運用$t$, $t$その他$t$, $t$大臣確認を受けた措置による（カテゴリー1より重い）$t$, null, $t$high$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, null, 43, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_g10$t$, $t$ptt_sx_closed_gilsp$t$, $t$p21$t$, $t$【宿主】病原性がない$t$, null, $t$該当すると見込まれる$t$, $t$宿主の要件$t$, $t$medium$t$, $t$literature$t$, $t$GILSP告示（経済産業省・NITE 手引き 第5.1版 第2章第2節）／SXの状況は閉鎖系レポート 1-1-1$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, null, 10, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_g20$t$, $t$ptt_sx_closed_gilsp$t$, $t$p21$t$, $t$【宿主】病原性に関係するウイルス・プラスミドを含まない$t$, null, $t$宿主の素性の確認が必要$t$, $t$宿主の要件$t$, $t$unverified$t$, $t$literature$t$, $t$GILSP告示（経済産業省・NITE 手引き 第5.1版 第2章第2節）／SXの状況は閉鎖系レポート 1-1-1$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, null, 20, true, $t$宿主の種名と、保有しているプラスミドを杉浦先生に確認する。$t$, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_g30$t$, $t$ptt_sx_closed_gilsp$t$, $t$p21$t$, $t$【宿主】長期の安全使用歴がある、または特殊な培養条件以外では増殖が制限される$t$, null, $t$好熱性（45〜70℃）が根拠になりうる。日本の河川・海域（おおむね10〜30℃）では増殖しない可能性がある。基準が求めるのは増殖の制限で、死滅ではない$t$, $t$宿主の要件$t$, $t$unverified$t$, $t$literature$t$, $t$GILSP告示（経済産業省・NITE 手引き 第5.1版 第2章第2節）／SXの状況は閉鎖系レポート 1-1-1$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, null, 30, true, $t$増殖が止まる下限温度と、10〜30℃で増殖しない（生存はしても増えない）ことを示すデータを杉浦先生に確認する。強化株の宿主が同じ好熱株で温度特性が保たれているかも確認する。温排水が合流して局所的に水温が高くなる放流先の扱いは、NITEの事前相談で確認する。$t$, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_g40$t$, $t$ptt_sx_closed_gilsp$t$, $t$p21$t$, $t$【ベクター】性質が明らかで、有害な配列を含まない$t$, null, $t$導入遺伝子（TmtA）の同定状況の確認が必要$t$, $t$供与核酸とベクターの要件$t$, $t$unverified$t$, $t$literature$t$, $t$GILSP告示（経済産業省・NITE 手引き 第5.1版 第2章第2節）／SXの状況は閉鎖系レポート 1-1-1$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, null, 40, true, $t$導入した遺伝子と配列が同定済みかを杉浦先生に確認する。$t$, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_g50$t$, $t$ptt_sx_closed_gilsp$t$, $t$p21$t$, $t$【ベクター】伝達性に乏しく、耐性マーカーを他の細胞へ伝えない$t$, null, $t$染色体へ組み込んだか自律複製プラスミドか、薬剤耐性マーカーが残っているかで判断が分かれる$t$, $t$供与核酸とベクターの要件$t$, $t$unverified$t$, $t$literature$t$, $t$GILSP告示（経済産業省・NITE 手引き 第5.1版 第2章第2節）／SXの状況は閉鎖系レポート 1-1-1$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, null, 50, true, $t$組み込み方と、耐性マーカーの残存・除去の可否を杉浦先生に確認する。強化株2が約100mLの段階にある今なら株設計で対応できる。$t$, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_g60$t$, $t$ptt_sx_closed_gilsp$t$, $t$p21$t$, $t$【組換え体】病原性がない$t$, null, $t$該当すると見込まれる$t$, $t$組換え微生物の要件$t$, $t$medium$t$, $t$literature$t$, $t$GILSP告示（経済産業省・NITE 手引き 第5.1版 第2章第2節）／SXの状況は閉鎖系レポート 1-1-1$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, null, 60, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_g70$t$, $t$ptt_sx_closed_gilsp$t$, $t$p21$t$, $t$【組換え体】宿主と比べて増殖する能力が高くない$t$, null, $t$強化株と野生型の増殖速度を同じ条件で比べたデータが必要$t$, $t$組換え微生物の要件$t$, $t$unverified$t$, $t$literature$t$, $t$GILSP告示（経済産業省・NITE 手引き 第5.1版 第2章第2節）／SXの状況は閉鎖系レポート 1-1-1$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, null, 70, true, $t$同じ条件で取った強化株と野生型の増殖曲線があるかを杉浦先生に確認する。$t$, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_r10$t$, $t$ptt_sx_closed_reactor$t$, $t$p21$t$, $t$【足りている】密閉スキッドと二次受け皿$t$, null, $t$最大保有液量の110%以上を保持する受け皿を持つ密閉スキッド$t$, null, $t$medium$t$, $t$manual$t$, $t$SX リアクター構造・封じ込め・交換運用設計 v0.1（2026-07-10）$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, null, 10, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_r20$t$, $t$ptt_sx_closed_reactor$t$, $t$p21$t$, $t$【足りている】最終菌体捕捉の二重系と完全性試験$t$, null, $t$粒子ろ過とは独立した、微生物保持を目的とする二重の捕捉と、その完全性試験$t$, null, $t$medium$t$, $t$manual$t$, $t$SX リアクター構造・封じ込め・交換運用設計 v0.1（2026-07-10）$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, null, 20, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_r30$t$, $t$ptt_sx_closed_reactor$t$, $t$p21$t$, $t$【足りている】異常時の遮断$t$, null, $t$送液を止めて両端を遮断し、スキッド内に保留する。未処理水を放流するバイパスを設けない$t$, null, $t$medium$t$, $t$manual$t$, $t$SX リアクター構造・封じ込め・交換運用設計 v0.1（2026-07-10）$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, null, 30, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_r40$t$, $t$ptt_sx_closed_reactor$t$, $t$p21$t$, $t$【足りている】交換と回収の担い手$t$, null, $t$SXまたは指名した事業者だけが交換・回収する。顧客は菌体に触れない。持ち出しは二次容器に入れる$t$, null, $t$medium$t$, $t$manual$t$, $t$SX リアクター構造・封じ込め・交換運用設計 v0.1（2026-07-10）$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, null, 40, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_r50$t$, $t$ptt_sx_closed_reactor$t$, $t$p21$t$, $t$【足りない】排気の除菌$t$, null, $t$設計文書に記載がない。生きた菌が光合成すれば、密閉槽から排気が必ず出る$t$, null, $t$unverified$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, null, 50, true, $t$カテゴリー1なら菌を捕まえられる換気が要る。GILSPなら不要の可能性がある。区分の判定が出てから設計へ反映する。$t$, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_r60$t$, $t$ptt_sx_closed_reactor$t$, $t$p21$t$, $t$【足りない】密閉性能の検査$t$, null, $t$設置時と定期に加え、漏れ止め部品を交換するたびに検査する。装置の仕様ではなく運用の義務で、保守の工数に乗る$t$, null, $t$unverified$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, null, 60, true, $t$検査の方法・頻度・外注費を中島先生に確認する。費用はコスト試算タブに仮置きしている。$t$, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_r70$t$, $t$ptt_sx_closed_reactor$t$, $t$p21$t$, $t$【足りない】作業区域の区分と表示$t$, null, $t$顧客工場の一角を作業区域として線引きし、表示する。装置ではなく契約と交渉の論点$t$, null, $t$unverified$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, null, 70, true, $t$増殖させずに保持するだけの槽が「培養又は発酵の用に供する設備」に当たるかを、NITEの事前相談で確認する。当たらなければ顧客工場を規制施設にせずに済む。$t$, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_r80$t$, $t$ptt_sx_closed_reactor$t$, $t$p21$t$, $t$【足りない】洗浄消毒・不活化・試験検査・区別保管の設備$t$, null, $t$顧客工場の一区画に揃えるのは現実的でない。SX拠点に集め、現場を施設要件から外せるかが分かれ目$t$, null, $t$unverified$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://sx-heisakei-ronten.vercel.app$t$, null, 80, true, $t$上の作業区域と同じく、NITEの事前相談で現場の扱いを確認する。$t$, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_r90$t$, $t$ptt_sx_closed_reactor$t$, $t$p21$t$, $t$【運用】判定の記録の保存$t$, null, $t$使用区分を判断した審議記録を、使用の終了後20年保存する。会社設立時に安全委員会と記録の体制が要る$t$, null, $t$high$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, null, 90, false, null, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_text, condition_text, confidence, source_kind, source_ref, source_url, note, sort_order, needs_check, check_reason, created_by, updated_by) values ($t$pte_sx_cls_r100$t$, $t$ptt_sx_closed_reactor$t$, $t$p21$t$, $t$【大学側】培養設備の総容量$t$, null, $t$20Lを超えると大量培養実験（LS1など）。現行の7Lは対象外、設計中の30〜100Lは超える$t$, null, $t$unverified$t$, $t$literature$t$, $t$カルタヘナ法 第2条・第12条・第13条／産業利用二種省令 第3〜5条・別表／研究開発二種省令 第2条・別表第三／経済産業省・NITE「第二種使用等の手引き及び注意事項」第5.1版（令和8年9月）$t$, $t$https://www.nite.go.jp/data/000160810.pdf$t$, null, 100, true, $t$いま強化株でどのレベルの承認を得ているかと、20Lを超えるときの手続き（機関承認で足りるか、大臣確認が要るか）を、愛媛大の遺伝子組換え実験安全委員会に確認する。$t$, $t$amie$t$, $t$amie$t$);
commit;
