-- 412: SX コスト試算（燃料）の seed。バイオディーゼル（FAME・船舶向け）の試算を project_cost_* に足す（2026-09-14 まさ依頼）
--
-- まさ「OSの技術ページに、新たに『コスト試算（燃料）』を追加してほしい。
-- そんで廃液処理のコスト試算と同様にバイオディーゼル事業のコスト試算シートを作ってほしい。」
-- 先に 411（燃料の試算の値を制約へ足す）を適用すること。
-- この試算を読む画面（排水処理のタブが case_kind = 'biodiesel' を読まない形）の配信が済んでから適用すること。
-- 配信前に適用すると、排水処理のコスト試算タブがこの試算を読んでしまう。
--   - 試算 cm_p21_fuel_260914（case_kind biodiesel、単位 L、原価目標 140円/L）
--   - 前提 29件（年間の燃料の量 5,000万L/年、売価200円/L、収率の3ケース、残渣の行き先ほか）
--   - 明細 51行（培養設備は排水処理の試算 cm_p21_260820 の自然株の行をコピー。各工場へ運ぶ保管・輸送設備は除く）
--   - 作業 5行、確認事項 8件、注記 10件
-- 生成: えいみ 2026-09-14（SXセッション）。DB の現行行（培養設備）と fixture を同じ定義（gen_fuel_seed.py）から書き出した。
begin;

insert into project_cost_models (cost_model_id, project_id, title, case_kind, case_label, version_label, status, source_url, source_note, summary_md, visibility, system_scope_md, target_total_cost_per_m3, target_margin_rate, target_note, unit_basis_label) values ('cm_p21_fuel_260914', 'p21', 'SX コスト試算（燃料）', 'biodiesel', 'バイオディーゼル（FAME・船舶向け）', '260914版', 'active', null, '260818 バイオ燃料アップサイド検討資料／260903 事業概要／260907 シアノ→FAME→SAF 工程とマテバラ推定／排水処理のコスト試算 260914版の培養設備', 'SXのシアノバクテリアで**バイオディーゼル（FAME・船舶向け）**を作って売る事業を、燃料1Lあたりの総コストで試算する。ゴールツリーの「バイオディーゼル事業は成立するか」に数字で答えるためのシート。

**二段階で計算する** — 第1段で燃料のための菌体1kgの原価を出し、第2段で燃料1Lあたりの総コスト（菌体費 ＋ 脱水・油回収 ＋ FAMEにする ＋ 残渣の処理 ＋ 品質確認・出荷 ＋ 燃料化設備の償却）を出す。燃料1Lに要る菌体の量は、菌体から燃料が取れる割合（収率）で決まる。

**事業の規模は売上100億円** — 排水処理のコスト試算と同じく、IPOできる大量生産の状態として、年間の燃料の量を5,000万L（想定売価200円/Lで売上100億円）で置く。年に要る菌体の量と、培養設備・燃料化設備の系列数は、この量から計算する。

**切り替えは2つ** — FAME転換を外部に委託するか自社で行うか（事業概要 2026-09-03 の分担は委託）と、収率の3ケース（低位・基準・改善。2026-09-07 の工程とマテバラ推定）。結果の欄に6通りの総コストを並べ、売価200円/Lと、粗利30%を残す原価目標140円/Lの線を引く。

**売価で成立する菌体の原価** — 選んだ組み合わせで、売価で損益ゼロになる菌体1kgの原価の上限を出す。マイナスなら、菌体をタダで手に入れても燃料化の工程だけで売価を超える。

培養設備の明細と作業は、排水処理のコスト試算（260914版）の培養設備1系列からコピーした（各工場へ運ぶ保管・輸送設備は除いた）。燃料化設備・溶媒・電力・熱・委託費は見積のない仮置きで、確度は低い。操作パネルで数字を書き換えると、結果がその場で再計算される。書き換えは保存されない。正本へ書くのは、管理者が「この値を保存」を押したときだけ。', 'amd_internal', '**製品** — FAME（脂肪酸メチルエステル。バイオディーゼルの成分）を、船舶燃料向けに売る。SAF（航空燃料）までの加工は入れていない。

**工程** — 1. 培養設備で菌体をつくり、濃縮する → 2. 燃料化設備で固形分20%まで脱水し、細胞を壊して溶媒で油（膜の脂質）を取り出し、溶媒を蒸留で回収する → 3. FAMEにする（外部に委託するか、自社でメタノールと酸触媒で反応させて精製する） → 4. 油を取ったあとの残渣を処理する → 5. 品質を分析し、タンクローリーで出荷する。

**分担** — 培養から油の回収までをSXの工場で行う（事業概要 2026-09-03「自社工程: 培養、濃縮、脱水、油回収」）。FAMEへの転換は外部の精製事業者への委託を基本に置き、自社で行う場合と比べる。作業はすべてSXがやり、費用はすべてSXが持つ（委託するときは委託費をSXが払う）。

**排水処理とは別のライン** — 燃料のために培養した菌体だけを使う。金属回収に使った菌体は原料にしない。

**規模** — 年間の燃料の量（事業全体）から年に要る菌体の量を計算し、培養設備（1系列 年33,333kg）と燃料化設備（1系列 年5万t）を必要な数だけ並べる。量産でまとめて大きくする効果は入れていない。

**入れていないもの** — 残渣や副生物の売上（フィコシアニンなどの有価物、液肥、グリセロール系の副生物）、CO2の削減価値、補助金、税（軽油引取税）、SAF。', 140, null, '想定売価200円/Lで粗利30%を残す総原価の上限（260818 バイオ燃料アップサイド検討資料、260903 事業概要）。', 'L');

insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_business_annual_volume', 'cm_p21_fuel_260914', null, '事業の規模と売価', '年間の燃料の量（事業全体）', 50000000, null, 'L/年', 'C', '仮置き', 'AMD（内部）', true, 'business_annual_volume', '排水処理のコスト試算と同じく、IPOできる大量生産の状態として売上100億円に届く量で置いた（売上100億円 ÷ 想定売価200円/L ＝ 5,000万L/年）。260818 バイオ燃料アップサイド検討資料の売上シナリオは、2033年度 80億円（4,000万L/年）、2035年度 400億円（2億L/年）。年に要る菌体の量と、培養設備・燃料化設備の系列数は、この量から計算する（入力ではない）。売価を変えると売上も変わるので、売上100億円に合わせるときはこの量も変える。', 'amd_internal', 100, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_sale_price', 'cm_p21_fuel_260914', null, '事業の規模と売価', '想定売価（船舶向けFAME）', 200, null, '円/L', 'C', '資料記載', 'AMD（内部）', true, 'sale_price', '260818 バイオ燃料アップサイド検討資料・260903 事業概要の仮置き。市場参照は、米国DOEの2025年10月のB99/B100小売平均 4.30ドル/ガロン（1ドル161円で約183円/L）。日本の船舶向けの販売条件（混合率・引き渡し場所・物流・品質契約・税）で置き換える。', 'amd_internal', 101, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_fame_potential', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', '全菌体のFAMEポテンシャル（基準）', 10, null, '%', 'H', '仮置き', '杉浦先生（外部分析）', true, 'fame_potential', '乾燥菌体を分析したときに得られるFAME（脂肪酸メチルエステル。バイオディーゼルの成分）の重さの割合。メタノールから加わるメチル基を含む分析上の量。2026-09-07 の工程とマテバラ推定の設計仮定で、SX株では測っていない。天然のシアノバクテリアは5〜12%程度が一般的とされる。シアノバクテリアの油は膜の糖脂質・リン脂質が中心なので、抽出した油の量（20%など）をそのままFAMEの量に置き換えない。燃料1Lに要る菌体の量にそのまま効く、いちばん大きい感度。', 'amd_internal', 110, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_fame_potential_low', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', '全菌体のFAMEポテンシャル（低位）', 5, null, '%', 'H', '仮置き', '杉浦先生（外部分析）', false, 'fame_potential_low', '2026-09-07 の工程とマテバラ推定の低位の仮定。', 'amd_internal', 111, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_fame_potential_high', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', '全菌体のFAMEポテンシャル（改善）', 20, null, '%', 'H', '仮置き', '杉浦先生（外部分析）', false, 'fame_potential_high', '2026-09-07 の工程とマテバラ推定の改善の仮定。統計的な上限や将来予測ではない。', 'amd_internal', 112, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_harvest_recovery', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', '菌体回収率（基準）', 95, null, '%', 'H', '仮置き', '中島先生', false, 'harvest_recovery', '培養液から濃縮・脱水で取り出せる菌体の割合。取り出せなかった菌体は培養へ戻す液と一緒に抜ける。2026-09-07 の工程とマテバラ推定の設計仮定。', 'amd_internal', 120, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_harvest_recovery_low', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', '菌体回収率（低位）', 90, null, '%', 'H', '仮置き', '中島先生', false, 'harvest_recovery_low', '2026-09-07 の工程とマテバラ推定の低位の仮定。', 'amd_internal', 121, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_harvest_recovery_high', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', '菌体回収率（改善）', 98, null, '%', 'H', '仮置き', '中島先生', false, 'harvest_recovery_high', '2026-09-07 の工程とマテバラ推定の改善の仮定。統計的な上限や将来予測ではない。', 'amd_internal', 122, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_extraction_recovery', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', '脂質抽出回収率（基準）', 90, null, '%', 'H', '仮置き', '中島先生', false, 'extraction_recovery', '固形分20%の湿った菌体から、細胞を壊して溶媒で取り出せる脂質の割合（分析上のFAMEポテンシャルに対して）。菌体を全部乾かす方法は、水を飛ばす熱が燃料の発熱量を大きく超えるので採らない。湿式で90%取れるかは検証課題。', 'amd_internal', 130, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_extraction_recovery_low', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', '脂質抽出回収率（低位）', 80, null, '%', 'H', '仮置き', '中島先生', false, 'extraction_recovery_low', '2026-09-07 の工程とマテバラ推定の低位の仮定。', 'amd_internal', 131, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_extraction_recovery_high', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', '脂質抽出回収率（改善）', 95, null, '%', 'H', '仮置き', '中島先生', false, 'extraction_recovery_high', '2026-09-07 の工程とマテバラ推定の改善の仮定。統計的な上限や将来予測ではない。', 'amd_internal', 132, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_methylation_rate', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', 'メチル化反応率（基準）', 97, null, '%', 'C', '仮置き', '精製事業者', false, 'methylation_rate', '取り出した脂質をメタノールと酸触媒でFAMEに変える割合。水分・遊離脂肪酸・膜脂質が多い原料なので、酸触媒で置いた。', 'amd_internal', 140, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_methylation_rate_low', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', 'メチル化反応率（低位）', 95, null, '%', 'C', '仮置き', '精製事業者', false, 'methylation_rate_low', '2026-09-07 の工程とマテバラ推定の低位の仮定。', 'amd_internal', 141, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_methylation_rate_high', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', 'メチル化反応率（改善）', 99, null, '%', 'C', '仮置き', '精製事業者', false, 'methylation_rate_high', '2026-09-07 の工程とマテバラ推定の改善の仮定。統計的な上限や将来予測ではない。', 'amd_internal', 142, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_purification_recovery', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', 'FAME精製回収率（基準）', 98, null, '%', 'C', '仮置き', '精製事業者', false, 'purification_recovery', '中和・メタノール回収・洗浄・吸着・脱水で、製品として残るFAMEの割合。', 'amd_internal', 150, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_purification_recovery_low', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', 'FAME精製回収率（低位）', 95, null, '%', 'C', '仮置き', '精製事業者', false, 'purification_recovery_low', '2026-09-07 の工程とマテバラ推定の低位の仮定。', 'amd_internal', 151, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_purification_recovery_high', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', 'FAME精製回収率（改善）', 99, null, '%', 'C', '仮置き', '精製事業者', false, 'purification_recovery_high', '2026-09-07 の工程とマテバラ推定の改善の仮定。統計的な上限や将来予測ではない。', 'amd_internal', 152, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_fame_density', 'cm_p21_fuel_260914', null, '菌体から取れる燃料（収率）', '燃料（FAME）の密度', 0.88, null, 'kg/L', 'B', '資料記載', 'AMD（内部）', false, 'fame_density', '重さ（kg）から量（L）へ換える値。260818 バイオ燃料アップサイド検討資料・2026-09-07 の工程とマテバラ推定と同じ。', 'amd_internal', 170, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_biomass_cost_override', 'cm_p21_fuel_260914', null, '菌体の原価', '菌体の原価（上書き）', null, null, '円/kg-DCW', 'H', '仮置き', null, true, 'biomass_cost_per_kg_override', '空欄なら培養設備の明細と作業から計算する。値を入れると、その原価で燃料1Lあたりの総コストを計算する。0を入れると、培養の費用を燃料側で持たない形（排水処理向けに作った菌体の余りを使う形など）の総コストが見られる。ただし余りで作れる燃料の量は、排水処理側で余る菌体の量までで、年間の燃料の量の前提とは別に確かめる。', 'amd_internal', 180, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_culture_line_capacity', 'cm_p21_fuel_260914', null, '培養設備（菌体をつくる）', '培養設備1系列の年間生産能力', 33333, null, 'kg-DCW/年', 'H', '推定', '杉浦先生', true, 'culture_line_capacity_kg_year', '排水処理のコスト試算（260914版）と同じ値。培養設備1系列（明細の設備一式）で年に作れる乾燥菌体の量。年に要る菌体の量 ÷ この量 の数だけ系列を並べ、設備の初期投資・年ごとの品質確認・培養の運転を系列の数だけ増やす。明細の設備でこの量を作れるかは確かめていない。燃料の量では系列が1万を超えるので、量産の培養設備の単位（1系列の大きさ）も確かめる。', 'amd_internal', 200, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_plant_line_capacity', 'cm_p21_fuel_260914', null, '燃料化設備：脱水・油回収', '燃料化設備1系列で処理できる菌体の量', 50000000, null, 'kg-DCW/年', 'H', '仮置き', 'AMD（内部）', true, 'plant_line_capacity_kg_year', '脱水・細胞破砕・溶媒抽出・溶媒回収（自社で行うときはFAME転換も）の設備1系列で、年に処理できる乾燥菌体の量。1日あたり約167t（稼働300日）の中規模の化学プラントとして置いた。年に要る菌体の量 ÷ この量 の数だけ系列を並べる。量産で設備を大きくしたときの規模の経済は入れていない。', 'amd_internal', 210, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_labor_rate', 'cm_p21_fuel_260914', null, '人件費（作業）', '作業単価（共通）', 4000, null, '円/時', 'B', '仮置き', 'AMD', false, 'labor_rate', 'すべての作業に共通の作業単価（排水処理のコスト試算と同じ4,000円/時）。作業の年額 ＝ 年間回数 ×（1回の工数 × この単価 ＋ 1回の経費）。', 'amd_internal', 300, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_residue_route', 'cm_p21_fuel_260914', null, '残渣の処理', '残渣の行き先', null, 'digestion', null, 'H', '仮置き', 'AMD（内部）', true, 'residue_route', '油を取ったあとの残渣（菌体の大部分）をどう処理するか。「発酵などで処理」はメタン発酵などで処理し、処理費とガス・液肥の価値が相殺される前提。「産業廃棄物として処分」は、脱水した残渣を汚泥として処分業者に出す前提で、残渣の乾燥1kgあたり 湿重量倍率 × 処分単価 がかかる。行き先はまだ決めていない。', 'amd_internal', 400, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_residue_dry', 'cm_p21_fuel_260914', null, '残渣の処理', '残渣の量（乾燥）', 0.878, null, 'kg/kg-DCW', 'B', '資料記載', 'AMD（内部）', false, 'residue_dry_kg_per_kg_dcw', '2026-09-07 の工程とマテバラ推定の基準ケースで、乾燥菌体1tから出る菌体・有機残渣（乾燥換算）878.10kg。タンパク質・糖・取り出せなかった脂質・灰分など。収率を変えても、この量は変えていない。', 'amd_internal', 401, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_residue_digestion_cost', 'cm_p21_fuel_260914', null, '残渣の処理', '発酵などで処理するときの正味の費用', 0, null, '円/kg-乾燥残渣', 'H', '仮置き', 'AMD（内部）', false, 'residue_digestion_cost', 'メタン発酵でガスと液肥にし、処理費とガス・液肥の価値が相殺される前提で0円と置いた（未確認）。メタン発酵の液肥の肥料成分の価値は約2,800円/tという評価がある（農林水産省関連資料）。残渣からフィコシアニンなどの有価物を取る場合の売上は入れていない。', 'amd_internal', 402, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_residue_wet_factor', 'cm_p21_fuel_260914', null, '残渣の処理', '脱水後の湿重量倍率', 5, null, 'kg湿/kg-乾燥残渣', 'H', '推定', '中島先生', false, 'residue_wet_factor', '含水率80%まで脱水して出す想定（乾燥1kg → 湿重量5kg）。排水処理のコスト試算の使用済み菌体と同じ置き方。産業廃棄物として処分するときだけ効く。', 'amd_internal', 403, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_residue_disposal_price', 'cm_p21_fuel_260914', null, '残渣の処理', '汚泥の処分単価（収集運搬込み）', 35, null, '円/kg湿', 'B', '資料記載', '処分業者（見積）', false, 'residue_disposal_price', '産業廃棄物（汚泥）の処理料金相場 25〜50円/kg の中央（排水処理のコスト試算と同じ値）。産業廃棄物として処分するときだけ効く。', 'amd_internal', 404, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_truck_capacity', 'cm_p21_fuel_260914', null, '品質確認・出荷', '出荷1台の積載量（タンクローリー）', 20000, null, 'L/台', 'B', '資料記載', '運送会社（見積）', false, 'truck_capacity_l', '大型のタンクローリー（12〜20kL級）の上限で置いた。セミトレーラーなら20〜30kL（消防法の上限30kL）。作業「タンクローリーでの出荷」の回数は、年間の燃料の量 ÷ この値で決まる。', 'amd_internal', 500, null, null);
insert into project_cost_assumptions (cost_assumption_id, cost_model_id, code, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('caf_lot_size', 'cm_p21_fuel_260914', null, '品質確認・出荷', '品質確認1ロットの量', 500000, null, 'L/ロット', 'H', '仮置き', '販売先（品質契約）', false, 'lot_size_l', '出荷前に規格（JIS K2390 相当）の分析を1回行う量。貯槽1基分（500kL）で置いた。販売先との品質契約で決まる。作業「品質の分析」の回数は、年間の燃料の量 ÷ この値で決まる。', 'amd_internal', 501, null, null);

insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_043', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', '培養槽本体', '槽・架台', '初期投資配賦', 1, '基', 1200000, '円/基', null, 1, 7, false, 'C', '推測', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。 菌体の製造拠点の構成は「円盤型培養設備／培養液供給設備／菌体濃縮設備／菌体保管・輸送設備」。
以下14項目は円盤型培養設備（培養槽本体・架台）
培養液供給設備（配管・継手バルブ・CO2供給・培養ポンプ・pH計・温度計・OD濁度計・制御盤・センサー配線）
付帯工事（洗浄用付帯設備・据付工事・輸送試運転）に相当する。', 'amd_internal', 1000, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_044', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', '槽架台・支持部材', '槽・架台', '初期投資配賦', 1, '式', 250000, '円/式', null, 1, 7, false, 'C', '推測', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1001, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_045', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', '培養配管', '配管・接続', '初期投資配賦', 1, '式', 180000, '円/式', null, 1, 7, false, 'C', '推測', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1002, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_046', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', '継手・バルブ', '配管・接続', '初期投資配賦', 1, '式', 120000, '円/式', null, 1, 7, false, 'C', '推測', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1003, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_047', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', 'CO2供給機器', '供給系', '初期投資配賦', 1, '式', 200000, '円/式', null, 1, 7, false, 'C', '推測', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1004, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_048', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', '培養ポンプ', '動力', '初期投資配賦', 1, '台', 150000, '円/台', null, 1, 7, false, 'C', '推測', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1005, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_049', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', 'pH計', '計装', '初期投資配賦', 1, '台', 80000, '円/台', null, 1, 7, false, 'C', '推測', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1006, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_050', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', '温度計', '計装', '初期投資配賦', 1, '台', 50000, '円/台', null, 1, 7, false, 'C', '推測', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1007, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_051', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', 'OD/濁度計', '計装', '初期投資配賦', 1, '台', 150000, '円/台', null, 1, 7, false, 'C', '推測', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1008, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_052', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', '制御盤', '制御', '初期投資配賦', 1, '式', 220000, '円/式', null, 1, 7, false, 'C', '推測', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1009, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_053', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', 'センサー配線', '制御', '初期投資配賦', 1, '式', 80000, '円/式', null, 1, 7, false, 'C', '推測', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1010, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_054', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', '洗浄用付帯設備', '洗浄設備', '初期投資配賦', 1, '式', 150000, '円/式', null, 1, 7, false, 'C', '推測', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1011, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_055', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', '据付工事', '工事', '初期投資配賦', 1, '式', 250000, '円/式', null, 1, 7, false, 'C', '推測', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1012, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_056', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', '輸送・試運転', '工事', '初期投資配賦', 1, '式', 150000, '円/式', null, 1, 7, false, 'C', '推測', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1013, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_057', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', '菌体濃縮設備', '濃縮', '初期投資配賦', 1, '式', 2500000, '円/式', null, 1, 7, false, 'H', '予測', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。 菌体の製造拠点で培養液から菌体を分離・濃縮する設備。現行の培養槽まわり14項目には含まれていなかったため新規計上。金額は予測値（連続式遠心分離機または膜濃縮ユニット小型機を想定）。実機選定・見積で要更新。', 'amd_internal', 1014, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_058', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', '　└ 遠心分離機または膜濃縮ユニット', '濃縮', '内訳', 1, '式', 0, '円/式', null, 1, 7, true, null, '先生回答', '中島先生', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1015, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_059', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', '　└ 供給ポンプ・配管', '濃縮', '内訳', 1, '式', 0, '円/式', null, 1, 7, true, null, '先生回答', '中島先生', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1016, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_060', 'cm_p21_fuel_260914', '中央培養', 'CAPEX', '培養設備', '　└ 濃縮液受槽', '濃縮', '内訳', 1, '式', 0, '円/式', null, 1, 7, true, null, '先生回答', '中島先生', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。', 'amd_internal', 1017, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_120', 'cm_p21_fuel_260914', '中央培養', 'OPEX', '培養', '原料', '培地主原料', '毎kg菌体比例', 1, 'kg-DCW', 9, '円/kg-DCW', null, 1, null, false, 'C', '仮置き', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。 菌体の製造拠点で発生する菌体製造費。現場設備OPEXとは分離し「菌体の製造拠点」の区分へ。菌体製造原価として事業全体で別途配賦する。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', 'amd_internal', 1018, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_121', 'cm_p21_fuel_260914', '中央培養', 'OPEX', '培養', '原料', '栄養塩', '毎kg菌体比例', 1, 'kg-DCW', 10.8, '円/kg-DCW', null, 1, null, false, 'C', '仮置き', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', 'amd_internal', 1019, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_122', 'cm_p21_fuel_260914', '中央培養', 'OPEX', '培養', '原料', '微量元素・添加剤', '毎kg菌体比例', 1, 'kg-DCW', 7.2, '円/kg-DCW', null, 1, null, false, 'C', '仮置き', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', 'amd_internal', 1020, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_123', 'cm_p21_fuel_260914', '中央培養', 'OPEX', '培養', 'ユーティリティ', 'CO2', '毎kg菌体比例', 1, 'kg-DCW', 4.5, '円/kg-DCW', null, 1, null, false, 'C', '仮置き', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', 'amd_internal', 1021, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_124', 'cm_p21_fuel_260914', '中央培養', 'OPEX', '培養', 'ユーティリティ', '補給水', '毎kg菌体比例', 1, 'kg-DCW', 1.8, '円/kg-DCW', null, 1, null, false, 'C', '仮置き', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', 'amd_internal', 1022, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_125', 'cm_p21_fuel_260914', '中央培養', 'OPEX', '培養', '洗浄', '洗浄水', '毎kg菌体比例', 1, 'kg-DCW', 2.7, '円/kg-DCW', null, 1, null, false, 'C', '仮置き', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', 'amd_internal', 1023, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_126', 'cm_p21_fuel_260914', '中央培養', 'OPEX', '培養', '洗浄', '洗浄薬剤', '毎kg菌体比例', 1, 'kg-DCW', 4.5, '円/kg-DCW', null, 1, null, false, 'C', '仮置き', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', 'amd_internal', 1024, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_127', 'cm_p21_fuel_260914', '中央培養', 'OPEX', '培養', '濃縮・回収', '濃縮用フィルタ', '毎kg菌体比例', 1, 'kg-DCW', 9, '円/kg-DCW', null, 1, null, false, 'B', '仮置き', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', 'amd_internal', 1025, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_128', 'cm_p21_fuel_260914', '中央培養', 'OPEX', '培養', '濃縮・回収', '濃縮補助材', '毎kg菌体比例', 1, 'kg-DCW', 5.4, '円/kg-DCW', null, 1, null, false, 'C', '仮置き', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', 'amd_internal', 1026, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_129', 'cm_p21_fuel_260914', '中央培養', 'OPEX', '培養', '品質確認', 'サンプリング分析', '年額固定', 1, '年', 120000, '円/年', null, 1, null, false, 'C', '仮置き', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。 二段階版で年額固定に換算した（旧版の4円/m³ × 30,000m³）。検査の回数は菌体量ではなくバッチに付くため。 2026-09-14 から、培養設備1系列あたりの年額として、系列の数だけ増やす。', 'amd_internal', 1027, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_130', 'cm_p21_fuel_260914', '中央培養', 'OPEX', '培養', '品質確認', '品質確認試験', '年額固定', 1, '年', 120000, '円/年', null, 1, null, false, 'C', '仮置き', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。 二段階版で年額固定に換算した（旧版の4円/m³ × 30,000m³）。検査の回数は菌体量ではなくバッチに付くため。 2026-09-14 から、培養設備1系列あたりの年額として、系列の数だけ増やす。', 'amd_internal', 1028, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_culture_134', 'cm_p21_fuel_260914', '中央培養', 'OPEX', '培養', 'ロス補充', '培養ロス補充', '毎kg菌体比例', 1, 'kg-DCW', 5.4, '円/kg-DCW', null, 1, null, false, 'C', '仮置き', 'AMD', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。 二段階版で 円/m³ → 円/kg-DCW へ換算した（旧版の基準菌体量 1.111 kg-DCW/m³ で割った値）。', 'amd_internal', 1029, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_plant_dewater', 'cm_p21_fuel_260914', '共通', 'CAPEX', '脱水・油回収', '脱水設備', 'デカンター型遠心分離機など', '初期投資配賦', 1, '式', 300000000, '円/式', null, 1, 15, false, 'H', '推測', 'プラントメーカー（見積）', '濃縮した菌体を固形分20%まで脱水する。燃料化設備1系列（乾燥菌体 年5万t）あたり。見積はない。従来型のバイオディーゼル工場の初期投資（年産能力1tあたり約300〜450ドル）や、大豆の溶媒抽出工場を手がかりに、湿った菌体の細胞破砕と乳化対策の分を上乗せした目安。プラントメーカーの概算で置き換える。', 'amd_internal', 2000, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_plant_disruption', 'cm_p21_fuel_260914', '共通', 'CAPEX', '脱水・油回収', '細胞破砕設備', '高圧ホモジナイザーなど', '初期投資配賦', 1, '式', 400000000, '円/式', null, 1, 15, false, 'H', '推測', 'プラントメーカー（見積）', '湿った菌体の細胞を壊し、膜の脂質を溶媒に移しやすくする。燃料化設備1系列（乾燥菌体 年5万t）あたり。見積はない。従来型のバイオディーゼル工場の初期投資（年産能力1tあたり約300〜450ドル）や、大豆の溶媒抽出工場を手がかりに、湿った菌体の細胞破砕と乳化対策の分を上乗せした目安。プラントメーカーの概算で置き換える。', 'amd_internal', 2001, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_plant_extraction', 'cm_p21_fuel_260914', '共通', 'CAPEX', '脱水・油回収', '溶媒抽出・相分離設備', '混合槽・分離機', '初期投資配賦', 1, '式', 800000000, '円/式', null, 1, 15, false, 'H', '推測', 'プラントメーカー（見積）', '極性と非極性の溶媒で脂質を取り出し、水・残渣と分ける。溶媒の組成は未決。燃料化設備1系列（乾燥菌体 年5万t）あたり。見積はない。従来型のバイオディーゼル工場の初期投資（年産能力1tあたり約300〜450ドル）や、大豆の溶媒抽出工場を手がかりに、湿った菌体の細胞破砕と乳化対策の分を上乗せした目安。プラントメーカーの概算で置き換える。', 'amd_internal', 2002, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_plant_solvent_recovery', 'cm_p21_fuel_260914', '共通', 'CAPEX', '脱水・油回収', '溶媒回収設備', '蒸留塔・凝縮器', '初期投資配賦', 1, '式', 700000000, '円/式', null, 1, 15, false, 'H', '推測', 'プラントメーカー（見積）', '循環させる溶媒（菌体1kgあたり3kg）を蒸留で回収して使い回す。燃料化設備1系列（乾燥菌体 年5万t）あたり。見積はない。従来型のバイオディーゼル工場の初期投資（年産能力1tあたり約300〜450ドル）や、大豆の溶媒抽出工場を手がかりに、湿った菌体の細胞破砕と乳化対策の分を上乗せした目安。プラントメーカーの概算で置き換える。', 'amd_internal', 2003, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_plant_residue', 'cm_p21_fuel_260914', '共通', 'CAPEX', '残渣を処理する', '残渣の脱水・搬出設備', '脱水機・コンベア・保管', '初期投資配賦', 1, '式', 300000000, '円/式', null, 1, 15, false, 'H', '推測', 'プラントメーカー（見積）', '油を取ったあとの残渣を脱水し、搬出するまで保管する。燃料化設備1系列（乾燥菌体 年5万t）あたり。見積はない。従来型のバイオディーゼル工場の初期投資（年産能力1tあたり約300〜450ドル）や、大豆の溶媒抽出工場を手がかりに、湿った菌体の細胞破砕と乳化対策の分を上乗せした目安。プラントメーカーの概算で置き換える。', 'amd_internal', 2004, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_plant_utility', 'cm_p21_fuel_260914', '共通', 'CAPEX', '脱水・油回収', '付帯設備・据付工事', '配管・計装・電気・土木・排水処理', '初期投資配賦', 1, '式', 1500000000, '円/式', null, 1, 15, false, 'H', '推測', 'プラントメーカー（見積）', '機器の据付と、配管・計装・受変電・建屋・工場の排水処理。化学プラントでは機器代の数倍になることが多い。燃料化設備1系列（乾燥菌体 年5万t）あたり。見積はない。従来型のバイオディーゼル工場の初期投資（年産能力1tあたり約300〜450ドル）や、大豆の溶媒抽出工場を手がかりに、湿った菌体の細胞破砕と乳化対策の分を上乗せした目安。プラントメーカーの概算で置き換える。', 'amd_internal', 2005, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_ship_tank', 'cm_p21_fuel_260914', '共通', 'CAPEX', '品質を確かめて出荷する', '製品の貯槽・出荷設備', 'FAMEの貯槽・ローリーの積み込み', '初期投資配賦', 1, '式', 150000000, '円/式', null, 1, 15, false, 'H', '推測', 'プラントメーカー（見積）', '精製したFAMEをためて、タンクローリーに積み込む設備。燃料化設備1系列あたり。見積はない。', 'amd_internal', 2006, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_op_power', 'cm_p21_fuel_260914', '共通', 'OPEX', '脱水・油回収', '電力', '脱水・細胞破砕・抽出・ポンプ', '毎kg菌体比例', 0.3, 'kWh/kg-DCW', 17.45, '円/kWh', null, 1, null, false, 'H', '推定', 'プラントメーカー（見積）', '乾燥菌体1kgあたり0.3kWhは見積のない目安（細胞破砕が大部分）。単価は特別高圧の産業用電力の全国平均 17.45円/kWh（2026年5月、新電力ネット）。排水処理のコスト試算の電力単価（27円/kWh）は高圧の小口を想定した値で、燃料化設備の規模は特別高圧になるため分けた。', 'amd_internal', 2100, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_op_heat', 'cm_p21_fuel_260914', '共通', 'OPEX', '脱水・油回収', '熱', '溶媒の蒸留回収', '毎kg菌体比例', 1.5, 'MJ/kg-DCW', 2.3, '円/MJ', null, 1, null, false, 'H', '推定', 'プラントメーカー（見積）', '循環させる溶媒（菌体1kgあたり3kg）を蒸留で回収する熱を、乾燥菌体1kgあたり1.5MJと置いた（熱の回収を含む目安、見積なし）。単価は蒸気1tあたり約5,000円（仮置き）。溶媒の種類で変わる。', 'amd_internal', 2101, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_op_solvent', 'cm_p21_fuel_260914', '共通', 'OPEX', '脱水・油回収', '抽出溶媒の補給', '回収できない分', '毎kg菌体比例', 0.0285, 'kg/kg-DCW', 200, '円/kg', null, 1, null, false, 'H', '仮置き', '溶媒メーカー（見積）', '量は2026-09-07 の工程とマテバラ推定（循環する溶媒 2,850kg のうち99%を回収し、乾燥菌体1tあたり28.5kgを補給）。単価は溶媒の種類が未決のため1kgあたり200円の仮置き。', 'amd_internal', 2102, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_op_water', 'cm_p21_fuel_260914', '共通', 'OPEX', '脱水・油回収', '水', '抽出・洗浄の水', '毎kg菌体比例', 0.0002, 'm³/kg-DCW', 200, '円/m³', null, 1, null, false, 'C', '仮置き', 'AMD（内部）', '量は2026-09-07 の工程とマテバラ推定（乾燥菌体1tあたり0.2m³）。単価は工業用水の目安。', 'amd_internal', 2103, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_op_maintenance', 'cm_p21_fuel_260914', '共通', 'OPEX', '脱水・油回収', '設備の保守', '燃料化設備（脱水・油回収・残渣・出荷）の初期投資の3%/年', '年額固定', 1, '年', 124500000, '円/年', null, 1, null, false, 'H', '仮置き', 'プラントメーカー（見積）', '燃料化設備1系列の初期投資（41.5億円）の3%/年。初期投資の明細を書き換えたら、この額も合わせて直す。', 'amd_internal', 2104, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_out_tolling', 'cm_p21_fuel_260914', '外部委託', 'OPEX', 'FAMEにする', 'FAME転換・精製の委託費', '委託先で酸触媒の前処理・反応・精製', '毎m³比例', 1, 'L', 60, '円/L', null, 1, null, false, 'H', '仮置き', '精製事業者（見積）', '見積はない。国内の廃食用油から作るBDFの製造原価は平均259.5円/L（2021年度、全国油脂事業協同組合連合会の実態調査。原料の回収を含む小規模設備）。藻類の原料油は遊離脂肪酸・リン脂質・色素・金属が多く、酸触媒の前処理が要る。精製事業者の見積で置き換える。', 'amd_internal', 3000, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_out_transport', 'cm_p21_fuel_260914', '外部委託', 'OPEX', 'FAMEにする', '委託先までの原料油の輸送', 'タンクローリー', '毎m³比例', 1, 'L', 5, '円/L', null, 1, null, false, 'H', '仮置き', '運送会社（見積）', '20kL級のタンクローリーで片道100km程度を1回約10万円と置いた目安（見積なし）。', 'amd_internal', 3001, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_in_capex', 'cm_p21_fuel_260914', '自社精製', 'CAPEX', 'FAMEにする', 'FAME転換・精製設備', '前処理・反応槽・メタノール回収・洗浄・吸着・乾燥', '初期投資配賦', 1, '式', 500000000, '円/式', null, 1, 15, false, 'H', '推測', 'プラントメーカー（見積）', '燃料化設備1系列あたり。従来型のバイオディーゼル工場の初期投資（年産能力1tあたり約300〜450ドル）を、改善ケースの生産量（1系列 年約9,100t）に当てはめ、藻類の原料油の前処理を上乗せした目安（見積なし）。', 'amd_internal', 3100, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_in_methanol', 'cm_p21_fuel_260914', '自社精製', 'OPEX', 'FAMEにする', 'メタノール', '反応で使う分と回収できない分', '毎m³比例', 0.1278, 'kg/L', 50, '円/kg', null, 1, null, false, 'C', '推定', '化学品商社（見積）', '量は2026-09-07 の工程とマテバラ推定（乾燥菌体1tあたり11.80kg ÷ 精製FAME 92.36L）。単価はアジアのスポット価格 約318ドル/t（2025年第3四半期、名古屋着）からの目安。', 'amd_internal', 3101, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_in_acid', 'cm_p21_fuel_260914', '自社精製', 'OPEX', 'FAMEにする', '硫酸（触媒）', '純分換算', '毎m³比例', 0.01234, 'kg/L', 30, '円/kg', null, 1, null, false, 'H', '仮置き', '化学品商社（見積）', '量は2026-09-07 の工程とマテバラ推定（抽出した脂質の1%、乾燥菌体1tあたり1.14kg）。単価は仮置き。', 'amd_internal', 3102, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_in_naoh', 'cm_p21_fuel_260914', '自社精製', 'OPEX', 'FAMEにする', '苛性ソーダ（中和）', '純分換算', '毎m³比例', 0.01007, 'kg/L', 60, '円/kg', null, 1, null, false, 'H', '推定', '化学品商社（見積）', '量は2026-09-07 の工程とマテバラ推定（乾燥菌体1tあたり0.93kg）。単価は液体の貿易統計の単価 約28円/kg（2023年）に、2026年の値上げ（固形換算30円/kg以上）を足した目安。', 'amd_internal', 3103, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_in_adsorbent', 'cm_p21_fuel_260914', '自社精製', 'OPEX', 'FAMEにする', '吸着剤', '粗FAMEの1%', '毎m³比例', 0.00899, 'kg/L', 100, '円/kg', null, 1, null, false, 'H', '仮置き', '化学品商社（見積）', '量は2026-09-07 の工程とマテバラ推定（粗FAMEの1%）。単価は仮置き。', 'amd_internal', 3104, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_in_utilities', 'cm_p21_fuel_260914', '自社精製', 'OPEX', 'FAMEにする', '電力・熱', 'メタノールの回収・乾燥', '毎m³比例', 1, 'L', 3, '円/L', null, 1, null, false, 'H', '仮置き', 'プラントメーカー（見積）', 'マテバラ推定はエネルギーを計算していない。メタノールの蒸留回収と製品の乾燥の目安（見積なし）。', 'amd_internal', 3105, null, null, 'sx');
insert into project_cost_items (cost_item_id, cost_model_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cif_in_maintenance', 'cm_p21_fuel_260914', '自社精製', 'OPEX', 'FAMEにする', 'FAME転換設備の保守', '初期投資の3%/年', '年額固定', 1, '年', 15000000, '円/年', null, 1, null, false, 'H', '仮置き', 'プラントメーカー（見積）', 'FAME転換・精製設備（5億円）の3%/年。初期投資を書き換えたら、この額も合わせて直す。', 'amd_internal', 3106, null, null, 'sx');

insert into project_cost_tasks (cost_task_id, cost_model_id, scenario, strain, application, group_label, label, hours_per_occurrence, count_driver, count_per_year, hourly_rate, expense_per_occurrence, confidence, source_kind, owner, note, visibility, sort_order, performer) values ('ctf_culture_operation', 'cm_p21_fuel_260914', '中央培養', null, null, '菌体をつくる', '培養・濃縮の運転（1日分）', null, 'production_line', 300, null, 0, 'H', '仮置き', '杉浦先生・中島先生', '排水処理のコスト試算（260914版）の培養設備1系列からコピーした行。毎日の培養の管理と、菌体を濃縮して燃料化設備へ送れる状態にする作業。1日あたりの工数が分かっていないので空欄（未確認）で、0時間として数えている。1系列あたり年300日 × 系列数。', 'amd_internal', 10, 'sx');
insert into project_cost_tasks (cost_task_id, cost_model_id, scenario, strain, application, group_label, label, hours_per_occurrence, count_driver, count_per_year, hourly_rate, expense_per_occurrence, confidence, source_kind, owner, note, visibility, sort_order, performer) values ('ctf_plant_operation', 'cm_p21_fuel_260914', '共通', null, null, '脱水・油回収', '脱水と油回収の運転（1日分）', 72, 'plant_line', 300, null, 0, 'H', '仮置き', 'プラントメーカー（見積）', '脱水・細胞破砕・溶媒抽出・溶媒回収・残渣の搬出を、24時間の3交代・1直3人で運転する目安（1日72時間）。燃料化設備1系列あたり年300日 × 系列数。', 'amd_internal', 20, 'sx');
insert into project_cost_tasks (cost_task_id, cost_model_id, scenario, strain, application, group_label, label, hours_per_occurrence, count_driver, count_per_year, hourly_rate, expense_per_occurrence, confidence, source_kind, owner, note, visibility, sort_order, performer) values ('ctf_inhouse_operation', 'cm_p21_fuel_260914', '自社精製', null, null, 'FAMEにする', 'FAME転換と精製の運転（1日分）', 24, 'plant_line', 300, null, 0, 'H', '仮置き', 'プラントメーカー（見積）', 'FAME転換と精製を、24時間の3交代・1直1人で運転する目安（1日24時間）。自社で行うときだけ。燃料化設備1系列あたり年300日 × 系列数。', 'amd_internal', 30, 'sx');
insert into project_cost_tasks (cost_task_id, cost_model_id, scenario, strain, application, group_label, label, hours_per_occurrence, count_driver, count_per_year, hourly_rate, expense_per_occurrence, confidence, source_kind, owner, note, visibility, sort_order, performer) values ('ctf_ship_qc', 'cm_p21_fuel_260914', '共通', null, null, '品質を確かめて出荷する', '品質の分析（1ロット）', 2, 'batch', null, null, 150000, 'H', '仮置き', '分析機関（見積）', '出荷前にJIS K2390 相当の項目を外部の分析機関で測る目安（1回15万円、見積なし）と、試料の採取・記録の2時間。回数は 年間の燃料の量 ÷ 品質確認1ロットの量。', 'amd_internal', 40, 'sx');
insert into project_cost_tasks (cost_task_id, cost_model_id, scenario, strain, application, group_label, label, hours_per_occurrence, count_driver, count_per_year, hourly_rate, expense_per_occurrence, confidence, source_kind, owner, note, visibility, sort_order, performer) values ('ctf_ship_truck', 'cm_p21_fuel_260914', '共通', null, null, '品質を確かめて出荷する', 'タンクローリーでの出荷（1台）', 0, 'truck_trip', null, null, 60000, 'H', '仮置き', '運送会社（見積）', '運送会社に頼む前提で、工数を0にして運賃を1回の経費に置いた（20kL級・片道100km程度で1回6万円、見積なし）。回数は 年間の燃料の量 ÷ 出荷1台の積載量。', 'amd_internal', 41, 'sx');

insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cnf_caveat_yield', 'cm_p21_fuel_260914', 'caveat', '収率はSX株の実測ではない', '燃料1Lに要る菌体の量は、全菌体のFAMEポテンシャル × 菌体回収率 × 脂質抽出回収率 × メチル化反応率 × FAME精製回収率 で決まる。どれも2026-09-07 の工程とマテバラ推定の設計仮定で、SX株では測っていない。

- FAMEポテンシャルは基準10%（低位5%・改善20%）。天然のシアノバクテリアは5〜12%程度が一般的とされる
- シアノバクテリアの油は膜の糖脂質・リン脂質が中心で、抽出した油の量（20%など）をそのままFAMEの量に置き換えない
- SXの強化株は遺伝子組換え体で閉鎖系の設備が要り、窒素を切ると油ではなく糖を溜める。燃料は自然株で考えている
- 最初に確かめるのは、乾燥菌体を外部の分析機関に出してFAMEポテンシャルと脂肪酸の組成を測ること', null, null, 'amd_internal', 10);
insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cnf_caveat_biomass', 'cm_p21_fuel_260914', 'caveat', '総コストの大半は菌体費で、培養設備は排水処理の試算のコピー', '燃料1Lには、基準の収率で乾燥菌体が約10.8kg要る（改善で約4.8kg、低位で約27kg）。菌体1kgの原価がそのまま約10.8倍（改善で約4.8倍）になって燃料1Lに乗る。

- 培養設備1系列の明細（初期投資 5,730,000円・7年、年ごとの品質確認 240,000円、培地・CO2・濃縮など菌体1kgあたり60.3円）と、培養の運転の作業（工数未確認）は、排水処理のコスト試算（260914版）の自然株の培養設備と同じ値をコピーした。各工場へ運ぶための保管・輸送設備（1,500,000円）は、燃料では使わないので除いた。片方を直しても、もう片方は変わらない
- 1系列が年33,333kgと小さいので、燃料の量では系列が1万を超え、系列ごとの品質確認がそのまま積み上がる。量産の培養設備の単位は未確定
- CO2の費用は菌体1kgあたり4.5円。マテバラ推定では菌体1kgに約2.3kgのCO2が要るので、CO2 1kgあたり約2円（工場の排ガスをほぼタダで使う水準）になっている', null, null, 'amd_internal', 20);
insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cnf_caveat_plant', 'cm_p21_fuel_260914', 'caveat', '燃料化設備・電力・熱・委託費は見積のない仮置き', '脱水・細胞破砕・溶媒抽出・溶媒回収の設備、FAME転換の設備、電力と熱の量と単価、溶媒の単価、委託費、運賃、分析費は、どれも見積がない。公開資料の目安（従来型のバイオディーゼル工場の初期投資、国内の電力単価、汚泥の処分相場など）から置いた（確度はH）。

- 燃料化設備の保守は初期投資の3%/年を額で置いている。初期投資の明細を書き換えたら、保守の額も合わせて直す
- 培養液を濃縮するときの凝集剤などの薬剤は未選定で、入れていない
- 燃料化設備1系列（乾燥菌体 年5万t）より大きくしたときの規模の経済は入れていない', null, null, 'amd_internal', 30);
insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cnf_caveat_residue', 'cm_p21_fuel_260914', 'caveat', '残渣の行き先で総コストの桁が変わる', '油を取ったあとの残渣は、乾燥菌体1kgあたり約0.88kg（乾燥）で、菌体の大部分が残る。いまは発酵などで処理し、処理費とガス・液肥の価値が相殺される前提（0円）で置いている。

- 産業廃棄物（汚泥）として処分すると、含水率80%・処分単価35円/kg湿で、残渣の乾燥1kgあたり175円になる。基準の収率では燃料1Lあたり約1,660円が上乗せされる
- 前提「残渣の行き先」で切り替えられる
- 残渣からフィコシアニンなどの有価物を取る場合の売上は入れていない。燃料より残渣の売上が主になる形は、別の試算が要る', null, null, 'amd_internal', 40);
insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cnf_caveat_line', 'cm_p21_fuel_260914', 'caveat', '排水処理とは別のラインで、金属回収に使った菌体は原料にしない', '燃料のために培養した菌体だけを原料にする（事業概要 2026-09-03「金属を含む排水処理ラインと燃料生産ラインは分離し、安全性と品質を守る」）。

- 金属回収は酸で菌体を溶かして金属を取り出すうえ、残渣の用途が限られ、金属が後段の触媒に持ち込まれる
- 燃料の生産は光合成を続けさせる必要があり、重金属を取り込ませて菌体が死ぬ工程とは同時にできない', null, null, 'amd_internal', 50);
insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cnf_bench_price', 'cm_p21_fuel_260914', 'benchmark', '売価と原価の目安', '| 項目 | 値 | 出典 |
|---|---|---|
| 想定売価（船舶向けFAME） | 200円/L | 260818 バイオ燃料アップサイド検討資料、260903 事業概要 |
| 粗利30%を残す原価目標 | 140円/L | 同上 |
| FAME系バイオディーゼルの市場参照 | 約183円/L | 米国DOE 2025年10月 B99/B100小売平均 4.30ドル/ガロン（1ドル161円） |
| 国内の廃食用油BDFの製造原価 | 平均259.5円/L | 全国油脂事業協同組合連合会 BDF取組事業者の実態調査（2021年度） |
| NEDOのバイオジェット燃料のコスト目標 | 100〜200円/L | NEDO 2019年度 技術戦略 |', 'https://www.jora.jp/wp-content/uploads/2023/03/bdf_2022chousa.pdf', '全国油脂事業協同組合連合会 BDF取組事業者の実態調査', 'amd_internal', 10);
insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cnf_bench_plant', 'cm_p21_fuel_260914', 'benchmark', '設備と単価の目安', '| 項目 | 値 | 出典 |
|---|---|---|
| 従来型のバイオディーゼル工場の初期投資 | 年産能力1tあたり約300〜450ドル | 業界資料（IMARC）、Tsagkari et al. 2020（約370ユーロ/t） |
| 藻類バイオマスの生産費（屋外の池の目標値） | 灰分を除く乾燥重量1tあたり340ドル、脱水87ドル | NREL 2022 藻類ハーモナイゼーション |
| 産業用電力（特別高圧） | 全国平均 17.45円/kWh（2026年5月） | 新電力ネット |
| 産業廃棄物（汚泥）の処分 | 25〜50円/kg | 産業廃棄物の処理料金相場 |
| メタン発酵の液肥の肥料成分の価値 | 約2,800円/t | 農林水産省関連資料 |
| タンクローリー | 大型12〜20kL、セミトレーラー20〜30kL（消防法の上限30kL） | 業界の解説 |', 'https://docs.nrel.gov/docs/fy24osti/87099.pdf', 'NREL 2022 Algae Harmonization Update', 'amd_internal', 20);
insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cnf_guide', 'cm_p21_fuel_260914', 'reading_guide', 'この画面の見方', '- 上の切り替えで、FAME転換（外部に委託 / 自社で行う）と収率（低位 / 基準 / 改善）を選ぶ。右の結果の欄には6通りの総コストを同じ目盛りの棒で並べる。破線が売価、点線が原価目標
- 選んだ組み合わせの内訳は、菌体費・脱水と油回収・FAMEにする・残渣の処理・品質確認と出荷・燃料化設備の償却の6つ。区分を押すと中身が開く
- 「売価で成立する菌体の原価」は、売価で損益ゼロになる菌体1kgの原価の上限。マイナスは、菌体をタダで手に入れても燃料化の工程だけで売価を超えるという意味
- 左の操作パネルで数字を書き換えると、その場で再計算する。保存はしない。管理者だけ、上の「保存していない変更」から「この値を保存」で正本へ書ける', null, null, 'amd_internal', 10);
insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cnf_history_v1', 'cm_p21_fuel_260914', 'history', '260914版（初版）', '2026-09-14 まさ「OSの技術ページに、新たに『コスト試算（燃料）』を追加してほしい。廃液処理のコスト試算と同様にバイオディーゼル事業のコスト試算シートを作ってほしい」で作った。

- 構成と数字の元: 260818 バイオ燃料アップサイド検討資料（売価・原価目標・売上シナリオ・分担）、260903 事業概要（自社工程と外部精製の分担）、260907 工程とマテバラ推定（収率の3ケース・溶媒とメタノールなどの量・残渣の量）、排水処理のコスト試算 260914版（培養設備・作業単価）、公開資料の目安（設備の初期投資・電力単価・処分相場など）
- 事業の規模は、検討資料の売上シナリオ（2033年度 80億円・2035年度 400億円）ではなく、排水処理の試算と同じ売上100億円（5,000万L/年）で置いた。前提の年間の燃料の量を書き換えれば、ほかの規模も見られる', null, null, 'amd_internal', 10);
insert into project_cost_notes (cost_note_id, cost_model_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cnf_history_gaps', 'cm_p21_fuel_260914', 'history', 'この試算が答えていないこと', '- SAF（航空燃料）まで加工する場合（水素化精製の委託費と歩留まり）
- 残渣や副生物からの売上（フィコシアニンなどの有価物、液肥、グリセロール系の副生物）。燃料以外の売上で採算を作る形は、別の試算が要る
- 必要な敷地の広さ（NEDOの目標は油の生産で1日1haあたり75L）と、培養の面積あたりの生産性
- 量産で設備を大きくしたときの規模の経済と、JV（共同事業体）で持つ場合
- 排水処理向けに作った菌体の余りを燃料に回す形。前提「菌体の原価（上書き）」に0を入れると培養の費用を持たない形の総コストは見られるが、余りで作れる量は別に確かめる
- 軽油引取税（FAMEだけなら課税されず、軽油に混ぜると課税される）、CO2の削減価値、補助金', null, null, 'amd_internal', 20);

insert into project_cost_questions (cost_question_id, cost_model_id, addressee, question, why_it_matters, impact_low, impact_high, status, answer, answered_on, linked_assumption_id, visibility, sort_order) values ('cqf_fame_potential', 'cm_p21_fuel_260914', '外部の分析機関（杉浦先生のサンプル）', 'SXの自然株の乾燥菌体で、①全菌体のFAMEポテンシャル（全菌体をそのままメチル化して測る方法） ②脂肪酸の組成 ③灰分 を測ってください。同じ培養サンプルで乾燥重量も測ります。', '燃料1Lに要る菌体の量は、FAMEポテンシャルに反比例する。基準の10%が5%なら菌体費と菌体に比例する費用は2倍、20%なら半分。いまは設計仮定で、SX株では測っていない。杉浦先生に聞いても分からないため、乾燥菌体を外部の分析に出す方針（2026-09-10）。', 629, 1258, 'open', null, null, 'caf_fame_potential', 'amd_internal', 10);
insert into project_cost_questions (cost_question_id, cost_model_id, addressee, question, why_it_matters, impact_low, impact_high, status, answer, answered_on, linked_assumption_id, visibility, sort_order) values ('cqf_culture', 'cm_p21_fuel_260914', '杉浦先生', '燃料向けの培養の物量を教えてください。①培養液1Lあたり1日で何g（乾燥重量）増えますか ②窒素やリンを減らしたとき、油（脂質）の割合と増え方はどう変わりますか ③何日ごとに収穫しますか ④まだ分からない場合、それを確かめる実験の条件と回数は。', '培養設備1系列で年に作れる菌体の量が決まり、菌体1kgの原価に効く。燃料の総コストは菌体費が大半を占める。円ではなく量と条件を聞いて、AMD側で円に変える。', 172, 344, 'open', null, null, 'caf_culture_line_capacity', 'amd_internal', 20);
insert into project_cost_questions (cost_question_id, cost_model_id, addressee, question, why_it_matters, impact_low, impact_high, status, answer, answered_on, linked_assumption_id, visibility, sort_order) values ('cqf_extraction', 'cm_p21_fuel_260914', '中島先生', '固形分20%程度の湿った菌体から溶媒で油を取り出すとき、①どの溶媒と装置を想定しますか ②油はどのくらいの割合で取り出せますか ③溶媒はどのくらい回収して使い回せますか ④乳化で分けにくくなりますか。', '脂質抽出回収率（基準90%）と、溶媒の補給・蒸留の熱に効く。', 66, 157, 'open', null, null, 'caf_extraction_recovery', 'amd_internal', 30);
insert into project_cost_questions (cost_question_id, cost_model_id, addressee, question, why_it_matters, impact_low, impact_high, status, answer, answered_on, linked_assumption_id, visibility, sort_order) values ('cqf_tolling', 'cm_p21_fuel_260914', '精製事業者（バイオディーゼル工場）', '藻類から取った原料油のFAME転換・精製を受託できますか。①委託費（円/L） ②受け入れる原料油の条件（遊離脂肪酸・リン・金属・水分） ③最低の量と頻度 ④FAMEになる割合。', 'FAME転換を委託するときの費用（いまは委託費60円/L・輸送5円/Lの仮置き）と、メチル化・精製の歩留まりに効く。', 30, 60, 'open', null, null, null, 'amd_internal', 40);
insert into project_cost_questions (cost_question_id, cost_model_id, addressee, question, why_it_matters, impact_low, impact_high, status, answer, answered_on, linked_assumption_id, visibility, sort_order) values ('cqf_offtake', 'cm_p21_fuel_260914', '船舶燃料の販売先・商社', '船舶向けのFAME（またはFAMEを混ぜた燃料）の引き取り条件を教えてください。①価格（円/L） ②引き渡し場所と物流 ③品質の規格 ④年に必要な量。', '想定売価200円/Lは米国の小売の参照値（約183円/L）から置いた仮置き。売価が変わると、売価で成立する菌体の原価がそのまま動く。', null, null, 'open', null, null, 'caf_sale_price', 'amd_internal', 50);
insert into project_cost_questions (cost_question_id, cost_model_id, addressee, question, why_it_matters, impact_low, impact_high, status, answer, answered_on, linked_assumption_id, visibility, sort_order) values ('cqf_residue', 'cm_p21_fuel_260914', 'AMD内部', '油を取ったあとの残渣（菌体の約9割）をどうしますか。①メタン発酵して熱と液肥にする ②フィコシアニンなどの有価物を先に取る ③産業廃棄物として処分する。', '産業廃棄物として処分すると、燃料1Lあたりの総コストが大きく上がる（前提「残渣の行き先」で見られる）。有価物を取るなら、燃料より残渣の売上が主になる可能性がある（2026-09-10 の整理）。', 0, 1664, 'open', null, null, 'caf_residue_route', 'amd_internal', 60);
insert into project_cost_questions (cost_question_id, cost_model_id, addressee, question, why_it_matters, impact_low, impact_high, status, answer, answered_on, linked_assumption_id, visibility, sort_order) values ('cqf_plant', 'cm_p21_fuel_260914', 'プラントメーカー（中島先生経由）', '乾燥菌体で年5万t（1日約170t）を処理する燃料化設備（脱水・細胞破砕・溶媒抽出・溶媒回収・残渣の脱水）の、①概算の初期投資 ②電力と熱の使用量 ③運転の人数 を教えてください。', '燃料化設備の償却と保守、電力・熱、運転の作業（いまはどれも見積のない仮置き）に効く。', 90, 181, 'open', null, null, 'caf_plant_line_capacity', 'amd_internal', 70);
insert into project_cost_questions (cost_question_id, cost_model_id, addressee, question, why_it_matters, impact_low, impact_high, status, answer, answered_on, linked_assumption_id, visibility, sort_order) values ('cqf_culture_unit', 'cm_p21_fuel_260914', '杉浦先生・中島先生', '燃料の量産で使う培養設備は、1系列で年に何tの菌体を作る大きさを想定しますか。品質の確認は系列ごとに必要ですか、拠点ごとでよいですか。', 'いまの1系列（年33,333kg）のままだと系列が1万を超え、系列ごとの品質確認（年24万円）がそのまま積み上がる。', 0, 78, 'open', null, null, 'caf_culture_line_capacity', 'amd_internal', 80);

commit;
