-- 424: SOL（p21）の区分「競合比較」の VC に出す星取り表2枚で、「色と金属の両方を扱う」の行を「色素を分解できる」にする（2026-09-14 まさ）。
-- まさ「『色と金属の両方を扱う』→これは『色素を分解できる』でいいんじゃないの？両方できるところが他にないっていうか、色素を分解できるところがないだけだと思うんだけど」
-- → 色素を分解できる相手はほかにもある（会社の表の Arvia Technology、既存の方式の表のオゾン・フェントン酸化）と伝え、まさ「うん、１にしよう！」。
-- - この行の ◎ は SolvioraX と Arvia（会社の表）、SolvioraX とオゾン・フェントン酸化（既存の方式の表）。◎ が SolvioraX だけの行は、会社の表で3つ（生きた細胞・取れる金属の種類・熱い排水）、既存の方式の表で2つ（生きた細胞・熱い排水）。
-- - 既存の方式の表のマスは 417 の「色を消す」と同じ事実（凝集沈殿 △ 脱色率50〜91%、樹脂 対象外、活性炭 ○ 吸着、活性汚泥 × 分解されにくい）。本文の記号の付け方の表も直す。
-- 各書き換えは、423 のあとに誰も区分「競合比較」を書き換えていないときだけ当てる（止まったら何も書かない）。生成: scratchpad v422/build424.py（コミットしない）。
begin;
do $do$ declare nt int; ne int; mt timestamptz; me timestamptz; begin
  select count(*), max(updated_at) into nt, mt from project_tech_topics where project_id = $t$p21$t$ and tech_domain = $t$競合比較$t$;
  if nt <> 13 then raise exception '競合比較のトピック数が想定と違う: % 件', nt; end if;
  select count(*), max(e.updated_at) into ne, me from project_tech_entries e join project_tech_topics t on t.tech_topic_id = e.tech_topic_id
    where t.project_id = $t$p21$t$ and t.tech_domain = $t$競合比較$t$;
  if ne <> 274 then raise exception '競合比較の行数が想定と違う: % 件', ne; end if;
  if greatest(mt, me) > timestamptz $t$2026-09-14 09:35:14+00$t$ then raise exception '423 のあとに競合比較が書き換えられている: %', greatest(mt, me); end if;
  if (select count(*) from project_tech_entries where tech_topic_id = $t$ptt_sx_compare$t$) <> 54 then raise exception 'ptt_sx_compare の行数が想定と違う'; end if;
  if (select count(*) from project_tech_entries where tech_topic_id = $t$ptt_sx_compare_methods$t$) <> 36 then raise exception 'ptt_sx_compare_methods の行数が想定と違う'; end if;
end $do$;
delete from project_tech_entries where project_id = $t$p21$t$ and tech_topic_id = $t$ptt_sx_compare$t$;
update project_tech_topics set block_kind = $t$matrix$t$, title = $t$競合の会社との星取り表 — 排水や廃液から金属・色を取る新しい技術$t$, summary = $t$SolvioraX を、排水や廃液から金属や色を取る新しい技術の会社8社（日本3社・海外5社）と比べる。排水の金属を生きた細胞に取り込ませるのは、調べた範囲で SolvioraX だけ。2026年9月時点の公開資料から。$t$, body_md = $t$**排水の金属を生きた細胞に取り込ませる方式は、調べた範囲で SolvioraX だけ** — 排水や廃液から金属や色を取る技術の会社を、国内外で約30社調べた（2026年9月時点の公開資料）。排水の金属を、生きた細胞の中へ取り込ませる会社は、SolvioraX のほかに見つからなかった。生きた微生物を使う会社はあるが、微生物がつくる硫化物で金属を沈める（Paques）などで、金属を細胞の中へ取り込ませる方式ではない。乾かした細胞や、生きものからつくった材料・タンパク質に金属を付ける会社（ガルデリア・Mint Innovation・Allonnia）もある。

**比べる相手** — 生きものを使う会社（ガルデリア・Allonnia・Paques・Mint Innovation）、電気や材料で金属を取る会社（ElectraMet・パナソニック環境エンジニアリング・ディーピーエス）、染色排水の色を分解する会社（Arvia Technology）。工場でいま使われている方式との比較は、次の「既存の方式との星取り表」。

**記号の付け方**

| 観点 | ◎ | ○ | △ | × | — |
|---|---|---|---|---|---|
| 生きた細胞が金属を取り込む | 生きた細胞が、金属を細胞の中へ取り込む | 生きた微生物を使い、微生物がつくる物質で金属を沈める | 生きものからつくった材料・物質に、金属を付ける | （使わない） | 生きものを使わない、または金属を取る方式ではない |
| 色素を分解できる | 色素を分解して消す | 分解はしないが、吸着などで取り除く | 染料の種類や条件で効きにくい | 色素は分解されにくい | 色は対象外 |
| 取れる金属の種類 | レアアースと、銅などのほかの金属の両方 | 複数の金属 | 1種類の金属 | （使わない） | 金属は対象外 |
| 熱い排水（45℃以上）をそのまま処理 | 45℃以上がむしろ向く | そのまま使える | 一部の温度でだけ確認 | 冷ます必要がある | （使わない） |

「?」は公開資料で確認できないところ。取れる金属の種類は、各社の公開資料に書かれている金属による（SolvioraX の鉛・Dy・Nd はラボの速報）。「狙う液」「段階」の行は記号を付けず、事実を並べた。

**時点と範囲** — 2026年9月時点。各社の欄は各社の公開資料（製品ページ・事例・プレスリリース）による。費用は液の種類と規模で大きく変わるため、この表では比べていない。$t$, tech_domain = $t$競合比較$t$, sort_order = 80, confidentiality = $t$public$t$, source_kind = $t$manual$t$, source_ref = $t$2026-09 公開情報の調査（出典はマスごと）／SolvioraX 事業概要 v1.7（2026-09-06）・研究チームの実験結果$t$, source_url = null, needs_check = false, check_reason = null, updated_by = $t$amie$t$, updated_at = now() where tech_topic_id = $t$ptt_sx_compare$t$ and project_id = $t$p21$t$;
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_010_01$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$生きた細胞が金属を取り込む$t$, $t$SolvioraX$t$, null, null, $t$生きた細胞が細胞の中へ取り込む$t$, null, $t$excellent$t$, null, $t$2026-09-14$t$, $t$high$t$, $t$manual$t$, $t$SolvioraX 事業概要 v1.7（2026-09-06）／研究チームの報告（2026-09-02、取り込みを強めた株）$t$, null, $t$好熱性シアノバクテリア。取り込みを強めた株もある$t$, false, null, 1001, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_010_02$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$生きた細胞が金属を取り込む$t$, $t$ガルデリア（日本）$t$, null, null, $t$乾かした藻の細胞の表面に吸着$t$, null, $t$fair$t$, null, null, $t$high$t$, $t$vendor_spec$t$, $t$ガルデリア 会社サイト（乾燥させた細胞から吸着剤）$t$, $t$https://galdieria.com/en/solution-en/$t$, $t$温泉の紅藻から作る吸着剤$t$, false, null, 1002, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_010_03$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$生きた細胞が金属を取り込む$t$, $t$Allonnia（米国）$t$, null, null, $t$改変したタンパク質で結合$t$, null, $t$fair$t$, null, null, $t$high$t$, $t$vendor_spec$t$, $t$Allonnia RE-Cover（改変したタンパク質でレアアースを選んで結合、ラボで回収率90%超、モンタナにパイロット地点）$t$, $t$https://allonnia.com/re-cover/$t$, $t$レアアースを選んで結合$t$, false, null, 1003, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_010_04$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$生きた細胞が金属を取り込む$t$, $t$Paques（オランダ）$t$, null, null, $t$微生物がつくる硫化物で沈める$t$, null, $t$good$t$, null, null, $t$high$t$, $t$vendor_spec$t$, $t$Paques THIOTEQ Metal 製品ページ（微生物がつくる硫化物で金属を沈める、0〜80℃、高純度の金属硫化物）$t$, $t$https://www.paquesglobal.com/products/thioteq-metal$t$, $t$微生物は別の槽にいる$t$, false, null, 1004, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_010_05$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$生きた細胞が金属を取り込む$t$, $t$Mint Innovation（ニュージーランド）$t$, null, null, $t$生物由来の材料に吸着$t$, null, $t$fair$t$, null, null, $t$medium$t$, $t$vendor_spec$t$, $t$Mint Innovation 技術の説明（電子基板、金に結合するバイオマス、高純度の銅・商品グレードの金、シドニーで稼働）$t$, $t$https://www.mint.bio/technology$t$, $t$自然由来のバイオマス$t$, false, null, 1005, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_010_06$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$生きた細胞が金属を取り込む$t$, $t$ElectraMet（米国）$t$, null, null, $t$電気化学で金属を析出$t$, null, $t$na$t$, null, null, $t$high$t$, $t$vendor_spec$t$, $t$ElectraMet 半導体の銅CMP排水の事例（銅5〜35ppm、1年以上の連続運転で基準2.07ppm未満、高純度の銅板で回収）$t$, $t$https://electramet.com/case-study/cmp-wastewater-copper-removal-and-recovery/$t$, null, false, null, 1006, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_010_07$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$生きた細胞が金属を取り込む$t$, $t$パナソニック環境エンジニアリング（日本）$t$, null, null, $t$電解で銅を固形の金属に$t$, null, $t$na$t$, null, $t$2026-07-21$t$, $t$high$t$, $t$vendor_spec$t$, $t$パナソニック環境エンジニアリング プレスリリース 2026-07-21（RARELOOP を2026年4月に発売、エッチング廃液の銅を電解で固形の金属に）$t$, $t$https://news.panasonic.com/jp/press/jn260721-1$t$, null, false, null, 1007, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_010_08$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$生きた細胞が金属を取り込む$t$, $t$ディーピーエス（日本）$t$, null, null, $t$多孔質シリカの吸着材$t$, null, $t$na$t$, null, null, $t$high$t$, $t$vendor_spec$t$, $t$ディーピーエス 会社概要（多孔質シリカ粒子 DualPore、リサイクル用の金属スカベンジャーで貴金属・レアメタルを回収）$t$, $t$https://www.dps-inc.co.jp/company/$t$, null, false, null, 1008, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_010_09$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$生きた細胞が金属を取り込む$t$, $t$Arvia Technology（英国）$t$, null, null, $t$電気の酸化力で色を分解$t$, null, $t$na$t$, null, null, $t$high$t$, $t$vendor_spec$t$, $t$Arvia Technology 染色排水の事例（色度1,755→472、滞留約5.4分、薬品なし・汚泥なし）$t$, $t$https://arviatechnology.com/about/case-studies/case-study-removal-of-chemical-dye-from-textile-wastewater/$t$, $t$金属は対象外$t$, false, null, 1009, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_020_01$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$色素を分解できる$t$, $t$SolvioraX$t$, null, null, $t$様々な着色廃液を透明化（ラボ）$t$, null, $t$excellent$t$, null, $t$2026-09-14$t$, $t$medium$t$, $t$measurement$t$, $t$SolvioraX 研究チームの実験結果（ラボ、2026年9月時点）／事業概要 v1.7（2026-09-06、モデル色素の分解）$t$, null, $t$モデル色素は15分で濃度が半分$t$, false, null, 2001, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_020_02$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$色素を分解できる$t$, $t$ガルデリア（日本）$t$, null, null, $t$対象外$t$, null, $t$na$t$, null, $t$2026-06-05$t$, $t$high$t$, $t$vendor_spec$t$, $t$ガルデリア プレスリリース 2026-06-05（柿原工業でパラジウム回収を商用導入）$t$, $t$https://prtimes.jp/main/html/rd/p/000000005.000183076.html$t$, $t$貴金属の回収$t$, false, null, 2002, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_020_03$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$色素を分解できる$t$, $t$Allonnia（米国）$t$, null, null, $t$対象外$t$, null, $t$na$t$, null, null, $t$medium$t$, $t$vendor_spec$t$, $t$Allonnia RE-Cover（改変したタンパク質でレアアースを選んで結合、ラボで回収率90%超、モンタナにパイロット地点）$t$, $t$https://allonnia.com/re-cover/$t$, $t$レアアースの回収$t$, false, null, 2003, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_020_04$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$色素を分解できる$t$, $t$Paques（オランダ）$t$, null, null, $t$対象外$t$, null, $t$na$t$, null, null, $t$high$t$, $t$vendor_spec$t$, $t$Paques THIOTEQ Metal 製品ページ（微生物がつくる硫化物で金属を沈める、0〜80℃、高純度の金属硫化物）$t$, $t$https://www.paquesglobal.com/products/thioteq-metal$t$, $t$金属の回収$t$, false, null, 2004, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_020_05$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$色素を分解できる$t$, $t$Mint Innovation（ニュージーランド）$t$, null, null, $t$対象外$t$, null, $t$na$t$, null, null, $t$medium$t$, $t$vendor_spec$t$, $t$Mint Innovation 技術の説明（電子基板、金に結合するバイオマス、高純度の銅・商品グレードの金、シドニーで稼働）$t$, $t$https://www.mint.bio/technology$t$, $t$金属の回収$t$, false, null, 2005, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_020_06$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$色素を分解できる$t$, $t$ElectraMet（米国）$t$, null, null, $t$対象外$t$, null, $t$na$t$, null, null, $t$medium$t$, $t$vendor_spec$t$, $t$ElectraMet 会社サイト（半導体の排水、金属を含む汚泥を作らない、銅・銀・金・白金族）$t$, $t$https://electramet.com/$t$, $t$金属の回収$t$, false, null, 2006, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_020_07$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$色素を分解できる$t$, $t$パナソニック環境エンジニアリング（日本）$t$, null, null, $t$対象外$t$, null, $t$na$t$, null, $t$2026-07-21$t$, $t$high$t$, $t$vendor_spec$t$, $t$パナソニック環境エンジニアリング プレスリリース 2026-07-21（RARELOOP を2026年4月に発売、エッチング廃液の銅を電解で固形の金属に）$t$, $t$https://news.panasonic.com/jp/press/jn260721-1$t$, $t$金属の回収$t$, false, null, 2007, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_020_08$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$色素を分解できる$t$, $t$ディーピーエス（日本）$t$, null, null, $t$対象外$t$, null, $t$na$t$, null, null, $t$medium$t$, $t$vendor_spec$t$, $t$ディーピーエス 会社概要（多孔質シリカ粒子 DualPore、リサイクル用の金属スカベンジャーで貴金属・レアメタルを回収）$t$, $t$https://www.dps-inc.co.jp/company/$t$, $t$金属の回収$t$, false, null, 2008, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_020_09$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$色素を分解できる$t$, $t$Arvia Technology（英国）$t$, null, null, $t$色度1,755→472（染色排水）$t$, null, $t$excellent$t$, null, null, $t$high$t$, $t$vendor_spec$t$, $t$Arvia Technology 染色排水の事例（色度1,755→472、滞留約5.4分、薬品なし・汚泥なし）$t$, $t$https://arviatechnology.com/about/case-studies/case-study-removal-of-chemical-dye-from-textile-wastewater/$t$, $t$電気の酸化で分解する$t$, false, null, 2009, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_030_01$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$取れる金属の種類$t$, $t$SolvioraX$t$, null, null, $t$銅・ニッケル・鉄・鉛・Dy・Nd$t$, null, $t$excellent$t$, null, $t$2026-09-06$t$, $t$medium$t$, $t$measurement$t$, $t$SolvioraX 研究チームの速報（2026-07-10、Dy・Nd・鉛の取り込み）$t$, null, $t$重金属とレアアース。鉛・Dy・Ndは速報$t$, false, null, 3001, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_030_02$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$取れる金属の種類$t$, $t$ガルデリア（日本）$t$, null, null, $t$パラジウム・金など$t$, null, $t$good$t$, null, $t$2026-06-05$t$, $t$high$t$, $t$vendor_spec$t$, $t$ガルデリア プレスリリース 2026-06-05（パラジウム回収を商用導入、金・白金・ルテニウム・イリジウムへ展開）$t$, $t$https://prtimes.jp/main/html/rd/p/000000005.000183076.html$t$, $t$パラジウムは商用。白金族へ展開$t$, false, null, 3002, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_030_03$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$取れる金属の種類$t$, $t$Allonnia（米国）$t$, null, null, $t$レアアース（Nd・Pr・Yなど）$t$, null, $t$good$t$, null, null, $t$medium$t$, $t$vendor_spec$t$, $t$Allonnia RE-Cover（改変したタンパク質でレアアースを選んで結合、ラボで回収率90%超、モンタナにパイロット地点）$t$, $t$https://allonnia.com/re-cover/$t$, $t$ラボで回収率90%超$t$, false, null, 3003, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_030_04$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$取れる金属の種類$t$, $t$Paques（オランダ）$t$, null, null, $t$銅・亜鉛など$t$, null, $t$good$t$, null, null, $t$high$t$, $t$vendor_spec$t$, $t$Paques 鉱山向けの水処理（プエブロビエホ金鉱山で銅を年1万t超、Nyrstar Budel の亜鉛精錬所で亜鉛 年約300t）$t$, $t$https://www.paquesglobal.com/sector/water-treatment-for-mining$t$, $t$金鉱山で銅を年1万t超$t$, false, null, 3004, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_030_05$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$取れる金属の種類$t$, $t$Mint Innovation（ニュージーランド）$t$, null, null, $t$金・銀・銅・白金・パラジウムなど$t$, null, $t$good$t$, null, null, $t$medium$t$, $t$vendor_spec$t$, $t$Mint Innovation 技術の説明（金に結合するバイオマス、金・銅・銀・白金・パラジウムなど）$t$, $t$https://www.mint.bio/technology$t$, $t$電子基板から$t$, false, null, 3005, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_030_06$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$取れる金属の種類$t$, $t$ElectraMet（米国）$t$, null, null, $t$銅・銀・金・白金族$t$, null, $t$good$t$, null, null, $t$medium$t$, $t$vendor_spec$t$, $t$ElectraMet 会社サイト（半導体の排水、金属を含む汚泥を作らない、銅・銀・金・白金族）$t$, $t$https://electramet.com/$t$, null, false, null, 3006, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_030_07$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$取れる金属の種類$t$, $t$パナソニック環境エンジニアリング（日本）$t$, null, null, $t$銅$t$, null, $t$fair$t$, null, $t$2026-07-21$t$, $t$high$t$, $t$vendor_spec$t$, $t$パナソニック環境エンジニアリング プレスリリース 2026-07-21（RARELOOP を2026年4月に発売、エッチング廃液の銅を電解で固形の金属に）$t$, $t$https://news.panasonic.com/jp/press/jn260721-1$t$, $t$銀・スズ・ニッケルは今後$t$, false, null, 3007, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_030_08$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$取れる金属の種類$t$, $t$ディーピーエス（日本）$t$, null, null, $t$パラジウムなど貴金属・レアメタル$t$, null, $t$good$t$, null, null, $t$medium$t$, $t$vendor_spec$t$, $t$ディーピーエス 会社概要（多孔質シリカ粒子 DualPore、リサイクル用の金属スカベンジャーで貴金属・レアメタルを回収）$t$, $t$https://www.dps-inc.co.jp/company/$t$, null, false, null, 3008, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_030_09$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$取れる金属の種類$t$, $t$Arvia Technology（英国）$t$, null, null, $t$対象外$t$, null, $t$na$t$, null, null, $t$medium$t$, $t$vendor_spec$t$, $t$Arvia Technology 染色排水の事例（色度1,755→472、滞留約5.4分、薬品なし・汚泥なし）$t$, $t$https://arviatechnology.com/about/case-studies/case-study-removal-of-chemical-dye-from-textile-wastewater/$t$, null, false, null, 3009, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_040_01$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$熱い排水（45℃以上）をそのまま処理$t$, $t$SolvioraX$t$, null, null, $t$45〜70℃を好む$t$, null, $t$excellent$t$, null, $t$2026-09-06$t$, $t$high$t$, $t$manual$t$, $t$SolvioraX 事業概要 v1.7（2026-09-06）$t$, null, null, false, null, 4001, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_040_02$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$熱い排水（45℃以上）をそのまま処理$t$, $t$ガルデリア（日本）$t$, null, null, $t$公表なし$t$, null, $t$unknown$t$, null, null, $t$low$t$, $t$vendor_spec$t$, $t$創業手帳 谷本CEOインタビュー／Galdieria sulphuraria の生育温度の論文$t$, $t$https://sogyotecho.jp/galdieria-tanimoto-interview/$t$, $t$藻の生育の上限は56℃前後$t$, false, null, 4002, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_040_03$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$熱い排水（45℃以上）をそのまま処理$t$, $t$Allonnia（米国）$t$, null, null, $t$公開資料で未確認$t$, null, $t$unknown$t$, null, null, $t$low$t$, $t$vendor_spec$t$, $t$Allonnia RE-Cover（改変したタンパク質でレアアースを選んで結合、ラボで回収率90%超、モンタナにパイロット地点）$t$, $t$https://allonnia.com/re-cover/$t$, null, false, null, 4003, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_040_04$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$熱い排水（45℃以上）をそのまま処理$t$, $t$Paques（オランダ）$t$, null, null, $t$0〜80℃で運転$t$, null, $t$good$t$, null, null, $t$high$t$, $t$vendor_spec$t$, $t$Paques THIOTEQ Metal 製品ページ（微生物がつくる硫化物で金属を沈める、0〜80℃、高純度の金属硫化物）$t$, $t$https://www.paquesglobal.com/products/thioteq-metal$t$, null, false, null, 4004, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_040_05$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$熱い排水（45℃以上）をそのまま処理$t$, $t$Mint Innovation（ニュージーランド）$t$, null, null, $t$公開資料で未確認$t$, null, $t$unknown$t$, null, null, $t$low$t$, $t$vendor_spec$t$, $t$Mint Innovation 技術の説明（電子基板、金に結合するバイオマス、高純度の銅・商品グレードの金、シドニーで稼働）$t$, $t$https://www.mint.bio/technology$t$, null, false, null, 4005, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_040_06$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$熱い排水（45℃以上）をそのまま処理$t$, $t$ElectraMet（米国）$t$, null, null, $t$公開資料で未確認$t$, null, $t$unknown$t$, null, null, $t$low$t$, $t$vendor_spec$t$, $t$ElectraMet 半導体の銅CMP排水の事例（銅5〜35ppm、1年以上の連続運転で基準2.07ppm未満、高純度の銅板で回収）$t$, $t$https://electramet.com/case-study/cmp-wastewater-copper-removal-and-recovery/$t$, null, false, null, 4006, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_040_07$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$熱い排水（45℃以上）をそのまま処理$t$, $t$パナソニック環境エンジニアリング（日本）$t$, null, null, $t$公開資料で未確認$t$, null, $t$unknown$t$, null, null, $t$low$t$, $t$vendor_spec$t$, $t$パナソニック環境エンジニアリング プレスリリース 2026-07-21（RARELOOP を2026年4月に発売、エッチング廃液の銅を電解で固形の金属に）$t$, $t$https://news.panasonic.com/jp/press/jn260721-1$t$, null, false, null, 4007, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_040_08$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$熱い排水（45℃以上）をそのまま処理$t$, $t$ディーピーエス（日本）$t$, null, null, $t$公開資料で未確認$t$, null, $t$unknown$t$, null, null, $t$low$t$, $t$vendor_spec$t$, $t$ディーピーエス 2022-03-03（京都大学イノベーションキャピタルが出資、量産体制を構築、数ppmのパラジウムを高純度で回収）$t$, $t$https://www.dps-inc.co.jp/2619/$t$, null, false, null, 4008, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_040_09$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$熱い排水（45℃以上）をそのまま処理$t$, $t$Arvia Technology（英国）$t$, null, null, $t$公開資料で未確認$t$, null, $t$unknown$t$, null, null, $t$low$t$, $t$vendor_spec$t$, $t$Arvia Technology 染色排水の事例（色度1,755→472、滞留約5.4分、薬品なし・汚泥なし）$t$, $t$https://arviatechnology.com/about/case-studies/case-study-removal-of-chemical-dye-from-textile-wastewater/$t$, null, false, null, 4009, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_050_01$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$狙う液$t$, $t$SolvioraX$t$, null, null, $t$色のついた排水と、金属を含む排水$t$, null, null, null, $t$2026-09-06$t$, $t$high$t$, $t$manual$t$, $t$SolvioraX 事業概要 v1.7（2026-09-06）$t$, null, $t$染色・食品・めっき・磁石など$t$, false, null, 5001, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_050_02$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$狙う液$t$, $t$ガルデリア（日本）$t$, null, null, $t$めっきの洗浄水（強い酸性・貴金属がごく薄い）$t$, null, null, null, $t$2026-06-05$t$, $t$high$t$, $t$vendor_spec$t$, $t$ガルデリア プレスリリース 2026-06-05（柿原工業でパラジウム回収を商用導入）$t$, $t$https://prtimes.jp/main/html/rd/p/000000005.000183076.html$t$, null, false, null, 5002, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_050_03$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$狙う液$t$, $t$Allonnia（米国）$t$, null, null, $t$石炭灰の浸出液・鉱山の排水など$t$, null, null, null, null, $t$medium$t$, $t$vendor_spec$t$, $t$Allonnia RE-Cover（改変したタンパク質でレアアースを選んで結合、ラボで回収率90%超、モンタナにパイロット地点）$t$, $t$https://allonnia.com/re-cover/$t$, $t$レアアース$t$, false, null, 5003, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_050_04$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$狙う液$t$, $t$Paques（オランダ）$t$, null, null, $t$鉱山・製錬所の酸性の排水$t$, null, null, null, null, $t$high$t$, $t$vendor_spec$t$, $t$Paques 鉱山向けの水処理（プエブロビエホ金鉱山で銅を年1万t超、Nyrstar Budel の亜鉛精錬所で亜鉛 年約300t）$t$, $t$https://www.paquesglobal.com/sector/water-treatment-for-mining$t$, null, false, null, 5004, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_050_05$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$狙う液$t$, $t$Mint Innovation（ニュージーランド）$t$, null, null, $t$電子基板を溶かした液$t$, null, null, null, null, $t$high$t$, $t$vendor_spec$t$, $t$Mint Innovation 技術の説明（電子基板、金に結合するバイオマス、高純度の銅・商品グレードの金、シドニーで稼働）$t$, $t$https://www.mint.bio/technology$t$, null, false, null, 5005, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_050_06$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$狙う液$t$, $t$ElectraMet（米国）$t$, null, null, $t$半導体工場の研磨の排水$t$, null, null, null, null, $t$high$t$, $t$vendor_spec$t$, $t$ElectraMet 半導体の銅CMP排水の事例（銅5〜35ppm、1年以上の連続運転で基準2.07ppm未満、高純度の銅板で回収）$t$, $t$https://electramet.com/case-study/cmp-wastewater-copper-removal-and-recovery/$t$, $t$銅$t$, false, null, 5006, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_050_07$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$狙う液$t$, $t$パナソニック環境エンジニアリング（日本）$t$, null, null, $t$半導体・電子デバイス工場のエッチング廃液$t$, null, null, null, $t$2026-07-21$t$, $t$high$t$, $t$vendor_spec$t$, $t$パナソニック環境エンジニアリング プレスリリース 2026-07-21（RARELOOP を2026年4月に発売、エッチング廃液の銅を電解で固形の金属に）$t$, $t$https://news.panasonic.com/jp/press/jn260721-1$t$, $t$銅$t$, false, null, 5007, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_050_08$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$狙う液$t$, $t$ディーピーエス（日本）$t$, null, null, $t$触媒・めっき製造の液$t$, null, null, null, $t$2022-03-03$t$, $t$medium$t$, $t$vendor_spec$t$, $t$ディーピーエス 2022-03-03（京都大学イノベーションキャピタルが出資、量産体制を構築、数ppmのパラジウムを高純度で回収）$t$, $t$https://www.dps-inc.co.jp/2619/$t$, $t$パラジウム$t$, false, null, 5008, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_050_09$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$狙う液$t$, $t$Arvia Technology（英国）$t$, null, null, $t$染色などの工場排水$t$, null, null, null, null, $t$medium$t$, $t$vendor_spec$t$, $t$Arvia Technology 染色排水の事例（色度1,755→472、滞留約5.4分、薬品なし・汚泥なし）$t$, $t$https://arviatechnology.com/about/case-studies/case-study-removal-of-chemical-dye-from-textile-wastewater/$t$, $t$色・有機物$t$, false, null, 5009, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_060_01$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$段階$t$, $t$SolvioraX$t$, null, null, $t$ラボで再現性を確認（TRL4）$t$, null, null, null, $t$2026-09-06$t$, $t$high$t$, $t$manual$t$, $t$SolvioraX 事業概要 v1.7（2026-09-06）$t$, null, $t$2027年3月までに顧客に近い環境で実証$t$, false, null, 6001, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_060_02$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$段階$t$, $t$ガルデリア（日本）$t$, null, null, $t$商用導入1件（2026年6月）$t$, null, null, null, $t$2026-06-05$t$, $t$high$t$, $t$vendor_spec$t$, $t$ガルデリア プレスリリース 2026-06-05（柿原工業で商用導入）／日本経済新聞 2025-02-28（4億円を調達）$t$, $t$https://prtimes.jp/main/html/rd/p/000000005.000183076.html$t$, $t$2025年2月に4億円を調達$t$, false, null, 6002, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_060_03$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$段階$t$, $t$Allonnia（米国）$t$, null, null, $t$レアアースはパイロットの準備$t$, null, null, null, $t$2025-12-10$t$, $t$medium$t$, $t$vendor_spec$t$, $t$Allonnia 2025-12-10（シリーズAの追加で2,000万ドル超・累計1億ドル超、イーグル鉱山で実地運転を開始）$t$, $t$https://allonnia.com/allonnia-raises-more-than-20-million-to-accelerate-deployment-of-critical-materials-biotechnology/$t$, $t$別の技術はニッケル鉱山で実地運転。累計1億ドル超$t$, false, null, 6003, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_060_04$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$段階$t$, $t$Paques（オランダ）$t$, null, null, $t$商用（鉱山・製錬所）$t$, null, null, null, null, $t$high$t$, $t$vendor_spec$t$, $t$Paques 鉱山向けの水処理（プエブロビエホ金鉱山で銅を年1万t超、Nyrstar Budel の亜鉛精錬所で亜鉛 年約300t）$t$, $t$https://www.paquesglobal.com/sector/water-treatment-for-mining$t$, null, false, null, 6004, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_060_05$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$段階$t$, $t$Mint Innovation（ニュージーランド）$t$, null, null, $t$シドニーで稼働（2022年〜）$t$, null, null, null, $t$2023-02-16$t$, $t$medium$t$, $t$vendor_spec$t$, $t$Mint Innovation シリーズC（6,000万NZドル）$t$, $t$https://www.mint.bio/news-and-press/mint-innovation-closes-60m-in-series-c-capital-raise$t$, $t$2023年に6,000万NZドルを調達$t$, false, null, 6005, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_060_06$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$段階$t$, $t$ElectraMet（米国）$t$, null, null, $t$半導体工場で1年以上の連続運転$t$, null, null, null, null, $t$high$t$, $t$vendor_spec$t$, $t$ElectraMet 半導体の銅CMP排水の事例（銅5〜35ppm、1年以上の連続運転で基準2.07ppm未満、高純度の銅板で回収）$t$, $t$https://electramet.com/case-study/cmp-wastewater-copper-removal-and-recovery/$t$, null, false, null, 6006, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_060_07$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$段階$t$, $t$パナソニック環境エンジニアリング（日本）$t$, null, null, $t$2026年4月に発売$t$, null, null, null, $t$2026-07-21$t$, $t$high$t$, $t$vendor_spec$t$, $t$パナソニック環境エンジニアリング プレスリリース 2026-07-21（RARELOOP を2026年4月に発売、エッチング廃液の銅を電解で固形の金属に）$t$, $t$https://news.panasonic.com/jp/press/jn260721-1$t$, $t$7月に排水処理・資源回収の事業を開始$t$, false, null, 6007, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_060_08$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$段階$t$, $t$ディーピーエス（日本）$t$, null, null, $t$量産体制を構築（2022年）$t$, null, null, null, $t$2022-03-03$t$, $t$medium$t$, $t$vendor_spec$t$, $t$ディーピーエス 2022-03-03（京都大学イノベーションキャピタルが出資、量産体制を構築、数ppmのパラジウムを高純度で回収）$t$, $t$https://www.dps-inc.co.jp/2619/$t$, $t$京都大学イノベーションキャピタルが出資$t$, false, null, 6008, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpco_060_09$t$, $t$ptt_sx_compare$t$, $t$p21$t$, $t$段階$t$, $t$Arvia Technology（英国）$t$, null, null, $t$染色排水で現場の試験$t$, null, null, null, null, $t$medium$t$, $t$vendor_spec$t$, $t$Arvia Technology 染色排水の事例（色度1,755→472、滞留約5.4分、薬品なし・汚泥なし）$t$, $t$https://arviatechnology.com/about/case-studies/case-study-removal-of-chemical-dye-from-textile-wastewater/$t$, null, false, null, 6009, $t$amie$t$, $t$amie$t$);
delete from project_tech_entries where project_id = $t$p21$t$ and tech_topic_id = $t$ptt_sx_compare_methods$t$;
update project_tech_topics set block_kind = $t$matrix$t$, title = $t$既存の方式との星取り表 — 工場でいま使われている排水処理$t$, summary = $t$SolvioraX を、工場の排水処理でいま使われている5つの方式（凝集沈殿・イオン交換・キレート樹脂・オゾン・フェントン酸化・活性炭・活性汚泥）と比べる。2026年9月時点。$t$, body_md = $t$**比べる相手** — 工場の排水処理でいま使われている方式。金属を含む排水には凝集沈殿とイオン交換・キレート樹脂、色のついた排水には凝集沈殿と活性汚泥が標準で、色が残るときにオゾン・フェントン酸化や活性炭を足す。SolvioraX は、これらの設備に足す形で入る。活性汚泥も生きた微生物を使うが、役目は有機物の分解で、金属は取らない。新しい技術の会社との比較は、ひとつ前の「競合の会社との星取り表」。

**記号の付け方**

| 観点 | ◎ | ○ | △ | × | — |
|---|---|---|---|---|---|
| 生きた細胞が金属を取り込む | 生きた細胞が、金属を細胞の中へ取り込む | 生きた微生物を使い、微生物がつくる物質で金属を沈める | 生きものからつくった材料・物質に、金属を付ける | （使わない） | 生きものを使わない、または金属を取る方式ではない |
| 色素を分解できる | 色素を分解して消す | 分解はしないが、吸着などで取り除く | 染料の種類や条件で効きにくい | 色素は分解されにくい | 色は対象外 |
| 熱い排水（45℃以上）をそのまま処理 | 45℃以上がむしろ向く | そのまま使える | 一部の温度でだけ確認 | 冷ます必要がある | （使わない） |
| 取った金属を資源に戻す | 金属のまま高純度で取り出す | 資源として取り出す・売る | 取り出すには別の工程が要る | 汚泥・廃棄物になる | 金属の回収には使わない |
| 汚泥・廃棄物が少ない | ほぼ出ない | 使い終わった材料だけ・売れる形で出る | 使い終わった材料や薬品の汚泥が出る | 汚泥が多い | （使わない） |

「?」は公開資料で確認できないところ。「段階」の行は記号を付けず、事実を並べた。

**時点と範囲** — 2026年9月時点の公開情報と、SolvioraX の実験結果（ラボ）。費用は液の種類と規模で大きく変わるため、この表では比べていない。$t$, tech_domain = $t$競合比較$t$, sort_order = 81, confidentiality = $t$public$t$, source_kind = $t$manual$t$, source_ref = $t$2026-09 公開情報の調査（出典はマスごと）／SolvioraX 事業概要 v1.7（2026-09-06）・研究チームの実験結果$t$, source_url = null, needs_check = false, check_reason = null, updated_by = $t$amie$t$, updated_at = now() where tech_topic_id = $t$ptt_sx_compare_methods$t$ and project_id = $t$p21$t$;
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_010_01$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$生きた細胞が金属を取り込む$t$, $t$SolvioraX$t$, null, null, $t$生きた細胞が細胞の中へ取り込む$t$, null, $t$excellent$t$, null, $t$2026-09-14$t$, $t$high$t$, $t$manual$t$, $t$SolvioraX 事業概要 v1.7（2026-09-06）／研究チームの報告（2026-09-02、取り込みを強めた株）$t$, null, $t$好熱性シアノバクテリア。取り込みを強めた株もある$t$, false, null, 1001, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_010_02$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$生きた細胞が金属を取り込む$t$, $t$凝集沈殿$t$, null, null, $t$薬品で固めて沈める$t$, null, $t$na$t$, null, null, $t$high$t$, $t$literature$t$, $t$栗田工業 水処理の基礎「重金属の処理」$t$, $t$https://kcr.kurita.co.jp/solutions/water-school/018.html$t$, $t$金属は水酸化物の汚泥になる$t$, false, null, 1002, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_010_03$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$生きた細胞が金属を取り込む$t$, $t$イオン交換・キレート樹脂$t$, null, null, $t$樹脂に金属イオンを結合させる$t$, null, $t$na$t$, null, null, $t$high$t$, $t$vendor_spec$t$, $t$ピュロライト キレート樹脂の製品説明$t$, $t$https://www.purolite.co.jp/products/chelation-resins$t$, $t$酸で外して樹脂を再生$t$, false, null, 1003, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_010_04$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$生きた細胞が金属を取り込む$t$, $t$オゾン・フェントン酸化$t$, null, null, $t$強い酸化力で色素を壊す$t$, null, $t$na$t$, null, null, $t$high$t$, $t$literature$t$, $t$埼玉県公害センター年報 11号（1984）オゾンによる染色排水の脱色$t$, $t$https://www.pref.saitama.lg.jp/documents/21791/15444.pdf$t$, $t$金属は対象外$t$, false, null, 1004, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_010_05$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$生きた細胞が金属を取り込む$t$, $t$活性炭$t$, null, null, $t$炭の細かい穴に吸着$t$, null, $t$na$t$, null, null, $t$high$t$, $t$literature$t$, $t$有機合成化学協会誌 33巻5号（1975）染色排水の処理 表4・表5・表7$t$, $t$https://www.jstage.jst.go.jp/article/yukigoseikyokaishi1943/33/5/33_5_377$t$, null, false, null, 1005, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_010_06$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$生きた細胞が金属を取り込む$t$, $t$活性汚泥$t$, null, null, $t$生きた微生物が有機物を分解$t$, null, $t$na$t$, null, null, $t$high$t$, $t$literature$t$, $t$栗田工業 水処理の基礎「活性汚泥法」$t$, $t$https://kcr.kurita.co.jp/solutions/water-school/016.html$t$, $t$金属を取る方式ではない$t$, false, null, 1006, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_020_01$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$色素を分解できる$t$, $t$SolvioraX$t$, null, null, $t$様々な着色廃液を透明化（ラボ）$t$, null, $t$excellent$t$, null, $t$2026-09-14$t$, $t$medium$t$, $t$measurement$t$, $t$SolvioraX 研究チームの実験結果（ラボ、2026年9月時点）／事業概要 v1.7（2026-09-06、モデル色素の分解）$t$, null, $t$モデル色素は15分で濃度が半分$t$, false, null, 2001, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_020_02$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$色素を分解できる$t$, $t$凝集沈殿$t$, null, null, $t$脱色率50〜91%$t$, null, $t$fair$t$, null, null, $t$high$t$, $t$literature$t$, $t$有機合成化学協会誌 33巻5号（1975）染色排水の処理 表4・表5・表7$t$, $t$https://www.jstage.jst.go.jp/article/yukigoseikyokaishi1943/33/5/33_5_377$t$, $t$染料の種類で効きにくいものがある$t$, false, null, 2002, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_020_03$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$色素を分解できる$t$, $t$イオン交換・キレート樹脂$t$, null, null, $t$対象外$t$, null, $t$na$t$, null, null, $t$high$t$, $t$vendor_spec$t$, $t$ピュロライト キレート樹脂の製品説明$t$, $t$https://www.purolite.co.jp/products/chelation-resins$t$, $t$金属イオン向け$t$, false, null, 2003, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_020_04$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$色素を分解できる$t$, $t$オゾン・フェントン酸化$t$, null, null, $t$反応染料を99.5%脱色$t$, null, $t$excellent$t$, null, null, $t$medium$t$, $t$literature$t$, $t$埼玉県公害センター年報 11号（1984）オゾンによる染色排水の脱色$t$, $t$https://www.pref.saitama.lg.jp/documents/21791/15444.pdf$t$, $t$分散染料は65%。実際の排水では効率が落ちる$t$, false, null, 2004, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_020_05$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$色素を分解できる$t$, $t$活性炭$t$, null, null, $t$吸着して取り除く$t$, null, $t$good$t$, null, null, $t$medium$t$, $t$literature$t$, $t$有機合成化学協会誌 33巻5号（1975）染色排水の処理 表4・表5・表7$t$, $t$https://www.jstage.jst.go.jp/article/yukigoseikyokaishi1943/33/5/33_5_377$t$, $t$のり剤・助剤で吸着力が落ちる$t$, false, null, 2005, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_020_06$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$色素を分解できる$t$, $t$活性汚泥$t$, null, null, $t$染料は分解されにくい$t$, null, $t$poor$t$, null, null, $t$medium$t$, $t$literature$t$, $t$水環境学会誌 23巻5号（1994）染色排水の色$t$, $t$https://www.jstage.jst.go.jp/article/jriet1972/23/5/23_5_281$t$, $t$凝集沈殿と組み合わせる$t$, false, null, 2006, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_030_01$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$熱い排水（45℃以上）をそのまま処理$t$, $t$SolvioraX$t$, null, null, $t$45〜70℃を好む$t$, null, $t$excellent$t$, null, $t$2026-09-06$t$, $t$high$t$, $t$manual$t$, $t$SolvioraX 事業概要 v1.7（2026-09-06）$t$, null, null, false, null, 3001, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_030_02$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$熱い排水（45℃以上）をそのまま処理$t$, $t$凝集沈殿$t$, null, null, $t$公開資料で未確認$t$, null, $t$unknown$t$, null, null, $t$low$t$, $t$literature$t$, $t$栗田工業 水処理の基礎「重金属の処理」$t$, $t$https://kcr.kurita.co.jp/solutions/water-school/018.html$t$, null, false, null, 3002, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_030_03$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$熱い排水（45℃以上）をそのまま処理$t$, $t$イオン交換・キレート樹脂$t$, null, null, $t$80℃まで使える$t$, null, $t$good$t$, null, null, $t$high$t$, $t$vendor_spec$t$, $t$Purolite S930Plus 製品データシート（イミノジ酢酸型キレート樹脂、使用温度の上限80℃）$t$, $t$https://www.purolite.com/product-pdf/S930PLUS.pdf$t$, $t$キレート樹脂の製品仕様の例$t$, false, null, 3003, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_030_04$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$熱い排水（45℃以上）をそのまま処理$t$, $t$オゾン・フェントン酸化$t$, null, null, $t$13〜35℃で確認$t$, null, $t$fair$t$, null, null, $t$low$t$, $t$literature$t$, $t$宮崎県工業技術センター 研究報告（2012）マイクロバブルオゾンによる消化液の脱色$t$, $t$https://www.iri.pref.miyazaki.jp/pdf/H24/2012-13.pdf$t$, $t$オゾン。それより高い温度は未確認$t$, false, null, 3004, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_030_05$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$熱い排水（45℃以上）をそのまま処理$t$, $t$活性炭$t$, null, null, $t$43℃での実測例$t$, null, $t$fair$t$, null, null, $t$low$t$, $t$literature$t$, $t$有機合成化学協会誌 33巻5号（1975）染色排水の処理 表4・表5・表7$t$, $t$https://www.jstage.jst.go.jp/article/yukigoseikyokaishi1943/33/5/33_5_377$t$, $t$1975年の1例$t$, false, null, 3005, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_030_06$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$熱い排水（45℃以上）をそのまま処理$t$, $t$活性汚泥$t$, null, null, $t$適温は20〜37℃$t$, null, $t$poor$t$, null, null, $t$medium$t$, $t$literature$t$, $t$スイレイ 技術ブログ（2025-10）活性汚泥法$t$, $t$https://www.suirei.co.jp/blog/2025/10/activated-sludge-method/$t$, $t$冷ます必要がある$t$, false, null, 3006, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_040_01$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$取った金属を資源に戻す$t$, $t$SolvioraX$t$, null, null, $t$菌体を溶かして金属を取り出す$t$, null, $t$good$t$, null, $t$2026-09-06$t$, $t$medium$t$, $t$manual$t$, $t$SolvioraX 事業概要 v1.7（2026-09-06）$t$, null, $t$分離・精製して売る計画$t$, false, null, 4001, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_040_02$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$取った金属を資源に戻す$t$, $t$凝集沈殿$t$, null, null, $t$汚泥に混ざる$t$, null, $t$poor$t$, null, null, $t$high$t$, $t$literature$t$, $t$栗田工業 水処理の基礎「重金属の処理」$t$, $t$https://kcr.kurita.co.jp/solutions/water-school/018.html$t$, $t$産業廃棄物になる$t$, false, null, 4002, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_040_03$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$取った金属を資源に戻す$t$, $t$イオン交換・キレート樹脂$t$, null, null, $t$酸で外して濃縮液にする$t$, null, $t$good$t$, null, null, $t$medium$t$, $t$vendor_spec$t$, $t$ピュロライト キレート樹脂の製品説明$t$, $t$https://www.purolite.co.jp/products/chelation-resins$t$, null, false, null, 4003, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_040_04$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$取った金属を資源に戻す$t$, $t$オゾン・フェントン酸化$t$, null, null, $t$対象外$t$, null, $t$na$t$, null, null, $t$medium$t$, $t$literature$t$, $t$埼玉県公害センター年報 11号（1984）オゾンによる染色排水の脱色$t$, $t$https://www.pref.saitama.lg.jp/documents/21791/15444.pdf$t$, null, false, null, 4004, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_040_05$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$取った金属を資源に戻す$t$, $t$活性炭$t$, null, null, $t$回収には使わない$t$, null, $t$na$t$, null, null, $t$low$t$, $t$literature$t$, $t$栗田工業 水処理の基礎「吸着」$t$, $t$https://kcr.kurita.co.jp/solutions/water-school/060.html$t$, null, false, null, 4005, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_040_06$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$取った金属を資源に戻す$t$, $t$活性汚泥$t$, null, null, $t$対象外$t$, null, $t$na$t$, null, null, $t$medium$t$, $t$literature$t$, $t$栗田工業 水処理の基礎「活性汚泥法」$t$, $t$https://kcr.kurita.co.jp/solutions/water-school/016.html$t$, null, false, null, 4006, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_050_01$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$汚泥・廃棄物が少ない$t$, $t$SolvioraX$t$, null, null, $t$薬品の汚泥が出ない$t$, null, $t$good$t$, null, $t$2026-09-06$t$, $t$medium$t$, $t$manual$t$, $t$SolvioraX 事業概要 v1.7（2026-09-06）$t$, null, $t$残るのは使い終わった菌体$t$, false, null, 5001, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_050_02$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$汚泥・廃棄物が少ない$t$, $t$凝集沈殿$t$, null, null, $t$汚泥0.5〜2.5kg/m³$t$, null, $t$poor$t$, null, null, $t$medium$t$, $t$meeting$t$, $t$水処理の市場ヒアリングの整理（2026-07-29、SolvioraX）$t$, null, null, false, null, 5002, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_050_03$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$汚泥・廃棄物が少ない$t$, $t$イオン交換・キレート樹脂$t$, null, null, $t$再生の廃液と使い終わった樹脂$t$, null, $t$fair$t$, null, null, $t$medium$t$, $t$vendor_spec$t$, $t$ピュロライト キレート樹脂の製品説明$t$, $t$https://www.purolite.co.jp/products/chelation-resins$t$, null, false, null, 5003, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_050_04$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$汚泥・廃棄物が少ない$t$, $t$オゾン・フェントン酸化$t$, null, null, $t$フェントンは鉄の汚泥$t$, null, $t$fair$t$, null, null, $t$medium$t$, $t$literature$t$, $t$畜産環境整備機構 資料（畜産排水の脱色処理の実証。フェントン・活性炭の費用）$t$, $t$https://www.leio.or.jp/pub_train/publication/tkj/tkj23/shingi1_a23.pdf$t$, $t$オゾンは汚泥が少ない$t$, false, null, 5004, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_050_05$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$汚泥・廃棄物が少ない$t$, $t$活性炭$t$, null, null, $t$使い終わった活性炭$t$, null, $t$fair$t$, null, null, $t$medium$t$, $t$literature$t$, $t$有機合成化学協会誌 33巻5号（1975）染色排水の処理 表4・表5・表7$t$, $t$https://www.jstage.jst.go.jp/article/yukigoseikyokaishi1943/33/5/33_5_377$t$, null, false, null, 5005, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_050_06$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$汚泥・廃棄物が少ない$t$, $t$活性汚泥$t$, null, null, $t$余剰汚泥$t$, null, $t$fair$t$, null, null, $t$medium$t$, $t$literature$t$, $t$栗田工業 水処理の基礎「活性汚泥法」$t$, $t$https://kcr.kurita.co.jp/solutions/water-school/016.html$t$, null, false, null, 5006, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_060_01$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$段階$t$, $t$SolvioraX$t$, null, null, $t$ラボで再現性を確認（TRL4）$t$, null, null, null, $t$2026-09-06$t$, $t$high$t$, $t$manual$t$, $t$SolvioraX 事業概要 v1.7（2026-09-06）$t$, null, $t$2027年3月までに顧客に近い環境で実証$t$, false, null, 6001, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_060_02$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$段階$t$, $t$凝集沈殿$t$, null, null, $t$最も普及$t$, null, null, null, null, $t$high$t$, $t$literature$t$, $t$愛知県産業技術研究所ニュース 2007年7月号（染色排水の処理）$t$, $t$https://www.aichi-inst.jp/other/up_docs/no64_03.pdf$t$, null, false, null, 6002, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_060_03$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$段階$t$, $t$イオン交換・キレート樹脂$t$, null, null, $t$めっき・半導体・貴金属回収で実用$t$, null, null, null, null, $t$medium$t$, $t$literature$t$, $t$ラボテック 技術記事（イオン交換樹脂の用途）$t$, $t$https://www.labotec.co.jp/news/1093-2-2-2-2-2-2-2-2-2/$t$, null, false, null, 6003, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_060_04$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$段階$t$, $t$オゾン・フェントン酸化$t$, null, null, $t$染色工場での導入例は見当たらない$t$, null, null, null, null, $t$medium$t$, $t$literature$t$, $t$大阪府立産業技術総合研究所 報告（2004）フェントン法による反応染料の脱色$t$, $t$https://orist.jp/dl/izumi/archive/shohou18/h2_shoho18.pdf$t$, null, false, null, 6004, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_060_05$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$段階$t$, $t$活性炭$t$, null, null, $t$仕上げとして普及$t$, null, null, null, null, $t$medium$t$, $t$literature$t$, $t$有機合成化学協会誌 33巻5号（1975）染色排水の処理 表4・表5・表7$t$, $t$https://www.jstage.jst.go.jp/article/yukigoseikyokaishi1943/33/5/33_5_377$t$, null, false, null, 6005, $t$amie$t$, $t$amie$t$);
insert into project_tech_entries (tech_entry_id, tech_topic_id, project_id, row_label, col_label, value_min, value_max, value_text, unit, rating, condition_text, observed_on, confidence, source_kind, source_ref, source_url, note, needs_check, check_reason, sort_order, created_by, updated_by) values ($t$pte_sx_cmpme_060_06$t$, $t$ptt_sx_compare_methods$t$, $t$p21$t$, $t$段階$t$, $t$活性汚泥$t$, null, null, $t$染色工場の標準$t$, null, null, null, null, $t$high$t$, $t$literature$t$, $t$愛知県産業技術研究所ニュース 2007年7月号（染色排水の処理）$t$, $t$https://www.aichi-inst.jp/other/up_docs/no64_03.pdf$t$, $t$凝集沈殿と組み合わせる$t$, false, null, 6006, $t$amie$t$, $t$amie$t$);
commit;
