-- 432: SOL（p21）の燃料のコスト試算に「脂質分泌株」のスイッチを置く（まさ 2026-09-14「脂質を分泌できる株の開発も理論的には可能っていう話を杉浦先生からもらったので、コスト試算表を「脂質分泌株」のスイッチオンオフで切り替えられるようにしてほしい。脂質分泌株だと一気にコストが下がりそうな気がしてる」）
--
--   - 明細・前提・作業の株に secreting（脂質分泌株）を足す（check 制約）
--   - 前提 lipid_secreting_strain「脂質分泌株」（value_text off）ほか10件を足す
--     （分泌速度・培養液からの回収率の3ケース、菌体の生産性、稼働日数、入れ替える菌体、分泌株の燃料化設備の処理量）
--   - 分泌株のときだけ効く明細13行・作業2行を足す（閉鎖系の追加・溶媒相・溶媒からの分離・脂肪酸の炭素のCO2）
--   - 菌体を集めて壊す形にしかない明細17行・作業2行を strain = 'wild' にする
--   - 版の履歴と注意の注記、確認事項2件を足す
-- 生成: apply432.py（scratchpad）。fixture を同じ定義から書き出した。
-- 書き換える行がこの migration を作った時点（2026-09-14）から変わっていたら、何もせずに止める。
begin;
select set_config('amd.cost_change_reason', '432: 燃料のコスト試算に脂質分泌株のスイッチを置く（まさ 2026-09-14）', true);
do $do$ begin
  if exists (select 1 from project_cost_assumptions where cost_model_id = 'cm_p21_fuel_260914' and role_key = 'lipid_secreting_strain') then raise exception '432: 脂質分泌株の前提がもうある'; end if;
  if exists (select 1 from project_cost_items where cost_model_id = 'cm_p21_fuel_260914' and strain is not null) then raise exception '432: 株を持つ明細がもうある'; end if;
  if (select pg_get_constraintdef(oid) from pg_constraint where conname = 'project_cost_items_strain_check') <> 'CHECK (((strain IS NULL) OR (strain = ANY (ARRAY[''enhanced''::text, ''wild''::text]))))' then raise exception '432: project_cost_items の株の制約が変わっている'; end if;
  if (select pg_get_constraintdef(oid) from pg_constraint where conname = 'project_cost_assumptions_strain_check') <> 'CHECK (((strain IS NULL) OR (strain = ANY (ARRAY[''enhanced''::text, ''wild''::text]))))' then raise exception '432: project_cost_assumptions の株の制約が変わっている'; end if;
  if (select pg_get_constraintdef(oid) from pg_constraint where conname = 'project_cost_tasks_strain_check') <> 'CHECK (((strain IS NULL) OR (strain = ANY (ARRAY[''enhanced''::text, ''wild''::text]))))' then raise exception '432: project_cost_tasks の株の制約が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_culture_057' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = 'ab37b250b3a43a7b51d1658c8a91f87b') then raise exception '432: 明細 cif_culture_057 が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_culture_058' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = '920c880fadf0f497f8b30503631c9eb4') then raise exception '432: 明細 cif_culture_058 が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_culture_059' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = '920c880fadf0f497f8b30503631c9eb4') then raise exception '432: 明細 cif_culture_059 が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_culture_060' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = '920c880fadf0f497f8b30503631c9eb4') then raise exception '432: 明細 cif_culture_060 が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_culture_127' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = 'f3c198d78bfa146e7270eb047cfdb6fd') then raise exception '432: 明細 cif_culture_127 が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_culture_128' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = '876a0f6bb29b7274e2ccff1c3500a86f') then raise exception '432: 明細 cif_culture_128 が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_plant_dewater' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = 'd5c1cf59e34bb03742029675fc1abe07') then raise exception '432: 明細 cif_plant_dewater が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_plant_disruption' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = '3fb9ff146a3357fef713dd0871beaf16') then raise exception '432: 明細 cif_plant_disruption が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_plant_extraction' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = '5b3f3989c442f884d2eddbf2a82bf5e6') then raise exception '432: 明細 cif_plant_extraction が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_plant_solvent_recovery' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = 'fe2df589d547428d7aef930b9b42f38d') then raise exception '432: 明細 cif_plant_solvent_recovery が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_plant_residue' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = '9cf6e902f16be69fa1a209f51fd2d91a') then raise exception '432: 明細 cif_plant_residue が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_plant_utility' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = 'e7050c4c1790689f53ce30519a50a547') then raise exception '432: 明細 cif_plant_utility が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_op_power' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = 'bd0729381f2db9212d6ddd4426dd6c8b') then raise exception '432: 明細 cif_op_power が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_op_heat' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = '8d7a928e04a9e4c1a9243d21b16c41c6') then raise exception '432: 明細 cif_op_heat が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_op_solvent' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = 'b3a8e0d313762d442f4c8fab98d3e8b9') then raise exception '432: 明細 cif_op_solvent が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_op_water' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = 'f677ca1444c8d4539b8efd6855a69798') then raise exception '432: 明細 cif_op_water が変わっている'; end if;
  if not exists (select 1 from project_cost_items where cost_item_id = 'cif_op_maintenance' and cost_model_id = 'cm_p21_fuel_260914' and strain is null and md5(note) = '1764be871b271c87d58ffaca71d74045') then raise exception '432: 明細 cif_op_maintenance が変わっている'; end if;
  if not exists (select 1 from project_cost_tasks where cost_task_id = 'ctf_culture_operation' and cost_model_id = 'cm_p21_fuel_260914' and strain is null) then raise exception '432: 作業 ctf_culture_operation が変わっている'; end if;
  if not exists (select 1 from project_cost_tasks where cost_task_id = 'ctf_plant_operation' and cost_model_id = 'cm_p21_fuel_260914' and strain is null) then raise exception '432: 作業 ctf_plant_operation が変わっている'; end if;
  if exists (select 1 from project_cost_notes where cost_note_id = 'cnf_history_secreting') then raise exception '432: 注記 cnf_history_secreting がもうある'; end if;
  if exists (select 1 from project_cost_notes where cost_note_id = 'cnf_caveat_secreting') then raise exception '432: 注記 cnf_caveat_secreting がもうある'; end if;
  if exists (select 1 from project_cost_questions where cost_question_id = 'cqf_secretion_rate') then raise exception '432: 確認事項 cqf_secretion_rate がもうある'; end if;
  if exists (select 1 from project_cost_questions where cost_question_id = 'cqf_secretion_recovery') then raise exception '432: 確認事項 cqf_secretion_recovery がもうある'; end if;
end $do$;

alter table project_cost_items drop constraint if exists project_cost_items_strain_check;
alter table project_cost_items add constraint project_cost_items_strain_check
  check (strain is null or strain in ('enhanced', 'wild', 'secreting'));
alter table project_cost_assumptions drop constraint if exists project_cost_assumptions_strain_check;
alter table project_cost_assumptions add constraint project_cost_assumptions_strain_check
  check (strain is null or strain in ('enhanced', 'wild', 'secreting'));
alter table project_cost_tasks drop constraint if exists project_cost_tasks_strain_check;
alter table project_cost_tasks add constraint project_cost_tasks_strain_check
  check (strain is null or strain in ('enhanced', 'wild', 'secreting'));
comment on column project_cost_items.strain is '株（null はどの株でも効く）。enhanced / wild は排水処理の試算の強化株 / 自然株、secreting は燃料の試算の脂質分泌株（migration 432）';

insert into project_cost_assumptions (cost_model_id, cost_assumption_id, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('cm_p21_fuel_260914', 'caf_lipid_secretion', '菌体から取れる燃料（収率）', '脂質分泌株', null, 'off', null, 'H', '推測', 'AMD（内部）', true, 'lipid_secreting_strain', '菌体を集めて壊さずに、菌体が作った脂肪酸を培養液へ出させ、それを回収する形にするか。スイッチは枠の上端の「株」にある（2026-09-14 まさ「脂質を分泌できる株の開発も理論的には可能っていう話を杉浦先生からもらったので、コスト試算表を「脂質分泌株」のスイッチオンオフで切り替えられるようにしてほしい。脂質分泌株だと一気にコストが下がりそうな気がしてる」）。ON にすると計算が次のように変わる: ①第1段で数える単位が「菌体1kg」から「脂肪酸1kg」になる。②燃料1Lに要る脂肪酸 ＝ 密度 ÷（培養液からの回収率 × メチル化反応率 × FAME精製回収率）で、FAMEポテンシャル・菌体回収率・脂質抽出回収率は使わない。③1系列が1年に出す脂肪酸 ＝ 1系列の培養液量 × 分泌速度 × 稼働日数（培養液量は、1系列の年間生産能力 ÷（菌体の生産性 × 稼働日数））。④菌体1kgあたりで入れてある培養の原料は、「脂肪酸1kgあたりに入れ替える菌体」を掛けて脂肪酸1kgあたりに直す。⑤脱水・細胞破砕・溶媒抽出・残渣の設備と、菌体の濃縮の行は数えない。代わりに閉鎖系の追加・溶媒相・溶媒からの分離の行を数える。既定は OFF。出どころ: 杉浦先生 2026-09-14「株を改変して脂質を分泌させるのは理論的に可能」。実際に作れた株はまだ研究室の規模で、Liu, Sheng, Curtiss 2011（PNAS 108:6899） の 改変 Synechocystis で培養液1Lあたり約0.2g、Kato ら 2017（Biotechnol Biofuels 10:141） の改変 Synechococcus に生体に優しい溶媒を重ねた形で18日に0.64g/L が最も高い。遺伝子組換え体なので閉鎖系の設備が要る。屋外や実証規模でこの形を動かした報告は見つかっていない。', 'amd_internal', 115, null, null);
insert into project_cost_assumptions (cost_model_id, cost_assumption_id, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('cm_p21_fuel_260914', 'caf_secretion_rate', '菌体から取れる燃料（収率）', '脂肪酸の分泌速度（基準）', 0.036, null, 'g/L/日', 'H', '資料記載', 'AMD（内部）', true, 'secretion_rate', '培養液1Lが1日に外へ出す脂肪酸。脂質分泌株のときだけ効き、要る培養液の量（培養設備の系列数）を決める。基準は Kato ら 2017（Biotechnol Biofuels 10:141） の、改変 Synechococcus elongatus に生体に優しい溶媒（ミリスチン酸イソプロピル）を重ねた形で、18日（432時間）に0.64 g/L ＝ 平均 1.5 mg/L/時 ＝ 0.036 g/L/日。確かめ方: 菌体の生産性（0.5 g/L/日）と比べる。分泌速度 0.036 g/L/日 は、菌体として作る量の約7%にあたる。光合成で1日に固定できる炭素の量が上限なので、菌体の生産性を大きく超える分泌速度は置けない。低位・改善は3ケースの表で動かす。SX株では測っていない。', 'amd_internal', 116, null, null);
insert into project_cost_assumptions (cost_model_id, cost_assumption_id, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('cm_p21_fuel_260914', 'caf_secretion_rate_low', '菌体から取れる燃料（収率）', '脂肪酸の分泌速度（低位）', 0.01, null, 'g/L/日', 'H', '資料記載', 'AMD（内部）', true, 'secretion_rate_low', 'Kato ら 2016（Biotechnol Biofuels 9:91） の、溶媒を重ねない改変株が培養液へ出した分 0.41 mg/L/時 ＝ 0.0098 g/L/日。出した脂肪酸の85%が細胞の中に残り、濃くなると出にくくなる（できた脂肪酸が自分の放出を止める）。', 'amd_internal', 117, null, null);
insert into project_cost_assumptions (cost_model_id, cost_assumption_id, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('cm_p21_fuel_260914', 'caf_secretion_rate_high', '菌体から取れる燃料（収率）', '脂肪酸の分泌速度（改善）', 0.074, null, 'g/L/日', 'H', '資料記載', 'AMD（内部）', true, 'secretion_rate_high', 'Kato ら 2017（Biotechnol Biofuels 10:141） の、いちばん速かった時期（72〜144時間）の 3.1 mg/L/時 ＝ 0.074 g/L/日 が18日続いたとした置き方。確かめ方: 菌体の生産性 0.5 g/L/日 の約15%。研究室の小さい容器での値で、屋外や大きい槽では光が届きにくくなる。', 'amd_internal', 118, null, null);
insert into project_cost_assumptions (cost_model_id, cost_assumption_id, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('cm_p21_fuel_260914', 'caf_broth_recovery', '菌体から取れる燃料（収率）', '培養液からの回収率（基準）', 90, null, '%', 'H', '資料記載', 'AMD（内部）', true, 'broth_recovery', '培養液に出た脂肪酸のうち、取り出せる割合。基準は Kato ら 2017（Biotechnol Biofuels 10:141） の「出た脂肪酸の90%以上が、重ねた溶媒の側へ移った」から90%。菌体回収率・脂質抽出回収率の代わりに効く。確かめ方: 培養液に残る脂肪酸を測り、槽の壁に付く分・菌体に戻る分と合わせて100%になるか見る。酸を入れて分ける形や樹脂に吸わせる形もあるが、培養液1Lに1gも無い薄さから取り出す実測はシアノバクテリアでは見つかっていない。', 'amd_internal', 119, null, null);
insert into project_cost_assumptions (cost_model_id, cost_assumption_id, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('cm_p21_fuel_260914', 'caf_broth_recovery_low', '菌体から取れる燃料（収率）', '培養液からの回収率（低位）', 80, null, '%', 'H', '仮置き', 'AMD（内部）', true, 'broth_recovery_low', '溶媒への移りが悪い、槽の壁や菌体に付く分が多いときの置き方。見積なし。', 'amd_internal', 120, null, null);
insert into project_cost_assumptions (cost_model_id, cost_assumption_id, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('cm_p21_fuel_260914', 'caf_broth_recovery_high', '菌体から取れる燃料（収率）', '培養液からの回収率（改善）', 95, null, '%', 'H', '仮置き', 'AMD（内部）', true, 'broth_recovery_high', '連続で溶媒へ移し続けられたときの置き方。見積なし。', 'amd_internal', 121, null, null);
insert into project_cost_assumptions (cost_model_id, cost_assumption_id, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('cm_p21_fuel_260914', 'caf_culture_productivity', '培養設備（菌体をつくる）', '培養の菌体の生産性', 0.5, null, 'g/L/日', 'H', '仮置き', 'AMD（内部）', true, 'culture_biomass_productivity', '培養液1Lが1日に増やす乾燥菌体。1系列の培養液量（＝1系列の年間生産能力 ÷（この値 × 稼働日数））を出すために使う。脂質分泌株のときだけ計算に効く（分泌株でないときは、1系列の年間生産能力をそのまま使う）。確かめ方: 0.5 g/L/日 は閉鎖型の培養槽でよく置かれる値で、開放池だと0.1〜0.2 g/L/日。この値を半分にすると1系列の培養液量が2倍になり、分泌株の設備の数と初期投資が2倍になる。1系列 33,333 kg-DCW/年 では培養液 222 m³ になり、明細の培養槽一式（1系列 573万円）で足りるかは確かめていない（確認事項「量産の培養設備の単位」と同じ問題）。見積なし。', 'amd_internal', 201, null, null);
insert into project_cost_assumptions (cost_model_id, cost_assumption_id, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('cm_p21_fuel_260914', 'caf_culture_days', '培養設備（菌体をつくる）', '培養の稼働日数', 300, null, '日/年', 'H', '仮置き', 'AMD（内部）', true, 'culture_operating_days', '1年のうち培養を回す日数。洗浄・立ち上げ・不調で止まる日を65日ほど見た置き方で、燃料化設備の運転日数（年300日）とそろえた。1系列の培養液量と、分泌株のときの1系列が年に出す脂肪酸の両方に効く。見積なし。', 'amd_internal', 202, null, null);
insert into project_cost_assumptions (cost_model_id, cost_assumption_id, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('cm_p21_fuel_260914', 'caf_cell_makeup', '培養の原料・品質確認', '脂肪酸1kgあたりに入れ替える菌体', 0.4, null, 'kg-DCW/kg-脂肪酸', 'H', '仮置き', 'AMD（内部）', true, 'cell_makeup_kg_per_unit', '脂質分泌株のとき、脂肪酸を出させ続けるために入れ替える菌体の量。菌体1kgあたりで入れてある培養の原料10行に掛けて、脂肪酸1kgあたりに直す。残渣の量にも掛かる（菌体を使い切らないので、残渣は入れ替えた分だけ）。確かめ方: Kato ら 2026（Biotechnol Biofuels Bioprod） は、成長を抑えた改変株が10日で「自分の重さの0.9倍」の脂肪酸を出したと報告している。同じ速さで菌体を約28日使い続けられるなら、菌体1kgで脂肪酸2.5kg ＝ 脂肪酸1kgあたり菌体0.4kg。菌体をどれだけ長く使えるかの実測は無く（いちばん長い報告で18日）、ここが分泌株の原料費をいちばん動かす。見積なし。', 'amd_internal', 311, null, null);
insert into project_cost_assumptions (cost_model_id, cost_assumption_id, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('cm_p21_fuel_260914', 'caf_plant_line_capacity_secreting', '燃料化設備：脱水・油回収', '燃料化設備1系列で処理できる脂肪酸の量', 5000000, null, 'kg-脂肪酸/年', 'H', '仮置き', 'AMD（内部）', true, 'plant_line_capacity_kg_year', '脂質分泌株のときの燃料化設備1系列の処理量。溶媒に受けた脂肪酸を分けて、FAMEにするまでを扱う。確かめ方: 脂肪酸1kgあたり溶媒を約23kg回すので、1系列で年に約11.5万tの溶媒を循環させる規模（1時間あたり約16t）。分泌株でないときの1系列（乾燥菌体 年5万t）と同じ「大きい1工場」の桁で置いた。見積なし。', 'amd_internal', 211, 'secreting', null);
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_sec_closed_exhaust', '中央培養', 'CAPEX', '閉鎖系の追加（脂質分泌株のみ）', '排気の除菌フィルター設備', '培養槽の排気口', '初期投資配賦', 1, '式', 500000, '円/式', null, 1.0, 7, false, 'H', '推測', 'AMD（内部）', '見積のない推測値。遺伝子組換え体を外へ出さないための設備。確かめ方: 廃液処理のコスト試算の強化株の「閉鎖系の追加」と同じ額を置いた（同じ閉じ込めの要求なので、そろえてある）。出どころ: 廃液処理のコスト試算（260914版）の ci2_c_exhaust_filter。', 'amd_internal', 1030, 'secreting', null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_sec_closed_waste', '中央培養', 'CAPEX', '閉鎖系の追加（脂質分泌株のみ）', '培養廃液の不活化設備', 'オートクレーブまたは薬剤不活化槽', '初期投資配賦', 1, '式', 1500000, '円/式', null, 1.0, 7, false, 'H', '推測', 'AMD（内部）', '見積のない推測値。組換え体を含む液を外へ出す前に殺す設備。確かめ方: 廃液処理のコスト試算の強化株の同じ行と同じ額。培養液は回して使う前提なので、抜く量（ブローダウン）ぶんの薬剤の費用は入れていない。出どころ: 廃液処理のコスト試算（260914版）の ci2_c_waste_inactivation。', 'amd_internal', 1031, 'secreting', null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_sec_closed_area', '中央培養', 'CAPEX', '閉鎖系の追加（脂質分泌株のみ）', '作業区域の区画・表示・区別保管', '区画・掲示・専用保管庫', '初期投資配賦', 1, '式', 300000, '円/式', null, 1.0, 7, false, 'H', '推測', 'AMD（内部）', '見積のない推測値。カルタヘナ法の拡散防止措置にあたる区画と掲示。確かめ方: 廃液処理のコスト試算の強化株の同じ行と同じ額。出どころ: 廃液処理のコスト試算（260914版）の ci2_c_work_area。', 'amd_internal', 1032, 'secreting', null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_sec_solvent_fill', '中央培養', 'CAPEX', '培養設備', '脂肪酸を受ける溶媒相（初期充填）', 'ミリスチン酸イソプロピル', '初期投資配賦', 11.1, 'm³', 450000, '円/m³', null, 1.0, 7, false, 'H', '推測', 'AMD（内部）', '見積のない推測値。培養液に重ねて、出てきた脂肪酸を受け続ける溶媒。分泌株のいちばん大きい設備の費用。確かめ方: 1系列の培養液 222 m³ の5%（11.1 m³）を溶媒の量とし、買値は1kg 500円 × 0.9 t/m³ ＝ 45万円/m³ で置いた。Kato ら 2017（Biotechnol Biofuels 10:141） の実験は培養液50 mL に溶媒20 mL（40%）だった。5%で足りるかは確かめていない（40%なら8倍になる）。買値は化粧品や食品に使う量の市販の桁として仮に置いたもので、見積は取っていない。培養液の量が変わったら、この行の量を置き直す。', 'amd_internal', 1033, 'secreting', null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_sec_contact', '中央培養', 'CAPEX', '培養設備', '溶媒相の接触・回収装置', '分離板・スキマー・移送ポンプ', '初期投資配賦', 1, '式', 800000, '円/式', null, 1.0, 7, false, 'H', '推測', 'AMD（内部）', '見積のない推測値。溶媒を培養液と触れさせ、脂肪酸を受けた溶媒を抜いて工場へ送る装置。確かめ方: 培養槽本体（120万円）・濃縮設備（250万円）と同じ桁で置いた。培養液を全部くみ上げて別の塔に通す形にすると、1日に培養液を1回まわすだけで桁が変わるので、この置き方は「槽の中で溶媒に受ける」形を前提にしている。', 'amd_internal', 1034, 'secreting', null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_sec_co2', '中央培養', 'OPEX', '脂肪酸の分泌', 'ユーティリティ', 'CO2（脂肪酸の炭素）', '毎kg菌体比例', 3.48, 'kg/kg-脂肪酸', 50, '円/kg', 'co2_supply', 1.0, null, false, 'C', '推定', 'AMD（内部）', '脂肪酸そのものの炭素になる CO2。菌体を作る分の CO2（上の「CO2（液化炭酸ガス）」）とは別に要る。確かめ方: 脂肪酸は重さの約76%が炭素なので、1kgあたり炭素0.76kg ＝ CO2 2.79kg。吹き込んだうち吸わせきれる割合を80%として 2.79 ÷ 0.8 ＝ 3.48 kg。菌体の行（2.29 kg/kg-DCW）と同じ出し方。工場の排ガスを使えるなら、この行も「排ガス利用可能」を ON にすると0円になる。', 'amd_internal', 1035, 'secreting', null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_sec_solvent_makeup', '中央培養', 'OPEX', '脂肪酸の分泌', '原料', '溶媒の補給（回収できない分）', '毎kg菌体比例', 0.11, 'kg/kg-脂肪酸', 500, '円/kg', null, 1.0, null, false, 'H', '推測', 'AMD（内部）', '見積のない推測値。溶媒を回して使うときに、培養液に溶けたり分離で失ったりする分の補給。確かめ方: 脂肪酸1kgあたり溶媒23kg（溶媒の中の濃さを40 g/L としたとき）を回し、1回まわすごとに0.5%失うとして 0.11 kg。溶媒の中の濃さも失う割合も実測が無い。ここが10倍になると、脂肪酸1kgあたり550円増える。', 'amd_internal', 1036, 'secreting', null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_sec_plant_strip', '共通', 'CAPEX', '脂肪酸を回収する', '溶媒から脂肪酸を分ける設備', '蒸留塔・凝縮器・受槽', '初期投資配賦', 1, '式', 500000000, '円/式', null, 1.0, 15, false, 'H', '推測', 'AMD（内部）', '見積のない推測値。脂肪酸を受けた溶媒から、脂肪酸だけを取り出して溶媒を戻す設備。確かめ方: 分泌株でないときの「溶媒回収設備（7億円）」より小さい桁で置いた（扱う液の量が少ないため）。分ける方法（蒸留・アルカリでの逆抽出・樹脂）は決めていない。', 'amd_internal', 2010, 'secreting', null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_sec_plant_solvent', '共通', 'CAPEX', '脂肪酸を回収する', '溶媒の貯槽・循環設備', 'タンク・ポンプ・熱交換器', '初期投資配賦', 1, '式', 300000000, '円/式', null, 1.0, 15, false, 'H', '推測', 'AMD（内部）', '見積のない推測値。工場側で溶媒を受けて回すための設備。確かめ方: 上の分離の設備の6割ほどの桁で置いた。培養の拠点との間の配管や輸送は入っていない。', 'amd_internal', 2011, 'secreting', null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_sec_plant_utility', '共通', 'CAPEX', '脂肪酸を回収する', '付帯設備・据付工事', '配管・計装・電気・土木・排水処理', '初期投資配賦', 1, '式', 600000000, '円/式', null, 1.0, 15, false, 'H', '推測', 'AMD（内部）', '見積のない推測値。分泌株のときの燃料化の工場の付帯。確かめ方: 機器の合計（8億円）の75%で置いた。分泌株でないときは機器合計25億円に対して付帯15億円（60%）。', 'amd_internal', 2012, 'secreting', null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_sec_op_heat', '共通', 'OPEX', '脂肪酸を回収する', '熱', '溶媒から脂肪酸を分ける', '毎kg菌体比例', 20, 'MJ/kg-脂肪酸', 2.3, '円/MJ', null, 1.0, null, false, 'H', '推測', 'AMD（内部）', '見積のない推測値。溶媒と脂肪酸を分けるのに使う熱。確かめ方: 脂肪酸1kgの発熱量が約39MJなので、その半分ほどを分けるのに使う置き方。実際の熱は分ける方法で変わる（蒸留なら溶媒を蒸発させる分、逆抽出なら薬剤の分）。ここが2倍になると燃料1Lあたり47円増える。', 'amd_internal', 2110, 'secreting', null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_sec_op_power', '共通', 'OPEX', '脂肪酸を回収する', '電力', '溶媒の循環・分離', '毎kg菌体比例', 0.5, 'kWh/kg-脂肪酸', 17.45, '円/kWh', null, 1.0, null, false, 'H', '推測', 'AMD（内部）', '見積のない推測値。溶媒を回すポンプと分離の動力。確かめ方: 分泌株でないときの電力（0.3 kWh/kg-DCW）より大きめに置いた（溶媒を多く回すため）。', 'amd_internal', 2111, 'secreting', null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_sec_op_maintenance', '共通', 'OPEX', '脂肪酸を回収する', '設備の保守', '燃料化設備（回収・分離・付帯・出荷）の初期投資の3%/年', '年額固定', 1, '年', 46500000, '円/年', null, 1.0, null, false, 'H', '推測', 'AMD（内部）', '見積のない推測値。分泌株のときの燃料化設備の保守。確かめ方: 1系列の初期投資（5億＋3億＋6億＋製品の貯槽1.5億 ＝ 15.5億円）の3%。分泌株でないときと同じ「初期投資の3%/年」の置き方。', 'amd_internal', 2112, 'secreting', null, 'sx');
update project_cost_items set strain = 'wild', note = '見積のない予測値。培養液から菌体を分けて濃くする設備で、連続式の遠心分離機か小型の膜濃縮ユニットを想定した額。確かめ方: 1系列の培養液の量に合う機種を選び、見積を取って比べる。出どころ: 2026-08-20版の試算シート（ちこさん作成）の設備に入っていなかったので、AMDがあとから足した。排水処理のコスト試算からコピーした行で、あちらを直してもこちらは変わらない。菌体を集めて濃縮する設備。脂質分泌株では菌体を集めないので数えない。', updated_at = now() where cost_item_id = 'cif_culture_057';
update project_cost_items set strain = 'wild', updated_at = now() where cost_item_id = 'cif_culture_058';
update project_cost_items set strain = 'wild', updated_at = now() where cost_item_id = 'cif_culture_059';
update project_cost_items set strain = 'wild', updated_at = now() where cost_item_id = 'cif_culture_060';
update project_cost_items set strain = 'wild', note = '仮置き（膜やフィルタの買値を調べられていない）。2026-08-20版の試算シートでAMDが置いた額（処理水1m³あたり10円）を、培養液1m³あたり45円に直して、菌体1kgの培養液0.2m³（菌体の濃さ5g/L、杉浦先生の回答）を掛けている。確かめ方: 濃縮を遠心分離にするか膜にするかを中島先生と決め、膜なら膜の面積・交換の年数・1m²の値段を見積もって、1年の額 ÷ 1系列が1年に作る菌体の量で比べる（遠心分離ならフィルタはほぼ要らず、電力が要る）。排水処理のコスト試算の同じ行と同じ値（2026-09-14 にそろえた）。片方を直しても、もう片方は変わらない。前の額（2026-09-14 に「使う量 × 買値」へ組み直す前）: 菌体1kgあたり9円で、量と買値の内訳は無かった。ちこさんの試算シート（2026-07-30版〜2026-08-20版）の「濃縮用フィルタ　処理水1m³あたり10円」（出所「仮置き」）を、処理水1m³に使う乾燥菌体1.111kgで割った額。7/30版で置かれた額で、決め方はシートに書かれていない。版ごとの流れは版の履歴「培養の原料の前の額は、どこから来たか」。菌体を濃縮するときのフィルタ。脂質分泌株では菌体を集めないので数えない。', updated_at = now() where cost_item_id = 'cif_culture_127';
update project_cost_items set strain = 'wild', note = '量: 凝集剤を培養液1Lに10mg（クロレラをキトサン10mg/Lで98%集めた報告。ポリアクリルアミドは5〜10mg/L）× 培養液200L ＝ 0.002kg。買値: 仮置き 2,700円/kg（買値を調べられていない。2026-08-20版の試算シートの額から逆算した値）。確かめ方: 凝集剤を使うか（遠心分離だけなら要らない）と種類を中島先生に聞き、水処理薬剤のメーカーに値段を聞いて比べる。排水処理のコスト試算の同じ行と同じ値（2026-09-14 にそろえた）。片方を直しても、もう片方は変わらない。前の額（2026-09-14 に「使う量 × 買値」へ組み直す前）: 菌体1kgあたり5.4円で、量と買値の内訳は無かった。ちこさんの試算シート（2026-07-30版〜2026-08-20版）の「濃縮補助材　処理水1m³あたり6円」（出所「仮置き」）を、処理水1m³に使う乾燥菌体1.111kgで割った額。7/30版で置かれた額で、決め方はシートに書かれていない。版ごとの流れは版の履歴「培養の原料の前の額は、どこから来たか」。菌体を濃縮するときの凝集剤。脂質分泌株では菌体を集めないので数えない。', updated_at = now() where cost_item_id = 'cif_culture_128';
update project_cost_items set strain = 'wild', note = '濃縮した菌体を固形分20%まで脱水する。燃料化設備1系列（乾燥菌体 年5万t）あたり。見積はない。従来型のバイオディーゼル工場の初期投資（年産能力1tあたり約300〜450ドル）や、大豆の溶媒抽出工場を手がかりに、湿った菌体の細胞破砕と乳化対策の分を上乗せした目安。プラントメーカーの概算で置き換える。集めた菌体を脱水する設備。脂質分泌株では菌体を脱水しないので数えない。', updated_at = now() where cost_item_id = 'cif_plant_dewater';
update project_cost_items set strain = 'wild', note = '湿った菌体の細胞を壊し、膜の脂質を溶媒に移しやすくする。燃料化設備1系列（乾燥菌体 年5万t）あたり。見積はない。従来型のバイオディーゼル工場の初期投資（年産能力1tあたり約300〜450ドル）や、大豆の溶媒抽出工場を手がかりに、湿った菌体の細胞破砕と乳化対策の分を上乗せした目安。プラントメーカーの概算で置き換える。細胞を壊す設備。脂質分泌株では細胞を壊さないので数えない。', updated_at = now() where cost_item_id = 'cif_plant_disruption';
update project_cost_items set strain = 'wild', note = '極性と非極性の溶媒で脂質を取り出し、水・残渣と分ける。溶媒の組成は未決。燃料化設備1系列（乾燥菌体 年5万t）あたり。見積はない。従来型のバイオディーゼル工場の初期投資（年産能力1tあたり約300〜450ドル）や、大豆の溶媒抽出工場を手がかりに、湿った菌体の細胞破砕と乳化対策の分を上乗せした目安。プラントメーカーの概算で置き換える。壊した菌体から溶媒で油を取り出す設備。脂質分泌株では培養液から回収するので数えない。', updated_at = now() where cost_item_id = 'cif_plant_extraction';
update project_cost_items set strain = 'wild', note = '循環させる溶媒（菌体1kgあたり3kg）を蒸留で回収して使い回す。燃料化設備1系列（乾燥菌体 年5万t）あたり。見積はない。従来型のバイオディーゼル工場の初期投資（年産能力1tあたり約300〜450ドル）や、大豆の溶媒抽出工場を手がかりに、湿った菌体の細胞破砕と乳化対策の分を上乗せした目安。プラントメーカーの概算で置き換える。抽出に使った溶媒を蒸留で回収する設備。脂質分泌株では別の回収の設備を数える。', updated_at = now() where cost_item_id = 'cif_plant_solvent_recovery';
update project_cost_items set strain = 'wild', note = '油を取ったあとの残渣を脱水し、搬出するまで保管する。燃料化設備1系列（乾燥菌体 年5万t）あたり。見積はない。従来型のバイオディーゼル工場の初期投資（年産能力1tあたり約300〜450ドル）や、大豆の溶媒抽出工場を手がかりに、湿った菌体の細胞破砕と乳化対策の分を上乗せした目安。プラントメーカーの概算で置き換える。油を取ったあとの残渣を脱水して運び出す設備。脂質分泌株では残渣が入れ替えた菌体の分だけなので数えない。', updated_at = now() where cost_item_id = 'cif_plant_residue';
update project_cost_items set strain = 'wild', note = '機器の据付と、配管・計装・受変電・建屋・工場の排水処理。化学プラントでは機器代の数倍になることが多い。燃料化設備1系列（乾燥菌体 年5万t）あたり。見積はない。従来型のバイオディーゼル工場の初期投資（年産能力1tあたり約300〜450ドル）や、大豆の溶媒抽出工場を手がかりに、湿った菌体の細胞破砕と乳化対策の分を上乗せした目安。プラントメーカーの概算で置き換える。脱水・油回収の工場の付帯設備。脂質分泌株では別の付帯設備を数える。', updated_at = now() where cost_item_id = 'cif_plant_utility';
update project_cost_items set strain = 'wild', note = '乾燥菌体1kgあたり0.3kWhは見積のない目安（細胞破砕が大部分）。単価は特別高圧の産業用電力の全国平均 17.45円/kWh（2026年5月、新電力ネット）。排水処理のコスト試算の電力単価（27円/kWh）は高圧の小口を想定した値で、燃料化設備の規模は特別高圧になるため分けた。脱水・細胞破砕・抽出の電力。脂質分泌株では数えない。', updated_at = now() where cost_item_id = 'cif_op_power';
update project_cost_items set strain = 'wild', note = '循環させる溶媒（菌体1kgあたり3kg）を蒸留で回収する熱を、乾燥菌体1kgあたり1.5MJと置いた（熱の回収を含む目安、見積なし）。単価は蒸気1tあたり約5,000円（仮置き）。溶媒の種類で変わる。抽出溶媒を蒸留で回収する熱。脂質分泌株では数えない。', updated_at = now() where cost_item_id = 'cif_op_heat';
update project_cost_items set strain = 'wild', note = '量は2026-09-07 の工程とマテバラ推定（循環する溶媒 2,850kg のうち99%を回収し、乾燥菌体1tあたり28.5kgを補給）。単価は溶媒の種類が未決のため1kgあたり200円の仮置き。抽出溶媒の補給。脂質分泌株では数えない。', updated_at = now() where cost_item_id = 'cif_op_solvent';
update project_cost_items set strain = 'wild', note = '量は2026-09-07 の工程とマテバラ推定（乾燥菌体1tあたり0.2m³）。単価は工業用水の目安。抽出・洗浄の水。脂質分泌株では数えない。', updated_at = now() where cost_item_id = 'cif_op_water';
update project_cost_items set strain = 'wild', note = '燃料化設備1系列の初期投資（41.5億円）の3%/年。初期投資の明細を書き換えたら、この額も合わせて直す。脱水・油回収の設備の保守。脂質分泌株では別の設備の保守を数える。', updated_at = now() where cost_item_id = 'cif_op_maintenance';
update project_cost_tasks set strain = 'wild', updated_at = now() where cost_task_id = 'ctf_culture_operation';
update project_cost_tasks set strain = 'wild', updated_at = now() where cost_task_id = 'ctf_plant_operation';
insert into project_cost_tasks (cost_model_id, cost_task_id, scenario, group_label, label, count_driver, count_per_year, hours_per_occurrence, expense_per_occurrence, confidence, source_kind, owner, note, visibility, sort_order, strain, application, performer) values ('cm_p21_fuel_260914', 'ctf_sec_culture_operation', '中央培養', '菌体をつくる', '培養と溶媒相の回収の運転（1日分）', 'production_line', 300, null, 0, 'H', '推測', 'AMD（内部）', '脂質分泌株のときの培養の運転。1系列を1日動かすのに何時間の人手が要るかは未確認（分泌株でないときの行と同じ）。溶媒を抜いて工場へ送る作業を含む。杉浦先生に聞く（確認事項「燃料向けの培養の物量」）。', 'amd_internal', 11, 'secreting', null, 'sx');
insert into project_cost_tasks (cost_model_id, cost_task_id, scenario, group_label, label, count_driver, count_per_year, hours_per_occurrence, expense_per_occurrence, confidence, source_kind, owner, note, visibility, sort_order, strain, application, performer) values ('cm_p21_fuel_260914', 'ctf_sec_plant_operation', '共通', '脂肪酸を回収する', '溶媒からの脂肪酸の回収の運転（1日分）', 'plant_line', 300, 72, 0, 'H', '推測', 'AMD（内部）', '見積のない推測値。1系列を1日24時間動かすのに3人（72人時）とした置き方で、分泌株でないときの「脱水と油回収の運転」と同じ。確かめ方: 年間の工数を系列の数で割って、1工場あたりの人数に直して見る。', 'amd_internal', 21, 'secreting', null, 'sx');
insert into project_cost_notes (cost_model_id, cost_note_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cm_p21_fuel_260914', 'cnf_history_secreting', 'history', '脂質分泌株のスイッチ（2026-09-14）', 'まさ 2026-09-14「脂質を分泌できる株の開発も理論的には可能っていう話を杉浦先生からもらったので、コスト試算表を「脂質分泌株」のスイッチオンオフで切り替えられるようにしてほしい。脂質分泌株だと一気にコストが下がりそうな気がしてる」

**何を足したか**

枠の上端の「株」を「脂質分泌株」にすると、菌体を集めて壊して油を取り出す形から、菌体は槽に居たまま作った脂肪酸を培養液へ出させ、それを回収する形に切り替わる。第1段で数える単位が「菌体1kg」から「脂肪酸1kg」になり、脱水・細胞破砕・溶媒抽出・残渣の設備を数えず、代わりに閉鎖系の追加・培養液に重ねる溶媒・溶媒からの分離を数える。

**燃料1Lあたりの総コスト（円/L、残渣は発酵などで処理、排ガス利用可能は OFF）**

| 組み合わせ | 菌体から取り出す | 脂質分泌株 |
|---|---|---|
| 外部に委託・低位 | 11,260.0 | 3,994.9 |
| 外部に委託・基準 | 6,033.4 | 1,311.8 |
| 外部に委託・改善 | 4,053.3 | 835.2 |
| 自社で行う・基準 | 6,007.5 | 1,273.9 |

**なぜ下がるか、なぜ売価に届かないか**

下がるのは原料。菌体から取り出す形は、燃料1Lに菌体 18.0 kg が要り、そのうち燃料になるのは6%だけで、残り94%は残渣として捨てる。培地・CO2・窒素源はその捨てる分にも払っている。分泌株は、燃料1Lに脂肪酸 1.0 kg（＋入れ替える菌体 0.4 kg）で足りるので、原料が4,955.8 → 342.3 円/L になる。

下がらないのは培養設備。1系列（培養液 222.2 m³）が1年に作れる燃料は、菌体から取り出す形で 1,847.2 L、分泌株で 2,333.3 L と大きく変わらない。光合成が1日に固定できる炭素の量で決まるので、株を変えても培養の槽の数はあまり減らない（27,068 → 21,429 系列）。分泌株では、そこに閉鎖系の設備と溶媒相の充填が乗るので、培養設備の費用は1Lあたりむしろ上がる（443.1 → 693.4 円/L）。

**置いた数字**（すべて見積なし・研究室の実測か推測）

- 分泌速度 0.036 g/L/日（基準）: Kato ら 2017 の、生体に優しい溶媒を重ねた改変 Synechococcus が18日で0.64 g/L。低位0.010・改善0.074
- 培養液からの回収率 90%（基準）: 同じ報告の「出た脂肪酸の90%以上が溶媒側へ移った」
- 脂肪酸1kgあたりに入れ替える菌体 0.4 kg: Kato ら 2026 の「10日で自分の重さの0.9倍」を、約28日使い続けられるとした置き方
- 溶媒相は培養液の5%・1kg 500円、溶媒の補給 0.11 kg/kg-脂肪酸、溶媒からの分離の熱 20 MJ/kg-脂肪酸
- 閉鎖系の追加は、廃液処理のコスト試算の強化株と同じ額（排気の除菌・廃液の不活化・区画で 230万円/系列）

**確かめていないこと**

菌体をどれだけ長く使い続けられるか（いちばん長い報告で18日）、培養液1Lに1gも無い薄さから脂肪酸を取り出す設備の実際の費用、屋外や大きい槽での分泌速度、溶媒相を培養液の5%で足りるか（研究室の実験は40%）、カルタヘナ法の拡散防止措置で屋外の培養ができるか。', null, null, 'amd_internal', 21);
insert into project_cost_notes (cost_model_id, cost_note_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cm_p21_fuel_260914', 'cnf_caveat_secreting', 'caveat', '脂質分泌株の数字は、研究室の値からの置き方', '脂質分泌株の列は、まだ作られていない株を前提にした試算。分泌速度・培養液からの回収率・菌体を使い続けられる日数は研究室の小さい容器の値で、屋外や大きい槽での実測は無い。溶媒相の量と買値、溶媒から脂肪酸を分ける設備と熱は、見積のない推測値。

いちばん効くのは分泌速度。0.036 g/L/日 を半分にすると培養設備の系列数と初期投資が2倍になり、「脂肪酸1kgあたりに入れ替える菌体 0.4 kg」を2倍にすると原料が2倍になる。両方とも画面で動かして確かめられる。', null, null, 'amd_internal', 25);
insert into project_cost_questions (cost_model_id, cost_question_id, addressee, question, why_it_matters, impact_low, impact_high, status, answer, answered_on, linked_assumption_id, visibility, sort_order) values ('cm_p21_fuel_260914', 'cqf_secretion_rate', '杉浦先生', '脂肪酸を培養液へ出させる株を作るとして、培養液1Lが1日に出せる量はどれくらいを見込めますか。また、同じ菌体を何日くらい使い続けられそうですか（入れ替えずに出し続けられる日数）。', '1日に出る量が培養設備の数（＝初期投資）を、使い続けられる日数が培地とCO2の量を決める。いまは研究室の報告（18日で0.64 g/L ＝ 0.036 g/L/日、10日で菌体の重さの0.9倍）から置いている。', null, null, 'open', null, null, 'caf_secretion_rate', 'amd_internal', 15);
insert into project_cost_questions (cost_model_id, cost_question_id, addressee, question, why_it_matters, impact_low, impact_high, status, answer, answered_on, linked_assumption_id, visibility, sort_order) values ('cm_p21_fuel_260914', 'cqf_secretion_recovery', '杉浦先生', '培養液1Lに1gも入っていない薄さの脂肪酸を取り出す方法は、生体に優しい溶媒を重ねて受ける形と、酸を入れて分ける形と、樹脂に吸わせる形のどれが現実的ですか。', '培養液の量が莫大なので、取り出す方法で設備と薬剤の費用が桁で変わる。いまは溶媒を重ねて受ける形（研究室で実測がある唯一の形）で置いている。', null, null, 'open', null, null, 'caf_broth_recovery', 'amd_internal', 16);
commit;
