-- 435: SOL（p21）の両方のコスト試算に、培養の加温・電力・排水を入れ、「排熱利用可能」のスイッチを置く
-- （まさ 2026-09-15「顧客の工場のCO2と排熱、排ガスをフル活用してやる方向も見えてくる」）
--
--   - 培養の加温・電力・排水は、これまで1円も入っていなかった（426 からの積み残し）。入れないと排熱の価値を数字にできない
--   - 明細4行 × 2つの試算 = 8行を足す（加温の熱・培養の電力・培養液の入れ替え・加温保温設備の CAPEX）
--   - 単価の連動のしかたに heat_supply を足す（前提 waste_heat が on なら加温の熱は0円）
--   - 前提 waste_heat「排熱利用可能」（value_text off）を両方の試算に足す。画面は加温の熱の行にスイッチを出す
--   - SX の株は好熱性で運転温度45〜70℃（技術台帳）。工場の排熱はちょうどこの温度帯
-- 生成: apply435.py（scratchpad）。fixture 2つを同じ定義から書き出した。
begin;
select set_config('amd.cost_change_reason', '435: 培養の加温・電力・排水を入れ、排熱利用可能のスイッチを置く（まさ 2026-09-15）', true);
do $do$ begin
  if (select pg_get_constraintdef(oid) from pg_constraint where conname = 'project_cost_items_price_rule_check') <> 'CHECK (((price_rule IS NULL) OR (price_rule = ANY (ARRAY[''biomass''::text, ''broth''::text, ''module_swap''::text, ''power_circulation''::text, ''power_injection''::text, ''spent_disposal''::text, ''co2_supply''::text, ''culture_loss''::text, ''medium_supply''::text]))))' then raise exception '435: 単価の連動のしかたの制約が変わっている'; end if;
  if exists (select 1 from project_cost_items where cost_item_id = 'ci2_c_heat') then raise exception '435: 明細 ci2_c_heat がもうある'; end if;
  if exists (select 1 from project_cost_items where cost_item_id = 'ci2_c_power') then raise exception '435: 明細 ci2_c_power がもうある'; end if;
  if exists (select 1 from project_cost_items where cost_item_id = 'ci2_c_blowdown') then raise exception '435: 明細 ci2_c_blowdown がもうある'; end if;
  if exists (select 1 from project_cost_items where cost_item_id = 'ci2_c_heat_capex') then raise exception '435: 明細 ci2_c_heat_capex がもうある'; end if;
  if exists (select 1 from project_cost_assumptions where cost_model_id = 'cm_p21_260820' and role_key = 'waste_heat') then raise exception '435: cm_p21_260820 に排熱の前提がもうある'; end if;
  if exists (select 1 from project_cost_notes where cost_note_id = 'cn17_h17') then raise exception '435: 注記 cn17_h17 がもうある'; end if;
  if exists (select 1 from project_cost_items where cost_item_id = 'cif_culture_heat') then raise exception '435: 明細 cif_culture_heat がもうある'; end if;
  if exists (select 1 from project_cost_items where cost_item_id = 'cif_culture_power') then raise exception '435: 明細 cif_culture_power がもうある'; end if;
  if exists (select 1 from project_cost_items where cost_item_id = 'cif_culture_blowdown') then raise exception '435: 明細 cif_culture_blowdown がもうある'; end if;
  if exists (select 1 from project_cost_items where cost_item_id = 'cif_culture_heat_capex') then raise exception '435: 明細 cif_culture_heat_capex がもうある'; end if;
  if exists (select 1 from project_cost_assumptions where cost_model_id = 'cm_p21_fuel_260914' and role_key = 'waste_heat') then raise exception '435: cm_p21_fuel_260914 に排熱の前提がもうある'; end if;
  if exists (select 1 from project_cost_notes where cost_note_id = 'cnf_history_heat') then raise exception '435: 注記 cnf_history_heat がもうある'; end if;
end $do$;

alter table project_cost_items drop constraint if exists project_cost_items_price_rule_check;
alter table project_cost_items add constraint project_cost_items_price_rule_check
  check (price_rule is null or price_rule in (
    'biomass', 'broth', 'module_swap', 'power_circulation', 'power_injection', 'spent_disposal',
    'co2_supply', 'culture_loss', 'medium_supply', 'heat_supply'
  ));
comment on column project_cost_items.price_rule is '単価の連動のしかた（null は unit_price をそのまま使う）。biomass / broth = 旧版の菌体量・培養液量の倍率、module_swap = モジュール一式 ÷ 耐用 ÷ 1バッチの量、power_circulation / power_injection = 動力 × 反応時間 × 電力単価 ÷ 1バッチの量、spent_disposal = 湿重量倍率 × 汚泥の処分単価、co2_supply = CO2（前提 co2_flue_gas が on なら0円）、culture_loss = 培養ロス補充（同じ群の菌体1kgあたりの原料の行の額の合計）、medium_supply = 培地の原料（前提 waste_medium が on なら unit_price × (1 − waste_medium_reduction%)）、heat_supply = 培養の加温（前提 waste_heat が on なら0円）。migration 435';

insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_260820', 'ci2_c_heat', '中央培養', 'OPEX', '培養', 'ユーティリティ', '加温の熱（45〜70℃に保つ）', '毎kg菌体比例', 200.0, 'MJ/kg-DCW', 2.3, '円/MJ', 'heat_supply', 1.0, null, false, 'H', '推測', '杉浦先生（CO2の入れ方）', '見積のない推測値。**この行は 2026-09-15 に新しく入れた**（それまで培養の加温は1円も入っていなかった）。SX の株は好熱性で運転温度は45〜70℃（技術台帳「培養温度」）。試作の47L装置にもヒーターが付いている。確かめ方: ①Slegers ら 2015（スペイン・平板型の閉鎖槽の模擬）は、熱の負荷を電気の30〜50倍と出しており、菌体1kgあたりに直すと約227 MJ。同じ研究は「投入するエネルギーが菌体の持つエネルギーを上回る」（NER 1.12〜2.10）とも書いている。②自前の計算: 1系列が1日に作る菌体 111 kg ÷ 面積あたりの生産性 25 g/m²/日 ＝ 受光面積 約4,444 m²。光を通す面は断熱材で覆えないので、二重の覆いで熱の伝わりやすさ 3 W/m²K、培養45℃ − 外の年平均15℃ ＝ 30K として熱損失 約400kW ＝ 年10,400GJ ＝ 菌体1kgあたり約311MJ。日射（年平均 約190 W/m² × 受光面積 ＝ 約840kW）でまかなえる分を70%とすると残りは93MJ。③幅は 93〜311 MJ/kg-DCW で、スペインの模擬（227）が真ん中あたりなので 200 MJ と置いた。**この試算でいちばん確度が低い行**（季節と昼夜の収支を計算していない。夏は余って冷やす側、冬と夜は足りない）。商用の藻の工場は加温しない: ハワイ（サイアノテック）・海南島と米国インペリアルバレー（DIC のスピルリナ）のように暖かい土地を選ぶか、冬は止める。45〜70℃が要る SX の株は、その逃げ道が無い。工場の排熱を使えるなら、この行の「排熱利用可能」を ON にすると0円になる。', 'amd_internal', 821, null, null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_260820', 'ci2_c_power', '中央培養', 'OPEX', '培養', 'ユーティリティ', '培養の電力（撹拌・送液・散気）', '毎kg菌体比例', 2.0, 'kWh/kg-DCW', 17.45, '円/kWh', null, 1.0, null, false, 'H', '推測', '杉浦先生（CO2の入れ方）', '見積のない推測値。**この行は 2026-09-15 に新しく入れた**（それまで培養の電力は1円も入っていなかった）。撹拌・培養液の送り・CO2と空気の吹き込みに使う電力。脱水や油回収の電力（燃料化設備の行）とは別。確かめ方: 開放池のかき混ぜは、この試算の生産性（0.5 g/L/日）に直すと菌体1kgあたり0.05〜0.24 kWh（Richardson ら 2014・Slegers ら 2015 の 0.22〜0.91 W/m² から）。SX は閉鎖型の縦型・チューブ型なのでこれより重く、文献の幅は 0.33〜233.7 kWh/kg と広い。ここでは 2.0 kWh/kg-DCW と置いた。排ガスの CO2 を使うときは、濃さが数%〜2割なので吹き込む量が5〜20倍になり、この電力は上がる（いまは同じ値のまま）。空気（0.04%）から取る実験では CO2 1kgあたり2.9 kWh かかっている。買値は高圧受電の 17.45 円/kWh（燃料化設備の電力と同じ）。', 'amd_internal', 822, null, null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_260820', 'ci2_c_blowdown', '中央培養', 'OPEX', '培養', 'ユーティリティ', '培養液の入れ替え（排水）', '毎kg菌体比例', 0.02, 'm³/kg-DCW', 345, '円/m³', null, 1.0, null, false, 'H', '推測', '杉浦先生（CO2の入れ方）', '見積のない推測値。**この行は 2026-09-15 に新しく入れた**（それまで培養の排水は1円も入っていなかった）。培養液は回して使うが、塩や増殖を止める物がたまるので一部を抜いて捨てる。確かめ方: 菌体1kgあたりの培養液は約200L（廃液の試算の閉鎖系の行と同じ置き方）で、その1割を入れ替えるとして 0.02 m³/kg-DCW。抜く割合の実測は文献にも無い（NREL も「管理が要る」と書くだけ）。単価 345 円/m³ は東京都の下水道料金の最上位区分（月1,000m³超、税別）。有機物が濃いと大阪市のような加算（BOD 350mg/L で +37円/m³）が付く。遺伝子組換え体（強化株・脂質分泌株）のときは、抜いた液を殺してから捨てる費用が別に要る（閉鎖系の追加の行）。', 'amd_internal', 823, null, null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_260820', 'ci2_c_heat_capex', '中央培養', 'CAPEX', '培養設備', '加温・保温設備', '熱交換器・保温・温度制御', '初期投資配賦', 1, '式', 1500000, '円/式', null, 1.0, 7, false, 'H', '推測', 'AMD', '見積のない推測値。**この行は 2026-09-15 に新しく入れた**。培養液を45〜70℃に保つための熱交換器・保温・温度の制御。確かめ方: 培養槽本体（1,200,000円）と同じ桁で置いた。工場の排熱を使うときは、排熱を受ける熱交換器がこれにあたる（排熱でも設備は要るので、「排熱利用可能」を ON にしてもこの行は0円にならない）。', 'amd_internal', 735, null, null, 'sx');
insert into project_cost_assumptions (cost_model_id, cost_assumption_id, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('cm_p21_260820', 'ca15_waste_heat', '菌体の製造拠点（原料・品質確認）', '排熱利用可能', null, 'off', null, 'H', '推測', 'AMD（内部）', true, 'waste_heat', '培養の加温を、工場の排熱でまかなえるか。スイッチは「加温の熱」の行にある（まさ 2026-09-15「顧客の工場のCO2と排熱、排ガスをフル活用してやる方向も見えてくる」）。ON にすると加温の熱の単価を0円として計算する（MJ の量と買う熱の単価は行に残る）。培養ロス補充は原料の合計から出すので一緒に下がる。既定は OFF（熱を買う）。**SX の株は好熱性で45〜70℃で運転する**ので、加温は他の藻の事業より重い。工場の排熱（蒸気のドレン・冷却水・排ガスの熱）はちょうどこの温度帯なので、相性がいい（製鉄所の排ガス 50〜170℃で藻の縦型槽を温めた報告（Hu ら 2024）、米国デューク・エナジーの石炭火力の冷却水で藻の槽を温めた実証（2015年、CO2 の取り込み 日中平均44%）、日本では大崎クールジェン（広島、石炭ガス化＋CO2回収 1日400t）の隣で NEDO・IHI が藻の研究をしている）。0円は、排熱をタダでそのまま使えるときの上限で、次は入っていない: 熱を受ける熱交換器（CAPEX の行にある）、排熱の量が季節や工場の稼働で変わること、培養の拠点を工場の隣に置くしばり。', 'amd_internal', 323, null, null);
insert into project_cost_notes (cost_model_id, cost_note_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cm_p21_260820', 'cn17_h17', 'history', '培養の加温・電力・排水を入れた（2026-09-15）', 'まさ 2026-09-15「顧客の工場のCO2と排熱、排ガスをフル活用してやる方向も見えてくる」（まさ「うん、進めて」）

**培養の加温・電力・排水は、これまで1円も入っていなかった**（426 で培養の原料を組み直したときからの積み残し）。入れないと「工場の排熱を使う価値」を数字にできないので、3行を足した。あわせて加温・保温の設備（CAPEX）も足した。

| 円/m³（自然株・オンサイト・直接投入） | 入れる前 | 入れた後 | 排熱 ON | 排熱＋排ガス＋排液 |
|---|---|---|---|---|
| 金属回収（売価500円/m³） | 528.3 | 1,233.8 | 594.9 | 300.7 |
| 色素分解（目標300円/m³） | 54.2 | 113.5 | 59.8 | 35.1 |

**受光面積**: 年2,000万m³の排水を処理する菌体には約 667 系列が要るので、受光面積は約 3.0 km²（296 ha）。

**なぜ加温が重い**: SX の株は好熱性で、運転温度は45〜70℃（技術台帳「培養温度」。試作の47L装置にもヒーターが付いている）。光を通す面は断熱材で覆えないので、熱が逃げる。1系列の受光面積 約4,444 m²、二重の覆いで 3 W/m²K、培養45℃ − 外の年平均15℃ ＝ 30K として熱損失は約400kW（年10,400GJ ＝ 菌体1kgあたり約311MJ）。そのうち日射（年平均 約190 W/m² × 受光面積 ＝ 約840kW）でまかなえる分を70%とし、残りの93 MJ/kg-DCW を買う熱とした。

**ここがいちばん確度が低い**: 季節と昼夜の収支を計算していない。夏は余って冷やす側、冬と夜は足りない。大きな水の塊なので一晩では冷めにくいが、夜の熱損失だけで培養液が30K近く下がる計算になるため、覆いの断熱・夜間の保温・季節ごとの運転の止め方をどう置くかで、この行は数倍動く。

**排熱の相性**: 工場の排熱（蒸気のドレン・冷却水・排ガスの熱）は、ちょうど45〜70℃の温度帯。「排熱利用可能」を ON にすると加温の熱が0円になる。熱を受ける熱交換器は CAPEX の行に残る（排熱でも設備は要る）。', null, null, 'amd_internal', 170);
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_culture_heat', '中央培養', 'OPEX', '培養', 'ユーティリティ', '加温の熱（45〜70℃に保つ）', '毎kg菌体比例', 200.0, 'MJ/kg-DCW', 2.3, '円/MJ', 'heat_supply', 1.0, null, false, 'H', '推測', '杉浦先生（CO2の入れ方）', '見積のない推測値。**この行は 2026-09-15 に新しく入れた**（それまで培養の加温は1円も入っていなかった）。SX の株は好熱性で運転温度は45〜70℃（技術台帳「培養温度」）。試作の47L装置にもヒーターが付いている。確かめ方: ①Slegers ら 2015（スペイン・平板型の閉鎖槽の模擬）は、熱の負荷を電気の30〜50倍と出しており、菌体1kgあたりに直すと約227 MJ。同じ研究は「投入するエネルギーが菌体の持つエネルギーを上回る」（NER 1.12〜2.10）とも書いている。②自前の計算: 1系列が1日に作る菌体 111 kg ÷ 面積あたりの生産性 25 g/m²/日 ＝ 受光面積 約4,444 m²。光を通す面は断熱材で覆えないので、二重の覆いで熱の伝わりやすさ 3 W/m²K、培養45℃ − 外の年平均15℃ ＝ 30K として熱損失 約400kW ＝ 年10,400GJ ＝ 菌体1kgあたり約311MJ。日射（年平均 約190 W/m² × 受光面積 ＝ 約840kW）でまかなえる分を70%とすると残りは93MJ。③幅は 93〜311 MJ/kg-DCW で、スペインの模擬（227）が真ん中あたりなので 200 MJ と置いた。**この試算でいちばん確度が低い行**（季節と昼夜の収支を計算していない。夏は余って冷やす側、冬と夜は足りない）。商用の藻の工場は加温しない: ハワイ（サイアノテック）・海南島と米国インペリアルバレー（DIC のスピルリナ）のように暖かい土地を選ぶか、冬は止める。45〜70℃が要る SX の株は、その逃げ道が無い。工場の排熱を使えるなら、この行の「排熱利用可能」を ON にすると0円になる。', 'amd_internal', 1037, null, null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_culture_power', '中央培養', 'OPEX', '培養', 'ユーティリティ', '培養の電力（撹拌・送液・散気）', '毎kg菌体比例', 2.0, 'kWh/kg-DCW', 17.45, '円/kWh', null, 1.0, null, false, 'H', '推測', '杉浦先生（CO2の入れ方）', '見積のない推測値。**この行は 2026-09-15 に新しく入れた**（それまで培養の電力は1円も入っていなかった）。撹拌・培養液の送り・CO2と空気の吹き込みに使う電力。脱水や油回収の電力（燃料化設備の行）とは別。確かめ方: 開放池のかき混ぜは、この試算の生産性（0.5 g/L/日）に直すと菌体1kgあたり0.05〜0.24 kWh（Richardson ら 2014・Slegers ら 2015 の 0.22〜0.91 W/m² から）。SX は閉鎖型の縦型・チューブ型なのでこれより重く、文献の幅は 0.33〜233.7 kWh/kg と広い。ここでは 2.0 kWh/kg-DCW と置いた。排ガスの CO2 を使うときは、濃さが数%〜2割なので吹き込む量が5〜20倍になり、この電力は上がる（いまは同じ値のまま）。空気（0.04%）から取る実験では CO2 1kgあたり2.9 kWh かかっている。買値は高圧受電の 17.45 円/kWh（燃料化設備の電力と同じ）。', 'amd_internal', 1038, null, null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_culture_blowdown', '中央培養', 'OPEX', '培養', 'ユーティリティ', '培養液の入れ替え（排水）', '毎kg菌体比例', 0.02, 'm³/kg-DCW', 345, '円/m³', null, 1.0, null, false, 'H', '推測', '杉浦先生（CO2の入れ方）', '見積のない推測値。**この行は 2026-09-15 に新しく入れた**（それまで培養の排水は1円も入っていなかった）。培養液は回して使うが、塩や増殖を止める物がたまるので一部を抜いて捨てる。確かめ方: 菌体1kgあたりの培養液は約200L（廃液の試算の閉鎖系の行と同じ置き方）で、その1割を入れ替えるとして 0.02 m³/kg-DCW。抜く割合の実測は文献にも無い（NREL も「管理が要る」と書くだけ）。単価 345 円/m³ は東京都の下水道料金の最上位区分（月1,000m³超、税別）。有機物が濃いと大阪市のような加算（BOD 350mg/L で +37円/m³）が付く。遺伝子組換え体（強化株・脂質分泌株）のときは、抜いた液を殺してから捨てる費用が別に要る（閉鎖系の追加の行）。', 'amd_internal', 1039, null, null, 'sx');
insert into project_cost_items (cost_model_id, cost_item_id, scenario, cost_type, group_label, mid_label, leaf_label, basis, quantity, quantity_unit, unit_price, unit_price_unit, price_rule, annual_factor, useful_life_years, is_breakdown, confidence, source_kind, owner, note, visibility, sort_order, strain, application, bearer) values ('cm_p21_fuel_260914', 'cif_culture_heat_capex', '中央培養', 'CAPEX', '培養設備', '加温・保温設備', '熱交換器・保温・温度制御', '初期投資配賦', 1, '式', 1500000, '円/式', null, 1.0, 7, false, 'H', '推測', 'AMD', '見積のない推測値。**この行は 2026-09-15 に新しく入れた**。培養液を45〜70℃に保つための熱交換器・保温・温度の制御。確かめ方: 培養槽本体（1,200,000円）と同じ桁で置いた。工場の排熱を使うときは、排熱を受ける熱交換器がこれにあたる（排熱でも設備は要るので、「排熱利用可能」を ON にしてもこの行は0円にならない）。', 'amd_internal', 1017, null, null, 'sx');
insert into project_cost_assumptions (cost_model_id, cost_assumption_id, group_label, label, value, value_text, unit, confidence, source_kind, owner, is_key, role_key, note, visibility, sort_order, strain, application) values ('cm_p21_fuel_260914', 'caf_waste_heat', '培養の原料・品質確認', '排熱利用可能', null, 'off', null, 'H', '推測', 'AMD（内部）', true, 'waste_heat', '培養の加温を、工場の排熱でまかなえるか。スイッチは「加温の熱」の行にある（まさ 2026-09-15「顧客の工場のCO2と排熱、排ガスをフル活用してやる方向も見えてくる」）。ON にすると加温の熱の単価を0円として計算する（MJ の量と買う熱の単価は行に残る）。培養ロス補充は原料の合計から出すので一緒に下がる。既定は OFF（熱を買う）。**SX の株は好熱性で45〜70℃で運転する**ので、加温は他の藻の事業より重い。工場の排熱（蒸気のドレン・冷却水・排ガスの熱）はちょうどこの温度帯なので、相性がいい（製鉄所の排ガス 50〜170℃で藻の縦型槽を温めた報告（Hu ら 2024）、米国デューク・エナジーの石炭火力の冷却水で藻の槽を温めた実証（2015年、CO2 の取り込み 日中平均44%）、日本では大崎クールジェン（広島、石炭ガス化＋CO2回収 1日400t）の隣で NEDO・IHI が藻の研究をしている）。0円は、排熱をタダでそのまま使えるときの上限で、次は入っていない: 熱を受ける熱交換器（CAPEX の行にある）、排熱の量が季節や工場の稼働で変わること、培養の拠点を工場の隣に置くしばり。', 'amd_internal', 314, null, null);
insert into project_cost_notes (cost_model_id, cost_note_id, section, title, body_md, source_url, source_label, visibility, sort_order) values ('cm_p21_fuel_260914', 'cnf_history_heat', 'history', '培養の加温・電力・排水を入れた（2026-09-15）', 'まさ 2026-09-15「顧客の工場のCO2と排熱、排ガスをフル活用してやる方向も見えてくる」（まさ「うん、進めて」）

**培養の加温・電力・排水は、これまで1円も入っていなかった**（426 で培養の原料を組み直したときからの積み残し）。入れないと「工場の排熱を使う価値」を数字にできないので、3行を足した。あわせて加温・保温の設備（CAPEX）も足した。

| 燃料1Lあたり（基準・委託） | 入れる前 | 入れた後 | 排熱 ON | 排熱＋排ガス＋排液 |
|---|---|---|---|---|
| 脂質分泌株を使わない | 6,033.4 | 15,657.4 | 6,941.5 | 2,928.7 |
| 脂質分泌株 | 1,289.7 | 1,598.3 | 1,399.6 | 1,129.1 |

**受光面積**: 1系列（培養液 222.2 m³）が1日に作る菌体 111kg を、面積あたりの生産性 25 g/m²/日 で割ると受光面積は約 4,444 m²。年5,000万Lの燃料には 27,068 系列（脂質分泌株で 21,429 系列）が要るので、**受光面積は約 120 km²（分泌株で約 95 km²）**。山手線の内側（63 km²）の約2倍。光合成が1日に固定できる炭素の量で決まるので、株や工程を変えても減らない。

**なぜ加温が重い**: SX の株は好熱性で、運転温度は45〜70℃（技術台帳「培養温度」。試作の47L装置にもヒーターが付いている）。光を通す面は断熱材で覆えないので、熱が逃げる。1系列の受光面積 約4,444 m²、二重の覆いで 3 W/m²K、培養45℃ − 外の年平均15℃ ＝ 30K として熱損失は約400kW（年10,400GJ ＝ 菌体1kgあたり約311MJ）。そのうち日射（年平均 約190 W/m² × 受光面積 ＝ 約840kW）でまかなえる分を70%とし、残りの93 MJ/kg-DCW を買う熱とした。

**ここがいちばん確度が低い**: 季節と昼夜の収支を計算していない。夏は余って冷やす側、冬と夜は足りない。大きな水の塊なので一晩では冷めにくいが、夜の熱損失だけで培養液が30K近く下がる計算になるため、覆いの断熱・夜間の保温・季節ごとの運転の止め方をどう置くかで、この行は数倍動く。

**排熱の相性**: 工場の排熱（蒸気のドレン・冷却水・排ガスの熱）は、ちょうど45〜70℃の温度帯。「排熱利用可能」を ON にすると加温の熱が0円になる。熱を受ける熱交換器は CAPEX の行に残る（排熱でも設備は要る）。', null, null, 'amd_internal', 24);
commit;
