-- Scope: waste cost model only. Transaction, drift guards, provenance and old/new change log.
begin;
select set_config('amd.cost_change_reason','487: まさ2026-10-07承認の好条件設計試算。自動化・光収支・回収率を仮説として採用し清掃等を計上。顧客総額500の枠とSOL料金を区別。実測・契約価格・月次計画の確定ではない。',true);
do $do$ begin
if not exists(select 1 from project_cost_items where cost_item_id='ci2_c_led_power' and quantity is not distinct from 108.9 and confidence is not distinct from 'H' and source_kind is not distinct from '推定' and note is not distinct from '推定値。**2026-09-22 に新しく入れた**（まさ 2026-09-22「光はLEDで当ててるよ。どのくらいの光量を当てたらいいのかは先生も知らない。なので推定して入れてほしい」）。LED の電気代は、光の強さの選び方より、**菌体1kgを作るのに光合成に使える光の粒（光子）が何モル要るか**で決まる。出し方: 1,000 g ÷ 光に対する菌体の収率 1.0 g/mol ÷ 培養液に吸われる割合 0.85 ÷ LED の光合成光量子効率 3.0 μmol/J ＝ 392,156,863 J ＝ 108.9 kWh/kg-DCW。**収率 1.0 g/mol**: シアノバクテリア Synechocystis の実測 1.0〜1.72 g/mol（赤色の光・中程度の強さ。PLOS ONE の藍藻と緑藻の比較研究）、連続培養のエネルギー収支で 1.24 g/mol（Touloupakis ら）、緑藻 Chlorella・Dunaliella の平板型の培養槽で 0.6〜0.8 g/mol（Zijffers ら 2010）。窒素源が硝酸のときの理論上の上限は 1.5 g/mol（同じ Zijffers ら 2010。光子8個で CO2 1分子という単純な値 約3 g/mol は、窒素を還元する分の光を数えていない）。SX の株（好熱性）の実測は無いので、上限の3分の2で置いた。**吸われる割合 0.85**: 文献値は見つからず、培養槽の設計で光を吸い切る前提の見当（0.7〜0.95）。**光合成光量子効率 3.0 μmol/J**: 園芸用 LED の業界基準（DLC 園芸照明 V4.0、2025年）の下限が 2.5、いまの上位の製品が 3.0〜3.3。**確かめ方**: 人工光で藻を育てる技術経済評価（Blanken ら 2013、Algal Research「Cultivation of microalgae on artificial light comes at a cost」）は、電気が菌体の化学エネルギーになる割合を4〜6%としていて、逆算すると菌体1kgあたり 92〜168 kWh。この行はその範囲に入る。同じ論文は、人工光は高く売れる製品でなければ割に合わないとしている。**幅**: 収率 0.6〜1.5 g/mol・効率 2.5〜3.5 μmol/J で、菌体1kgあたり 60〜230 kWh くらい動く。**加温との関係**: LED に入れた電気はほぼすべて熱になる（菌体1kgあたり約392 MJ）。加温の熱の見積（200 MJ/kg-DCW、屋外で日射を受ける前提）を上回るので、LED の熱を培養液に回せる室内の設計なら、加温の熱の行はほぼ0円になり、逆に冷やす費用が要ることもある。いまは両方を数えている（その分だけ多めに出ている）。**光の強さの目安**: 1系列（1日111kg）が要る光は毎秒約1.5 mol（排液で増える速さの倍率が1のとき）。光の強さを 300 μmol/m²/s にすると、照らす面は約5,000 m²。シアノバクテリアの培養では、実験室で 50〜200、好熱性の株の実証に近い平板型で 500〜2,000 μmol/m²/s が使われている。培養の電力（撹拌・送液・散気）の行とは別。買値は高圧受電の 17.45 円/kWh（燃料化設備の電力と同じ）。') then raise exception '487: input drift ci2_c_led_power'; end if;
if not exists(select 1 from project_cost_items where cost_item_id='ci2_c_led_capex' and quantity is not distinct from 15.1 and unit_price is not distinct from 315 and useful_life_years is not distinct from 7 and note is not distinct from '推定値。**2026-09-22 に新しく入れた**（まさ 2026-09-22「光はLEDで当ててるよ。どのくらいの光量を当てたらいいのかは先生も知らない。なので推定して入れてほしい」）。作る菌体が増えるとその分だけ器具が要るので、系列ではなく**菌体1kgあたりの量**で持つ（系列の大きさや、排液で増える速さの倍率では薄まらない。速く増やすにはその分の光が要る）。数量は、年に1kg作るのに置く LED の電力 ＝ 108.9 kWh ÷ 1年に点ける時間 7,200時間（300日 × 24時間、ずっと点ける前提）＝ 15.1 W。単価は、業務用の園芸用 LED の価格 1 μmol/s あたり 0.4〜1.0 ドル（Fluence の SPYDR など、2025年）の真ん中 0.7 ドル、1ドル150円、3.0 μmol/J で 315円/W。耐用年数は、寿命 50,000時間（L90。業務用で 50,000〜90,000時間）÷ 7,200時間 ＝ 約7年。初期投資は 15.1 W × 315円 ＝ 菌体を年に1kg作るごとに約4,756円。1日のうち点ける時間を短くすると、同じ光を短い時間で当てるので器具は増える（16時間なら1.5倍、電気代は同じ）。大量に買ったときの値引きは入れていない。確かめ方: 同じ規模の植物工場・藻の培養施設の照明の見積（器具1台の値段と、1台が出す光 μmol/s）を取り、1 μmol/s あたりの値段で比べる。') then raise exception '487: input drift ci2_c_led_capex'; end if;
if not exists(select 1 from project_cost_assumptions where cost_assumption_id='ca_recovery_eta' and value is not distinct from 90.0 and confidence is not distinct from 'H' and source_kind is not distinct from '仮置き' and owner is not distinct from '中島先生' and note is not distinct from 'V-501。00_変数辞書 Mid/プロセス分解P2。2026-09-15 から、処理のあと回収して次のバッチへ回せる菌体の割合として使う（中島先生 2026-08-28 のレビュー「回収率と初回必要投入量が混同されている」「回収率は「次バッチへ再利用できる量」に使用」、ちこさん 2026-09-15 の指摘）。毎バッチ、前のバッチから回した菌体に新しい菌体を足して、1バッチに要る菌体（（流入の濃さ − 目標放流水濃度）÷ 取り込み効率）にそろえる。回した菌体は1回ごとに η 倍になり、使用回数を使い切ったら入れ替えるので、新しく入れる菌体 ＝ 1バッチに要る菌体 ×（1 − η）÷（1 − η^使用回数）。色素分解（使用回数10回）では、90%で要る量の15.4%、95%で12.5%、98%で10.9%、100%で10.0%（使用回数で割るだけ）。使用回数1回の金属回収には効かない（毎バッチ要る量をそのまま新しく入れる）。回収できずに失う菌体と、使用回数を使い切って入れ替える菌体は、この新しく入れる量に入るので、明細の「菌体ロス補充分」「菌体性能低下による交換・再生分」は0円にした。確かめ方: 装置（循環カートリッジ・直接投入）ごとに、処理のあと次のバッチへ回せる菌体の割合を中島先生に聞く（確認事項）。2026-07 の設備アドオン試算は、色素分解の運転ロスを2%（回収率98%にあたる）で置いていた。前の使い方（2026-09-15 まで）: 必要な菌体を η で割っていた（260820版の③シートと同じ式。金属50ppm ÷ 取り込み効率0.05 ÷ 0.9 ＝ 1,111 g/m³）。') then raise exception '487: input drift ca_recovery_eta'; end if;
if not exists(select 1 from project_cost_tasks where cost_task_id='ct_run_injection' and hours_per_occurrence is not distinct from 7.5 and confidence is not distinct from 'A' and source_kind is not distinct from '先生回答' and owner is not distinct from '中島先生' and note is not distinct from '出所：中島試算シート100m³ケース②投入。手動運用のときの時間。自動制御の無人運転で何時間まで減るかは未確認（ダイキアクシスへ確認中）。 オフサイトでも、同じ運転をSX工場で行う前提で同じ時間を使う。 作業を誰がやるかは「処理する場所の人」: オンサイトでは顧客がやる作業として、SXの原価にも作業時間にも入れない（2026-09-14 まさ「全顧客の工場にSXの社員が張り付くってありえない」）。オフサイトではSX工場でSXがやるので、SXの原価に入れる。') then raise exception '487: input drift ct_run_injection'; end if;
if not exists(select 1 from project_cost_tasks where cost_task_id='ct4_culture_operation' and hours_per_occurrence is not distinct from null and confidence is not distinct from 'H' and source_kind is not distinct from '仮置き' and owner is not distinct from '杉浦先生・中島先生' and note is not distinct from '毎日の培養の管理と、菌体を濃縮して出荷できる状態にする作業。1日あたりの工数が分かっていないので空欄（未確認）にしている。年間回数は稼働日と同じ300日で置いた。工数が分かれば、菌体1kgの原価に入る。 2026-09-14 から、培養設備の系列ごとの作業として数える（1系列あたり年300日 × 系列数）。') then raise exception '487: input drift ct4_culture_operation'; end if;
if not exists(select 1 from project_cost_tasks where cost_task_id='ct4_post_dye' and hours_per_occurrence is not distinct from null and confidence is not distinct from 'H' and source_kind is not distinct from '仮置き' and owner is not distinct from 'ダイキアクシス' and note is not distinct from '使用済み菌体を脱水し、汚泥として処分業者へ引き渡すまでの作業。工数は未確認で空欄。処分費は明細の「使用済み菌体の処分」に積んでいる。 2026-09-14 から、オンサイトでは顧客工場で出る汚泥として顧客がやる。SX工場で処理するオフサイトではSXがやる。') then raise exception '487: input drift ct4_post_dye'; end if;
if not exists(select 1 from project_cost_assumptions where cost_assumption_id='ca_sale_price' and label is not distinct from '想定売上単価（オンサイト）' and note is not distinct from '既存処理コスト500円/m³前後という前提から置いた値。用途別の実勢価格では未検証。 オンサイト（顧客工場で処理）の売価。オフサイトは「想定売上単価（オフサイト）」を別に置く（2026-09-14 まさ）。') then raise exception '487: input drift ca_sale_price'; end if;
if not exists(select 1 from project_cost_assumptions where cost_assumption_id='ca11_offsite_annual_volume' and label is not distinct from '年間処理量（オフサイト）' and note is not distinct from 'オフサイト（顧客の排液をSX工場まで運んで処理）は、将来サイドビジネスとして足す形で、オンサイトと別に年間処理量を置く（2026-09-14 まさ「オフサイトは売価も処理量も別に分けて試算したい」「将来的にサイドビジネス的に、オフサイトもやれたらいいかなっていうくらいのadditionalな要素」）。30,000m³/年は、SX工場1か所がいまの前提（100m³/日 × 300日）で処理する量として置いた仮置き。オフサイトの売上・事業全体の年間・顧客数はこの量で出す。菌体の製造拠点で年に作る量は、この量にオフサイトの濃さで使い切る菌体量を掛けて、オンサイトの分に足して計算する（同じ製造拠点で作る）。') then raise exception '487: input drift ca11_offsite_annual_volume'; end if;
if not exists(select 1 from project_cost_assumptions where cost_assumption_id='ca_batch_volume' and label is not distinct from 'バッチ容量' and note is not distinct from '出どころ: ちこさんの試算シート 2026-08-20版の共通前提「バッチ容量 100 m³/バッチ」（メモなし）。同じ表の日処理量 100m³/日のメモは「260812打合せ：m³/日基準」（中島先生との打合せ）。1日1バッチとして、年間バッチ数 ＝ 稼働日/年 × 稼働率。確かめ方: 顧客工場の調整槽の容量と、1日に処理する量を聞いて比べる。') then raise exception '487: input drift ca_batch_volume'; end if;
if not exists(select 1 from project_cost_models where cost_model_id='cm_p21_260820' and version_label is not distinct from '260914版' and summary_md is not distinct from 'SXの排液処理を、**菌体の製造原価**と**用途別の処理原価**の二段階で試算する。

**事業の規模は売上10,000,000,000円** — IPOできる大量生産の状態を前提に、年間処理量を20,000,000m³/年で置く（売価500円/m³で売上10,000,000,000円。2026-09-14 まさ）。顧客1社あたり年30,000m³なら約667社分。**オフサイトは、将来サイドビジネスとして足す形で、売価と年間処理量をオンサイトと別に置く**（仮置き 50,000円/m³＝1Lあたり50円・30,000m³/年。2026-09-14 まさ「ペインがあれば割高でも成立するから」）。引き取る液は顧客工場の排水より濃いので、対象物質の濃度もオフサイトだけ別に置く（仮置き 色素1,000mg/L・金属5,000ppm。2026-09-14 まさ「置いて」）。菌体の製造拠点で年に作る量は、色素分解が株によらず約2,855t、金属回収が自然株で約22,612t・強化株で約17,919t（強化株は金属の取り込み効率が高い）。

**第1段 菌体の製造原価** — 株（強化株／自然株）ごとに、菌体の製造拠点で乾燥菌体1kgをつくる原価を出す。菌体の製造拠点は、顧客工場では培養せず、SX側でまとめて菌体を育て、濃縮して各工場へ運ぶところ。**年に作る量は計算で出す**（（オンサイトの年間処理量 × オンサイトで使い切る菌体量 ＋ オフサイトの年間処理量 × オフサイトで使い切る菌体量）÷ 販売率）。今の明細を培養設備の1系列として必要な数だけ並べるので、設備・固定費・系列ごとの作業は1kgあたり変わらず、拠点に1つの作業だけが量で薄まる。同じ株なら、1kgあたりの原価は用途でほとんど変わらない（自然株で3,521.0円、強化株で色素分解 3,542.5円・金属回収 3,542.4円。工場の排熱・排ガス・排液を使わないとき。2026-09-15 に培養の加温・電力・排水を、2026-09-22 に培養の LED の照明を足した）。いちばん大きいのは LED の照明（電気代 1,900円・器具 680円。光の量は推定）で、次が加温の熱（460円）。菌体の量に比例する培養の原料（窒素源・リン源・CO2・水など）は、菌体の成分と公開の買値から「使う量 × 買値」で置いている（2026-09-14、菌体1kgあたり274.6円のうちCO2 114.5円・窒素源 90.8円）。強化株は閉鎖系の追加費用が乗る。生産した菌体のうち売れる割合（販売率）で割るので、売れ残りが出ると1kgあたりの原価は上がる。

**第2段 用途別の処理原価** — 第1段の原価を一定として、色素分解と金属回収のそれぞれで排水1m³あたりの総コストを出す。用途で変わるのは、必要な菌体の量（1バッチに要る菌体 ＝（流入の濃さ − 目標放流水濃度）÷ 取り込み効率 を、回収率と菌体使用回数から毎バッチ新しく入れる量にしたもの。2026-09-15 から）と、使用済み菌体の後処理（金属回収は中央回収設備の償却を含む）。対象物質の濃度はオフサイトだけ別に置くので、同じ用途でもオフサイトは使い切る菌体の量が多い（金属回収で約125倍、色素分解で約22倍）。菌体を使い回せるのは色素分解だけで、金属回収は酸で菌体を溶かして金属を取り出すので、使用回数は1回で固定する。色素分解は10回使い回す前提で置いている（2026-07の設備アドオン試算と同じ。杉浦先生に確認中）。

**方式と装置を分けて並べる** — 方式は、顧客工場で処理するオンサイトと、排液をSX工場まで運んで処理するオフサイトの2つ。装置は、菌体を筒に閉じ込めて排液を通す循環カートリッジと、菌体を槽に入れて混ぜ膜でこし取る直接投入の2つで、どちらの方式でも選べる。

**SXの原価に入れるのはSXがやる作業だけ** — 顧客工場での処理の運転は顧客がやる作業として、SXの原価にも作業時間にも入れない。オフサイトではSX工場でSXが運転するので、SXの原価に入る。

**顧客工場の設備・装置の費用と汚泥の処分は顧客が持つ** — 顧客工場に置くリアクター（処理設備）と槽は顧客が買い、装置を動かす消耗品・電力・点検・交換部品（循環カートリッジの菌体保持モジュールを含む）、処理水の分析と薬剤、顧客工場で出る使用済み菌体の汚泥の処分も顧客が持つ（2026-09-14 まさ）。いずれもSXの原価に入れない。オンサイトでSXの原価に残る現場の費用は、菌体を運ぶ巡回と容器（回収できずに失う菌体の補充は、2026-09-15 から菌体費に入る）、モジュールや膜の交換の作業、立入制限と教育訓練（強化株）。明細ごとに誰が持つか（SX / 顧客 / 処理する場所の持ち主）を持ち、画面で変えられる。SX工場で処理するオフサイトでは、設備・槽・装置の費用・汚泥の処分はSXが持つ。

操作パネルで株・用途・方式・装置を切り替え（開いたときは自然株）、前提・作業リスト・明細の数字を書き換えると、結果がその場で再計算される。前提・作業リスト・明細は「事業と処理の条件」「CAPEX（初期投資）」「OPEX（毎年の費用）」の3つに分け、その中を小分けにして並べる。作業単価はすべての作業に共通の1つ。選んだ組み合わせで使わない前提・作業・明細は薄く出る。結果の欄には総コストの内訳を棒グラフで出し、操作パネルの一番上には作業の流れと段ごとの年間工数を出す。書き換えた数字は保存されない。正本へ書くのは、管理者が「この値を保存」を押したときだけ。

ちこ作成の260820版の明細を土台に、2026-09-13に二段階へ組み替えた。人件費・巡回サービス・閉鎖系の追加費用・色素用の後処理・色素の濃さを追加し、いずれも確度つきで置いている。同日、人件費を作業リスト（作業ごとの工数 × 作業単価）で持つ形に変え、販売率を足した。さらに同日、作業を流れの段に並べ直し、オフサイトの比較を足した。2026-09-14 に、方式（オンサイト / オフサイト）と装置（循環カートリッジ / 直接投入）を分け、作業ごとに誰がやるかを持たせた。同日、色素分解の菌体使用回数を10回にし、顧客工場のリアクター・槽と汚泥の処分を顧客が持つ形にした。同日、年間生産能力を入力から外し、年間処理量（売上10,000,000,000円に届く20,000,000m³/年）から年に作る量を計算する形にした。同日、作業単価をすべての作業に共通の1つにし、前提・作業リスト・明細を「事業と処理の条件 / CAPEX / OPEX」の区分に並べ直した。同日、上端の槽の表示を外し、選んだ組み合わせで使わない前提を薄く出すようにした。同日、顧客工場の装置の消耗品・電力・点検・交換部品を顧客の持ち分にし、オフサイトの循環カートリッジの処理の運転をSXの作業にした。同日、金額をカンマ区切りの円にそろえた（10,000,000,000円の形。億・万で丸めない）。同日、オフサイトの売価と年間処理量をオンサイトと別の前提に分けた。' and system_scope_md is not distinct from '**対象** — 工場排液を、生きたシアノバクテリア（藍藻）で処理する。用途は色素分解と金属回収の2つを並べる。

**規模** — オンサイトで年間 20,000,000 m³（売価500円/m³で売上10,000,000,000円。IPOできる大量生産の状態、2026-09-14 まさ）。オフサイトは将来のサイドビジネスとして、年間 30,000 m³・売価50,000円/m³（1Lあたり50円）で別に置く（仮置き、2026-09-14 まさ）。引き取る液の濃さも別に置く（仮置き 色素1,000mg/L・金属5,000ppm。オンサイトは色素50mg/L・金属50ppm。2026-09-14 まさ）。顧客工場1拠点あたり 100 m³/日 × 300 日/年 ＝ 30,000 m³/年で、約667社分。1バッチ100 m³、反応時間（HRT）4時間のバッチ運転。

**第1段：菌体は菌体の製造拠点で作る** — 顧客工場では培養せず、SX側でまとめて菌体を育て、濃縮して各工場へ運ぶ。年に作る量 ＝（年間処理量（オンサイト）× オンサイトで使い切る菌体量 ＋ 年間処理量（オフサイト）× オフサイトで使い切る菌体量）÷ 販売率（入力ではなく計算。2026-09-14 まさ）。今の明細を培養設備の1系列（年33,333kg、仮置き）として、年に作る量 ÷ 1系列 の数だけ並べ、1拠点に置く。乾燥菌体1kgあたりの原価は、「(設備の償却年額 ＋ 年ごとの固定費 ＋ 製造拠点の作業) ÷ 年に作る量 ＋ 菌体量に比例する費用」を販売率で割って出す。設備・固定費・系列ごとの作業（培養の運転・密閉性能検査・除菌フィルター交換）は系列の数だけ増え、拠点に1つの作業（安全委員会の運営など）は増えない。量産で設備や原料をまとめて買ったときの値下がりは入れていない。

**第2段：方式と装置を分けて比較する**

方式（どこで処理するか）
- **オンサイト** — 顧客工場の槽の横に、顧客が買ったリアクター（装置）を置いて処理する。処理の運転と、使用済み菌体の汚泥の処分は顧客がやる。装置を動かす消耗品・電力・点検・交換部品と、処理水の分析・薬剤も顧客が持つ（2026-09-14 まさ）。SXは菌体の搬入・搬出や交換で巡回する。槽は、既存調整タンクの流用でも新設でも顧客の設備
- **オフサイト** — 排液をタンクローリーでSX工場まで運び、SX工場に新設する槽で処理する。処理の運転はSXがやり、処理水はSX工場から流す。顧客工場への巡回と、顧客工場内の区画・立入制限は発生しない。代わりに、排液の輸送・受け入れ・放流の費用が乗る。設備・槽・装置の費用・汚泥の処分はSXが持つ。処理の運転は、循環カートリッジも直接投入もSXがやる

装置（菌体と排液をどう触れさせるか。どちらの方式でも選べる）
- **循環カートリッジ** — 菌体をカートリッジ内の保持モジュールに留め、排液を循環させて接触させる。モジュールは耐用バッチ数ごとに交換する
- **直接投入** — 菌体を槽へ直接投入して撹拌し、反応後に UF/MF 膜で菌体を分離回収する。膜は約3年で交換する

**槽** — オンサイトの槽は顧客の設備（既存調整タンクの流用でも新設でも）で、SXの原価に入らない（2026-09-14 まさ）。オフサイトは SX工場にコンクリート地下タンク100 m³（18,000,000円・10年償却）を新設する。用途ごとに、オンサイト2通り（装置2）とオフサイト2通り（装置2）の4シナリオになる。オンサイトの槽をSXが持つ形に変えると、既設（0円）／新設の2通りに戻る。

**使用済み菌体の後処理** — 金属回収は、SXが使用済み菌体を引き取って酸で溶かし、金属を回収する（SXの原価）。酸で溶かし中和・固液分離をする中央回収設備の初期投資も、使用済み菌体1kgあたりの償却として入れている（2026-09-15 から。見積は無い）。色素分解は使用済み菌体を脱水汚泥として処分し、オンサイトでは顧客がやる（SXの原価に入れない）。

**菌体の量** — 1バッチに要る菌体 ＝（流入の濃さ − 目標放流水濃度）÷ 取り込み効率。回収率は、処理のあと回収して次のバッチへ回せる菌体の割合として使い、使用回数（色素分解10回・金属回収1回）と組み合わせて、毎バッチ新しく入れる菌体を出す（菌体のバッチ間のマスバランス。中島先生 2026-08-28 のレビュー、2026-09-15 から）。回収できずに失う分と、使用回数を使い切って入れ替える分はこの量に入る。菌体の製造拠点で培養に失敗して作り直す分（培養ロス補充）は、別に菌体1kgの原価に入れている。金属の取り込み効率は24時間の単回試験の値で、反応時間4時間とはそろっていない。

**オンサイトの設備は独立プラント新設ではなく増分アドオン** — 顧客の既存調整タンク・排水ライン・ユーティリティ・主処理設備を使い、密閉接触・循環、菌体捕捉、回収サービスを足す（2026-07-23 確定）。このリアクターは顧客が買う（2026-09-14 まさ）。

**収益モデル** — 処理費のみ。売価はオンサイト500円/m³、オフサイト50,000円/m³（自社で処理しにくい液を引き取る値段）。回収物（金属など）の売却収入はまだモデルに入れていない。

**作業（人件費）** — 総コストに入れる（2026-09-13 まさ指示）。作業リストに、作業ごとの1回の工数・年間回数・1回の経費を置き、年額 ＝ 年間回数 ×（工数 × 作業単価 ＋ 経費）で積む。作業単価はすべての作業に共通の1つ（前提の「作業単価（共通）」、2026-09-14 まさ）。作業ごとに誰がやるか（SX / 顧客 / 処理する場所の人）を持ち、**SXの原価に入れるのはSXがやる作業だけ**。処理の運転は中島先生の試算にある手動運用の作業時間で置き、オンサイトでは顧客の作業（SXの原価にも作業時間にも入れない）、オフサイトではSXの作業とする（2026-09-14 まさ）。菌体の搬入・搬出、移動、モジュール・膜の交換、閉鎖系の検査や安全委員会も同じリストに並べる。作業は流れの段（菌体をつくる → 菌体を運ぶ／排液を運ぶ → 排液を処理する → 設備を保つ → 使用済み菌体を後処理する → 閉鎖系を管理する）の順に並べ、段ごとの年間工数を出す。' and target_total_cost_per_m3 is not distinct from 300 and target_note is not distinct from '2026-07-24 SX定例で置いた総コスト目標。既存処理コスト500円/m³前後に対して300円/m³を狙う。売価500円のままなら利益率40%に相当する。 オンサイト（売価500円/m³）に対する目標。オフサイトは売価を別に置くので、この目標と比べず売価との差だけを見る（2026-09-14）。' and source_note is not distinct from '原典: Google Sheets SX_コスト試算_260820 (ちこ)。中島先生の設備・運用想定を反映した版。 2026-09-13 に二段階版へ組み替え（migration 393）。 同日、作業リストと販売率を足した（migration 394/395）。 同日、作業の流れの段、オフサイトの比較、金属回収の使用回数の固定を足した（migration 396/397）。 2026-09-14、方式と装置を分け、作業に誰がやるかを持たせた（migration 398/399）。 同日、顧客がやる作業の時間を画面と注記から外した（migration 400）。 同日、色素分解の菌体使用回数を10回にし、明細に誰が持つかを持たせ、顧客工場のリアクター・槽と汚泥の処分を顧客の持ち分にした（migration 402/403）。 同日、年間生産能力を入力から外し、年間処理量（売上10,000,000,000円）から年に作る量を計算する形にした（migration 404/405）。 同日、作業単価を共通の1つにし、前提・作業リスト・明細を「事業と処理の条件 / CAPEX / OPEX」の区分に並べ直した（migration 406/407）。 同日、上端の槽の表示を外し、選んだ組み合わせで使わない前提を薄く出すようにした（migration 409）。 同日、顧客工場の装置の消耗品・電力・点検・交換部品を顧客の持ち分にし、オフサイトの循環カートリッジの処理の運転をSXの作業にした（migration 410）。 同日、文章の中の金額をカンマ区切りの円にそろえた（migration 416）。 同日、オフサイトの売価と年間処理量をオンサイトと別の前提に分けた（migration 419）。') then raise exception '487: input drift cm_p21_260820'; end if;
if not exists(select 1 from project_cost_notes where cost_note_id='cn2_c8' and body_md is not distinct from '作業リストの「処理の運転」は、中島先生の試算にある1バッチあたりの作業時間（循環カートリッジ5.75時間、直接投入7.5時間）で置いている。

**オンサイトでは、顧客工場での処理の運転は顧客がやる**（2026-09-14 まさ「全顧客の工場にSXの社員が張り付くってありえない」）。SXの原価にも、SXの作業時間にも入れない。

**オフサイトでは、SX工場でSXが運転する**ので、同じ時間をSXの作業として原価に入れる（循環カートリッジ 230円/m³、直接投入 300円/m³。2026-09-14 まさ「オフサイトならSX」）。自動制御で無人運転に近づけたときの数字は、工数を下げて見る。

誰がやるかは作業リストの「誰がやるか」で変えられる。SXが運転まで請け負う形にすると、オンサイトでもSXの原価に入る。') then raise exception '487: input drift cn2_c8'; end if;
if not exists(select 1 from project_cost_notes where cost_note_id='cn_260820_c4' and body_md is not distinct from '乾燥菌体1kgの原価は、菌体の製造拠点の費用を、年に作る菌体の量で割って出す。

**年に作る量は計算で出す**（2026-09-14 まさ「年間の生産能力は入力値じゃなくて計算結果にしてほしい」）。年に作る量 ＝（年間処理量（オンサイト）× 排水1m³あたりに使い切る菌体量 ＋ 年間処理量（オフサイト）× 引き取る液1m³あたりに使い切る菌体量）÷ 販売率。オンサイトは、IPOできる規模として売上10,000,000,000円に届く20,000,000m³/年で置いている（売価500円/m³）。オフサイトはサイドビジネスとして30,000m³/年（仮置き）を足し、引き取る液の濃さ（仮置き 色素1,000mg/L・金属5,000ppm）で使い切る菌体量を出す。用途ごとに、その用途だけでこの量を処理したときとして計算する（2026-09-22 の前提で、色素分解は株によらず約2,855t/年、金属回収は自然株で約22,612t/年・強化株で約17,919t/年）。

**設備は系列を並べて増やす**。今の明細（培養設備一式・濃縮・保管、強化株は閉鎖系の追加）を1系列とし、1系列で年33,333kgを作れる前提（仮置き）で、年に作る量をこの量で割った数だけ系列を並べる（自然株で色素分解 約86系列、金属回収 約678系列。強化株は色素分解 約86系列、金属回収 約538系列）。培養の LED 照明器具（2026-09-22）は、系列ではなく作る菌体1kgあたりの量で持つ設備で、製造拠点の初期投資の大半を占める（初期投資の合計は、自然株で色素分解 約14,328,900,000円・金属回収 約113,475,600,000円。強化株は閉鎖系の追加で1系列が高く、色素分解 約14,525,900,000円・金属回収 約91,160,500,000円。工場の排熱・排ガス・排液を使わないとき）。設備の初期投資・年ごとの固定費・系列ごとの作業（培養の運転、密閉性能検査、除菌フィルター交換）は系列の数だけ、LED 照明器具は作る量だけ増えるので、1kgあたりは変わらない。工場の排液を培地に使うときは、排液で増える速さの倍率（4倍）で系列が4分の1になる。拠点に1つの作業（安全委員会の運営など）だけが、作る量が増えるほど1kgあたり薄まる。量産で設備や原料をまとめて買ったときの値下がりは入れていない。

**販売率**（既定100%）は、作った菌体のうち売れる割合。下げると、売る量を確保するために作る量が増え、系列ごとの費用と菌体量に比例する費用が増える。

1系列の年間生産能力（33,333kg/年）は、旧版が暗黙に置いていた「必要な菌体量＝生産量」を引き継いだ仮置き。培養液1Lあたりの1日の増殖量と1系列の培養容積が分かるまで確定しない。') then raise exception '487: input drift cn_260820_c4'; end if;
if not exists(select 1 from project_cost_notes where cost_note_id='cn_260820_c6' and body_md is not distinct from 'このタブ上部の方式・装置ごとの総コストと総コスト目標300円/m³は、工場排液を処理する事業のモデル。バイオ燃料の140〜280円/Lは、販売価格と粗利率から逆算した**許容原価**で、現在の製造原価ではない。単位も工程範囲も異なるため合算・直接比較しない。') then raise exception '487: input drift cn_260820_c6'; end if;
if not exists(select 1 from project_cost_notes where cost_note_id='cn_260820_r1' and body_md is not distinct from '- **第1段 菌体の製造原価** — 株ごとに、乾燥菌体1kgをつくる原価。年に作る量は年間処理量から計算し、培養設備を系列の数だけ並べる。培養設備の償却・年ごとの固定費・製造拠点の作業・菌体量に比例する費用に分け、販売率で割って見る
- **菌体費** — 第1段の原価 × 排水1m³あたりに使い切る菌体量
- **運ぶ（巡回・輸送）** — オンサイトは顧客工場への菌体の搬入・搬出と移動、オフサイトは排液の輸送。作業リストの工数・経費と、共通の作業単価で動かす
- **運転・保守・管理** — SXがやる、運ぶ以外の作業（オフサイトの処理の運転、モジュールや膜の交換、閉鎖系の管理など）
- **顧客がやる作業** — オンサイトの処理の運転など。SXの原価にも作業時間にも入れない
- **顧客が持つ明細** — オンサイトのリアクター（処理設備）と槽、装置を動かす消耗品・電力・点検・交換部品、処理水の分析と薬剤、汚泥の処分。SXの原価に入れない（明細の「誰が持つか」で変えられる）
- **使用済み菌体の後処理** — SXが持つ後処理。金属回収は酸処理。色素分解の汚泥の処分は、オンサイトでは顧客が持つので入らない（オフサイトだけ）
- **消耗品・電力・放流など** — オンサイトは菌体を運ぶ容器だけ（回収できずに失う菌体の補充は、2026-09-15 から菌体費に入る）。オフサイトは、SX工場の装置の消耗品・電力・点検・交換部品、処理水の分析と薬剤、放流費
- **設備と槽の償却** — SXが持つ処理設備と槽、金属回収の中央回収設備（2026-09-15 から）の初期投資 ÷ 耐用年数。オンサイトのリアクターと槽は顧客が買うので入らない（オフサイトはSX工場の設備と槽）
- **うち閉鎖系の追加** — 強化株のときだけ乗る費用。上の区分に含まれている分を、第1段の分と合わせて出す
- **総コスト** — 売価（オンサイト500円/m³、オフサイト50,000円/m³）に対して成立するか。総コスト目標はオンサイトにだけ当てる
- **オンサイトの年間 / オフサイトの年間** — 選んだ方式の年間処理量と売価での売上・総コスト・利益。顧客1社の年間を、顧客の数だけ足したもの') then raise exception '487: input drift cn_260820_r1'; end if;
if exists(select 1 from project_cost_assumptions where cost_assumption_id='ca_amie_customer_total_budget') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_assumptions where cost_assumption_id='ca_amie_customer_residual_cost') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_assumptions where cost_assumption_id='ca_amie_unpriced_extra_cost') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_assumptions where cost_assumption_id='ca_amie_culture_cooling_cop') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_assumptions where cost_assumption_id='ca_amie_flue_gas_co2_percent') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_assumptions where cost_assumption_id='ca_amie_flue_gas_pressure_pa') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_assumptions where cost_assumption_id='ca_amie_flue_gas_blower_efficiency') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_assumptions where cost_assumption_id='ca_amie_business_overhead_annual') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_items where cost_item_id='ci_amie_cooling') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_items where cost_item_id='ci_amie_flue_gas') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_items where cost_item_id='ci_amie_overhead') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_tasks where cost_task_id='ct_amie_tank_cleaning') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_tasks where cost_task_id='ct_amie_fault_response') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_notes where cost_note_id='cn_amie_hearing_scope') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_notes where cost_note_id='cn_amie_optimistic') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_notes where cost_note_id='cn_amie_savings') then raise exception '487: already applied'; end if;
if exists(select 1 from project_cost_notes where cost_note_id='cn_amie_history_261008') then raise exception '487: already applied'; end if;
end $do$;
do $constraint$ begin if not exists(select 1 from pg_constraint where conname='project_cost_items_price_rule_check' and conrelid='project_cost_items'::regclass and pg_get_constraintdef(oid)='CHECK (((price_rule IS NULL) OR (price_rule = ANY (ARRAY[''biomass''::text, ''broth''::text, ''module_swap''::text, ''power_circulation''::text, ''power_injection''::text, ''spent_disposal''::text, ''co2_supply''::text, ''culture_loss''::text, ''medium_supply''::text, ''heat_supply''::text, ''recovery_capex''::text]))))') then raise exception '487: price rule constraint drift'; end if; end $constraint$;
alter table project_cost_items drop constraint project_cost_items_price_rule_check;
alter table project_cost_items add constraint project_cost_items_price_rule_check check(price_rule is null or price_rule in ('biomass','broth','module_swap','power_circulation','power_injection','spent_disposal','co2_supply','culture_loss','medium_supply','heat_supply','recovery_capex','culture_cooling','flue_gas_transport','business_overhead'));
update project_cost_items set quantity=52.68426321057899,confidence='H',source_kind='推定',note='好条件の工学仮定。菌体収率1.5g/吸収光子mol、吸収率95%、器具効率3.7µmol/J。1000÷1.5÷0.95÷3.7÷3.6＝52.684kWh/kg。SOL株の実測ではない。入射光あたり1.425g/molは参考のシアノバクテリア約1.5g/molを超えない。短光路と混合を要する。数量を変える場合は器具容量も照合。根拠: https://link.springer.com/article/10.1007/s10126-010-9258-2 、https://www.usa.lighting.philips.com/application-areas/specialist-applications/horticulture/greenpower-specialist-applications/led-toplighting 。加温購入費は排熱ONで0、冷却電力は別計上。' where cost_item_id='ci2_c_led_power';
update project_cost_items set quantity=7.317258779247082,unit_price=388.5,useful_life_years=5,note='好条件の設計仮定。52.684kWh/kg÷7200h×1000＝7.317W/(年産kg)。光子量の買値105円/(µmol/s)を維持し、3.7µmol/Jで388.5円/W。価格を値下げしていない。器具36,000h÷年7200h＝5年。園芸器具の仕様を参考とし、培養への適合・配線・防水・冷却機器の見積は未確認。光路2cm・800µmol/m²/s・菌体5g/Lなら1系列133,332kg/年に照射面約4512m²、液量約90m³、LED約976kWが要る。既存873万円/系列の本体設備がこの規模を満たす見積ではない。' where cost_item_id='ci2_c_led_capex';
update project_cost_assumptions set value=98,confidence='H',source_kind='推定',owner='AMD（内部）',note='好条件の設計仮定。2026-07設備アドオン試算の運転ロス2%を採用。処理後に次バッチへ回せる菌体98%であり、金属回収には効かない。色素分解10回の活性維持と回収率を同時に実証する。必要補充量＝B×(1−η)/(1−η^N)。50→5mg/L、α0.05g/g、10回なら0.098400kg/m³。αは金属から借りた未測定仮定。実測値として扱わない。' where cost_assumption_id='ca_recovery_eta';
update project_cost_tasks set hours_per_occurrence=0.5,confidence='H',source_kind='推定',owner='AMD（内部）',note='自動化の好条件設計枠0.5人時/100m³。始動・終了確認、記録、軽微な操作。制御440万円を含む現場設備2565万円を残す。8/12議論は自動運転を想定するが、0.5hの実測ではない。膜清掃・準備・回収等の他作業は既存行へ残し、槽内清掃は別作業。旧7.5hは手動運転の回答で、変更記録に保持。' where cost_task_id='ct_run_injection';
update project_cost_tasks set hours_per_occurrence=4,confidence='H',source_kind='推定',owner='AMD（内部）',note='好条件の設計仮定。培養・濃縮・出荷状態までを1系列日4人時で計上。年300日×必要系列数。空欄を0円とせず工数を置いた。実測と作業分解で再確認。' where cost_task_id='ct4_culture_operation';
update project_cost_tasks set hours_per_occurrence=0.1,confidence='H',source_kind='推定',owner='AMD（内部）',note='好条件の設計仮定。脱水・処分手配を1バッチ0.1人時。処分料金は既存の別明細。顧客の実人件費・清掃工数と重複を確認。' where cost_task_id='ct4_post_dye';
update project_cost_assumptions set label='SOL単独の仮料金（総額上限未設定時）',note='既存処理コスト500円/m³前後という前提から置いた値。用途別の実勢価格では未検証。 オンサイト（顧客工場で処理）の売価。オフサイトは「想定売上単価（オフサイト）」を別に置く（2026-09-14 まさ）。 顧客総額の上限があるオンサイトは、この値で請求せず、総額上限から顧客負担を引いた料金上限を計算する。' where cost_assumption_id='ca_sale_price';
update project_cost_assumptions set label='引き取る排水の事業全体年間量（オフサイト）',note='オフサイト（顧客の排液をSX工場まで運んで処理）は、将来サイドビジネスとして足す形で、オンサイトと別に年間処理量を置く（2026-09-14 まさ「オフサイトは売価も処理量も別に分けて試算したい」「将来的にサイドビジネス的に、オフサイトもやれたらいいかなっていうくらいのadditionalな要素」）。30,000m³/年は、SX工場1か所がいまの前提（100m³/日 × 300日）で処理する量として置いた仮置き。オフサイトの売上・事業全体の年間・顧客数はこの量で出す。菌体の製造拠点で年に作る量は、この量にオフサイトの濃さで使い切る菌体量を掛けて、オンサイトの分に足して計算する（同じ製造拠点で作る）。 顧客1工場の年30,000m³とは別の入力。どちらも排水量で、培養拠点の菌体能力ではない。' where cost_assumption_id='ca11_offsite_annual_volume';
update project_cost_assumptions set label='顧客1工場の1回の排水処理量',note='出どころ: ちこさんの試算シート 2026-08-20版の共通前提「バッチ容量 100 m³/バッチ」（メモなし）。同じ表の日処理量 100m³/日のメモは「260812打合せ：m³/日基準」（中島先生との打合せ）。1日1バッチとして、年間バッチ数 ＝ 稼働日/年 × 稼働率。確かめ方: 顧客工場の調整槽の容量と、1日に処理する量を聞いて比べる。 単位は排水m³で、菌体製造kgではない。100m³×300日×稼働率100%＝年30,000m³/工場。' where cost_assumption_id='ca_batch_volume';
update project_cost_models set version_label='261008 好条件・両社採算版',summary_md='好条件の量産設計試算。自然株・色素分解・顧客工場で直接投入・既設槽を使う。自動運転0.5人時/100m³、回収98%・10回使用、光収率1.5g/mol・吸収95%・LED効率3.7µmol/Jで試算。実測性能・設備見積・契約価格ではない。

顧客1工場の排水は年30,000m³。菌体製造量はkg/年で別に計算する。製造設備の原価と、顧客側の装置・工事・運転・清掃等を合算して総額500円/m³の枠を評価する。未見積の設備増額と顧客に残る処理費を残枠から差し引く。

削減の優先順位は、張付きの自動化、培養の光収支、菌体回収と10回の活性維持。定期清掃・冷却・製造運転・脱水・故障対応・管理費は仮定を置いて計上。初期小水量・3年回収の装置販売は別仕様で評価する。',system_scope_md='顧客1工場：100m³/回×300回/年＝排水30,000m³/年。事業全体：顧客工場での排水処理2000万m³/年＋引取処理30,000m³/年。菌体の製造量は各需要に必要補充kg/m³を掛け、販売率で割って導出する。培養・濃縮設備と顧客の排水処理設備を別々に積み上げる。所在地・拠点数・実設備能力は仮定。',target_total_cost_per_m3=null,target_note='顧客の総額提供上限500円/m³を前提行で設定。設備償却・運転・清掃等の両社合算と比較する。既存の500円前後は運転費として読む根拠が強く、償却込みの現状総額は未確認。料金配分は試算で、契約価格・月次売上には未採用。',source_note='原典: Google Sheets SX_コスト試算_260820 (ちこ)。中島先生の設備・運用想定を反映した版。 2026-09-13 に二段階版へ組み替え（migration 393）。 同日、作業リストと販売率を足した（migration 394/395）。 同日、作業の流れの段、オフサイトの比較、金属回収の使用回数の固定を足した（migration 396/397）。 2026-09-14、方式と装置を分け、作業に誰がやるかを持たせた（migration 398/399）。 同日、顧客がやる作業の時間を画面と注記から外した（migration 400）。 同日、色素分解の菌体使用回数を10回にし、明細に誰が持つかを持たせ、顧客工場のリアクター・槽と汚泥の処分を顧客の持ち分にした（migration 402/403）。 同日、年間生産能力を入力から外し、年間処理量（売上10,000,000,000円）から年に作る量を計算する形にした（migration 404/405）。 同日、作業単価を共通の1つにし、前提・作業リスト・明細を「事業と処理の条件 / CAPEX / OPEX」の区分に並べ直した（migration 406/407）。 同日、上端の槽の表示を外し、選んだ組み合わせで使わない前提を薄く出すようにした（migration 409）。 同日、顧客工場の装置の消耗品・電力・点検・交換部品を顧客の持ち分にし、オフサイトの循環カートリッジの処理の運転をSXの作業にした（migration 410）。 同日、文章の中の金額をカンマ区切りの円にそろえた（migration 416）。 同日、オフサイトの売価と年間処理量をオンサイトと別の前提に分けた（migration 419）。 2026-10-08 好条件の採算監査に基づく入力更新（migration487）。旧値と理由を変更記録に保存。' where cost_model_id='cm_p21_260820';
update project_cost_notes set body_md='オンサイトの直接投入は自動化を想定し、0.5人時/100m³を設計仮定として置く。実測ではない。旧7.5人時は先生の手動運転回答として履歴へ保持。顧客負担でも総額の原価に数える。リアクターの所有者スイッチは費用の分担を変え、両社合計を下げない。循環カートリッジの手動5.75人時は据え置き。オフサイトではSOLが運転費を持つ。' where cost_note_id='cn2_c8';
update project_cost_notes set body_md='菌体の年産量＝（顧客工場での事業全体排水量×必要補充kg/m³＋引取処理の事業全体排水量×必要補充kg/m³）÷販売率。顧客1工場の年30,000m³はこの処理量と別。1系列の菌体能力33,333kg/年×排液利用の増殖4倍（設計仮定）＝133,332kg/年で必要系列数を出す。事業規模2000万m³/年を維持するが、総額500から顧客費用を引くため、SOL単独売上100億円を意味しない。系列は比例配賦で、端数系列・拠点分散・所在地・供給距離・実能力は未検証。初期小規模には量産値を流用しない。' where cost_note_id='cn_260820_c4';
update project_cost_notes set body_md='廃液の総額提供上限500円/m³と、燃料の許容原価は別の事業・単位・費用範囲。廃液の旧SOL目標300円/m³は今回解除した。燃料・金属の売却収益で色素分解の赤字を埋めない。燃料モデルの入力と月次・資本政策は今回変更しない。' where cost_note_id='cn_260820_c6';
update project_cost_notes set body_md='- **第1段 菌体の製造原価** — 株ごとに、乾燥菌体1kgをつくる原価。年に作る量は年間処理量から計算し、培養設備を系列の数だけ並べる。培養設備の償却・年ごとの固定費・製造拠点の作業・菌体量に比例する費用に分け、販売率で割って見る
- **菌体費** — 第1段の原価 × 排水1m³あたりに使い切る菌体量
- **運ぶ（巡回・輸送）** — オンサイトは顧客工場への菌体の搬入・搬出と移動、オフサイトは排液の輸送。作業リストの工数・経費と、共通の作業単価で動かす
- **運転・保守・管理** — SXがやる、運ぶ以外の作業（オフサイトの処理の運転、モジュールや膜の交換、閉鎖系の管理など）
- **顧客がやる作業** — オンサイトの処理の運転など。SXの原価にも作業時間にも入れない
- **顧客が持つ明細** — オンサイトのリアクター（処理設備）と槽、装置を動かす消耗品・電力・点検・交換部品、処理水の分析と薬剤、汚泥の処分。SXの原価に入れない（明細の「誰が持つか」で変えられる）
- **使用済み菌体の後処理** — SXが持つ後処理。金属回収は酸処理。色素分解の汚泥の処分は、オンサイトでは顧客が持つので入らない（オフサイトだけ）
- **消耗品・電力・放流など** — オンサイトは菌体を運ぶ容器だけ（回収できずに失う菌体の補充は、2026-09-15 から菌体費に入る）。オフサイトは、SX工場の装置の消耗品・電力・点検・交換部品、処理水の分析と薬剤、放流費
- **設備と槽の償却** — SXが持つ処理設備と槽、金属回収の中央回収設備（2026-09-15 から）の初期投資 ÷ 耐用年数。オンサイトのリアクターと槽は顧客が買うので入らない（オフサイトはSX工場の設備と槽）
- **うち閉鎖系の追加** — 強化株のときだけ乗る費用。上の区分に含まれている分を、第1段の分と合わせて出す
- **総コスト** — 売価（オンサイト500円/m³、オフサイト50,000円/m³）に対して成立するか。総コスト目標はオンサイトにだけ当てる
- **オンサイトの年間 / オフサイトの年間** — 選んだ方式の年間処理量と売価での売上・総コスト・利益。顧客1社の年間を、顧客の数だけ足したもの

顧客総額の上限が設定されたオンサイトでは、顧客の全登録費用（リアクター以外の処分・分析等を含む）を合計し、上限から引いてSOL料金上限を計算する。未入力の残存処理・設備増額は確認待ち。料金上限と残枠は契約額・確定利益ではない。' where cost_note_id='cn_260820_r1';
insert into project_cost_assumptions (cost_assumption_id,cost_model_id,group_label,label,value,value_text,unit,confidence,source_kind,owner,is_key,role_key,note,visibility,sort_order,strain,application) values ('ca_amie_customer_total_budget','cm_p21_260820','総額採算','顧客総額の提供上限（設備・運転等込み）',500,null,'円/m³','H','推定','AMD（内部）',true,'customer_total_budget','まさ2026-10-07〜08の設計条件。SOLと顧客の設備償却・運転・清掃等を合わせた総枠。顧客に費用を移して達成扱いにしない。契約価格ではない。','amd_internal',90,null,'dye');
insert into project_cost_assumptions (cost_assumption_id,cost_model_id,group_label,label,value,value_text,unit,confidence,source_kind,owner,is_key,role_key,note,visibility,sort_order,strain,application) values ('ca_amie_customer_residual_cost','cm_p21_260820','総額採算','顧客に残る既存処理費',null,null,'円/m³','H','推定','AMD（内部）',true,'customer_residual_cost','未確認。色素以外のBOD/COD、窒素・リン、中和、油分、既存清掃・分析等から実際に残る費用を入力。空欄は総額へ含めず、残枠から引く必要がある。','amd_internal',91,null,'dye');
insert into project_cost_assumptions (cost_assumption_id,cost_model_id,group_label,label,value,value_text,unit,confidence,source_kind,owner,is_key,role_key,note,visibility,sort_order,strain,application) values ('ca_amie_unpriced_extra_cost','cm_p21_260820','総額採算','未見積設備・接続等の追加年額換算',null,null,'円/m³','H','推定','AMD（内部）',true,'unpriced_extra_cost','未確認。照射面・液量に対応する設備増額、受入・接続・前処理・敷地・冷却機器・金利等。初期額を年数と実処理量で割る。空欄は0円の見積ではない。','amd_internal',92,null,'dye');
insert into project_cost_assumptions (cost_assumption_id,cost_model_id,group_label,label,value,value_text,unit,confidence,source_kind,owner,is_key,role_key,note,visibility,sort_order,strain,application) values ('ca_amie_culture_cooling_cop','cm_p21_260820','培養の補助運転','培養冷却の成績係数',5,null,'倍','H','推定','AMD（内部）',true,'culture_cooling_cop','好条件COP5。LED電力全量を冷却負荷として計上。LED熱による加温節約を二重計上しない。冷却機器の初期額は追加見積。','amd_internal',276,null,null);
insert into project_cost_assumptions (cost_assumption_id,cost_model_id,group_label,label,value,value_text,unit,confidence,source_kind,owner,is_key,role_key,note,visibility,sort_order,strain,application) values ('ca_amie_flue_gas_co2_percent','cm_p21_260820','培養の補助運転','受け入れる排ガスのCO₂濃度',6.5,null,'%','H','推定','AMD（内部）',true,'flue_gas_co2_percent','台帳の実験ガス6.5%を参考にする設計仮定。無料CO₂でも搬送電力と受入設備は必要。不純物・前処理は工場ごとに確認。','amd_internal',277,null,null);
insert into project_cost_assumptions (cost_assumption_id,cost_model_id,group_label,label,value,value_text,unit,confidence,source_kind,owner,is_key,role_key,note,visibility,sort_order,strain,application) values ('ca_amie_flue_gas_pressure_pa','cm_p21_260820','培養の補助運転','排ガス搬送の差圧',10000,null,'Pa','H','推定','AMD（内部）',true,'flue_gas_pressure_pa','搬送の好条件仮定10kPa。配管長・圧損・前処理設備で再見積。','amd_internal',278,null,null);
insert into project_cost_assumptions (cost_assumption_id,cost_model_id,group_label,label,value,value_text,unit,confidence,source_kind,owner,is_key,role_key,note,visibility,sort_order,strain,application) values ('ca_amie_flue_gas_blower_efficiency','cm_p21_260820','培養の補助運転','排ガス送風機の効率',60,null,'%','H','推定','AMD（内部）',true,'flue_gas_blower_efficiency','好条件の設計仮定60%。モル体積は25℃で24.465m³/kmol、CO₂44.01kg/kmolとして単位照合。','amd_internal',279,null,null);
insert into project_cost_assumptions (cost_assumption_id,cost_model_id,group_label,label,value,value_text,unit,confidence,source_kind,owner,is_key,role_key,note,visibility,sort_order,strain,application) values ('ca_amie_business_overhead_annual','cm_p21_260820','営業・本部管理','営業・本部管理の年間予算',150000000,null,'円/年','H','推定','AMD（内部）',true,'business_overhead_annual','量産時の原価配賦に使う仮予算。オンサイト事業全体の処理量で割る。月次計画の管理費・資本政策は変更しない。','amd_internal',280,null,null);
insert into project_cost_items (cost_item_id,cost_model_id,scenario,cost_type,group_label,mid_label,leaf_label,basis,quantity,quantity_unit,unit_price,unit_price_unit,price_rule,annual_factor,useful_life_years,is_breakdown,confidence,source_kind,owner,note,visibility,sort_order,strain,application,bearer) values ('ci_amie_cooling','cm_p21_260820','中央培養','OPEX','培養補助運転','培養の冷却電力','培養の冷却電力','毎kg菌体比例',1,'式',183.86807860492067,'円/kg-DCW','culture_cooling',1,null,false,'H','推定','AMD（内部）','照明の電力明細÷冷却成績係数×照明の電力単価。LED数量と買値の変更に連動する。培養補助運転として別計上し、既存の培養ロス補充5%の原料群へ重ねない。年産能力・販売率に応じて1kg原価へ配賦。冷却機器購入額は未見積。','amd_internal',826,null,null,'sx');
insert into project_cost_items (cost_item_id,cost_model_id,scenario,cost_type,group_label,mid_label,leaf_label,basis,quantity,quantity_unit,unit_price,unit_price_unit,price_rule,annual_factor,useful_life_years,is_breakdown,confidence,source_kind,owner,note,visibility,sort_order,strain,application,bearer) values ('ci_amie_flue_gas','cm_p21_260820','中央培養','OPEX','培養補助運転','排ガス搬送の追加電力','排ガス搬送の追加電力','毎kg菌体比例',1,'式',1.5821864373287347,'円/kg-DCW','flue_gas_transport',1,null,false,'H','推定','AMD（内部）','CO₂量÷44.01×24.465÷排ガスCO₂濃度×差圧÷効率÷3600000×電力単価。6.5%、10kPa、60%では菌体1kgあたり約1.582円。排ガスONだけ。既存の散気2kWh/kgは残す。接続・受入・不純物除去の初期額は未見積。','amd_internal',827,null,null,'sx');
insert into project_cost_items (cost_item_id,cost_model_id,scenario,cost_type,group_label,mid_label,leaf_label,basis,quantity,quantity_unit,unit_price,unit_price_unit,price_rule,annual_factor,useful_life_years,is_breakdown,confidence,source_kind,owner,note,visibility,sort_order,strain,application,bearer) values ('ci_amie_overhead','cm_p21_260820','現場共通','OPEX','営業・本部管理','営業・本部管理の配賦','営業・本部管理の配賦','毎m³比例',1,'式',150000000,'円/m³','business_overhead',1,null,false,'H','推定','AMD（内部）','量産時の仮予算1.5億円/年÷オンサイト事業全体の排水量2000万m³＝7.5円/m³。単価欄が年額予算。実体制から見積もるため確定費ではない。月次計画の管理費と合算せず、今回そこを変更しない。金属・燃料の収益で補填しない。','amd_internal',910,null,null,'sx');
insert into project_cost_tasks (cost_task_id,cost_model_id,scenario,group_label,label,hours_per_occurrence,count_driver,count_per_year,hourly_rate,expense_per_occurrence,confidence,source_kind,owner,note,visibility,sort_order,strain,application,performer) values ('ct_amie_tank_cleaning','cm_p21_260820','共通','定期清掃・臨時対応','定期槽清掃（人数×時間の人時）',16,'fixed',4,null,0,'H','推定','AMD（内部）','好条件の設計仮定。2人×8h＝16人時/回、年4回、共通単価4000円/h。年3万m³で8.533円/m³。通常CIP・膜ハウジング清掃等の登録行を残し、槽内の追加清掃のみ。重複が確認できれば減額。周期・外注・機材・排出物は未確認。','amd_internal',43,null,null,'reactor');
insert into project_cost_tasks (cost_task_id,cost_model_id,scenario,group_label,label,hours_per_occurrence,count_driver,count_per_year,hourly_rate,expense_per_occurrence,confidence,source_kind,owner,note,visibility,sort_order,strain,application,performer) values ('ct_amie_fault_response','cm_p21_260820','共通','定期清掃・臨時対応','臨時故障対応（追加作業）',8,'fixed',2,null,0,'H','推定','AMD（内部）','好条件の仮定8人時×年2回。既存の点検・交換部品・予備費は残す。作業が既存費に含まれるか確認し、二重計上なら減額。','amd_internal',44,null,null,'sx');
insert into project_cost_notes (cost_note_id,cost_model_id,section,title,body_md,visibility,sort_order,source_url,source_label) values ('cn_amie_hearing_scope','cm_p21_260820','benchmark','顧客の500円前後の費用範囲','かるちゃん7/7共有はランニングコスト500円台後半。設備投資と清掃費は別項目。500〜700円の範囲そのものと清掃の算入は未確認。7/9共有には槽清掃の人手と兼任人件費の過小計上の指摘。個社の年間量・薬品・電力・人時・清掃・修繕・更新費を同じ範囲で比較し、実際に減る費目と残る費目を分ける。','amd_internal',1,'https://teamarmadahq.slack.com/archives/C093DQ4D04W/p1783411970112839','2026-10-07〜08 採算監査');
insert into project_cost_notes (cost_note_id,cost_model_id,section,title,body_md,visibility,sort_order,source_url,source_label) values ('cn_amie_optimistic','cm_p21_260820','caveat','好条件の確度と成立条件','約428円/m³は量産・高稼働・自動化・光利用・回収98%を同時に達成する設計仮定。設備増額と既存残存費は未確認で、約72円の残枠から引く。50円の利益を残す場合は追加費合計約22円以内。1系列133,332kg/年に照射面約4512m²・培養液約90m³・LED約976kWが要り、既存の本体873万円がこの能力を持つ見積ではない。','amd_internal',1,null,'2026-10-07〜08 採算監査');
insert into project_cost_notes (cost_note_id,cost_model_id,section,title,body_md,visibility,sort_order,source_url,source_label) values ('cn_amie_savings','cm_p21_260820','reading_guide','改善の優先順位と削減効果','元の登録原価の両社合計894円から、手動7.5→0.5人時で280円削減、光収支で約158円削減、その後の回収90→98%で約72円削減。追加工数・冷却・清掃・管理等を積むと約428円。独立の回収改善約118円を約158円と合算しない。排ガス無料と増殖4倍は主因ではない。膜寿命は3年を維持。','amd_internal',1,null,'2026-10-07〜08 採算監査');
insert into project_cost_notes (cost_note_id,cost_model_id,section,title,body_md,visibility,sort_order,source_url,source_label) values ('cn_amie_history_261008','cm_p21_260820','history','好条件・両社採算への更新（2026-10-08）','487: まさ2026-10-07承認の好条件設計試算。自動化・光収支・回収率を仮説として採用し清掃等を計上。顧客総額500の枠とSOL料金を区別。実測・契約価格・月次計画の確定ではない。

旧LED108.9kWh・15.1W・315円/W・7年→52.684kWh・7.317W・388.5円/W・5年。回収90→98%。手動工数7.5→0.5h。培養/脱水の空欄→4/.1h。新たに槽清掃・故障対応・冷却・排ガス搬送・管理配賦を追加。旧SOL原価402.5と顧客463.3は旧保存条件の値として履歴に保持。総額上限500から顧客の全登録費用を引く料金上限を導出。旧SOL目標300の設定は解除し、総額500の枠へ集約。燃料・月次・資本政策・長期計画/DDの制作元は変更しない。','amd_internal',230,null,'2026-10-07〜08 採算監査');
commit;
