-- 2026-10-08 user request: existing SOL NDA + AMD contract ledger; single contract ID.
-- Signed PDF SHA256: 3c4689cb51429ceba041122b0ddd504ad65de7b49da5896e52f3b0292c5af3e7
-- Completion email: 1a11a417534c6b7e, 2026-10-08T15:44:18+09:00.
-- No schema, billing, DD visibility, Drive permissions or notification changes. Never reapply.
BEGIN;
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM contracts c WHERE contract_id='b5e39c23-6039-428d-bddf-5f90bb6f862a' AND project_id='p21' AND status='awaiting_signature' AND relationship_scope='amd_contract' AND registry_status='accepted' AND md5(to_jsonb(c)::text)='721ec511cc5c8b7e6fc685a579e79aa8') THEN
 RAISE EXCEPTION 'NDA before state changed; review instead of reapplying'; END IF;
 IF NOT EXISTS (SELECT 1 FROM projects WHERE project_id='p21' AND md5(contract_terms_json::text)='c98710dbcdf2fa1111bb993c8348c30d') THEN
 RAISE EXCEPTION 'SOL current contracts changed; review instead of reapplying'; END IF;
 IF (SELECT count(*) FROM contract_documents WHERE contract_id='b5e39c23-6039-428d-bddf-5f90bb6f862a') <> 2 THEN
 RAISE EXCEPTION 'NDA document history changed'; END IF;
END $$;
UPDATE contract_documents SET is_latest=false,updated_at=now() WHERE contract_id='b5e39c23-6039-428d-bddf-5f90bb6f862a' AND is_latest;
INSERT INTO contract_documents(document_id,contract_id,project_id,document_kind,version_label,drive_file_id,drive_folder_id,web_view_link,file_name,mime_type,file_size_bytes,source_kind,received_at,uploaded_by,is_latest)
 VALUES ('3c7667bf-3f90-4cfd-90f5-e230934a5c04','b5e39c23-6039-428d-bddf-5f90bb6f862a','p21','signed','締結版（電子署名済み・2026-10-08）','1MKLHDOX7lmwZgURsjNcj22u8E9mwFtMZ','1Za13W_eQn4HoSd-qXNShm7YmbNJs1HH9','https://drive.google.com/file/d/1MKLHDOX7lmwZgURsjNcj22u8E9mwFtMZ/view?usp=drivesdk','いよぎんキャピタル_NDA_締結版_20261008.pdf','application/pdf',540826,'user_provided_signed_pdf','2026-10-08T15:44:18+09:00','amie',true);
UPDATE contracts SET status='signed',signed_at='2026-10-08T15:44:18+09:00',signed_document_id='3c7667bf-3f90-4cfd-90f5-e230934a5c04',effective_date='2026-10-08',renewal_type='締結日より1年間。期間終了1ヶ月前までに書面の更新拒絶通知がなければ1年間自動更新',is_current_for_project=true,
 drive_folder_id='1Za13W_eQn4HoSd-qXNShm7YmbNJs1HH9',review_required=false,review_status='accepted',business_owner='肥塚恭子',confidentiality_coverage='in_contract',confidentiality_note='秘密として指定された相互開示情報を目的外利用・第三者開示しない。第三者開示は書面による事前同意が原則（第2条の除外対象あり）',confidentiality_survival_note='第2条〜第5条の義務は契約終了後1年間存続（第6条第4項）',operational_terms_json='{"sourceTitle":"いよぎんキャピタル_NDA_締結版_20261008.pdf","sourceRef":"https://drive.google.com/file/d/1MKLHDOX7lmwZgURsjNcj22u8E9mwFtMZ/view?usp=drivesdk","verifiedAt":"2026-10-08","verifiedBy":"amie:user-confirmed-and-cloudsign-completion","scopeSummary":"愛媛大学・杉浦美羽研究代表者のPSI GAP採択課題の事業化に向け、設立予定会社への出資検討と情報交換","renewalType":"締結日より1年間。期間終了1ヶ月前までに書面の更新拒絶通知がなければ1年間自動更新","confidentialitySummary":"秘密として指定された相互開示情報を目的外利用・第三者開示しない。第三者開示は書面による事前同意が原則（第2条の除外対象あり）","confidentialitySurvival":"第2条〜第5条の義務は契約終了後1年間存続（第6条第4項）","usageRights":"本目的の範囲内で使用。本目的の範囲内の複写・複製は第2条第2項の例外","terminationTerms":"書面による合意解除の日に終了。相手方請求時に秘密情報を指定方法で速やかに返却・廃棄（第4条、第6条第3項）","liabilityTerms":"契約違反により相手方へ与えた損害を賠償。帰責できない事由、特別事情の損害、逸失利益は対象外（第5条）","governingLawJurisdiction":"日本法。被告の主たる事業所所在地を管轄する地方裁判所を第一審の専属管轄（第8条）","specialTerms":"変更は双方の権限ある代表者の署名又は記名・押印のある文書による（第9条）","cockpitSummary":{"scope":"愛媛大学・杉浦美羽研究代表者のPSI GAP採択課題の事業化に向け、設立予定会社への出資検討と情報交換","deliverables":"利用は出資検討とそれに伴う情報交換の範囲","execution":"第三者開示は事前の書面同意が原則。第2条の除外対象と各受領者の守秘義務を確認"},"nda":{"effectiveDate":"2026-10-08","signatureStatus":"電子署名・締結完了確認済み","term":"締結日より1年間。期間終了1ヶ月前までに書面の更新拒絶通知がなければ1年間自動更新","postTerminationConfidentiality":"第2条〜第5条の義務は終了後1年間存続","purpose":"愛媛大学・杉浦美羽研究代表者のPSI GAP採択課題の事業化に向け、設立予定会社への出資検討と情報交換"},"notes":"締結日と締結完了は署名済みPDF・クラウドサイン完了メールで確認。第6条は期間を1年間と定め、満了日・通知期限の暦日は明記しないため日付列は未確定。大学由来情報の開示条件は情報提供元との契約で別途確認。"}'::jsonb,
 source_summary='2026-10-08クラウドサインで合意締結完了。署名済みPDF・完了通知を確認。契約当事者はいよぎんキャピタルとチームアルマダ、SOL関連NDA。第6条の有効期間・更新条件・終了後義務を登録。',
 source_refs_json=source_refs_json || '[{"kind":"gmail","message_id":"1a11a417534c6b7e","date":"2026-10-08","note":"クラウドサイン合意締結完了通知 15:44:18 JST"},{"kind":"drive","file_id":"1MKLHDOX7lmwZgURsjNcj22u8E9mwFtMZ","date":"2026-10-08","note":"署名済みPDF。両社印影・電子署名フィールド確認","sha256":"3c4689cb51429ceba041122b0ddd504ad65de7b49da5896e52f3b0292c5af3e7"}]'::jsonb,ledger_notes='締結日と締結完了は署名済みPDF・クラウドサイン完了メールで確認。第6条は期間を1年間と定め、満了日・通知期限の暦日は明記しないため日付列は未確定。大学由来情報の開示条件は情報提供元との契約で別途確認。',last_activity_at='2026-10-08T15:45:07+09:00',updated_at=now(),updated_by='amie'
 WHERE contract_id='b5e39c23-6039-428d-bddf-5f90bb6f862a';
-- Add a contract-specific NDA snapshot; keep the university-service contract and all PJ fee/primary settings intact.
UPDATE projects SET contract_terms_json=jsonb_set(contract_terms_json,'{currentContracts}',coalesce(contract_terms_json->'currentContracts','[]'::jsonb) || jsonb_build_array('{"contractId":"b5e39c23-6039-428d-bddf-5f90bb6f862a","title":"いよぎんキャピタルとの秘密保持契約（SOL）","contractType":"nda","status":"signed","signatureStatus":"電子署名・締結完了確認済み","counterpartyName":"いよぎんキャピタル株式会社","effectiveDate":"2026-10-08","expirationDate":null,"renewalType":"締結日より1年間。期間終了1ヶ月前までに書面の更新拒絶通知がなければ1年間自動更新","renewalNoticeDate":null,"documentUrl":"https://drive.google.com/file/d/1MKLHDOX7lmwZgURsjNcj22u8E9mwFtMZ/view?usp=drivesdk","terms":{"sourceTitle":"いよぎんキャピタル_NDA_締結版_20261008.pdf","sourceRef":"https://drive.google.com/file/d/1MKLHDOX7lmwZgURsjNcj22u8E9mwFtMZ/view?usp=drivesdk","verifiedAt":"2026-10-08","verifiedBy":"amie:user-confirmed-and-cloudsign-completion","scopeSummary":"愛媛大学・杉浦美羽研究代表者のPSI GAP採択課題の事業化に向け、設立予定会社への出資検討と情報交換","renewalType":"締結日より1年間。期間終了1ヶ月前までに書面の更新拒絶通知がなければ1年間自動更新","confidentialitySummary":"秘密として指定された相互開示情報を目的外利用・第三者開示しない。第三者開示は書面による事前同意が原則（第2条の除外対象あり）","confidentialitySurvival":"第2条〜第5条の義務は契約終了後1年間存続（第6条第4項）","usageRights":"本目的の範囲内で使用。本目的の範囲内の複写・複製は第2条第2項の例外","terminationTerms":"書面による合意解除の日に終了。相手方請求時に秘密情報を指定方法で速やかに返却・廃棄（第4条、第6条第3項）","liabilityTerms":"契約違反により相手方へ与えた損害を賠償。帰責できない事由、特別事情の損害、逸失利益は対象外（第5条）","governingLawJurisdiction":"日本法。被告の主たる事業所所在地を管轄する地方裁判所を第一審の専属管轄（第8条）","specialTerms":"変更は双方の権限ある代表者の署名又は記名・押印のある文書による（第9条）","cockpitSummary":{"scope":"愛媛大学・杉浦美羽研究代表者のPSI GAP採択課題の事業化に向け、設立予定会社への出資検討と情報交換","deliverables":"利用は出資検討とそれに伴う情報交換の範囲","execution":"第三者開示は事前の書面同意が原則。第2条の除外対象と各受領者の守秘義務を確認"},"nda":{"effectiveDate":"2026-10-08","signatureStatus":"電子署名・締結完了確認済み","term":"締結日より1年間。期間終了1ヶ月前までに書面の更新拒絶通知がなければ1年間自動更新","postTerminationConfidentiality":"第2条〜第5条の義務は終了後1年間存続","purpose":"愛媛大学・杉浦美羽研究代表者のPSI GAP採択課題の事業化に向け、設立予定会社への出資検討と情報交換"},"notes":"締結日と締結完了は署名済みPDF・クラウドサイン完了メールで確認。第6条は期間を1年間と定め、満了日・通知期限の暦日は明記しないため日付列は未確定。大学由来情報の開示条件は情報提供元との契約で別途確認。"}}'::jsonb),true)
 WHERE project_id='p21';
INSERT INTO contract_signals(contract_id,project_id,source_kind,source_table,source_id,source_url,title,snippet,signal_type,confidence,review_required,status,detected_at,metadata_json) VALUES ('b5e39c23-6039-428d-bddf-5f90bb6f862a','p21','gmail','gmail_messages','1a11a15fe0fdb9e5','https://mail.google.com/mail/u/?authuser=masa%40team-armada.jp#all/1a11a15fe0fdb9e5','先方が当日付の電子契約発信を案内','2026-10-08付でクラウドサインを発信し、先方署名後に山地へ通知する旨を案内。','contract_exchange',1,false,'linked','2026-10-08T14:56:47+09:00','{"event_time_basis":"gmail_sent_at","review_basis":"user_requested_signed_nda_registration"}'::jsonb);
INSERT INTO contract_signals(contract_id,project_id,source_kind,source_table,source_id,source_url,title,snippet,signal_type,confidence,review_required,status,detected_at,metadata_json) VALUES ('b5e39c23-6039-428d-bddf-5f90bb6f862a','p21','gmail','gmail_messages','1a11a1fb290af0c1','https://mail.google.com/mail/u/?authuser=masa%40team-armada.jp#all/1a11a1fb290af0c1','クラウドサインの確認依頼を受領','対象NDAの電子署名確認依頼を受領。','contract_exchange',1,false,'linked','2026-10-08T15:07:26+09:00','{"event_time_basis":"gmail_sent_at","review_basis":"user_requested_signed_nda_registration"}'::jsonb);
INSERT INTO contract_signals(contract_id,project_id,source_kind,source_table,source_id,source_url,title,snippet,signal_type,confidence,review_required,status,detected_at,metadata_json) VALUES ('b5e39c23-6039-428d-bddf-5f90bb6f862a','p21','gmail','gmail_messages','1a11a417534c6b7e','https://mail.google.com/mail/u/?authuser=masa%40team-armada.jp#all/1a11a417534c6b7e','クラウドサインで合意締結が完了','両社のNDAの合意締結完了通知を確認。締結日2026-10-08。署名済みPDFを保存し最新版に登録。','contract_exchange',1,false,'linked','2026-10-08T15:44:18+09:00','{"event_time_basis":"gmail_sent_at","review_basis":"user_requested_signed_nda_registration"}'::jsonb);
INSERT INTO contract_signals(contract_id,project_id,source_kind,source_table,source_id,source_url,title,snippet,signal_type,confidence,review_required,status,detected_at,metadata_json) VALUES ('b5e39c23-6039-428d-bddf-5f90bb6f862a','p21','gmail','gmail_messages','1a11a4242a388bc1','https://mail.google.com/mail/u/?authuser=masa%40team-armada.jp#all/1a11a4242a388bc1','山地が押印完了を先方へ報告','山地の送信済みメールで押印完了の報告を確認。','contract_exchange',1,false,'linked','2026-10-08T15:45:07+09:00','{"event_time_basis":"gmail_sent_at","review_basis":"user_requested_signed_nda_registration"}'::jsonb);
COMMIT;
