'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {WORKFLOW_STATUS,MAIL_EVENT_LABEL,workflowActions,type WorkflowRequest,type WorkflowContract,type WorkflowDocument,type WorkflowMailEvent} from '@/lib/workflows';
type Data={actor:string;requests:WorkflowRequest[];requestCount:number;pendingCount:number;contracts:WorkflowContract[];contractCount:number;mailEvents:WorkflowMailEvent[];mailCount:number;deliveries:Array<{event_key:string;recipient_member_id:string;status:string;sent_at:string|null}>;monitor:{last_checked_at:string|null;last_success_at:string|null;last_error:string|null;scanned_count:number};rule:{enabled:boolean;activated_at:string};members:Array<{member_id:string;code_name:string}>};
type Event={event_id:string;action:string;actor_member_id:string|null;note:string|null;created_at:string};
const eventLabels:Record<string,string>={submitted:'申請',approve:'きよ承認',return:'差戻し',cancel:'取下げ',superseded:'変更・再申請',release:'押印手続き開始',complete:'締結版照合完了'};
const date=(value:string|null)=>value?new Date(value).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'未確認';
const termLabels:Record<string,string>={scopeSummary:'業務範囲',paymentTerms:'支払条件',deliverablesNote:'成果物',expenseReimbursementNote:'経費',confidentialitySummary:'秘密保持',confidentialitySurvival:'秘密保持の存続',ipOwnership:'知財の帰属',usageRights:'利用権',publicityRights:'公開・発表',subcontractingTerms:'再委託',exclusivityTerms:'独占・競業',terminationTerms:'解除',liabilityTerms:'賠償・責任',governingLawJurisdiction:'準拠法・管轄',specialTerms:'特記事項',renewalType:'更新',notes:'確認事項'};
const input='min-h-11 w-full rounded-none border border-border bg-background px-3 py-2 text-base focus-visible:outline-2 focus-visible:outline-primary';
export function WorkflowWorkspace({embedded=false,initialContractId='',initialRequestId=''}:{embedded?:boolean;initialContractId?:string;initialRequestId?:string}){
 const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [selected,setSelected]=useState<WorkflowRequest|null>(null);
 const [events,setEvents]=useState<Event[]>([]);const [eventsLoading,setEventsLoading]=useState(false);const [docsLoading,setDocsLoading]=useState(false);
 const [showForm,setShowForm]=useState(false);const [search,setSearch]=useState('');const [contractId,setContractId]=useState(initialContractId);const [documents,setDocuments]=useState<WorkflowDocument[]>([]);const [documentId,setDocumentId]=useState('');const [purpose,setPurpose]=useState('');const [desiredDate,setDesiredDate]=useState('');const [note,setNote]=useState('');const [confirmed,setConfirmed]=useState(false);const [notice,setNotice]=useState('');
 const reload=useCallback(async(append=false)=>{
  try{const offset=append?data?.requests.length||0:0;const response=await fetch(`/api/workflows?offset=${offset}`,{cache:'no-store'});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'読み込めなかった');
  setData(old=>({...result,requests:append?[...(old?.requests||[]),...result.requests]:result.requests}));setError('');
  if(initialRequestId&&!append){const detail=await fetch(`/api/workflows/${encodeURIComponent(initialRequestId)}`,{cache:'no-store'});const focused=await detail.json();if(focused.ok)setSelected(focused.request);else setError(focused.error);}
  }catch(e){setError(e instanceof Error?e.message:'読み込めなかった');}
 },[data?.requests.length,initialRequestId]);
 useEffect(()=>{void reload(); /* first load */},[]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(initialContractId){setShowForm(true);}},[initialContractId]);
 useEffect(()=>{if(!contractId){setDocuments([]);setDocumentId('');return;}let alive=true;setDocsLoading(true);setDocuments([]);setDocumentId('');fetch(`/api/workflows?contractId=${encodeURIComponent(contractId)}`,{cache:'no-store'}).then(r=>r.json()).then(r=>{if(alive&&r.ok){setDocuments(r.documents);setDocumentId(r.documents[0]?.document_id||'');}else if(alive)setError(r.error||'文書を読み込めなかった');}).catch(()=>{if(alive)setError('文書を読み込めなかった');}).finally(()=>{if(alive)setDocsLoading(false);});return()=>{alive=false;};},[contractId]);
 useEffect(()=>{setConfirmed(false);setNote('');setEvents([]);if(!selected)return;let alive=true;setEventsLoading(true);
 fetch(`/api/workflows/${selected.request_id}`,{cache:'no-store'}).then(r=>r.json()).then(r=>{if(alive&&r.ok)setEvents(r.events);else if(alive)setError(r.error);}).catch(()=>{if(alive)setError('履歴を読み込めなかった');}).finally(()=>{if(alive)setEventsLoading(false);});return()=>{alive=false;};},[selected?.request_id]);
 const mutate=async(url:string,body:unknown)=>{setBusy(true);setError('');try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'保存できなかった');setSelected(null);setShowForm(false);setNotice('保存完了');await reload();return true;}catch(e){setError(e instanceof Error?e.message:'保存できなかった');return false;}finally{setBusy(false);}};
 const searchContracts=async()=>{setBusy(true);try{const response=await fetch(`/api/workflows?search=${encodeURIComponent(search)}`,{cache:'no-store'});const result=await response.json();if(!result.ok)throw new Error(result.error);setData(old=>old?{...old,contracts:result.contracts,contractCount:result.contractCount}:old);}catch{setError('契約を検索できなかった');}finally{setBusy(false);}};
 const names=(id:string)=>data?.members.find(m=>m.member_id===id)?.code_name||'メンバー';
 const title=(r:WorkflowRequest)=>String(r.terms_snapshot.contract_title||'押印申請');
 const monitorStale=!!data&&(!data.monitor.last_checked_at||Date.now()-new Date(data.monitor.last_checked_at).getTime()>15*60_000);
 const actions=selected&&data?workflowActions(selected.status,data.actor,selected.requested_by,selected.approver_member_id):null;
 return <section className="w-full max-w-[1200px] text-sm" data-testid="workflow-workspace">
  {!embedded&&<header className="mb-3"><h1 className="text-xl font-semibold">業務フロー</h1><p className="mt-1 text-sm text-muted-foreground">押印する最終版を申請し、きよの承認を受けて進める。</p></header>}
  <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border pb-3"><div><h2 className="font-semibold">押印申請</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">申請 → きよ承認 → 押印手続き → 締結版照合。文書・条件が変わったら再申請。</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void reload()} disabled={busy}>更新</Button><Button onClick={()=>setShowForm(true)} disabled={busy||!data}>押印を申請</Button></div></div>
  {error&&<p role="alert" className="my-3 border-l-2 border-destructive bg-destructive/5 px-3 py-2 text-destructive">{error}</p>}{notice&&<p role="status" className="my-2">{notice}</p>}
  {!data&&!error&&<p className="py-6 text-muted-foreground" role="status">申請と監視状況を読み込み中…</p>}
  {data&&<>
   <p className="py-2 text-xs text-muted-foreground">承認待ち {data.pendingCount}件 / 表示 {data.requests.length}件・全 {data.requestCount}件</p>
   <div className="overflow-x-auto"><table className="w-full min-w-[650px] border-collapse text-left"><thead className="border-y border-border bg-muted/30 text-xs text-muted-foreground"><tr>{['契約・相手先','申請者・承認者','希望日','状態','操作'].map(x=><th className="px-3 py-2 font-medium" key={x}>{x}</th>)}</tr></thead><tbody>{data.requests.map(r=><tr key={r.request_id} className="border-b border-border hover:bg-muted/30"><td className="max-w-[360px] px-3 py-2"><p className="line-clamp-2 font-medium">{title(r)}</p><p className="mt-1 text-xs text-muted-foreground">{String(r.terms_snapshot.counterparty_name||'相手先未確認')}</p></td><td className="px-3 py-2 text-xs"><Link href={`/mypage?memberId=${r.requested_by}`} className="underline underline-offset-2">{names(r.requested_by)}</Link> → <Link href={`/mypage?memberId=${r.approver_member_id}`} className="underline underline-offset-2">{names(r.approver_member_id)}</Link></td><td className="whitespace-nowrap px-3 py-2 text-xs">{r.desired_date||'指定なし'}</td><td className="px-3 py-2 text-xs font-medium">{WORKFLOW_STATUS[r.status]}</td><td className="px-3 py-2"><Button variant="outline" className="min-h-11 sm:min-h-8" onClick={()=>setSelected(r)}>確認</Button></td></tr>)}</tbody></table>{!data.requests.length&&<p className="py-4 text-muted-foreground">押印申請はまだない。「押印を申請」から最終版を選択。</p>}</div>
   {data.requests.length<data.requestCount&&<Button variant="outline" className="mt-2" onClick={()=>void reload(true)}>次の50件を表示</Button>}
   <div className="mt-5 border-y border-border py-3"><h2 className="font-semibold">契約メールの監視</h2><p className={`mt-1 text-sm leading-6 ${data.monitor.last_error||monitorStale?'text-destructive':'text-muted-foreground'}`}>{data.monitor.last_error||(monitorStale?'監視の実行が未確認、または15分以上止まっている':'監視中・受信と送信を5分ごとに確認')} / 最終確認 {date(data.monitor.last_checked_at)}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">契約のやりとりを検知すると、まさときよの個別Slackへ通知。検知は承認ではなく、OS外の押印を止めるものではない。</p></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[620px] border-collapse text-left"><thead className="border-b border-border bg-muted/30 text-xs text-muted-foreground"><tr>{['日時・送受信','契約の動き','メール件名','Slack配信'].map(x=><th key={x} className="px-3 py-2 font-medium">{x}</th>)}</tr></thead><tbody>{data.mailEvents.map(event=>{const delivered=data.deliveries.filter(d=>d.event_key===`mail:${event.event_id}`);const label=delivered.length===2&&delivered.every(d=>d.status==='sent')?'2人へ配信済み':delivered.some(d=>d.status==='uncertain')?'配信結果の照合が必要':delivered.some(d=>d.status==='failed')?'配信失敗・再試行待ち':'配信待ち';return <tr key={event.event_id} className="border-b border-border"><td className="whitespace-nowrap px-3 py-2 text-xs">{date(event.occurred_at)}<br/>{event.direction==='sent'?'まさの送信':'まさの受信'}</td><td className="px-3 py-2 text-xs font-medium">{MAIL_EVENT_LABEL[event.event_kind]}{event.event_kind==='completion'&&<p className="mt-1 text-destructive">承認記録との照合が必要</p>}</td><td className="max-w-[400px] px-3 py-2"><a href={event.source_url} target="_blank" rel="noopener noreferrer" className="line-clamp-2 text-primary underline underline-offset-2">{event.subject}</a></td><td className="px-3 py-2 text-xs">{label}</td></tr>;})}</tbody></table></div>
   {!data.mailEvents.length&&<p className="py-3 text-muted-foreground">監視開始後の契約メールはまだ検知されていない。</p>}{data.mailCount>50&&<p className="py-2 text-xs text-muted-foreground">最新50件を表示 / 全 {data.mailCount}件</p>}
  </>}
  <Dialog open={showForm} onOpenChange={open=>{if(!busy)setShowForm(open);}}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-[700px]"><DialogHeader><DialogTitle>押印を申請</DialogTitle><DialogDescription>契約本文と添付を含む最新版のPDFを固定して、きよへ承認を依頼する。Wordのままなら、最終版PDFを契約の「文書と版」に登録。</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();void mutate('/api/workflows',{contractId,documentId,purpose,desiredDate});}}>
   <label className="block text-xs font-medium">契約を検索<div className="mt-1 flex gap-2"><input className={input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="契約名"/><Button type="button" variant="outline" onClick={()=>void searchContracts()} disabled={busy}>検索</Button></div></label>
   <label className="block text-xs font-medium">契約<select required className={`mt-1 ${input}`} value={contractId} onChange={e=>setContractId(e.target.value)}><option value="">未締結の契約を選択</option>{data?.contracts.map(c=><option key={c.contract_id} value={c.contract_id}>{c.project_id} / {c.contract_title}</option>)}</select></label>
   {!!data&&data.contractCount>100&&<p className="text-xs text-muted-foreground">候補は最新100件。契約名で検索して絞り込む。</p>}
   <label className="block text-xs font-medium">押印対象の最終版PDF<select required className={`mt-1 ${input}`} value={documentId} onChange={e=>setDocumentId(e.target.value)}><option value="">PDFを選択</option>{documents.map(d=><option key={d.document_id} value={d.document_id}>{d.version_label} / {d.file_name}</option>)}</select></label>
   {contractId&&docsLoading&&<p role="status" className="text-xs text-muted-foreground">最新版のPDFを確認中…</p>}{contractId&&!docsLoading&&!documents.length&&<p className="text-xs text-destructive">最新版の未押印PDFがまだ登録されていない。<Link className="underline" href="/admin/contracts">契約管理で登録</Link></p>}
   <label className="block text-xs font-medium">押印する目的・確認してほしい点<textarea className={`mt-1 ${input}`} rows={3} required maxLength={2000} value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><label className="block text-xs font-medium">押印希望日（任意）<input type="date" className={`mt-1 ${input}`} value={desiredDate} onChange={e=>setDesiredDate(e.target.value)}/></label>
   {error&&<p role="alert" className="text-destructive">{error}</p>}<div className="flex justify-end gap-2 border-t border-border pt-3"><Button type="button" variant="outline" disabled={busy} onClick={()=>setShowForm(false)}>閉じる</Button><Button disabled={busy||!documentId} type="submit">{busy?'申請中…':'きよへ押印申請'}</Button></div>
  </form></DialogContent></Dialog>
  <Dialog open={!!selected} onOpenChange={open=>{if(!open&&!busy)setSelected(null);}}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-[760px]"><DialogHeader><DialogTitle>{selected?title(selected):'押印申請'}</DialogTitle><DialogDescription>{selected?WORKFLOW_STATUS[selected.status]:''}</DialogDescription></DialogHeader>{selected&&actions&&<div className="space-y-3">
   <dl className="grid gap-3 border-y border-border py-3 sm:grid-cols-2">{[['相手先',String(selected.terms_snapshot.counterparty_name||'未確認')],['当事者',String(selected.terms_snapshot.amd_entity_name||'未確認')],['申請者・承認者',`${names(selected.requested_by)} → ${names(selected.approver_member_id)}`],['申請日・希望日',`${date(selected.created_at)} / ${selected.desired_date||'指定なし'}`]].map(([k,v])=><div key={k}><dt className="text-xs text-muted-foreground">{k}</dt><dd className="mt-1 break-words">{v}</dd></div>)}</dl>
   <div><p className="text-xs font-medium text-muted-foreground">押印の目的・確認事項</p><p className="mt-1 whitespace-pre-wrap leading-6">{selected.purpose}</p></div>
   <a className="inline-flex min-h-11 items-center text-primary underline underline-offset-2" href={`https://drive.google.com/file/d/${selected.snapshot_file_id}/view`} target="_blank" rel="noopener noreferrer">申請時に固定した最終版PDFを開く</a>
   <details><summary className="min-h-11 cursor-pointer py-3 text-xs font-medium">申請時の契約条件を確認</summary><dl className="divide-y divide-border">{Object.entries((selected.terms_snapshot.operational_terms_json||{}) as Record<string,unknown>).filter(([k,v])=>!!termLabels[k]&&(typeof v==='string'||typeof v==='number')).map(([key,value])=><div key={key} className="py-2"><dt className="text-xs text-muted-foreground">{termLabels[key]}</dt><dd className="whitespace-pre-wrap break-words leading-6">{String(value)}</dd></div>)}</dl></details>
   <details><summary className="min-h-11 cursor-pointer py-3 text-xs font-medium">申請・承認の履歴</summary>{eventsLoading?<p role="status">履歴を読み込み中…</p>:<ol className="divide-y divide-border">{events.map(event=><li key={event.event_id} className="py-2"><p className="text-xs text-muted-foreground">{date(event.created_at)} / {event.actor_member_id?names(event.actor_member_id):'OS'}</p><p className="mt-1 font-medium">{eventLabels[event.action]||'更新'}</p>{event.note&&<p className="mt-1 whitespace-pre-wrap leading-6">{event.note}</p>}</li>)}</ol>}</details>
   {selected.decision_note&&<p className="border-l-2 border-border pl-3 leading-6">きよの確認：{selected.decision_note}</p>}
   {(actions.approve||actions.release||actions.complete)&&<label className="flex min-h-11 items-start gap-2 border-y border-border py-3"><input className="mt-1 h-5 w-5 shrink-0" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span className="leading-6">{actions.complete?<><Link href="/admin/contracts" className="text-primary underline">契約管理の締結版</Link>を開き、承認対象の内容と一致することを確認した</>:'固定した最終版PDFと契約条件を確認した'}</span></label>}
   {(actions.approve||actions.return)&&<label className="block text-xs font-medium">確認コメント（差戻しは必須）<textarea className={`mt-1 ${input}`} rows={2} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label>}
   {error&&<p role="alert" className="text-destructive">{error}</p>}<div className="flex flex-wrap justify-end gap-2 border-t border-border pt-3">
   {actions.cancel&&<Button variant="outline" disabled={busy} onClick={()=>void mutate(`/api/workflows/${selected.request_id}`,{action:'cancel'})}>申請を取下げ</Button>}
   {actions.return&&<Button variant="outline" disabled={busy||!note.trim()} onClick={()=>void mutate(`/api/workflows/${selected.request_id}`,{action:'return',note})}>差戻し</Button>}
   {actions.approve&&<Button disabled={busy||!confirmed} onClick={()=>void mutate(`/api/workflows/${selected.request_id}`,{action:'approve',confirmed,note})}>この最終版の押印を承認</Button>}
   {actions.release&&<Button disabled={busy||!confirmed} onClick={()=>void mutate(`/api/workflows/${selected.request_id}`,{action:'release',confirmed})}>承認対象の押印手続きへ進む</Button>}
   {actions.complete&&<Button disabled={busy||!confirmed} onClick={()=>void mutate(`/api/workflows/${selected.request_id}`,{action:'complete',confirmed})}>締結版を照合して完了</Button>}
   </div><p className="text-xs leading-5 text-muted-foreground">紙の押印や外部サービスでの電子署名は、この画面とは別の操作。承認された最終版を使用。</p>
  </div>}</DialogContent></Dialog>
 </section>;
}
