'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {WORKFLOW_STATUS,WORKFLOW_CONTRACT_TYPES,MAIL_EVENT_LABEL,workflowActions,type WorkflowRequest,type WorkflowContract,type WorkflowDocument,type WorkflowMailEvent} from '@/lib/workflows';
import {WorkflowProgress} from './WorkflowProgress';
import {WorkflowStartForm,workflowInputClass as input,type WorkflowStartInput} from './WorkflowStartForm';

type Data={actor:string;requests:WorkflowRequest[];requestCount:number;pendingCount:number;contracts:WorkflowContract[];contractCount:number;projects:Array<{project_id:string;project_name:string}>;mailEvents:WorkflowMailEvent[];mailCount:number;deliveries:Array<{event_key:string;recipient_member_id:string;status:string;sent_at:string|null}>;monitor:{last_checked_at:string|null;last_success_at:string|null;last_error:string|null};members:Array<{member_id:string;code_name:string}>};
type Event={event_id:string;action:string;actor_member_id:string|null;note:string|null;created_at:string};
const eventLabels:Record<string,string>={started:'契約フロー開始',final_pdf_registered:'最終版PDF登録',signed_pdf_registered:'締結版PDF登録',submitted:'押印申請',approve:'きよ承認',return:'差戻し',cancel:'取下げ',superseded:'変更・再申請',release:'押印手続き開始',complete:'締結版照合完了'};
const date=(value:string|null)=>value?new Date(value).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'未確認';
const termLabels:Record<string,string>={scopeSummary:'業務範囲',paymentTerms:'支払条件',deliverablesNote:'成果物',expenseReimbursementNote:'経費',confidentialitySummary:'秘密保持',confidentialitySurvival:'秘密保持の存続',ipOwnership:'知財の帰属',usageRights:'利用権',publicityRights:'公開・発表',subcontractingTerms:'再委託',exclusivityTerms:'独占・競業',terminationTerms:'解除',liabilityTerms:'賠償・責任',governingLawJurisdiction:'準拠法・管轄',specialTerms:'特記事項',renewalType:'更新',notes:'確認事項'};
const dialogClass='max-h-[90vh] overflow-y-auto rounded-none [&>button]:size-11 [&>button]:top-1 [&>button]:right-1 sm:max-w-[760px]';
const contractField=(r:WorkflowRequest,key:'contract_title'|'counterparty_name'|'contract_type'|'amd_entity_name')=>String((r.status==='preparing'?r.contract?.[key]:r.terms_snapshot[key])||r.terms_snapshot[key]||'未確認');
export function WorkflowWorkspace({embedded=false,initialContractId='',initialRequestId=''}:{embedded?:boolean;initialContractId?:string;initialRequestId?:string}){
 const detailHeading=useRef<HTMLHeadingElement>(null);const detailSequence=useRef(0);
 const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [selected,setSelected]=useState<WorkflowRequest|null>(null);
 const [events,setEvents]=useState<Event[]>([]);const [documents,setDocuments]=useState<WorkflowDocument[]>([]);const [detailLoading,setDetailLoading]=useState(false);
 const [showForm,setShowForm]=useState(!!initialContractId);const [formContractId,setFormContractId]=useState(initialContractId);
 const [documentId,setDocumentId]=useState('');const [driveLink,setDriveLink]=useState('');const [note,setNote]=useState('');const [confirmed,setConfirmed]=useState(false);const [notice,setNotice]=useState('');
 const reload=useCallback(async(offset=0)=>{
  const response=await fetch(`/api/workflows?offset=${offset}${initialContractId?`&focusContractId=${encodeURIComponent(initialContractId)}`:''}`,{cache:'no-store'});const result=await response.json();
  if(!response.ok||!result.ok)throw new Error(result.error||'読み込めなかった');
  setData(old=>({...result,requests:offset?[...(old?.requests||[]),...result.requests]:result.requests}));
 },[initialContractId]);
 const loadDetail=useCallback(async(requestId:string)=>{
  const generation=++detailSequence.current;
  const response=await fetch(`/api/workflows/${encodeURIComponent(requestId)}`,{cache:'no-store'});const result=await response.json();
  if(generation!==detailSequence.current)return;
  if(!response.ok||!result.ok)throw new Error(result.error||'フローを読み込めなかった');
  setSelected(result.request);setEvents(result.events);setDocuments(result.documents);setDocumentId(result.documents.find((d:WorkflowDocument)=>d.document_kind!=='signed')?.document_id||'');
 },[]);
 useEffect(()=>{let active=true;reload().then(()=>initialRequestId?loadDetail(initialRequestId):undefined).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[reload,loadDetail,initialRequestId]);
 const openDetail=async(request:WorkflowRequest)=>{setError('');setSelected(request);setEvents([]);setDocuments([]);setDocumentId('');setDriveLink('');setConfirmed(false);setNote('');setDetailLoading(true);try{await loadDetail(request.request_id);}catch(e){setError(e instanceof Error?e.message:'読み込めなかった');}finally{setDetailLoading(false);}};
 const perform=async(url:string,body:unknown,message='保存完了')=>{setBusy(true);setError('');try{
  const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();
  if(!response.ok||!result.ok)throw new Error(result.error||'保存できなかった');
  if(result.requestId){setShowForm(false);setConfirmed(false);setNote('');setDriveLink('');await loadDetail(result.requestId);}else if(selected){await loadDetail(selected.request_id);setConfirmed(false);setNote('');setDriveLink('');}
  setNotice(message);await reload();
 }catch(e){setError(e instanceof Error?e.message:'保存できなかった');}finally{setBusy(false);}};
 const searchContracts=async(search:string)=>{setBusy(true);setError('');try{const response=await fetch(`/api/workflows?search=${encodeURIComponent(search)}`,{cache:'no-store'});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error);setData(old=>old?{...old,contracts:result.contracts,contractCount:result.contractCount}:old);}catch{setError('契約を検索できなかった');}finally{setBusy(false);}};
 const names=(id:string)=>data?.members.find(m=>m.member_id===id)?.code_name||'メンバー';
 const title=(r:WorkflowRequest)=>contractField(r,'contract_title');
 const typeLabel=(value:string)=>WORKFLOW_CONTRACT_TYPES[value]||value;
 const monitorStale=!!data&&(!data.monitor.last_success_at||!data.monitor.last_checked_at||Date.now()-new Date(data.monitor.last_checked_at).getTime()>15*60_000);
 const actions=selected&&data?workflowActions(selected.status,data.actor,selected.requested_by,selected.approver_member_id):null;
 const signedDocument=documents.find(d=>d.document_id===selected?.contract?.signed_document_id&&d.document_kind==='signed');
 const refresh=async()=>{setBusy(true);setError('');try{await reload();if(selected)await loadDetail(selected.request_id);}catch(e){setError(e instanceof Error?e.message:'更新できなかった');}finally{setBusy(false);}};
 const restart=async()=>{if(!selected)return;await perform('/api/workflows',{action:'start',startId:crypto.randomUUID(),contractId:selected.contract_id,purpose:selected.purpose,desiredDate:selected.desired_date},'再申請の準備を開始');};
 return <section className="w-full max-w-[1200px] text-sm" data-testid="workflow-workspace">
  {!embedded&&<header className="mb-3"><h1 className="text-xl font-semibold">業務フロー</h1><p className="mt-1 text-sm text-muted-foreground">契約の開始から、きよの承認・押印・締結版の照合までを追う。</p></header>}
  <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border pb-3"><div><h2 className="font-semibold">契約フロー</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">契約書の準備 → きよの承認 → 押印・締結版の保存 → 締結版の照合 → 完了</p></div><div className="flex gap-2"><Button className="min-h-11" variant="outline" onClick={()=>void refresh()} disabled={busy}>更新</Button><Button className="min-h-11" onClick={()=>{setFormContractId('');setError('');setShowForm(true);}} disabled={busy||!data}>契約フローを開始</Button></div></div>
  {error&&!selected&&!showForm&&<p role="alert" className="my-3 border-l-2 border-destructive bg-destructive/5 px-3 py-2 text-destructive">{error}</p>}{notice&&<p role="status" className="my-2">{notice}</p>}
  {!data&&!error&&<p className="py-6 text-muted-foreground" role="status">フローと監視状況を読み込み中…</p>}
  {data&&<>
   <p className="py-2 text-xs text-muted-foreground">承認待ち {data.pendingCount}件 / 表示 {data.requests.length}件・全 {data.requestCount}件</p>
   <div className="overflow-x-auto"><table className="w-full min-w-[720px] border-collapse text-left"><thead className="border-y border-border bg-muted/30 text-xs text-muted-foreground"><tr>{['契約・相手先','契約の種類','申請者・承認者','希望日','現在の段階','操作'].map(x=><th className="px-3 py-2 font-medium" key={x}>{x}</th>)}</tr></thead><tbody>{data.requests.map(r=><tr key={r.request_id} className="border-b border-border hover:bg-muted/30"><td className="max-w-[360px] px-3 py-2"><p className="line-clamp-2 font-medium">{title(r)}</p><p className="mt-1 text-xs text-muted-foreground">{contractField(r,'counterparty_name')}</p></td><td className="px-3 py-2 text-xs">{typeLabel(contractField(r,'contract_type'))}</td><td className="px-3 py-2 text-xs"><Link href={`/mypage?memberId=${r.requested_by}`} className="underline underline-offset-2">{names(r.requested_by)}</Link> → <Link href={`/mypage?memberId=${r.approver_member_id}`} className="underline underline-offset-2">{names(r.approver_member_id)}</Link></td><td className="whitespace-nowrap px-3 py-2 text-xs">{r.desired_date||'指定なし'}</td><td className="px-3 py-2 text-xs font-medium">{r.status==='released'&&r.contract?.signed_document_id?'きよの締結版照合待ち':WORKFLOW_STATUS[r.status]}</td><td className="px-3 py-2"><Button variant="outline" className="min-h-11 sm:min-h-8" disabled={busy||detailLoading} onClick={()=>void openDetail(r)}>確認</Button></td></tr>)}</tbody></table>{!data.requests.length&&<p className="py-4 text-muted-foreground">契約フローはまだない。「契約フローを開始」から相手先・契約の種類・目的を登録。</p>}</div>
   {data.requests.length<data.requestCount&&<Button className="mt-2 min-h-11" variant="outline" disabled={busy} onClick={()=>void reload(data.requests.length).catch(()=>setError('次のフローを読み込めなかった'))}>次の50件を表示</Button>}
   <div className="mt-5 border-y border-border py-3"><h2 className="font-semibold">契約メールの監視</h2><p className={`mt-1 text-sm leading-6 ${data.monitor.last_error||monitorStale?'text-destructive':'text-muted-foreground'}`}>{data.monitor.last_error||(monitorStale?'監視の実行が未確認、または15分以上止まっている':'監視中・受信と送信を5分ごとに確認')} / 最終確認 {date(data.monitor.last_checked_at)}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">契約のやりとりを検知すると、まさときよの個別Slackへ通知。検知は承認ではなく、OS外の押印を止めるものではない。</p></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[620px] border-collapse text-left"><thead className="border-b border-border bg-muted/30 text-xs text-muted-foreground"><tr>{['日時・送受信','契約の動き','メール件名','Slack配信'].map(x=><th key={x} className="px-3 py-2 font-medium">{x}</th>)}</tr></thead><tbody>{data.mailEvents.map(event=>{const delivered=data.deliveries.filter(d=>d.event_key===`mail:${event.event_id}`);const label=delivered.length===2&&delivered.every(d=>d.status==='sent')?'2人へ配信済み':delivered.some(d=>d.status==='uncertain')?'配信結果の照合が必要':delivered.some(d=>d.status==='failed')?'配信失敗・再試行待ち':'配信待ち';return <tr key={event.event_id} className="border-b border-border"><td className="whitespace-nowrap px-3 py-2 text-xs">{date(event.occurred_at)}<br/>{event.direction==='sent'?'まさの送信':'まさの受信'}</td><td className="px-3 py-2 text-xs font-medium">{MAIL_EVENT_LABEL[event.event_kind]}{event.event_kind==='completion'&&<p className="mt-1 text-destructive">承認記録との照合が必要</p>}</td><td className="max-w-[400px] px-3 py-2"><a href={event.source_url} target="_blank" rel="noopener noreferrer" className="line-clamp-2 text-primary underline underline-offset-2">{event.subject}</a></td><td className="px-3 py-2 text-xs">{label}</td></tr>;})}</tbody></table></div>
   {!data.mailEvents.length&&<p className="py-3 text-muted-foreground">監視開始後の契約メールはまだ検知されていない。</p>}{data.mailCount>50&&<p className="py-2 text-xs text-muted-foreground">最新50件を表示 / 全 {data.mailCount}件</p>}
  </>}
  <Dialog open={showForm} onOpenChange={open=>{if(!busy)setShowForm(open);}}><DialogContent className={dialogClass}><DialogHeader><DialogTitle className="pr-8">契約フローを開始</DialogTitle><DialogDescription>相手先・契約の種類・目的を登録して準備を開始。契約書は開始後に登録できる。</DialogDescription></DialogHeader>{data&&<WorkflowStartForm contracts={data.contracts} contractCount={data.contractCount} projects={data.projects} busy={busy} error={error} initialContractId={formContractId} onSearch={searchContracts} onStart={(values:WorkflowStartInput)=>perform('/api/workflows',values,'契約フローを開始。次は最終版PDFを準備')} onClose={()=>setShowForm(false)}/>}</DialogContent></Dialog>
  <Dialog open={!!selected} onOpenChange={open=>{if(!open&&!busy){detailSequence.current++;setSelected(null);}}}><DialogContent className={dialogClass} initialFocus={detailHeading}><DialogHeader><DialogTitle ref={detailHeading} tabIndex={-1} className="pr-8 break-words outline-none">{selected?title(selected):'契約フロー'}</DialogTitle><DialogDescription>{selected?(selected.status==='released'&&selected.contract?.signed_document_id?'きよの締結版照合待ち':WORKFLOW_STATUS[selected.status]):''}</DialogDescription></DialogHeader>{selected&&actions&&<div className="space-y-4">
   <dl className="grid gap-3 border-y border-border py-3 sm:grid-cols-2">{[['相手先',contractField(selected,'counterparty_name')],['契約の種類',typeLabel(contractField(selected,'contract_type'))],['当事者',contractField(selected,'amd_entity_name')],['申請者・承認者',`${names(selected.requested_by)} → ${names(selected.approver_member_id)}`],['開始日・押印希望日',`${date(selected.created_at)} / ${selected.desired_date||'指定なし'}`],['押印申請日',selected.submitted_at?date(selected.submitted_at):'準備中・未申請']].map(([k,v])=><div key={k}><dt className="text-xs text-muted-foreground">{k}</dt><dd className="mt-1 break-words">{v}</dd></div>)}</dl>
   <WorkflowProgress status={selected.status} requester={names(selected.requested_by)} approver={names(selected.approver_member_id)} signedArtifact={!!selected.contract?.signed_document_id}/>
   <div><p className="text-xs font-medium text-muted-foreground">契約の目的・確認事項</p><p className="mt-1 whitespace-pre-wrap leading-6">{selected.purpose}</p></div>
   {selected.decision_note&&<p className="border-l-2 border-border pl-3 leading-6">きよの確認：{selected.decision_note}</p>}
   {detailLoading&&<p role="status" className="py-2 text-muted-foreground">文書と履歴を確認中…</p>}
   {!detailLoading&&actions.prepare&&<section aria-label="契約書の準備" className="space-y-3 border-t border-border pt-3"><h3 className="font-semibold">最終版PDFを準備して押印申請</h3>
    <p className="text-sm leading-6 text-muted-foreground">契約本文と添付を含む最終版PDFをDriveに保存し、そのリンクを登録。WordはPDFに変換して登録。</p>
    <form className="flex flex-wrap items-end gap-2" onSubmit={e=>{e.preventDefault();void perform(`/api/workflows/${selected.request_id}`,{action:'register_pdf',driveLink},'最終版PDFを登録');}}><label className="min-w-0 flex-[1_1_240px] text-sm font-medium">最終版PDFのDriveリンク<input required type="url" className={`mt-1 ${input}`} value={driveLink} onChange={e=>setDriveLink(e.target.value)} placeholder="https://drive.google.com/file/d/…"/></label><Button className="min-h-11" disabled={busy} type="submit">PDFを登録</Button></form>
    <label className="block text-sm font-medium">押印対象の最終版PDF<select className={`mt-1 ${input}`} value={documentId} onChange={e=>setDocumentId(e.target.value)}><option value="">PDFを選択</option>{documents.filter(d=>d.document_kind!=='signed').map(d=><option key={d.document_id} value={d.document_id}>{d.version_label} / {d.file_name}</option>)}</select></label>
    {documentId?<a className="inline-flex min-h-11 items-center text-primary underline" href={`https://drive.google.com/file/d/${documents.find(d=>d.document_id===documentId)?.drive_file_id}/view`} target="_blank" rel="noopener noreferrer">選択した最終版PDFを確認</a>:<p className="text-sm text-muted-foreground">最終版PDFが未登録。登録すると承認を依頼できる。</p>}
    <Button className="min-h-11" disabled={busy||!documentId} onClick={()=>void perform('/api/workflows',{contractId:selected.contract_id,documentId,purpose:selected.purpose,desiredDate:selected.desired_date},'きよへ押印申請を送った')}>きよへ押印申請</Button>
   </section>}
   {selected.snapshot_file_id&&<a className="inline-flex min-h-11 items-center text-primary underline underline-offset-2" href={`https://drive.google.com/file/d/${selected.snapshot_file_id}/view`} target="_blank" rel="noopener noreferrer">申請時に固定した最終版PDFを開く</a>}
   {!detailLoading&&actions.release&&<p className="text-sm leading-6 text-muted-foreground">きよが承認した最終版を確認し、下の操作から押印手続きを開始。</p>}
   {!detailLoading&&selected.status==='released'&&<section className="space-y-3 border-t border-border pt-3" aria-label="締結版の保存">
    <h3 className="font-semibold">締結版PDFの保存・照合</h3>
    {signedDocument?<a className="inline-flex min-h-11 items-center text-primary underline" href={`https://drive.google.com/file/d/${signedDocument.drive_file_id}/view`} target="_blank" rel="noopener noreferrer">登録された締結版PDFを開く</a>:<p className="text-sm leading-6 text-muted-foreground">押印・署名が完了したPDFをDriveに保存して登録。きよが承認対象との一致を確認して完了する。</p>}
    {!selected.contract?.signed_document_id&&data?.actor===selected.requested_by&&<form className="flex flex-wrap items-end gap-2" onSubmit={e=>{e.preventDefault();void perform(`/api/workflows/${selected.request_id}`,{action:'register_pdf',driveLink},'締結版PDFを登録。きよの照合待ち');}}><label className="min-w-0 flex-[1_1_240px] text-sm font-medium">締結版PDFのDriveリンク<input required type="url" className={`mt-1 ${input}`} value={driveLink} onChange={e=>setDriveLink(e.target.value)} placeholder="https://drive.google.com/file/d/…"/></label><Button className="min-h-11" disabled={busy} type="submit">締結版を登録</Button></form>}
   </section>}
   {selected.status==='completed'&&signedDocument&&<a className="inline-flex min-h-11 items-center text-primary underline" href={`https://drive.google.com/file/d/${signedDocument.drive_file_id}/view`} target="_blank" rel="noopener noreferrer">照合済みの締結版PDFを開く</a>}
   {actions.restart&&<div className="space-y-2 border-t border-border pt-3"><p className="text-sm leading-6">{selected.contract?.status==='signed'?'締結版が登録されている。契約管理で事実と次の手続きを確認。':'文書・条件を確認して新しい申請を準備。元の承認は使用できない。'}</p><Button className="min-h-11" variant="outline" disabled={busy||selected.contract?.status==='signed'} onClick={()=>void restart()}>再申請を準備</Button></div>}
   <Link className="inline-flex min-h-11 items-center text-primary underline" href="/admin/contracts">契約管理で条件・文書の版を確認</Link>
   {selected.snapshot_file_id&&<details><summary className="min-h-11 cursor-pointer py-3 text-sm font-medium">申請時の契約条件を確認</summary><dl className="divide-y divide-border">{Object.entries((selected.terms_snapshot.operational_terms_json||{}) as Record<string,unknown>).filter(([k,v])=>!!termLabels[k]&&(typeof v==='string'||typeof v==='number')).map(([key,value])=><div key={key} className="py-2"><dt className="text-xs text-muted-foreground">{termLabels[key]}</dt><dd className="whitespace-pre-wrap break-words leading-6">{String(value)}</dd></div>)}</dl></details>}
   <details><summary className="min-h-11 cursor-pointer py-3 text-sm font-medium">申請・承認の履歴</summary>{detailLoading?<p role="status">履歴を読み込み中…</p>:<ol className="divide-y divide-border">{events.map(event=><li key={event.event_id} className="py-2"><p className="text-xs text-muted-foreground">{date(event.created_at)} / {event.actor_member_id?names(event.actor_member_id):'OS'}</p><p className="mt-1 font-medium">{eventLabels[event.action]||'更新'}</p>{event.note&&<p className="mt-1 whitespace-pre-wrap leading-6">{event.note}</p>}</li>)}</ol>}</details>
   {(actions.approve||actions.release||(actions.complete&&!!selected.contract?.signed_document_id))&&<label className="flex min-h-11 items-start gap-2 border-y border-border py-3"><input className="mt-1 size-5 shrink-0" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span className="leading-6">{actions.complete?'登録された締結版を開き、承認対象の内容と一致することを確認した':'固定した最終版PDFと契約条件を確認した'}</span></label>}
   {(actions.approve||actions.return)&&<label className="block text-sm font-medium">確認コメント（差戻しは必須）<textarea className={`mt-1 ${input}`} rows={2} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label>}
   {error&&<p role="alert" className="text-destructive">{error}</p>}
   <div className="flex flex-wrap justify-end gap-2 border-t border-border pt-3">
    <Button className="min-h-11" variant="outline" disabled={busy} onClick={()=>void refresh()}>最新の状態を確認</Button>
    {actions.cancel&&<Button className="min-h-11" variant="outline" disabled={busy||detailLoading} onClick={()=>void perform(`/api/workflows/${selected.request_id}`,{action:'cancel'},'フローを取下げ')}>フローを取下げ</Button>}
    {actions.return&&<Button className="min-h-11" variant="outline" disabled={busy||detailLoading||!note.trim()} onClick={()=>void perform(`/api/workflows/${selected.request_id}`,{action:'return',note},'差戻しを記録')}>差戻し</Button>}
    {actions.approve&&<Button className="min-h-11" disabled={busy||detailLoading||!confirmed} onClick={()=>void perform(`/api/workflows/${selected.request_id}`,{action:'approve',confirmed,note},'きよの承認を記録')}>この最終版の押印を承認</Button>}
    {actions.release&&<Button className="min-h-11" disabled={busy||detailLoading||!confirmed} onClick={()=>void perform(`/api/workflows/${selected.request_id}`,{action:'release',confirmed},'押印手続きを開始')}>承認対象の押印手続きへ進む</Button>}
    {actions.complete&&<Button className="min-h-11" disabled={busy||detailLoading||!confirmed||!selected.contract?.signed_document_id} onClick={()=>void perform(`/api/workflows/${selected.request_id}`,{action:'complete',confirmed},'締結版の照合が完了')}>締結版を照合して完了</Button>}
   </div><p className="text-xs leading-5 text-muted-foreground">紙の押印や外部サービスでの電子署名は、この画面とは別の操作。承認された最終版を使用。</p>
  </div>}</DialogContent></Dialog>
 </section>;
}
